### ISSUE TITLE
MLKIT Research HELP

### ISSUE THREAD

**Issue by akrishnan93** [googlesamples/mlkit#103]
I am working on a project with a couple of my friends and I was wondering if you could help us answer a few questions regarding this code base. Please let me know if someone would be available to help us! Thanks 👍

**Comment by swiyu** [comment]
Could you list your questions here?

**Comment by akrishnan93** [comment]
Hey, thanks so much for replying. Yeah, let me go ahead and post them here:

1. We are using mlkit for a project we are working on and we are happy with its performance so far. One question that we had was we noticed that out of the box, it starts to detect objects a couple feet away. We were wondering whether there is a way to change this distance threshold somehow so that the user can start get notifying earlier, or is it fixed.

2. Also, I know that for live video - object detection, the engine does not make any API calls because it needs to process the video quickly. But is there a way to make a fire base ML kit API call for a certain frame of the video to get a more accurate understanding of what the object is? 

I'll add more as they come up. Thanks so much for the help everyone!

**Comment by swiyu** [comment]
> Hey, thanks so much for replying. Yeah, let me go ahead and post them here:
> 
> 1. We are using mlkit for a project we are working on and we are happy with its performance so far. One question that we had was we noticed that out of the box, it starts to detect objects a couple feet away. We were wondering whether there is a way to change this distance threshold somehow so that the user can start get notifying earlier, or is it fixed.
The model is not trained with distance in mind. It takes the primary object in the image without knowing the distance. There is no distance threshold we could set in this feature at this moment. Could you elaborate more about your use case? 

> 2. Also, I know that for live video - object detection, the engine does not make any API calls because it needs to process the video quickly. But is there a way to make a fire base ML kit API call for a certain frame of the video to get a more accurate understanding of what the object is?
I think you mean the API call to the cloud server for an accurate understanding. In our new ML Kit SDK, we provide a way for  [custom image classification for ODT](https://developers.google.com/ml-kit/vision/object-detection/custom-models/android), where you could provide a model to classify your interested objects.

> 
> I'll add more as they come up. Thanks so much for the help everyone!
