### ISSUE TITLE
Unable to access current frame inside LivePreviewActivity

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [googlesamples/mlkit#105]
I am unable to access the current frame inside LivePreviewActivity. I do not find any Class or method that can access the current frame being processed. 

Please help me.

**Comment by steven-chengji-yan** [comment]
You could take a look at the CameraSource class. https://github.com/googlesamples/mlkit/blob/f630a6357d9f1e79fde8e1f13e29f9434fd84c78/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/CameraSource.java#L730
