### ISSUE TITLE
Qr code not remove 

### ISSUE THREAD

**Issue by arunsparki** [googlesamples/mlkit#108]
I am implemented your scanner in my android app(java) on dashboard screen (Button click ->visible camera view ).second time scanning time ,the first captured qr not remove from the camera view and also BarcodeResultFragment calling itself

**Comment by calren** [comment]
Hey @arunsparki , thanks for giving the sample apps a try! Can you expand a bit further about what the buggy behavior you saw was?

From what I understand, it sounds like the sample app only captured the QR code the first time, and wasn't able to 'refresh' itself to capture the QR code the second time? 

I'm also not sure what you meant by the BarcodeResultFragment was calling itself, can you elaborate on that a bit?

**Comment by arunsparki** [comment]
![Screenshot_2020-08-19-09-30-02-827_20200819_093021181](https://user-images.githubusercontent.com/53429469/90591670-53faa000-e201-11ea-927f-bfd470dd65a7.jpg)

![Screenshot_2020-08-17-23-30-28-896_20200817_233452011](https://user-images.githubusercontent.com/53429469/90591722-6bd22400-e201-11ea-9f03-369057d85a36.jpg)

I am attaching two screen of my app .when i am clicking the scan code button(first screen), will call the setupworkflowmodel method .  the app only captured the QR code the first time . when i click the  scan code button at second time ,the scanner wasn't able to refresh  and also show the result of first scanned qr image .


 private void setUpWorkflowModel() {


    workflowModel =  ViewModelProviders.of(this).get(WorkflowModel.class);

// Observes the workflow state changes, if happens, update the overlay view indicators and
// camera preview state.
        workflowModel.getWorkflowState().observe(this, workflowState -> {
          


            if (workflowState == null || Objects.equal(currentWorkflowState, workflowState)) {
                return;
            }

            currentWorkflowState = workflowState;

            Log.d(TAG, "Current workflow state: ${currentWorkflowState!!.name}");

            switch (workflowState) {
                case DETECTING: {
                    startCameraPreview();
                    break;
                }
                case CONFIRMING: {
                    startCameraPreview();
                    break;
                }
                case SEARCHING: {
                    stopCameraPreview();
                    break;
                }
                case DETECTED: {
                    stopCameraPreview();
                    break;
                }
                case SEARCHED: {
                    stopCameraPreview();
                    break;
                }
            }
        });

        workflowModel.getDetectedBarcode().observe(this, barcode -> {
            if (barcode != null) {

             /*   ArrayList<BarcodeField> barcodeFieldList = new ArrayList<>();
                barcodeFieldList.add(new BarcodeField("Raw Value", barcode.getRawValue()));*/
                stopCameraPreview();
    
                    scanCompleted(barcode.getRawValue());
                
            }
        });
        if (workflowModel != null)
            workflowModel.markCameraFrozen();
        currentWorkflowState = WorkflowModel.WorkflowState.NOT_STARTED;

        if (workflowModel != null)
            workflowModel.setWorkflowState(WorkflowModel.WorkflowState.DETECTING);
        if (cameraSource != null) {
            cameraSource.setFrameProcessor(new BarcodeProcessor(graphicOverlay, workflowModel));
        }

    }
