### ISSUE TITLE
vision-quickstart is not signed

### ISSUE THREAD

**Issue by jeffwiy** [googlesamples/mlkit#123]
When trying to run vision-quickstart,

Error: The apk for your currently selected variant (vision-quickstart-proguard.apk) is not signed. Please specify a signing configuration for this variant (proguard).

Other sample apps seem to run fine.

**Comment by calren** [comment]
You can build a debug version through the command line to avoid having to sign the apk. 

If you're building the app through Android Studio, you can configure the [gradle file](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/build.gradle#L28) to build the debug version by default

**Comment by calren** [comment]
We've also made the change to the gradle file internally, so for the next samples release this should no longer be an issue.

**Comment by razzieel** [comment]
Sorry, but I don't know how to configure for fix the error, could you share the correct build.gradle please?

**Comment by razzieel** [comment]
I try with many configurations but the error still appears

My code:

`buildTypes {
        proguard {
            debuggable true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard.cfg'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguardTest-rules.pro', 'proguard.cfg'
        }
        testBuildType "proguard"
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
        }

        staging {
            signingConfig signingConfigs.debug
            externalNativeBuild {
                cmake {
                    cppFlags "-DDEBUG_FLAG"
                }
            }

        }

    }
`

**Comment by razzieel** [comment]
![image](https://user-images.githubusercontent.com/65725299/92179864-405b5600-ee0b-11ea-843b-a0085a2e9aea.png)

**Comment by zhouyiself** [comment]
Try removing this line:  "testBuildType "proguard".

**Comment by zhouyiself** [comment]
I think your default build variant is "proguard" rather "debug", you can change it back to "debug" by following https://developer.android.com/studio/run

**Comment by zhouyiself** [comment]
https://developer.android.com/studio/run#changing-variant

**Comment by razzieel** [comment]
> I think your default build variant is "proguard" rather "debug", you can change it back to "debug" by following https://developer.android.com/studio/run

Excellent it works with:

To change the build variant Android Studio uses, select Build > Select Build Variant in the menu bar.

but how you knew?

**Comment by zhouyiself** [comment]
It's mentioned in the error message you posted
"The apk for your currently selected variant (vision-quickstart-proguard.apk) is not signed"

**Comment by razzieel** [comment]
> It's mentioned in the error message you posted
> "The apk for your currently selected variant (vision-quickstart-proguard.apk) is not signed"

Ok thanks, I'll search more about proguard

**Comment by suyashjoshi** [comment]
ran into the same problem and this helped me resolve the issue.
