### ISSUE TITLE
pod "GoogleMLKit/Translate" not found

### ISSUE THREAD

**Issue by yudhisthira123** [googlesamples/mlkit#125]
I am getting following error while making pod install command :- 

[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/Translate":
  In Podfile:
    GoogleMLKit/Translate

Specs satisfying the `GoogleMLKit/Translate` dependency were found, but they required a higher minimum deployment target.

**Comment by miworking3** [comment]
Hey @yudhisthira123, could you share the command that you used to install the Pod? I tried to reproduce this issue by running `pod install --repo-update` locally, but didn't run into the issue you reported.

Here is the Podfile.lock I got after the installation and the `- GoogleMLKit/Translate (0.63.0)` pod was installed  successfully.

Could you re-try with this command and see if it will happen again?

Thanks!

[Podfile.lock.zip](https://github.com/googlesamples/mlkit/files/5158873/Podfile.lock.zip)

**Comment by yudhisthira123** [comment]
@miworking3 first i tried pod install command and now pod install --repo-update but result is same. 
here is my Podfile and Podfile.lock

[Archive.zip](https://github.com/googlesamples/mlkit/files/5160871/Archive.zip)

**Comment by miworking3** [comment]
Will it be installed if you use 
platform :ios, '10.0'

in the Podfile?

**Comment by yudhisthira123** [comment]
@miworking3 yes, I am able to install after making platform :ios, '10.0'

**Comment by miworking3** [comment]
Great, then I will close this bug, pls feel free to reopen it if you have any further questions. Thanks!
