### ISSUE TITLE
FPS is  low initially and then increases with hardware acceleration ON & in Accurate mode.

### ISSUE THREAD

**Issue by tarun-nain** [googlesamples/mlkit#127]
I am using the LivePreviewActivity and I have turned on the hardware acceleration in the manifest. After this, the FPS increased significantly in the Accurate mode and goes up to 22-25 FPS.

The issue is that initially when the camera is started, the FPS is around 1-2 and after a few seconds, it increases to 22-25.

I have tested it with several devices including Samsung Note8 and S20. All of them show the same behavior.

**Comment by zhouyiself** [comment]
Glad you're trying out the hardware acceleration and it helps. Initial low FPS is kind of expected because it does some warm up internally that could affect frame number to be processed
