### ISSUE TITLE
High latency when camera opened

### ISSUE THREAD

**Issue by rohitgarg29** [googlesamples/mlkit#128]
Hi,

I am trying to use the text Recognition using this code but i am getting too much latency aprx 3500 and camera is very slow. Can you please help me?

Regards,
R

**Comment by calren** [comment]
Hey @rohitgarg29 , can you comment a bit more about what you're seeing? It'd be helpful to know:
- which mlkit api you're using
- which device you're seeing this behavior on
- What the latency issue you're seeing is. Is it that the camera initialization is taking longer than you expect? Or is it that you point the camera at the text and the results are taking longer than expected to come back? For latency issues, it would also be good to know how slow it was in terms of milliseconds.

**Comment by chrisito** [comment]
@rohitgarg29 any updates, so we can help? Thanks.

**Comment by bcdj** [comment]
Closing this bug due to lack of response.  Please open a new report if the issue persists.
