### ISSUE TITLE
Pose Detection getting reverse direction

### ISSUE THREAD

**Issue by PraveenPotla** [googlesamples/mlkit#129]
when I run the vision example(Pose Detection). I am not showing my full body to the camera. It is drawing like Please find attachment
![PoseDetctionApp](https://user-images.githubusercontent.com/43574666/92098632-1f890580-edf7-11ea-9c24-023852db5c79.jpg)

**Comment by steven-chengji-yan** [comment]
In the dev doc, it says "The user's face must be present in order to detect a pose." https://developers.google.com/ml-kit/vision/pose-detection

Hope it helps.
