### ISSUE TITLE
Pose Detection getting reverse direction

### ISSUE THREAD

**Issue by Priya2711** [googlesamples/mlkit#130]
I am using vision app. When I am trying to capture poses  whenever I am showing my whole body it is detecting poses clearly. But when I am showing my legs it is giving reverse points. For more info find attached screenshot
![Screenshot_2020-09-03-15-11-23-99_fa6797958615d8ea5849c081f6510d6a](https://user-images.githubusercontent.com/29098559/92101852-59f4a180-edfb-11ea-8cf4-7b1ffcc1e092.jpg)

**Comment by shahid898** [comment]
Try to get specific Pose Landmarks individually if you are not want to detect whole Body.
see the  document it might help 
[](https://developers.google.com/ml-kit/vision/pose-detection/android#kotlin)

**Comment by steven-chengji-yan** [comment]
In the dev doc, it says "The user's face must be present in order to detect a pose." https://developers.google.com/ml-kit/vision/pose-detection

Hope it helps.
