### ISSUE TITLE
camera zoom is not consistent across devices

### ISSUE THREAD

**Issue by tarun-nain** [googlesamples/mlkit#133]
I  need to zoom the camera a little more so that it focuses on the face only. I am using the face detection model.

To zoom the camera it set the 

Camera.parameters.setZoom(int) - (where int is somewhere between the maxSupportedZoom of the device)

`Camera.Parameters parameters = camera.getParameters();
 parameters.setZoom(30);
  parameters.setPreviewFpsRange(
                previewFpsRange[Camera.Parameters.PREVIEW_FPS_MIN_INDEX],
                previewFpsRange[Camera.Parameters.PREVIEW_FPS_MAX_INDEX]);

  parameters.setPreviewFormat(IMAGE_FORMAT);
 camera.setParameters(parameters);`

yes, this zooms the video, but for some devices, the zoom is very much, and on some devices, it is very low zoom.

I have thoroughly checked and the aspect ratio of the camera and the preview size is the same.

What is the possible workaround to get the same zoom factor for most of the devices.

**Comment by cs-googler** [comment]
Hey,

setZoom(...) is a camera1 API which is not controlled by MLKit. Closing
