### ISSUE TITLE
ML Kit Translate : Translation result losing its original string format

### ISSUE THREAD

**Issue by ArcherEmiya05** [googlesamples/mlkit#134]
After translating a string formatted with some `\n` the result lose the format spacing. I highly believed the translated string should always respect the original string spacing format.

**Comment by zhouyiself** [comment]
It's a known behavior of the underlying translation engine, you can check the below similar discussion for more context
https://stackoverflow.com/questions/61968723/how-to-translate-text-without-losing-newline-characters
