### ISSUE TITLE
ML-kit Pose Detection: Create custom algorithm/classifier to interpret a pose

### ISSUE THREAD

**Issue by BetaPundit** [googlesamples/mlkit#135]
I am looking for ways to use the output of the Pose detection API to train a custom classifier for different poses. 
Is there a way to run ml-kit on the desktop so that I can train a classifier on the pose landmark output of 10000+ images.

Or any other approach to design an algorithm to recognize a pose.

Thanks in advance!

**Comment by steven-chengji-yan** [comment]
I don't see a way to run it on desktop.  One thing you could try:

Write some script to push those images batch by batch to a phone.
Write an app to to run pose detection through those images and write the output to a certain file.
It will probably take couple of hours to finish processing all the 10000+ images in this way.

**Comment by BetaPundit** [comment]
> I don't see a way to run it on desktop. One thing you could try:
> 
> Write some script to push those images batch by batch to a phone.
> Write an app to to run pose detection through those images and write the output to a certain file.
> It will probably take couple of hours to finish processing all the 10000+ images in this way.

That's what I was thinking too! 
I haven't done anything similar before. Let's see if I can pull it off! 

Also, if you can suggest any reference/tutorial for that, it'll be much helpful.
Thanks

**Comment by steven-chengji-yan** [comment]
If I am doing it, I will probably use python or bash to write some script. And I will break it down into the following parts and research how to do each of them:
1. adb push   images to the device
2. write an app to read images from a certain folder, and run it through the ML Kit detector, and then write the result to a file
3. use adb command to run that app
4. adb pull to get the result file (and merge its content with the ones from previous runs)
5. do it batch by batch until you finish processing all your images.

**Comment by BetaPundit** [comment]
Well, thanks for the flow!
But I have already built an app which fulfills my purpose!
