### ISSUE TITLE
ML Kit Face Detection cause some memory leak problem

### ISSUE THREAD

**Issue by dudskrk** [googlesamples/mlkit#137]
Hi guys. I'm working on ML kit with some thermal video input(flir one).
I have bitmap, so I use processBitmap fuction.
Guide said "If a new video frame becomes available while the detector is running, drop the frame. See the VisionProcessorBase class in the quickstart sample app for an example".
I've some test, and I think this make some memory leaks..
How can I handle this dropped frame?

**Comment by swiyu** [comment]
When you call `Task<List<Face>> facesTask = FaceDetector.process()` method in the code, please only send a second image into process() call after facesTask is completed. 

For example, [the code](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/VisionProcessorBase.java#L155)  only process a new image when the previous image is finished.

**Comment by dudskrk** [comment]
@swiyu
Thanks. I got it, but one more question.
The camera I'm using is not as fast as the built-in camera(about 4~6fps).
Can I use processBitmap function in this case?

I'm asking this question because I have two apps.
One is a customized sample app(using processBitmap fuction, didn't use processlatest fuction, not memory leak), 
and the other, I only use the necessary functions at the guide(cause memory leak with same frames).

`InputImage image = InputImage.fromBitmap(bitmap, rotationDegree);

Task<List<Face>> result =
        detector.process(image)
                .addOnSuccessListener(
                        new OnSuccessListener<List<Face>>() {
                            @Override
                            public void onSuccess(List<Face> faces) {
                                // draw, process ...
                            }
                        })
                .addOnFailureListener(
                        new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                // Task failed with an exception
                                // ...
                            }
                        });
`

Can this be a problem? I don't understand the difference between the two apps I made.
