### ISSUE TITLE
ML Kit Translate doess not preserve formatting with newlines "\n"

### ISSUE THREAD

**Issue by ArcherEmiya05** [googlesamples/mlkit#139]
I will report this issue again because someone from contributor mark it as "closed" after giving a vague answer comes from SO that is not even a solution. The problem here is I tested other ML translator product like the one from HMS ML Kit and the translated text result does respect the original format of string.

In HMS ML Kit translator, the engine managed to preserve the non-linguistic part. The original string formatted with "\n" was kept on the translated result. My question is why this feature does not exist in Firebase ML Kit translate?

**Comment by bcdj** [comment]
Please do not rely on the translator to preserve special characters. You could instead break the text by "\n", pass each segment into the translator and then concatenate the output by "\n".

**Comment by ArcherEmiya05** [comment]
> 
> 
> Please do not rely on the translator to preserve special characters. You could instead break the text by "\n", pass each segment into the translator and then concatenate the output by "\n".

You mean I need to loop and make multiple request translation in each new line? I think that would be too heavy and slow.

**Comment by sheepmaster** [comment]
The overhead from issuing multiple translation requests is going to be negligible compared to actually doing the translation.

**Comment by dkaraush** [comment]
Wouldn't that remove the needed context from previous lines for a model to translate?
