### ISSUE TITLE
Slow runtime when running on video from memory

### ISSUE THREAD

**Issue by yonatanbitton** [googlesamples/mlkit#142]
Hello
I'm running the code on video from memory.
I'm looking at this code as reference: https://developers.google.com/ml-kit/vision/pose-detection/android

I create the pose detector as follows: 
```java
        PoseDetectorOptions options =
                new PoseDetectorOptions.Builder()
                        .setDetectorMode(PoseDetectorOptions.STREAM_MODE)
                        .setPerformanceMode(PoseDetectorOptions.PERFORMANCE_MODE_FAST)
                        .build();
        PoseDetector poseDetector = PoseDetection.getClient(options);
```

I read the video from storage as follows: 
```java
MediaMetadataRetriever retriever = new MediaMetadataRetriever();
        try {
            //path of the video of which you want frames
            retriever.setDataSource(video_abs_path);
        } catch (Exception e) {
            Log.d(TAG, "Error reading video");
        }
```
Then I iterate the frames and receive them as Bitmaps, then converts it to InputImage, and extract the pose:
```java
        for (int frame_num = 0; frame_num < number_of_frames; frame_num++)
        {
            Bitmap bmp = retriever.getFrameAtIndex(frame_num);
            InputImage frame = InputImage.fromBitmap(bmp, rotationDegree);
            Hashtable<String, String> joints_dict = extract_pose(poseDetector, file_name, frame, frame_num);
```
I measure time for handling single frame, and it ~2 seconds. 
Meaning for a video with 800 frames it should take ~26 minutes.

Does it make sense?
Is there a better way / practice to perform such functionality on a video?

Thanks

**Comment by swiyu** [comment]
Is the ~2 seconds for running the model or the frame retriever? Also, what is the image resolution for your video? Converting a large image to bitmap is very time-consuming.

**Comment by yonatanbitton** [comment]
The time is measured for the 3 lines in the loop: getting frame at index, converting from the bitmap to InputImage, performing the prediction and insert it to the Hashtable. Resolution is 640x480

**Comment by steven-chengji-yan** [comment]
Hi yonatanbitton,

I remember you asked this https://github.com/googlesamples/mlkit/issues/141 as well. How did you end up with handling that issue? Are you using the while loop for wait? Could you provide your current implementation of extract_pose here?

**Comment by yonatanbitton** [comment]
Hey. About the other issue - my app doesn't have GUI, I just need to extract pose, so I don't mind putting it in the main activity. I do use the while. 

In the extract pose I convert the Landmarks to Hashtable with a string format:
```java
private Hashtable<String, String> get_joints_dict(ArrayList imagePoseLandmarks) {
        Hashtable<String, String> joints_dict = new Hashtable<String, String>();
        for (int i=0; i<imagePoseLandmarks.size(); i ++){
            PoseLandmark lm = (PoseLandmark) imagePoseLandmarks.get(i);
//                                            String joint_name = "\"" + lm.getLandmarkType().toString() + "\"";
            String joint_name = lm.getLandmarkType().toString();
            String x_y_str = lm.getPosition().toString();
            String x_y_str_clean = x_y_str.substring("PointF".length(), x_y_str.length()-1);
            String conf = String.valueOf(lm.getInFrameLikelihood());
            String x_y_conf = x_y_str_clean + ", " + conf + ")";
            joints_dict.put(joint_name, x_y_conf);
        }
        return joints_dict;
    }
```

**Comment by steven-chengji-yan** [comment]
One thing that could help debug this might be: just monitor the time consumed by the poseDetector#process method to understand whether it is the MLKit process() is slow or it is the pre-process or post-process.

Could you provide the **complete code** for this, e.g. how do you record the time, the implementation of extract_pose?

**Comment by yonatanbitton** [comment]
This is how I record the time:
```java
            long tStart = System.currentTimeMillis();
            Bitmap bmp = retriever.getFrameAtIndex(frame_num);
            InputImage frame = InputImage.fromBitmap(bmp, rotationDegree);
            Hashtable<String, String> joints_dict = extract_pose(poseDetector, file_name, frame, frame_num);
            long tEnd = System.currentTimeMillis();
            long tDelta = tEnd - tStart;
            double elapsedSeconds = tDelta / 1000.0;
            all_elapsed_seconds += elapsedSeconds;
            double average_for_frame = all_elapsed_seconds / (frame_num + 1);
```

That's the extract pose;
```java
private Hashtable<String, String> extract_pose(PoseDetector poseDetector, final String file_name, InputImage image, final int frame_num) {
        Task<Pose> result =
                poseDetector.process(image)
                        .addOnSuccessListener(
                                new OnSuccessListener<Pose>() {
                                    @Override
                                    public void onSuccess(Pose pose) {
                                        // Task completed successfully
//                                        write_pose_joints(pose, file_name, frame_num);
                                        Log.d(TAG, "onSuccess");

                                        // Or get specific PoseLandmarks individually. These will all be null if no person
                                        // was detected
                                    }
                                })
                        .addOnFailureListener(
                                new OnFailureListener() {
                                    @Override
                                    public void onFailure(@NonNull Exception e) {
                                        // Task failed with an exception
                                        Log.d(TAG, "onFailure");
                                    }
                                });
        while (!result.isComplete()){}
        Hashtable<String, String> joints_dict = null;
        if (result.isComplete()){
            Pose pose_result = result.getResult();
            joints_dict = get_joints_dict(pose_result);
        } else {
            Log.d(TAG, "Tasks not completed yet " + file_name + " " + frame_num);
        }
        return joints_dict;
    }
```

I've posted the implementation of `get_joints_dict` couple messages before, so it's the full code

**Comment by steven-chengji-yan** [comment]
Thanks for sharing the code.

Have you tried to move the recording time logic to just around the MLKit process? Specifically, move the start before poseDetector.process(image) line, and move the stop time right after  while (!result.isComplete()){} ?

I usually tend not to use "while (!result.isComplete()){}", not sure if that may affect it.

**Comment by yonatanbitton** [comment]
Thanks I will try it. I am just interested if other people receive similar run time per frame.

**Comment by steven-chengji-yan** [comment]
No problem.

Please let us know if you can get the number.
We do want to understand whether there is any potential SDK issue that we didn't find before.

Thanks,

**Comment by steven-chengji-yan** [comment]
Hi yonatanbitton, 

Just want to follow up. Did you fix the issue?

**Comment by yonatanbitton** [comment]
Hey
I just used less data. It still takes around 2 seconds per frame. I opened this issue in order to see if it is normal or to see if I'm doing something wrong. But if everything is normal then ok, I think we can close the issue. Thanks for the assistance.

**Comment by steven-chengji-yan** [comment]
Hi yonatanbitton,

2 seconds per frame is not normal.
In our sample app, with the fast mode + streaming mode, you should get 20~30 frames per second process rate on Android, depending on your device.

So that is why I would like to learn a bit more from you to see if there is any underlying issue in the SDK or if there is anything we could help on your integration with the SDK.

**Comment by yonatanbitton** [comment]
I figured out why it was slow. 
I had an app was ~2000 images. 
When the app was running in foreground mode, the rate is much faster. 
After few images, when I left the phone, it enters background mode. It still runs, but much slower. 
If I "click" on my phone in order to enter foreground mode, the speed accelerates again. 
So the solution is to keep the app in foreground mode.
