### ISSUE TITLE
complete label list for the mlkit mobile base model 

### ISSUE THREAD

**Issue by LuxsThor** [googlesamples/mlkit#143]
Hi!
I am desperately trying to find a complete List of all the possible label spit out by the base model as described here with apparently 400 labels:
https://developers.google.com/ml-kit/vision/image-labeling
Thanks in advance

best regards

**Comment by chrisito** [comment]
We just published the [label list](https://developers.google.com/ml-kit/vision/image-labeling/label-map) on the ML Kit website, hope this helps!

**Comment by LuxsThor** [comment]
Hi! thanks a lot for the update it helps! I noticed while parsing out the table data that the label indexes are not coherent. for example label number 6 is missing. Is that a mistake or have the labels just been assign in this fashion? I haven't checked the complete list manually. parsing out everything results in a  list with 429 labels not 446. So there must be more inconsistencies. e.g 444 is also missing i just saw at the end.

**Comment by chrisito** [comment]
This is the full label list, over time we have made changes and decided to drop certain labels or combine with others. We could not renumber the index since that would break existing integrations. We'll update the table to clarify this.

**Comment by LuxsThor** [comment]
ok clear thanks
