### ISSUE TITLE
Could you please share tflite barcode model?

### ISSUE THREAD

**Issue by longld103** [googlesamples/mlkit#146]
Could you please share tflite barcode model?

**Comment by chrisito** [comment]
The ML Kit Barcode scanning implementation does not consist of just a TF Lite model, but is a more complex pipeline with multiple models and non-ML processing blocks. We don't have plans to open source the implementation.

Is there a use case that you want to cover that is not covered yet? Thanks.

**Comment by longld103** [comment]
Hi @chrisito , thank for your reply

There are many types of barcode ML Kit can't recognize. So I want to improve it.
Example case of image below: I will redraw to datamatrix standard. But I don't know exact area of barcode.
So, I want use TF Lite model to detect bound of barcode.

![cropped](https://user-images.githubusercontent.com/8160105/93729967-c5f34a00-fbf0-11ea-870d-81398c668f42.jpg)

**Comment by ervlh** [comment]
> Could you please share tflite barcode model?

same with the Text Recognition model

**Comment by jackqdyulei** [comment]
We released a new [barcode SDK](https://developers.google.com/ml-kit/release-notes#august_11_2021), please check whether it fulfill your requirement. Thanks.

ML Kit is free to use however itself is close sourced for models & implementation(with legal rights). So unfortunately we can't provide the model.

**Comment by chappiii** [comment]
also i couldn't scan QR codes version 25 and above
