### ISSUE TITLE
Android documentation typos in code snippets

### ISSUE THREAD

**Issue by Schwaggot** [googlesamples/mlkit#147]
The code snippets on https://developers.google.com/ml-kit/vision/digital-ink-recognition/android have consistent typing errors:

* DigitalkRecognitionModelIdentifier --> Digital**Ink**RecognitionModelIdentifier 
* DigitalkRecognitionModel --> Digital**Ink**RecognitionModel
* ...

There are similar typos across the code snippets on that page.

**Comment by steven-chengji-yan** [comment]
Hi Schwaggot,

When I search "DigitalkRecognitionModelIdentifier" and "DigitalkRecognitionModel" on the dev doc page, I cannot find any match. Could you point me to the exact section where you saw this?

**Comment by Schwaggot** [comment]
That's strange:
![image](https://user-images.githubusercontent.com/23381725/93867302-235aca00-fcc9-11ea-806c-e8bdab7d6757.png)

**Comment by steven-chengji-yan** [comment]
![Screen Shot 2020-09-22 at 10 30 52 AM](https://user-images.githubusercontent.com/3616861/93916752-da9e1380-fcbe-11ea-8edf-dc6c58765c72.png)
Here is what I see.

Did you turn on some auto-translation? 
Or maybe try to clear cache and then revisit?

**Comment by Schwaggot** [comment]
Appears to be browser related. I had the issue with Firefox, but it works with Chrome for me. Not sure, haven't turned on anything intentionally. Sorry for the inconvenience.
