### ISSUE TITLE
Empty joints for some of the frames I send

### ISSUE THREAD

**Issue by yonatanbitton** [googlesamples/mlkit#148]
Hello
I activate the process by this example here: https://developers.google.com/ml-kit/vision/pose-detection/android

And many times I receive empty joints while accessing the pose landmarks:
```java
ArrayList imagePoseLandmarks = (ArrayList) pose.getAllPoseLandmarks();
if (imagePoseLandmarks.size() == 0){
        Log.d(TAG, "empty joints " + file_name + " number of empty joints : " + empty_joints_num + " file_name: " + file_name);        
        empty_joints_num += 1;
        return null;
}
```
The number of joints I receieve are 0 and I return null instead of the joints. 

The dimensions of all of the images I send are 480 × 640 (width, height). 

Everything else is by the examples you supply. 

I create the options with `PoseDetectorOptions.STREAM_MODE`.
And I prepare the InputImage from bitmap like the example you supplied: 
```InputImage image = InputImage.fromBitmap(bitmap, rotationDegree);```

Does someone has an estimation for the reason it happens? 

Thank you.

**Comment by steven-chengji-yan** [comment]
Hi yonatanbitton,

If it is ok, could you provide some image samples that you cannot get any detection? That will help us reproduce and investigate the issue.

Thanks,

**Comment by steven-chengji-yan** [comment]
About the detector mode, are you still working on the same project you mentioned before?  I remember you said you are running the detector through a set of images. If those images are not consecutive video frames, you are supposed to use PoseDetectorOptions.SINGLE_IMAGE instead of STREAM_MODE.

**Comment by yonatanbitton** [comment]
Hey
Thanks for the clarrification about the `PoseDetectorOptions.SINGLE_IMAGE`. I've tried to use `STREAM_MODE` to improve the runtime. 

I've created an example for you. 
![6](https://user-images.githubusercontent.com/26148975/93813413-bf4dec80-fc5b-11ea-9a39-17382b245cde.png)
This image receives empty joints by the algorithm. 

I also attach parts from the debbuger that shows the empty joints and shows the image bitmap
![Screen Shot 2020-09-21 at 10 39 17 PM](https://user-images.githubusercontent.com/26148975/93813521-e9071380-fc5b-11ea-826f-886283d5dce7.png)

![Screen Shot 2020-09-21 at 10 36 22 PM](https://user-images.githubusercontent.com/26148975/93813510-e5738c80-fc5b-11ea-9178-607103b99f3e.png)

**Comment by steven-chengji-yan** [comment]
Hi yonatanbitton,

I tried your example, I cannot detect the pose with the original image as well. However, cropping it a bit and make the person occupy more area of the photo solve the issue.  In the dev doc, it suggests "ensure that the subject occupies as much of the image as possible"

BTW, the model currently need to find a person's face then detect the pose. In the image you provided, it can still detect the face successfully. However if you have images without face/head at all, it may fail as well.
