### ISSUE TITLE
Digital Ink Recognition: Poor performance given many strokes

### ISSUE THREAD

**Issue by mustafardestroyer** [googlesamples/mlkit#149]
The handwriting recognition API is great! However, it seems to perform best given only a few words and lacks a sense of scale. In my experiments:

- Given full pages of text, it may recognize the entire page as a single "i" character. 
- Given long strings of text it recognizes "............................."
- Newlines are not recognized

Is there a way to achieve better performance on this sort of input using the existing API?

Are there any plans to improve performance for transcribing full pages of text?

Thanks!

**Comment by steven-chengji-yan** [comment]
Hi mustafardestroyer,

Here is a Tip from the dev doc that might help you
https://developers.google.com/ml-kit/vision/digital-ink-recognition/android#writing-area

A more involved solution would be to find a heuristic method to segment the full page into single lines or use some UI to guide your users to write content line by line, and send the single lines individually for recognition.

For multi-line detection, it is an area of active research. We are working on it, but don't have a concrete timeline at the moment.

Thanks :)
