### ISSUE TITLE
Problems in DataMatrix code scanning

### ISSUE THREAD

**Issue by taruntyagi946** [googlesamples/mlkit#15]
### Steps:
1. Clone `googlesamples/mlkit/ios` and `install pods`. 
    At the time of these tests, project is using `GoogleMLKit/BarcodeScanning (0.60.0)`
    It is being run using `Xcode 11.5` on `macOS Catalina 10.15.4`.

2. Run the barcode detector sample code on this image -
![DataMatrix](https://user-images.githubusercontent.com/10864476/84766194-089ff780-afee-11ea-95ca-b3f9ba518955.png)

### Results:
**Actual**: It does not recognize this `DataMatrix` code.
**Expected**: It recognizes this `DataMatrix` code. The code has valid data - 
`HP ProBook 440 G4,Z1Z83UT#ABA,5CD712BZVJ,1y1y0y`

### Verification:
Use an online decoder service - https://online-barcode-reader.inliteresearch.com/
![Verification](https://user-images.githubusercontent.com/10864476/84766586-b27f8400-afee-11ea-979a-9934542e1770.png)

### Additional Info:
1. It is reproducible with `ML Kit for Firebase` sample as well.
2. I tried to change the image _sharpness_ / _contrast_ / _exposure_ & _color_ settings in `Preview.app` on `macOS` to no avail.
3. I also tried to run the camera mode on this image being in focus (while trying to change color  settings mentioned in step 2) and it didn't help either.

**Comment by taruntyagi946** [comment]
Hi Team,

It's been over 2 months since this issue was reported.

Is there any way to know whether -
1) this is considered invalid bug and not being worked on
2) this is considered valid bug and will be fixed in an upcoming release
?

Thanks.

**Comment by twellsrez** [comment]
Hi all,

Any updates here? This ticket has been open 4.5 months now with no response. I have customers who can't perform scanning actions on valid DM codes that other tools can scan easily. I'd really like to be able to find a solution for them.

Thanks!

**Comment by miworking3** [comment]
Hi, we just got back from our research team:
The blurriness and the pixel size of the given image lead to the limitation of the barcode recognition on it:
```Datamatrix size is 26 x 26 and image size is 90 x 78. Considering actual area of DM, every smallest square is of size 1.35 pixel, which is smaller than 3 pixel size criteria we have.
Please note that up-scaling same image will not work here because original image is blurry.
```
