### ISSUE TITLE
java language version

### ISSUE THREAD

**Issue by uchup** [googlesamples/mlkit#150]
why is there no java language version? how do we implement but there is no java language version

**Comment by steven-chengji-yan** [comment]
Hi uchup,

Could you clarify which app are you talking about? A link would be helpful.

**Comment by uchup** [comment]
hi steven

I use java in the android project, but this mlkit example only uses kotlin
is there any version using java all language?

**Comment by steven-chengji-yan** [comment]
This repo contains several apps. Some are in Kotlin, some are in Java, some both.

So I was asking WHICH exactly app you are talking about.   A link to that app's code would be helpful.

**Comment by uchup** [comment]
code project material-showcase @steven-chengji-yan
all code make kotlin

**Comment by steven-chengji-yan** [comment]
I see. That app includes the ODT and Barcode feature. As its names indicates, it is mostly for show case. If you would like to get some sample code for both Java and Kotlin, you can take a look at https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

If you want to reuse some of the code in the showcase app, there are also several ways to convert Kotlin code to Java that you could try: https://www.google.com/search?q=convert+kotlin+to+java+android+studio&oq=convert+kotlin+to+java&aqs=chrome.1.69i57j0l4j69i64l3.4927j0j7&sourceid=chrome&ie=UTF-8
