### ISSUE TITLE
InputImage does not support RGBA 8888

### ISSUE THREAD

**Issue by ZacharyTech** [googlesamples/mlkit#152]
I use `MediaProjection` to capture screen images. `MediaProjection` only supports RGBA 8888. Currently, I need to convert each frame to `Bitmap` before I can use it with M Kit. Is there a better way?

In addition, when the app is in the background, ML Kit will no longer run after a period of time without any prompts or warnings. How can I continue to run ML Kit?

**Comment by cs-googler** [comment]
Hi, RGBA 8888 is not currently supported to be directly consumed by MLKit vision APIs. 

Assuming your app is running in background, ML Kit detectors may stop running in following circumstances: 
1. If you call detector.close()   
2. If you use lifecycle.addObserver(detector), detector will stop on destroy() event
3. Detector stops with OOM
