### ISSUE TITLE
Translator NullPointerException

### ISSUE THREAD

**Issue by kyh8496** [googlesamples/mlkit#155]
debug mode working but not working in release

TranslatorOptions translatorOptions = new TranslatorOptions.Builder()
                .setSourceLanguage(TranslateLanguage.KOREAN)
                .setTargetLanguage(TranslateLanguage.ENGLISH)
                .build();

Translator translator = Translation.getClient(translatorOptions); <<<<====

nullPointerException !!

error message : 
Attempt to invoke virtual method 'com.google.mlkit.nl.translate.Translator com.google.mlkit.nl.translate.TranslatorImpl$Factory.zza(com.google.mlkit.nl.translate.TranslatorOptions)' on a null object reference

Is it related to dexguard?

**Comment by zhouyiself** [comment]
Thanks for the report!
I don't have experience on dexguard, is the crash reproducible if you disable dexguard?

**Comment by DNights** [comment]
This does not error when dexguard is disabled.
It happens when dexguard is activated and com.google.** is ignored.

This is the library version I use.
`implementation 'com.google.mlkit:translate:16.1.0'`

**Comment by DNights** [comment]
Sorry zhouyiself, The problem was solved by updating

[Dexguard update note]
![image](https://user-images.githubusercontent.com/17425202/95291903-6a40e600-08ab-11eb-9373-25e6ef293618.png)
