### ISSUE TITLE
Android/translate sample error when downloading model

### ISSUE THREAD

**Issue by AlexMisiulia** [googlesamples/mlkit#157]
Hi I have this error in log when download "es" model: "com.google.mlkit.common.MlKitException: No existing model file". After several hours I realized that Internet permission is missing in AndroidManifest.xml.

**Comment by zhouyiself** [comment]
Thanks for the report!
We have added it inside the library so App side doesn't have to do it explicitly. The fix will be available in our next release targeting to December.
