### ISSUE TITLE
Record a video with Graphicoverlay

### ISSUE THREAD

**Issue by patolax** [googlesamples/mlkit#159]
I am referring to the face detection sample but this applies to most samples. In the face detection sample, a bounding rectangle is overlayed on top of the camera output. Is there a way to capture a video that includes both camera + graphic overlay?

**Comment by steven-chengji-yan** [comment]
If you are talking about Android, will "adb shell screenrecord" work for you?
https://adbshell.com/commands/adb-shell-screenrecord

**Comment by patolax** [comment]
I am talking about android, sorry.
how can the app user capture a video and save it in the phone gallery? 
adb does not work in that case.
I was able to capture just camera output using MediaRecorder. But it does not capture the overlay.

**Comment by steven-chengji-yan** [comment]
I tried to do some search and found this https://stackoverflow.com/questions/32513379/how-to-record-screen-and-take-screenshots-using-android-api. Could you try if that helps?

This question doesn't seem to be ML Kit-specific though, so I will close it. You could probably follow up in one of those StackOverflow threads :)

**Comment by Mouadabdelghafouraitali** [comment]
@patolax  did you find any solution to do this, right now, I'm using MediaRecorder to generate video file from array of bitmaps

**Comment by patolax** [comment]
@Mouadabdelghafouraitali
