### ISSUE TITLE
the barcode return different values by getDisplayValue and getRawValue

### ISSUE THREAD

**Issue by DaveBoy** [googlesamples/mlkit#162]
when the value type is text,the [doc](https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/Barcode#public-string-getdisplayvalue) "getDisplayValue () will be equal to getRawValue()."is not true.there are "]C1" in getRawValue .i don't know what it is.

barcode: getDisplayValue:00009999991306917902
barcode: getRawValue:]C100009999991306917902
barcode: getValueType:7

![Snipaste_2020-10-15_16-15-14](https://user-images.githubusercontent.com/16101638/96095757-a1457600-0f01-11eb-8754-3d309eb59b5b.png)

**Comment by DaveBoy** [comment]
i found it because of the special barcode is Code 128.
I solved this problem like this:
```
                            String text=barcodeList.get(0).getRawValue();

                            int format=barcodeList.get(0).getFormat();
                            switch (format){
                                case Barcode.FORMAT_CODE_128:
                                    text=text.replace("]C1","");
                                    break;
                                default:
                                    break;
                            }```
I don't know if it's appropriate to do so

**Comment by zhouyiself** [comment]
"]C1" is an identifier to indicate it's GS1-128 standard
https://en.wikipedia.org/wiki/GS1-128

I think your workaround looks appropriate.

**Comment by DaveBoy** [comment]
> "]C1" is an identifier to indicate it's GS1-128 standard
> https://en.wikipedia.org/wiki/GS1-128
> 
> I think your workaround looks appropriate.

thanks for your reply
