### ISSUE TITLE
Face detection and show a smile face and record the vedio on android

### ISSUE THREAD

**Issue by patolax** [googlesamples/mlkit#163]
Is there a way to show a smiley face instead of the bounding box and capture the video like in TikTok? That is real-time recording.

**Comment by bcdj** [comment]
You can use ML Kit to detect the contours of various parts of the face, as well as interesting points (aka landmarks) on the face:

https://developers.google.com/ml-kit/vision/face-detection/android

We also have a quickstart app showing how to do face detection:

https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/facedetector

Based on the contours and landmarks, I think you can draw your own smile face.  You can also work on the recording part separately.  

Good luck!

**Comment by covideoNaveen** [comment]
Hi, I am using virtual background in camera using selfie segmentation. In preview I am able to see the virtual bg using ML but when I record video I can not see the Background, but only the video.
