### ISSUE TITLE
Model Download progress using progressbar

### ISSUE THREAD

**Issue by kuromadara** [googlesamples/mlkit#165]
is it possible to show the progress of downloading a digital ink model using progress bar?

**Comment by steven-chengji-yan** [comment]
Hi kuromadara,
At this moment, the download API doesn't report the exact downloading progress, e.g. 10%, 20%, 50%...
If we see more interests in it, we would consider adding such a support.

Before that, you could consider using a ["spinner"(e.g. barloader)](https://www.google.com/search?q=spinner+UI&tbm=isch&ved=2ahUKEwj7__KAp8HsAhXGAzQIHdQDDYwQ2-cCegQIABAA&oq=spinner+UI&gs_lcp=CgNpbWcQAzICCAAyAggAMgIIADICCAAyBggAEAUQHjIGCAAQBRAeMgYIABAFEB4yBggAEAUQHjIGCAAQBRAeMgYIABAIEB46BQgAELEDOgQIABBDUNgPWM4SYN4UaABwAHgAgAFJiAHXAZIBATOYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=b92NX7uMN8aH0PEP1Ie04Ag&bih=843&biw=1680#imgrc=-FpzX4WsD5IAOM). Show it when start downloading and hide it when done.

**Comment by kuromadara** [comment]
okay thanks I would love to see that feature in future

**Comment by gitMartynas** [comment]
still no progress implemented?

**Comment by listvin** [comment]
You may find useful my answer https://stackoverflow.com/a/78772742/22888686
