### ISSUE TITLE
ios framework binaries without cocoapod

### ISSUE THREAD

**Issue by soufianee** [googlesamples/mlkit#170]
0

i work with dynamic framework in ios xcode including mlkit libraries.

i have already using the firebase libraries and integrated binaries using carthage. see the link below :

https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

now i want to migrate to mlkit by using binaries without cocoapod, like using carthage.

i have already tried some resolution, like :

https://guides.cocoapods.org/plugins/pre-compiling-dependencies.html

but it doesn't work !!!

any help please

thanks

**Comment by bcdj** [comment]
ML Kit does not support carthage.  Cocoapod is the only format it currently supports.
