### ISSUE TITLE
not able to download from the repository 

### ISSUE THREAD

**Issue by NavalKishor** [googlesamples/mlkit#171]
In build.gradle (app level) 
repositories {
   maven { url 'https://androidx.dev/snapshots/builds/6787662/artifacts/repository/' }

   //maven { url 'https://androidx.dev/snapshots/builds/6941498/artifacts' }
}
dependencies {
 implementation 'com.google.mlkit:barcode-scanning:16.0.3'
    // CameraX
    implementation "androidx.camera:camera-camera2:1.0.0-SNAPSHOT"
    implementation "androidx.camera:camera-lifecycle:1.0.0-SNAPSHOT"
    implementation "androidx.camera:camera-view:1.0.0-SNAPSHOT"
// ViewModel and LiveData
    implementation "androidx.lifecycle:lifecycle-livedata:2.2.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.2.0"
}
but Gradle sync failing with

10:57:46 * What went wrong:
10:57:46 Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
10:57:46 > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
10:57:46    > Could not resolve androidx.camera:camera-camera2:1.0.0-SNAPSHOT.
10:57:46      Required by:
10:57:46          project :app
10:57:46       > Skipped due to earlier error
10:57:46    > Could not resolve androidx.camera:camera-lifecycle:1.0.0-SNAPSHOT.
10:57:46      Required by:
10:57:46          project :app
10:57:46       > Skipped due to earlier error
10:57:46    > Could not resolve androidx.camera:camera-view:1.0.0-SNAPSHOT.
10:57:46      Required by:
10:57:46          project :app
10:57:46       > Skipped due to earlier error
10:57:46 
10:57:46 * Try:
10:57:46 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by steven-chengji-yan** [comment]
I assume you got the error when you using the line you commented off.

You missed the "/repository/" part at the end.

Please reopen if that doesn't solve it.

**Comment by NavalKishor** [comment]
Hi @steven-chengji-yan , Thanks for the reply. i had tried both one by one and I am getting result as a failure.
the one which not comment is the current configuration and it gives the error I have reported

**Comment by NavalKishor** [comment]
i have replaced the url from my app level gradle to root level and it fixed my problem.
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://androidx.dev/snapshots/builds/[buildId]/artifacts/repository' }
    }
}

**Comment by steven-chengji-yan** [comment]
It works for me by simply downloading the vision quick start app and change nothing.

I am glad it works for you now.  Thanks for sharing the fix. It might be helpful for others facing similar issue as well.
