### ISSUE TITLE
Pose estimation in landscape

### ISSUE THREAD

**Issue by coreywhiting** [googlesamples/mlkit#172]
Has anyone successfully used the pose estimation in iOS in landscape? I'd like to use front facing camera in landscape, but currently the image gets cropped to 256x256 and then is distorted when trying to plot on the rectangular frame.

Thanks in advance for help on this!

**Comment by miworking3** [comment]
Currently this quickstart app doesn't support landscape orientation. 
The limitation comes from the quickstart app itself, annotation layer, not from API.
The API would returns correct result when setting `visionImage` correctly ([guidance](https://developers.google.com/ml-kit/vision/pose-detection/ios)).
