### ISSUE TITLE
Face Detection was slow in Debug mode - iOS

### ISSUE THREAD

**Issue by sureshmopidevi** [googlesamples/mlkit#173]
I was using `GoogleMLKit/FaceDetection` in one of my private pod as a dependency.  when i run project in `debug` mode. face detection response is very slow (vary between 1 ~ 3 seconds). it is super fast in `Release` mode. 

version: GoogleMLKit/FaceDetection 0.64.0
Xcode: 12.1

**Comment by bcdj** [comment]
GoogleMLKit/FaceDetection cocoapod itself is always pre-built in `Release` mode, even if you run your project in `Debug` mode. Have you measured the latency of the ML Kit face detection API calls themselves (please calculate the average over a large number, e.g. hundreds of calls)?  Also, I assume you are using the [synchronous face detection API ](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L175)for handling a streaming video? If the face detection API itself is not slow, then you may want to look into other parts of your app to see where the slowness come from.  

The full iOS vision quickstart sample apps (in both swift and objc) are located [here](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision).
