### ISSUE TITLE
German Umlaut not supported in barcodescanner (Code-128)

### ISSUE THREAD

**Issue by tlindener** [googlesamples/mlkit#174]
The barcodescanner can't handle "umlaut" in code-128 in qr codes it is no problem.

![grafik](https://user-images.githubusercontent.com/651357/98542992-16eafa80-2292-11eb-95cd-56185fa980b5.png)
The above code is read as "Testgerdt". 
Code is created here:
https://barcode.tec-it.com/de/?data=Testger%C3%A4t

Google Lens suffers the same issue.

**Comment by chrisito** [comment]
Thanks for reporting, we currently don't support [FNC4](https://www.google.com/url?q=https://en.wikipedia.org/wiki/Code_128%23Using_FNC4_to_encode_high_(128%25E2%2580%2593255)_characters&sa=D&usg=AFQjCNF9tt07PsBpZwtrTMD-kX7GO4Rnsw) but will take into consideration for our upcoming update of the API.
