### ISSUE TITLE
Barcode Scanning: Truncated PDF417

### ISSUE THREAD

**Issue by red5leader** [googlesamples/mlkit#175]
So from the old GitHub repo for android-vision there was an open issue https://github.com/googlesamples/android-vision/issues/335 for being able to read PDF417 truncated barcode formats. 

Is PDF417 truncated actually supported now with MLKit `com.google.mlkit:barcode-scanning:16.0.3`

It scans PDF417 just fine but I have been unsuccessful trying to read truncated PDF417 barcodes. If it is supported any guidance on what to send to my `BarcodeScannerOptions` would be most helpful.

Regular PDF417
![image](https://user-images.githubusercontent.com/59453706/98614731-01dc8e80-22c7-11eb-87d4-fa5baaf24bf0.png)

Truncated PDF417
![image](https://user-images.githubusercontent.com/59453706/98614757-11f46e00-22c7-11eb-9fa5-3cfca38d547e.png)

**Comment by laus102** [comment]
I also am having trouble scanning truncated / compacted PDF417 barcodes, albeit with the iOS MLKit SDK.

**Comment by zhouyiself** [comment]
Thanks for the request!
It's not supported currently and will file internal feature request to track this.

**Comment by sybrin-innovations** [comment]
Hey, 

I see on the official MLKit website https://developers.google.com/ml-kit/vision/barcode-scanning/android 

There is support for "Adds support for broken PDF417 start/stop pattern detection," Just wanted to confirm if this works for the truncated issue?

**Comment by rjmangubat23** [comment]
@zhouyiself may I ask if this is supported on latest version?

**Comment by zhouyiself** [comment]
Thanks for bumping this up!

Unfortunately not. Will ping here once there's update.

**Comment by rjmangubat23** [comment]
hello again, @zhouyiself just want to ask if this is supported in latest version?

**Comment by rjmangubat23** [comment]
Hello, for reference
I filed this in MLKit google issue tracker: https://issuetracker.google.com/issues/247450973?pli=1

**Comment by AndreasGabel** [comment]
Truncated PDF417 scanning with MLKit would be very much appreciated.

**Comment by miworking3** [comment]
I'm afraid with the shift of priority in our team, there is no plan in the near future to address this.
