### ISSUE TITLE
Barcode scanner detected CODE128 wrong barcode sometimes poorly

### ISSUE THREAD

**Issue by denonzhu** [googlesamples/mlkit#176]
![申通条码异常件](https://user-images.githubusercontent.com/5187679/98619603-8b7b7300-233e-11eb-99c8-bfc03829146d.jpeg)
mlkit had detect to ]C1772011388354748, the true value is 772011388354748

`
implementation 'com.google.mlkit:barcode-scanning:16.0.3'
`

**Comment by zhouyiself** [comment]
"]C1" is an identifier to indicate it's GS1-128 standard
https://en.wikipedia.org/wiki/GS1-128

Please refer to https://github.com/googlesamples/mlkit/issues/162 for the workaround.
