### ISSUE TITLE
How can i use a Stream instead of the Camera?

### ISSUE THREAD

**Issue by PortScanner** [googlesamples/mlkit#177]
How can i use a Stream instead of the Camera?
Thanks

**Comment by steven-chengji-yan** [comment]
Hi PortScanner, 

This repo has both Android and iOS samples. Could you clarify which platform you are talking about? It would be even better if you could tell us which app/feature you are referring to.

Thanks

**Comment by cs-googler** [comment]
If you want to use a video as an input instead of Camera. You will need to write your own class to extract the video Frame from asset and then construct a MLKit InputImage to be processed frame by frame.

**Comment by PortScanner** [comment]
@steven-chengji-yan 
Sorry! I want to use it for android.
@cs-googler
Thanks for your suggestion.

I am currently in the process of separating the Custom Object Detection (Bird Classification) in my own app. But think it's too complicated for me. I would like to run the bird.tflite model on my Raspberry Pi. But the bird.tflite is incompatible and I can't find a solution anywhere.
Thanks a lot!

**Comment by ZeroOneZeroR** [comment]
May be [this](https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video)  is what you need.
https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video

**Comment by duckyngo** [comment]
You can easily use the [Fast-Video-Frame-Extraction](https://github.com/duckyngo/Fast-Video-Frame-Extraction) to extract all the frames in video with high speed then apply MLKit Pose Extraction with STREAM_MODE on all frames.
