### ISSUE TITLE
iOS examples fail to build on Apple Silicon Mac/Developer Transition Kit

### ISSUE THREAD

**Issue by thillsman** [googlesamples/mlkit#178]
I'm using the Developer Transition Kit (DTK) which has an Apple Silicon ARM architecture. After a straight download of the repo and `pod install` with Cocoapods 1.10.0, the example iOS projects (for Translate and Smart Reply, at least) fail to build with these errors, respectively.

Translate
```
ld: building for iOS Simulator, but linking in object file (/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/translate/Pods/MLKitTranslate/Frameworks/MLKitTranslate.framework/MLKitTranslate) built for iOS, file '/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/translate/Pods/MLKitTranslate/Frameworks/MLKitTranslate.framework/MLKitTranslate' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Smart Reply
```
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/smartreply/Pods/MLKitLanguageID/Frameworks/MLKitLanguageID.framework/MLKitLanguageID' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm unsure if it's project configuration thing or a dependency limitation at the moment. Any help would be appreciated!

**Comment by bcdj** [comment]
ML Kit is not yet supported on Apple Silicon Arm Macs.

**Comment by thillsman** [comment]
Ok, thanks! I hadn't seen that mentioned anywhere, one way or another, but assumed it could be the case.

**Comment by weibel** [comment]
Is there a timeline for this? It breaks our test builds

**Comment by jasin755** [comment]
After one year no change?

**Comment by weibel** [comment]
@jasin755 This is the issue on Goolges tracker https://issuetracker.google.com/issues/178965151
But yes, after one year no change :-(

**Comment by umutmisket** [comment]
Is it still not supported ? I can use ML Kit in one of my projects but i can not use in another but those projects are identical. Any suggestions ?
