### ISSUE TITLE
MLkit barcode scanner cannot decode simple 1D code, Example "5" 

### ISSUE THREAD

**Issue by longld103** [googlesamples/mlkit#18]
<img width="251" alt="Screen Shot 2020-06-17 at 10 26 38 AM" src="https://user-images.githubusercontent.com/8160105/84878443-0b652000-b0b4-11ea-9355-d80ca530acf0.png">

Can't read barcode of one character

**Comment by calren** [comment]
Hey @longld103 , I believe this barcode format isn't supported https://developers.google.com/ml-kit/vision/barcode-scanning#key_capabilities .

**Comment by longld103** [comment]
@calren It is Code 128 format, which format is supported as your link
