### ISSUE TITLE
Pose detection with video input?

### ISSUE THREAD

**Issue by linsea** [googlesamples/mlkit#181]
The demo shows pose detection with camera preview input source (STREAM_MODE) and image source (SINGLE_IMAGE_MODE), I want to play a local video file and show  pose detection result overlays on it, is that possible? How can I achieve  that, any clue? 
Thank you in advance.

**Comment by linsea** [comment]
android platform, thanks.

**Comment by steven-chengji-yan** [comment]
I haven't done this before, but didn't some Google search and found the followings:

[MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever)
[MediaMetadataRetriever get frame](https://www.google.com/search?hl=en&sxsrf=ALeKk03alP-tGTfgeGv8uh1YmoX25_hvDA%3A1605643381580&ei=dSy0X_b1IpK-tQXN677QBw&q=MediaMetadataRetriever+get+frame&oq=MediaMetadataRetriever+get+frame&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQR1AAWABglvEKaABwA3gAgAEAiAEAkgEAmAEAqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwi2hJTbr4rtAhUSX60KHc21D3oQ4dUDCA0&uact=5)
[StackOverflow: Getting frames from Video Android](https://stackoverflow.com/questions/10102242/getting-frames-from-videos-android)
[MediaMetadataRetriever.getFrameAtTime() returns only first frame](https://stackoverflow.com/questions/12772547/mediametadataretriever-getframeattime-returns-only-first-frame)

You will probably need to dig a bit more into it based on these pointers to find a most optimal solution for yourself.

Hope it helps, more or less.

**Comment by duckyngo** [comment]
I tried some methods to deal with this problem before. 

First method:
I use MediaMetadataRetriever.getFrameAtTime() to get each frame in a particular time but it really slow. Also, I feel that we can't get exactly all the frames in the video in this way.

Second method: 
I use the [ExtractMpegFramesTest](https://bigflake.com/mediacodec/#ExtractMpegFramesTest) to render all the frames to an off-screen pbuffer and then saved as PNG. This method is much faster than the above method and you can generate all frames in the video.

**Comment by steven-chengji-yan** [comment]
Thanks duckyngo!

Hi linsea, could you let us know if the pointer duckyngo gave helps?

**Comment by steven-chengji-yan** [comment]
Friendly ping.
Hi linsea, does duckyngo's suggestion hepl?

**Comment by linsea** [comment]
> Friendly ping.
> Hi linsea, does duckyngo's suggestion hepl?

sorry, @steven-chengji-yan , the projec has postpone this research recently，I will give feedback once we restart this work. thank you.

**Comment by cs-googler** [comment]
Please let us know if you encounters any problem with MLKit APIs:)

**Comment by osmium8** [comment]
Is it possible to compare postures from a pre-recorded video with postures from live camera feed?

**Comment by steven-chengji-yan** [comment]
It is for sure possible and we know some developers already launched their apps for dancing learning by doing so using ML Kit Pose Detection. (example: https://www.groovetime.com/)

Once you are able to detect pose from both video input and live camera feed, the challenging part you need to figure out is how to match the frames and results from the two sources. One way to do it is probably just by time: e.g. playing the video on the screen, and let users to follow and expect at any given time, user's pose should match the pose in the video if they are doing it right.

**Comment by osmium8** [comment]
> It is for sure possible and we know some developers already launched their apps for dancing learning by doing so using ML Kit Pose Detection. (example: https://www.groovetime.com/)
> 
> Once you are able to detect pose from both video input and live camera feed, the challenging part you need to figure out is how to match the frames and results from the two sources. One way to do it is probably just by time: e.g. playing the video on the screen, and let users to follow and expect at any given time, user's pose should match the pose in the video if they are doing it right.

@steven-chengji-yan the **points we get per second** from live camera using ml-kit are not fixed, am I right? If not then how can we compare?

**Comment by steven-chengji-yan** [comment]
You could do this:
- You need some trick to align the video and user input by time. One option is to play the video on the screen and instruct the user to follow.
- Now if the user follows correctly, the user should do the same pose at n-th second as the pose at n-th second in the video. 
- Then you can compare.

Do I misunderstand your use case?

**Comment by ZeroOneZeroR** [comment]
May be [this](https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video)  is what you need.
https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video

**Comment by duckyngo** [comment]
You can easily use the [Fast-Video-Frame-Extraction](https://github.com/duckyngo/Fast-Video-Frame-Extraction) to extract all the frames in video with high speed then apply MLKit Pose Extraction with STREAM_MODE on all frames.

**Comment by anujkapoor** [comment]
@osmium8 @steven-chengji-yan were you able to implement this comparison? Any repository or pointers you have? We are trying to do the same thing.

One option, I think, could be to pick frames from live video and recorded video every 500ms. Now compare one frame from live video, to 5 frames before and 5 frames after the current frame in the recorded video and choose the best match. This will take care of the delay of action in recorded video and live video. Obviously the values 500ms, 5 frames can be configured as per need.
