### ISSUE TITLE
Callbacks after detecting pose on a bundle of images

### ISSUE THREAD

**Issue by duckyngo** [googlesamples/mlkit#185]
I am using MLKit Pose Detection for detecting the human pose on a bundle of images. 
Now I am facing a problem that I need to have a callback when all the images are done

I can get a callback when a single image is completed by using the following code: 

`        detectInImage(inputImage)
                .addOnCompleteListener(result->{
                   ...
                })
                .addOnSuccessListener(
                       ...
                .addOnFailureListener(
                        executor,
                        e -> {
                           ...
                        });
`

I need to have a callback when all the images are finished to do further processing. I don't have much experience with asynchronous so I feel a little confusing at this task. 
I have been tried to count the number of the completed task and compared with the total number of images but I think it is not a good idea since my app will be stuck if some task is not completed 

I would appreciate it if you could give me some advice to deal with this situation.

**Comment by steven-chengji-yan** [comment]
If the process on a certain image takes longer, what do you want to do? Just ignore results from that image? If so, you could try the [Tasks.await API with timeout](https://developers.google.com/android/reference/com/google/android/gms/tasks/Tasks#public-static-tresult-await-tasktresult-task,-long-timeout,-timeunit-unit).  However, when doing Tasks.await, it will block on the task until it is done or timeout. If you still want to maximize the benefit of multiple thread, could you create an Executor e.g. [newCachedThreadPool](https://developer.android.com/reference/java/util/concurrent/Executors#newCachedThreadPool()) and use it to execute the process tasks and wait.

One step back, for your current code, when you add listeners, what executor are you using? If that is a multi thread executor, your current implementation might count the complete task wrong, if you don't do any synchronization. Two ways to fix that: (1) don't pass in the executor param and let it use main thread by default to execute the listener logic; (2) Use AtomicInteger or the synchronized key word for updating the count.

**Comment by duckyngo** [comment]
Thank you for your answer. I recently asked the question about detecting the pose on all frames from the video. After taking all the frames from the video I using Pose Detection for extracting human pose from single images. 

I based on the ML Kit Pose Detection example for detecting the pose and the code for detecting all frames as follow:

```
        // frameList: List of frames
        val completeTaskCount = 0
        for (i in 0 until frameList.size) {
            inputImage = InputImage.fromBitmap(frameList[i].getBitmap(), 0)
            detectInImage(inputImage).addOnCompleteListener(result->{
                completeTaskCount += 1
                if (completeTaskCount == frameList.size){
                    ...
                    // I need a callback here after all the frame are complete
                }
            })
        }
```

All other part is in [VisionImageProcessor ](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/VisionImageProcessor.java) interface.  

I tried to count the number of the completed task and compared it with the total number of images as the above code. I implemented the counter in OnCompleteListener without passing any executor param so I think the code will run on the main thread. The current code works but I think it is not a good idea since my app will be stuck if some task is not completed.

**Comment by steven-chengji-yan** [comment]
Have you seen any real cases that one task take a much much longer time than other process?

Based on the current API implementation, large image will take longer to process, but there shouldn't be any deadlock issue that you need to wait for arbitrary long time.  The task may fail though.   To take failure into consideration as well, you could either use the addOnCompleteListener callback to catch both success or failure OR adding onCancel and onFailure listener to your current implementation.

If you feel strong about the case that one process() run very long, you could consider using the Task.await() API with timeout mentioned previously.

**Comment by duckyngo** [comment]
Thank you a lot for your recommendation about the onCancel and on Failure listener to catch all the cases. I have never seen a case that one task takes much much longer time than others. If the image resolution is large then it takes a longer time to process.
The Task.await() API with timeout also very useful. I will consider using that if I had problems with arbitrary long time processes.
