### ISSUE TITLE
Pixel 2XL setTargetResolution causes all input image size to 1200x1200 and breaks barcode scanning

### ISSUE THREAD

**Issue by simonxcheng** [googlesamples/mlkit#187]
Device: Pixel 2XL
Build number: RP1A.201005.004
OS: Android 11
Camera2 version: 1.0.0-beta12, 1.0.0-beta9, 1.0.0-SNAPSHOT
Video link: https://photos.app.goo.gl/7xVsKodUPGn2FrVr9

Steps to reproduce:
1) Open Vision-quickstart app
2) click on "Run the ML Kit Quickstart written in Kotlin"
3) click on the third choice "CameraXLivePreviewAcitivity"
4) Choose Barcode Scanning from the popup menu at the bottom of the screen (default value is Object Detection)
5) Aim the camera to a QR code, you will see the content of the QR code printed at the top of the object
6) Change the CameraX target resolution to any values by clicking the top right corner setting icon
7) Observe the preview gets very slow and no QR code content will be printed on the screen and the input image resolution is alway 1200x1200 no matter which resolution to choose

**Comment by steven-chengji-yan** [comment]
Thanks for recording the video. That's helpful.

Here are several things you could try first:
1. After changing the resolution to 400x400, could you exit the activity/app and re-start to see if the input image resolution change from 1200x1200 to something smaller.   If that is the case, it could be several 1200x1200 queued up earlier and when you switch to 400x400, it was still processing some of the 1200x1200 images.
2. If 1 doesn't explain the issue, could you try changing the resolution to something even smaller, e.g. 100x100 and see if it still show 1200x1200?
3. For not able to detect issue, not sure if it is related to https://github.com/googlesamples/mlkit/issues/167. Could you try to lower the camerax dep version as mentioned [here](https://github.com/googlesamples/mlkit/issues/167#issuecomment-720073440) to see if it fix the issue.     The ML Kit side fix of this will be in the coming December release.

**Comment by simonxcheng** [comment]
Hi Steven, thanks for your reply:
1. Restart app does not work. Resolution is still 1200x1200
2. Set to 100x200 does not help. Resolution is still 1200x1200
3. I have tried CameraX beta7. No luck.
All other testing phones (Samsung S8, Note 8, Pixel 1, Huawei P20 Pro, etc. are all fine. So, I guess this problem is only for Pixel 2XL. I have reported a bug to CameraX as well: https://issuetracker.google.com/issues/174065186

**Comment by steven-chengji-yan** [comment]
I don't have a Pixel 2XL to help reproduce it right now.
 
Could you try just using CameraX without MLKit by following instruction [here](https://developer.android.com/training/camerax/analyze) and check the size of the image you get in analyzer? 

This could help us confirm whether it is CameraX issue or ML Kit sample app issue.
When doing that, please use the same camerax dep version.

Thanks!

**Comment by simonxcheng** [comment]
It is not easy to disable MLKit in the sample app, so I removed MLKit in my company's code and the size of the image is still 1200x1200 even I setTargetResolution to 960x720 or 100x100. So I guess the problem is coming from CameraX.

On sample app, with 1200x1200, Object Detection, Face Detection, Pose Detection are working but very slow. For example FaceDetect FPS is 5 and latency is 50ms.

Hope these experiments will help.

**Comment by simonxcheng** [comment]
I have some finding here: https://issuetracker.google.com/issues/174065186
Conclusion:
1) On Pixel 2XL, setTargetResolution will NOT automatically fall back to the next available supported resolution
2) On Pixel 2XL, BarcodeScanner is not working with images of which resolution is higher than 480x640.

**Comment by steven-chengji-yan** [comment]
Note for future readers: please check https://issuetracker.google.com/issues/174065186 for discussion details.
