### ISSUE TITLE
Only face bounding box is none

### ISSUE THREAD

**Issue by lbq779660843** [googlesamples/mlkit#189]
When I run facedetector in my android phone and using the java demo, I find only 'face.getBoundingBox()' can make out the result but other APIs , such as face.getHeadEulerAngleX and face.getLandmark, don't work normally although the window correctly shows the bbox and these key points.
![3](https://user-images.githubusercontent.com/27773249/100214484-e8844500-2f4a-11eb-88da-6e70d891b831.PNG)

**Comment by cs-googler** [comment]
Hi,

In order to detect landmarks you will need to enable it in the demo app settings. Check [the documentation](https://developers.google.com/ml-kit/vision/face-detection/android#1.-configure-the-face-detector) to see how it works.  If you have already enabled it in the setting, could you share all options you have set for face detection in the demo app?

Thanks!

**Comment by lbq779660843** [comment]
This is my set,
`
    public FaceDetectorProcessor(Context context) {
        this(
                context,
                new FaceDetectorOptions.Builder()
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .enableTracking()
                        .build());
    }
`
and this is my whole code,
`
package com.google.mlkit.vision.demo.java.facedetector;

import android.content.Context;
import android.graphics.PointF;

import androidx.annotation.NonNull;

import android.util.Log;

import com.google.android.gms.tasks.Task;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.demo.GraphicOverlay;
import com.google.mlkit.vision.demo.java.VisionProcessorBase;
import com.google.mlkit.vision.face.Face;
import com.google.mlkit.vision.face.FaceDetection;
import com.google.mlkit.vision.face.FaceDetector;
import com.google.mlkit.vision.face.FaceDetectorOptions;
import com.google.mlkit.vision.face.FaceLandmark;

import java.util.List;
import java.util.Locale;

/**
 * Face Detector Demo.
 */
public class FaceDetectorProcessor extends VisionProcessorBase<List<Face>> {

    private static final String TAG = "FaceDetectorProcessor";

    private final FaceDetector detector;

    public FaceDetectorProcessor(Context context) {
        this(
                context,
                new FaceDetectorOptions.Builder()
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .enableTracking()
                        .build());
    }

    public FaceDetectorProcessor(Context context, FaceDetectorOptions options) {
        super(context);
        Log.v(MANUAL_TESTING_LOG, "Face detector options: " + options);
        detector = FaceDetection.getClient(options);
    }

    @Override
    public void stop() {
        super.stop();
        detector.close();
    }

    @Override
    protected Task<List<Face>> detectInImage(InputImage image) {
        return detector.process(image);
    }

    @Override
    protected void onSuccess(@NonNull List<Face> faces, @NonNull GraphicOverlay graphicOverlay) {
        for (Face face : faces) {
            graphicOverlay.add(new FaceGraphic(graphicOverlay, face));
            logExtrasForTesting(face);
        }
    }

    private static void logExtrasForTesting(Face face) {
        if (face != null) {
            Log.v(MANUAL_TESTING_LOG, "face bounding box: " + face.getBoundingBox().flattenToString());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle X: " + face.getHeadEulerAngleX());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle Y: " + face.getHeadEulerAngleY());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle Z: " + face.getHeadEulerAngleZ());

            // All landmarks
            int[] landMarkTypes =
                    new int[]{
                            FaceLandmark.MOUTH_BOTTOM,
                            FaceLandmark.MOUTH_RIGHT,
                            FaceLandmark.MOUTH_LEFT,
                            FaceLandmark.RIGHT_EYE,
                            FaceLandmark.LEFT_EYE,
                            FaceLandmark.RIGHT_EAR,
                            FaceLandmark.LEFT_EAR,
                            FaceLandmark.RIGHT_CHEEK,
                            FaceLandmark.LEFT_CHEEK,
                            FaceLandmark.NOSE_BASE
                    };
            String[] landMarkTypesStrings =
                    new String[]{
                            "MOUTH_BOTTOM",
                            "MOUTH_RIGHT",
                            "MOUTH_LEFT",
                            "RIGHT_EYE",
                            "LEFT_EYE",
                            "RIGHT_EAR",
                            "LEFT_EAR",
                            "RIGHT_CHEEK",
                            "LEFT_CHEEK",
                            "NOSE_BASE"
                    };
            for (int i = 0; i < landMarkTypes.length; i++) {
                FaceLandmark landmark = face.getLandmark(landMarkTypes[i]);
                if (landmark == null) {
                    Log.v(
                            MANUAL_TESTING_LOG,
                            "No landmark of type: " + landMarkTypesStrings[i] + " has been detected");
                } else {
                    PointF landmarkPosition = landmark.getPosition();
                    String landmarkPositionStr =
                            String.format(Locale.US, "x: %f , y: %f", landmarkPosition.x, landmarkPosition.y);
                    Log.v(
                            MANUAL_TESTING_LOG,
                            "Position for face landmark: "
                                    + landMarkTypesStrings[i]
                                    + " is :"
                                    + landmarkPositionStr);
                }
            }
            if (face.getLeftEyeOpenProbability() != null) {
                Log.v(
                        MANUAL_TESTING_LOG,
                        "face left eye open probability: " + face.getLeftEyeOpenProbability());
            }
            if (face.getRightEyeOpenProbability() != null) {
                Log.v(
                        MANUAL_TESTING_LOG,
                        "face right eye open probability: " + face.getRightEyeOpenProbability());
            }
            if (face.getSmilingProbability() != null) {
                Log.v(MANUAL_TESTING_LOG, "face smiling probability: " + face.getSmilingProbability());
                float smileProb = face.getSmilingProbability();
            }
            if (face.getTrackingId() != null) {
                Log.v(MANUAL_TESTING_LOG, "face tracking id: " + face.getTrackingId());
                int id = face.getTrackingId();
            }
        }
    }

    @Override
    protected void onFailure(@NonNull Exception e) {
        Log.e(TAG, "Face detection failed " + e);
    }
}

`

**Comment by lbq779660843** [comment]
I modify the whole **FaceDetectorProcessor.java** as:
`
package com.google.mlkit.vision.demo.java.facedetector;

import android.content.Context;
import android.graphics.PointF;

import androidx.annotation.NonNull;

import android.util.Log;

import com.google.android.gms.tasks.Task;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.demo.GraphicOverlay;
import com.google.mlkit.vision.demo.java.VisionProcessorBase;
import com.google.mlkit.vision.face.Face;
import com.google.mlkit.vision.face.FaceDetection;
import com.google.mlkit.vision.face.FaceDetector;
import com.google.mlkit.vision.face.FaceDetectorOptions;
import com.google.mlkit.vision.face.FaceLandmark;

import java.util.List;
import java.util.Locale;

/**
 * Face Detector Demo.
 */
public class FaceDetectorProcessor extends VisionProcessorBase<List<Face>> {

    private static final String TAG = "FaceDetectorProcessor";

    private final FaceDetector detector;

    public FaceDetectorProcessor(Context context) {
        this(
                context,
                new FaceDetectorOptions.Builder()
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
                        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
                        .enableTracking()
                        .build());
    }

    public FaceDetectorProcessor(Context context, FaceDetectorOptions options) {
        super(context);
        Log.v(MANUAL_TESTING_LOG, "Face detector options: " + options);
        detector = FaceDetection.getClient(options);
    }

    @Override
    public void stop() {
        super.stop();
        detector.close();
    }

    @Override
    protected Task<List<Face>> detectInImage(InputImage image) {
        return detector.process(image);
    }

    @Override
    protected void onSuccess(@NonNull List<Face> faces, @NonNull GraphicOverlay graphicOverlay) {
        for (Face face : faces) {
            graphicOverlay.add(new FaceGraphic(graphicOverlay, face));
            logExtrasForTesting(face);
        }
    }

    private static void logExtrasForTesting(Face face) {
        if (face != null) {
            Log.v(MANUAL_TESTING_LOG, "face bounding box: " + face.getBoundingBox().flattenToString());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle X: " + face.getHeadEulerAngleX());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle Y: " + face.getHeadEulerAngleY());
            Log.v(MANUAL_TESTING_LOG, "face Euler Angle Z: " + face.getHeadEulerAngleZ());

            // All landmarks
            int[] landMarkTypes =
                    new int[]{
                            FaceLandmark.MOUTH_BOTTOM,
                            FaceLandmark.MOUTH_RIGHT,
                            FaceLandmark.MOUTH_LEFT,
                            FaceLandmark.RIGHT_EYE,
                            FaceLandmark.LEFT_EYE,
                            FaceLandmark.RIGHT_EAR,
                            FaceLandmark.LEFT_EAR,
                            FaceLandmark.RIGHT_CHEEK,
                            FaceLandmark.LEFT_CHEEK,
                            FaceLandmark.NOSE_BASE
                    };
            String[] landMarkTypesStrings =
                    new String[]{
                            "MOUTH_BOTTOM",
                            "MOUTH_RIGHT",
                            "MOUTH_LEFT",
                            "RIGHT_EYE",
                            "LEFT_EYE",
                            "RIGHT_EAR",
                            "LEFT_EAR",
                            "RIGHT_CHEEK",
                            "LEFT_CHEEK",
                            "NOSE_BASE"
                    };
            for (int i = 0; i < landMarkTypes.length; i++) {
                FaceLandmark landmark = face.getLandmark(landMarkTypes[i]);
                if (landmark == null) {
                    Log.v(
                            MANUAL_TESTING_LOG,
                            "No landmark of type: " + landMarkTypesStrings[i] + " has been detected");
                } else {
                    PointF landmarkPosition = landmark.getPosition();
                    String landmarkPositionStr =
                            String.format(Locale.US, "x: %f , y: %f", landmarkPosition.x, landmarkPosition.y);
                    Log.v(
                            MANUAL_TESTING_LOG,
                            "Position for face landmark: "
                                    + landMarkTypesStrings[i]
                                    + " is :"
                                    + landmarkPositionStr);
                }
            }
            if (face.getLeftEyeOpenProbability() != null) {
                Log.v(
                        MANUAL_TESTING_LOG,
                        "face left eye open probability: " + face.getLeftEyeOpenProbability());
            }
            if (face.getRightEyeOpenProbability() != null) {
                Log.v(
                        MANUAL_TESTING_LOG,
                        "face right eye open probability: " + face.getRightEyeOpenProbability());
            }
            if (face.getSmilingProbability() != null) {
                Log.v(MANUAL_TESTING_LOG, "face smiling probability: " + face.getSmilingProbability());
                float smileProb = face.getSmilingProbability();
            }
            if (face.getTrackingId() != null) {
                Log.v(MANUAL_TESTING_LOG, "face tracking id: " + face.getTrackingId());
                int id = face.getTrackingId();
            }
        }
    }

    @Override
    protected void onFailure(@NonNull Exception e) {
        Log.e(TAG, "Face detection failed " + e);
    }
}
`

**Comment by cs-googler** [comment]
Hi, the landmark results and other informations should be returned with exactly the same setting. You mentioned that you the key points are showing in the Screen. It might be possible that you only print log when landmarks are null. Could you also print when there is landmark results to see if they are always null? If it doesn't help,  feel free to [report a bug]([url](https://b.corp.google.com/issues/new?component=897785&template=1457144)) with a logcat trace or bugreport to us.

**Comment by lbq779660843** [comment]
Thanks for your reply.
I get and I change as what you mentioned, but I find the landmark results are still null while I check through the whole logcat. I think there is something wrong in calling '**Face.calss**'. Otherwise, these face Euler Angles are not equal to zero at least.
![捕获](https://user-images.githubusercontent.com/27773249/101304728-ec359700-387b-11eb-8bde-7c155702ab4b.PNG)

**Comment by cs-googler** [comment]
I see. I think the problem is that the test app respect settings from the app which will override the FaceDetectorOptions you have in the code. The settings button stays on the top right corner of the live preview activity. If you open the settings button and scroll down, you will find the face detection related options.

**Comment by lbq779660843** [comment]
I make it works as what you said, thanks!
http://loc.dingtalk.com/9cb6d331e043a842e03c43132cc7aba6cf58fd2975b9956acd8b8d46ea038492QzpcVXNlcnNcYWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDY5MjA1ODUyMl92MlxJbWFnZUZpbGVzXDE2MDc2Nzc3MjE2OTdfNjJDNTAyREUtQzk2Qy00ZTg3LTgzOTItMzVFNzMxNDkwRjBFLnBuZw==

**Comment by cs-googler** [comment]
Anytime:) !
