### ISSUE TITLE
Android Material Showcase - Use CameraX + PreviewView?

### ISSUE THREAD

**Issue by michaelcarrano** [googlesamples/mlkit#19]
Hi,

I really like these samples and was wondering if there are plans to update [android/material-showcase](https://github.com/googlesamples/mlkit/tree/master/android/material-showcase) to use CameraX + PreviewView.

If not, can you explain the technical reason(s) why this cannot be done?

I noticed there is this PR - #14 to update the translate-showcase sample to use CameraX + Preview.

Thanks!

**Comment by sheepmaster** [comment]
Indeed! 🙂  This is in progress.
