### ISSUE TITLE
OutOfMemoryError after around 100 scans

### ISSUE THREAD

**Issue by kriefsacha** [googlesamples/mlkit#190]
Hi,

I'm using the ML Kit feature on my app to scan QR Codes but i have an issue.

I need to do multiples scans one after the next.

After around 100-200 scans (depends on settings), i have an OutOfMemoryError.

I wanted to know if you can help about this.

Thank you !

**Comment by chrisito** [comment]
Thanks for filing, is this on Android or iOS? Can you please provide the following info as well?
- OS version
- Device model
- If you're using the bundled or unbundled version of the Barcode API? (only applicable to Android)
- Example of barcode you're scanning so we can reproduce

**Comment by chrisito** [comment]
Friendly ping, if you can provide the additional information we can see what is happening, thanks!

**Comment by swiyu** [comment]
I think the reason is that you need to wait for the first image complete before sending a new image.
