### ISSUE TITLE
Firebase Crashlytics issue

### ISSUE THREAD

**Issue by neha16101996** [googlesamples/mlkit#199]
Add the Firebase Android SDK (17.1.1 or higher) or Unity Plugin (6.15.0 or higher), then build, run, and crash your app
View the SDK docs. We’ll be listening for your app to communicate with our servers.I am facing this issue on my firebase either i was already updated dependency for all .Please help how can i resolve it

**Comment by chrisito** [comment]
Can you clarify which ML Kit APIs you are using in your app (gradle dependencies)? Also can you share the exception / crash you are running into (e.g. output you get with 'adb logcat'). This will help us debug this issue. Thanks!

**Comment by chrisito** [comment]
Friendly ping, thanks!

**Comment by neha16101996** [comment]
@chrisito i was updated all the firebase dependencies with new version still i can not caught crashes on firebase

**Comment by cs-googler** [comment]
Hi, this looks like a firebase crashlytics issue. Could you ask it [here](https://github.com/firebase/firebase-android-sdk)?
