### ISSUE TITLE
Google MLKit metrics upload details/communication protocol

### ISSUE THREAD

**Issue by TonyZhang19950601** [googlesamples/mlkit#207]
In the Google ML Kit web documentation it discusses that usage metrics will be uploaded but does not give a lot of detail: https://developers.google.com/ml-kit/terms#privacy

Are these metrics being encrypted in transit (Https etc.)?

**Comment by chrisito** [comment]
Correct, the metrics are encrypted in transit using SSL (Https). We'll add this clarification to our privacy page. Any other clarifications you would like to see there? Thanks!
