### ISSUE TITLE
MLKit Android with JNI on edge device?

### ISSUE THREAD

**Issue by yangcheng** [googlesamples/mlkit#209]
Hi I am working on an app on edge device that has a NPU, they have a tool to convert tflite model to a quantized model optimized on their NPU and in generally 2-10x faster than running directly on CPU.  However, their SDK requires using JNI calls. how could I replace MLKit's model loading and inference part with device specific APIs ?

Thanks

**Comment by zhouyiself** [comment]
Could you clarify which MLKit API you're using? MLKit currently only support custom model as input for Image Labeling and Object Detection API, but model loading and inference part are not customizable.
https://developers.google.com/ml-kit/custom-models

**Comment by yangcheng** [comment]
I am trying to use pose detection, so do I need to use mediapipe if I need to customize model loading and inference?

**Comment by steven-chengji-yan** [comment]
Hi yangcheng,

As you mentioned, for more advanced customization(quantized model, loading, inference), using mediapipe directly would be easier. 
Thanks for bringing this up though. We will keep it in mind and if we get decent amount of related requests, we will consider adding some sort of that support as well.

Best,

**Comment by linnaok** [comment]
Hi I am working on an app on edge device that has a NPU, they have a tool to convert tflite model to a quantized model optimized on their NPU and in generally 2-10x faster than running directly on CPU. However, their SDK requires using JNI calls. how could I replace MLKit's model loading and inference part with device specific APIs ?

Thanks

**Comment by ai-plays** [comment]
This is not supported by ML Kit at the moment. Could you use [TFLite interpreter](https://www.tensorflow.org/lite) for specific languages directly?
