### ISSUE TITLE
VisionProcessor can only run 2 processors at once

### ISSUE THREAD

**Issue by some2014** [googlesamples/mlkit#212]
Dear developers:

VisionProcessor can only run 2 processors at once, and more than 2 processors will not work.

**Comment by zhouyiself** [comment]
Thanks for the comment. A bit confused though, what do you mean by "2 processors"? More context or some sample code could help.

**Comment by chrisito** [comment]
Friendly ping, can you provide some sample code so we can help resolve? Thank you.
