### ISSUE TITLE
Proguard Issue of using BarcodeScanner

### ISSUE THREAD

**Issue by mehdi-salehi** [googlesamples/mlkit#213]
Step 1: Describe your environment
Android device: Pixel3
Android OS version: Android 10
Google Play Services version: 17
Firebase/Play Services SDK version: 17
Step 2: Describe the problem:
I would like to use Firebase ML Kit BarcodeScanner, and run into a proguard obfuscating issue . Any groguard guideline/example would be appreciated.

I have added these rules

-keepnames class com.google.firebase.** { *; }
-keepnames class com.google.android.gms.** { *; }

sample code:
BarcodeScanner scanner = BarcodeScanning.getClient();

after shrinking by proguard:

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl$zza.zza(com.google.mlkit.vision.barcode.BarcodeScannerOptions)' on a null object reference
W/System.err: at com.google.mlkit.vision.barcode.BarcodeScanning.getClient(SourceFile:3)
W/System.err: at com.mrb.cameradetectorlib.DetectorViewModel.barcodeDetector(SourceFile:90)
W/System.err: at com.mrb.cameradetectorlib.DetectorViewModel$processImage$1.invokeSuspend(SourceFile:42)
W/System.err: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
W/System.err: at kotlinx.coroutines.DispatchedTask.run(SourceFile:56)
W/System.err: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:571)
W/System.err: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:738)
W/System.err: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:678)
W/System.err: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:665)

When I added -dontobfuscate to my proguard rules, the initialization works.

**Comment by zhouyiself** [comment]
Are you using DexGuard? If so, it may be a similar issue to  #155 and can be resolved by upgrading DexGuard.

**Comment by chrisito** [comment]
Friendly ping, did zhouyiself's suggestion help? Thanks!

**Comment by thalesbm** [comment]
Hi, I've been getting the same issue:

``` 
Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl 

com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl$zza.zza(o.bqW)' on a null object reference
```

DexGuard, version 8.7.03
implementation "com.google.mlkit:barcode-scanning:16.0.3"

**Comment by cs-googler** [comment]
Hi, could you add this to your proguard rule?
-keepclasseswithmembernames class * {
    native <methods>;
}
This prevents the names of native methods from being obfuscated and prevents UnsatisfiedLinkErrors.

**Comment by cs-googler** [comment]
Hi, could you try to add these to your proguard config?

-dontwarn com.google.firebase.components.Component$Instantiation
-dontwarn com.google.firebase.components.Component$ComponentType
-keep class * implements com.google.firebase.components.ComponentRegistrar

We don't think this is required normally but it worth giving it a try.

**Comment by thalesbm** [comment]
@cs-googler I've added the lines below in my proguard file and it didn't work:

```
-keep class com.google.mlkit.vision.barcode.internal.** { *;} 
-dontwarn com.google.firebase.components.Component$Instantiation
-dontwarn com.google.firebase.components.Component$ComponentType
-keep class * implements com.google.firebase.components.ComponentRegistrar
```

**Comment by thalesbm** [comment]
I've done a few tests, and I think I am getting there.

1. I removed everything related to barcode in my proguard file 
```
Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl o.brt.Ι(o.brn)' 
on a null object reference 
```

2. I added the lines below in my proguard file:
```
-keep class com.google.mlkit.**  { *; }
-keep enum com.google.mlkit.**  { *; }
-keep interface com.google.mlkit.**  { *; }

Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl 
com.google.mlkit.vision.barcode.internal.zzd.zzb(com.google.mlkit.vision.barcode.BarcodeScannerOptions)' 
on a null object reference
```

**Comment by thalesbm** [comment]
I was able to get the stacktrace:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl com.google.mlkit.vision.barcode.internal.zzd.zzb(com.google.mlkit.vision.barcode.BarcodeScannerOptions)' on a null object reference
        at com.google.mlkit.vision.barcode.BarcodeScanning.getClient(:3)
        at o.բ.ɩ(:131)
        at o.բ.ı(:90)
        at o.Mn.onResume(:128)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

// code
BarcodeScannerOptions op = new BarcodeScannerOptions.Builder().setBarcodeFormats(
                            Barcode.FORMAT_EAN_13,
                            Barcode.FORMAT_CODE_39,
                            Barcode.FORMAT_QR_CODE,
                            Barcode.FORMAT_ITF).build();

BarcodeScanning.getClient(op).process(InputImage.fromBitmap(bitmap, 0)).addOnSuccessListener(new OnSuccessListener<List<Barcode>>() {
                @Override
                public void onSuccess(List<Barcode> barcodes) {
                    Log.d("TEST_LOG", "SUCCESS");
                }
            }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    Log.d("TEST_LOG", "FAILURE");
                }
            });
```

**Comment by thalesbm** [comment]
We figure out that we were using the dexguard.jar 8.7.03 and the dexguard-gradle-plugin.jar 8.6.09, after we updated both jar files to 8.7.09 it worked fine.

**Comment by cs-googler** [comment]
Awesome! thanks for the updates! It is very helpful for other developers who may also encounter this issue.

**Comment by lalakii** [comment]
```code
-keepclassmembers class com.google.mlkit.vision.barcode.internal.BarcodeRegistrar {
    public <methods>;
}
-keepclassmembers class com.google.mlkit.common.internal.CommonComponentRegistrar {
    public <methods>;
}
```

It's work well for me.
