### ISSUE TITLE
ECI support

### ISSUE THREAD

**Issue by ivan200** [googlesamples/mlkit#214]
Good day
I have a question.
MLKit seems does not support ECI mode inside qr, and for example, in this QR, encoding is not recognized correctly

![photo_2020-12-29 15 42 49](https://user-images.githubusercontent.com/15914922/103286760-01709200-49f2-11eb-9978-5cd7fb24f6b1.jpeg)

Although zxing [can](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java#L91) recognize, as well as apple mlkit.
Are there any plans to add support?

ps. image created with this site: https://www.free-barcode-generator.net/qr-code/#qr-link

**Comment by cs-googler** [comment]
Hi, you can get the result by calling barcode.getRawBytes() and encode it to UTF8.

**Comment by ivan200** [comment]
Inside this barcode is ECI mode indicator, which means to encode next bytes in one of predefined encoding. 
In this case there is indicator for Windows-1251 encoding, and if i "encode it to UTF8", i will have wrong encoding

this indicator is transparent for normal byte reading, and rawBytes is not contain it
and mlkit seems not understand it, since displayValue has wrong encoding

> Extended Channel Interpretation (ECI) mode specifies the character set (e.g. UTF-8) directly. However, some QR code readers do not support ECI mode and will not understand QR codes that use it.

i cant myself set encoding because i dont know which encoding to choose from 20+ variants
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/common/CharacterSetECI.java#L32

**Comment by cs-googler** [comment]
I see. In order to convert the result to a utf-8 format, you will need to detect the encode format of the barcode. This is currently done internally but we have't exposed it in the public API. We will work on supporting this in the next version of barcode detector. Thanks for raising this request!
