### ISSUE TITLE
Any suggestions to recognize DataMatrix behind a film

### ISSUE THREAD

**Issue by yoldar** [googlesamples/mlkit#215]
Thanks Google ML Kit Team for sharing this great lib! I have successfully connected ML Kit to my app and it is working great. But I have one situation when DataMatrix can not be read. It is when DataMatrix behind a film like on image below:

![WhatsApp Image 2021-01-02 at 12 59 13 (1)](https://user-images.githubusercontent.com/1597578/103457301-4402d900-4d28-11eb-9f53-be4726c18b79.jpeg)

Could you suggest something to make it possible to recognize DataMatrix? May be by adding some filters to image?

**Comment by miworking3** [comment]
Hi, we got the insight from research team that: `Yes, it is very blurry and small. We will need approx 3 pixels per smallest square in datamatrix. So, even if this was not as blurry, this would likely fail due to size issue.`. Thanks!

**Comment by yoldar** [comment]
Hi! @miworking3! Thanks for advise! Happily I have solved this issue by adding some contrast to the image.
