### ISSUE TITLE
ML kit pose detection for Windows 10?

### ISSUE THREAD

**Issue by kevinliu-ez** [googlesamples/mlkit#216]
could you consider to release Windows 10 version? thanks a lot!

**Comment by steven-chengji-yan** [comment]
Hi Kevin,

ML Kit focuses on mobile and we don't have plan to support desktop in near future.

For pose detection on desktop, you can try https://google.github.io/mediapipe/solutions/pose.html

**Comment by Y-PLONI** [comment]
The link is not correct

**Comment by ai-plays** [comment]
Mediapipe changed their website. You can probably follow their github https://github.com/google-ai-edge/mediapipe and post question their for a desktop solution.
