### ISSUE TITLE
Undefined symbols for architecture armv7:   "_OBJC_CLASS_$_MLKTextLine"

### ISSUE THREAD

**Issue by chitrakhatri-ios** [googlesamples/mlkit#219]
Hello,

I can run the application on device and simulator perfectly. But when I am trying Archive the application I am getting following error.

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MLKTextLine", referenced from:
      objc-class-ref in OCRViewController.o
  "_OBJC_CLASS_$_MLKTextBlock", referenced from:
      objc-class-ref in OCRViewController.o
  "_OBJC_CLASS_$_MLKTextElement", referenced from:
      objc-class-ref in OCRViewController.o
  "_OBJC_CLASS_$_MLKTextRecognizer", referenced from:
      objc-class-ref in OCRViewController.o
  "_OBJC_CLASS_$_MLKVisionImage", referenced from:
      objc-class-ref in OCRViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Solutions I have Tried:

1. Active Architecture Only in pod and in Project->target
Active Architecture Only -> set Yes in Build Settings

2. Link Search Libraries
 Build Settings -> Link Search Path -> Add $(inherited)

3. Framework Search Path
In build Settings -> Framework Search path -> Add $(inherited)

4. Header Search Path
In build settings -> header Search path -> Add $(inherited)

5. Deintegrate Cocoapods and re install again.

6. Cocoapods update

7. Pod file update
post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
    end

Any help would be much appreciated.

Thanks,

**Comment by bcdj** [comment]
The "armv7" architecture shown in the error message is for 32-bit devices (iPhone 5c or older).  ML Kit does not support 32-bit devices (armv7) or simulators (i386).  It only support 64-bit devices (arm64) or simulators (x86_64).  Does your app list armv7 as a supported architecture?  If so, ML Kit cannot support that architecture.

**Comment by blyscuit** [comment]
I can get by using `#if arch(arm64)` to wrap the code that use `MLKit`
```
#if arch(arm64)
import MLKit

class MLKitPassportScannerController: PassportScannerController {

    override func doOCR(image: UIImage) -> String {
        let textRecognizer = TextRecognizer.textRecognizer()
        let visionImage = VisionImage(image: image)
        visionImage.orientation = image.imageOrientation
        do {
            return try textRecognizer.results(in: visionImage).text
        } catch {
            return ""
        }
    }
}
#else
import UIKit

class MLKitPassportScannerController: UIViewController {}
#endif

```
