### ISSUE TITLE
implementation 'com.google.mlkit:translate:16.1.1'  Build Success but  App Run Java.lang.VerifyError

### ISSUE THREAD

**Issue by Pragramer** [googlesamples/mlkit#221]
java.lang.VerifyError: Verifier rejected class com.google.android.gms.internal.mlkit_translate.zzhv: com.google.android.gms.internal.mlkit_translate.zzu com.google.android.gms.internal.mlkit_translate.zzhv.zzc(org.json.JSONObject) failed to verify: com.google.android.gms.internal.mlkit_translate.zzu com.google.android.gms.internal.mlkit_translate.zzhv.zzc(org.json.JSONObject): [0x55] 'this' arg must be initialized (declaration of 'com.google.android.gms.internal.mlkit_translate.zzhv' appears in /data/app/com.aaas-3stodVlVBB2fl11JwztHHQ==/base.apk!classes2.dex)

**Comment by cs-googler** [comment]
Hi, after some google search, [clean your local build dir](https://stackoverflow.com/questions/28031905/java-lang-verifyerror-verifier-rejected-class-on-lollipop-when-using-release-ap) may help. If not, it might be related to your gradle pluglin version(see this [post](https://github.com/CleverTap/clevertap-android-sdk/issues/15)). 

Let us know if it helps!

**Comment by Pragramer** [comment]
VM has multidex support, MultiDex support library is disabled.
    Installing application
    VM has multidex support, MultiDex support library is disabled.
D/AndroidRuntime: Shutting down VM

**Comment by Pragramer** [comment]
May multidex can fix this problem but useless in my project. 
i think is multidex lead this problem, but dont know how to deal with

**Comment by cs-googler** [comment]
Hi could you be more explicit about "also use mlkit:translate successful when create new project."? Did you mean that it works now as you created a new project?

**Comment by Pragramer** [comment]
> Hi could you be more explicit about "also use mlkit:translate successful when create new project."? Did you mean that it works now as you created a new project?

yeah, it works by create a new project use the same gradle envirment , same kotlin version and java version.

someone told me can fix this problem by use MultiDex, I tried failed, my application still doesn't work now.  My device is android 9 and  Vm has multidex support, So it is noting to do with multidex

I try to decompile apk， may it can tell me the crash reason

**Comment by Pragramer** [comment]
Crash Log saied " 'this' arg must be initialized.'
i think may some  standard of compile will lead this problem.

**Comment by Pragramer** [comment]
the problem happened  conflict with other third-library.
