### ISSUE TITLE
Problem when FaceDetection Using ImageProxy.image Object

### ISSUE THREAD

**Issue by chobe111** [googlesamples/mlkit#223]
I use InputImage.fromMediaImage(mediaImage, imageProxy.imageInfo.rotationDegrees) for realtime FaceDetection 

Full Code is below \
`override fun analyze(imageProxy: ImageProxy) {
        val mediaImage: Image? = imageProxy.image

        if (imageWidth == 0) {
            imageWidth = imageProxy.width
        }

        if (imageHeight == 0) {
            imageHeight = imageProxy.height
        }

        if (mediaImage != null) {
            var bitmap = mediaImage.yuvToBitmap()
            bitmap = bitmap.rotate(270F)
            val image = InputImage.fromBitmap(bitmap, 0)
            val image =
                InputImage.fromMediaImage(mediaImage, imageProxy.imageInfo.rotationDegrees)
            detector.process(image).addOnSuccessListener {

                listener(it, imageWidth, imageHeight)
                imageProxy.close()
            }.addOnFailureListener {

                imageProxy.close()
            }
        }
        imageProxy.close()

    }`

but in this code when i use InputImage.fromMediaImage Function Directly the detector can not recognize face
but when i change imageProxy (YUV420_888 Format) to Bitmap and make InputImage From Bitmap the detector recognize face successfully 

i want to Know what am i wrong with my code 

thank you.

**Comment by cs-googler** [comment]
We made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "ML Kit"(without firebase branding) contains all the on-device APIs. [Here's](https://developers.google.com/ml-kit/migration) the migration guide from firebase ML Kit to ML Kit.

For CameraX/camera2 output, we have made some improvement in the new standalone ML Kit. You should be able to do face recognition with the new SDK.

Let us know If you still encounter any problem.
