### ISSUE TITLE
Move optional ML features to dynamic feature modules is not possible

### ISSUE THREAD

**Issue by vkryachko** [googlesamples/mlkit#224]
## Issue migrated from https://github.com/firebase/firebase-android-sdk/issues/1419

https://firebase.google.com/docs/ml-kit/android/reduce-app-size#advanced_move_optional_ml_features_to_dynamic_feature_modules

The doc says that we could move ML to dynamic feature, but I think it will effect the whole firebase app modules because of ComponentDiscoveryService.

All firebase modules depends on registering the extended ComponentRegistrar classes so that FirebaseApp init will discover them via AndroidManifest once. This flow will cause firebase components can't move to dynamic feature while base module has other components.

**Comment by cs-googler** [comment]
The page has already been removed for firebase mlkit and we have this as a known issue in the standalone MLKit's developer doc. Closing

**Comment by smpgallagher** [comment]
Figured it out, 

Step 1. disable MlKitInitProvider in app module
<provider
            android:name="com.google.mlkit.common.internal.MlKitInitProvider"
            android:authorities="${applicationId}.mlkitinitprovider"
            tools:node="remove"
            />
Step 2.
build apk and open the app manifest, find all MLKit Registrars used in your app.
Step 3. 
add all found to an array ArrayList<ComponentRegistrar>;
Step 4.
In the dynamic feature library, call MlKitContext.initialize(context, arr); (in getProvider the service provider);
