### ISSUE TITLE
`FirebaseVisionImage` cannot handle bitmaps when configuration is `HARDWARE`

### ISSUE THREAD

**Issue by vkryachko** [googlesamples/mlkit#226]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4
  * Firebase Component: ML Kit (Database, Firestore, Storage, Functions, etc)
  * Component version: 19.0.3

#### Steps to reproduce:

The library will fail when a `Bitmap` instance with configuration `Bitmap.Config.HARDWARE` is used to create a `FirebaseVisionImage` instance, with the factory method `FirebaseVisionImage.fromBitmap(Bitmap)`.

The error:
`A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc919d000 in tid 11059 (FirebaseMLHandl), pid 10959 (...)`

#### Relevant Code:

```kotlin
// This fails
val image = FirebaseVisionImage.fromBitmap(bitmap)
// This is fine
//val image = FirebaseVisionImage.fromFilePath(context, uri)

FirebaseVision.getInstance().visionBarcodeDetector.detectInImage(image)
    .addOnSuccessListener { Log.d(TAG, "$it") }
    .addOnFailureListener { Log.d(TAG, "$it") }
```

As in the code above, when using `FirebaseVisionImage.fromBitmap(Bitmap)` the error occurs.

In order to get a bitmap with `Bitmap.Config.HARDWARE`:  
```kotlin
val source = ImageDecoder.createSource(context.contentResolver, uri)
ImageDecoder.decodeBitmap(source)
```

**Comment by cs-googler** [comment]
Hi, currently, only ARGB_8888 format bitmap is supported by barcode scanner. Is there a specific reason that you need to use  Bitmap with config Bitmap.Config.HARDWARE? 

Also, we made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit.
