### ISSUE TITLE
Support for FNC2, FNC3, FNC4,... for Code 128

### ISSUE THREAD

**Issue by pkrzyszko** [googlesamples/mlkit#227]
Hi, 

MLKit version: 1.0.0 iOS

I have noticed that result for decoding image below:
![png2](https://user-images.githubusercontent.com/20656009/105032085-90535600-5a56-11eb-85cc-0f8c5cb3ee0b.png)

contains FNC1 as 29 (Ascii code)

Unfortunately there is no FNC2 in result.

Does MLKit support other hidden signs than FNC1 ?

Regards.

**Comment by miworking3** [comment]
Hi,
I'm afraid ML Kit doesn't support FNC2, FNC3 or FNC4 right now, that's why you only got the result of FNC1:

https://developers.google.com/ml-kit/vision/barcode-scanning
```
Note that this API does not recognize barcodes in these forms:

1D Barcodes with only one character
Barcodes in ITF format with fewer than six characters
Barcodes encoded with FNC2, FNC3 or FNC4
QR codes generated in the ECI mode
```
