### ISSUE TITLE
Pose Estimation Delegation

### ISSUE THREAD

**Issue by jalen-launchpad** [googlesamples/mlkit#229]
Hi, I know that there have been questions asked previously about whether or not the Pose Estimation API will have GPU delegation in the future, but will NNAPI and CoreML delegation also be supported?  And is there a better ETA on this now?

Thanks!

**Comment by ksulaimon** [comment]
Hey jalen-launchpad,

Thanks for the question! We're indeed exploring NNAPI and CoreML delegation along with GPU, but we sadly have no ETA on when this will be available. Once we have an update, we will announce it in a blog post and update our main ML Kit website (https://developers.google.com/ml-kit/guides). Please stay tuned!

Thanks!
