### ISSUE TITLE
[Object detection and tracking Android] Lost track and frequently change tracking ID

### ISSUE THREAD

**Issue by truongnhat-ryo** [googlesamples/mlkit#232]
I implement multiple object tracking in STREAM_MODE, enable Detect and track multiple objects and Classify objects with Classification confidence threshold = 0.6. I can track multiple object but object can be tracked across several frames and then lost and then appear again with different ID. Can I extend buffer or memory to remember object across more frames. 
Thank you for help!

**Comment by steven-chengji-yan** [comment]
Hi truongnhat-ryo,

Thanks for the report. Here are several things I would like to check with you:

1. Does it work fine when only tracking one object (disable multiple objects)?
2. Could you share a video to demonstrate the issue you observe? 
adb shell screenrecord /sdcard/odt_lost_tracking.mp4
adb pull /sdcard/odt_lost_tracking.mp4 ~/Downloads

**Comment by steven-chengji-yan** [comment]
Hi truongnhat-ryo,

I just answered another question you posted. Maybe the answer there could help here as well: https://github.com/googlesamples/mlkit/issues/233#issuecomment-774244231

**Comment by steven-chengji-yan** [comment]
Close this issue now, since no reply in 17 days. Feel free to re-open if you want any followups :)

**Comment by Shaitaan9999** [comment]
I like ur application thanks buddy ❤️
