### ISSUE TITLE
 Increase maximum number of detected objects (default = 5)

### ISSUE THREAD

**Issue by truongnhat-ryo** [googlesamples/mlkit#233]
I want to check more than 5 object in every frame to count total number of object in video. 
As docs "Enables multiple objects for detection.
When enabled, the maximum number of detected objects per image is 5.
By default, the detector detects prominent object only."

Are there any method to increase maximum number of detected objects per image. Thanks for help!

**Comment by chrisito** [comment]
The ML Kit ODT API only supports a maximum of 5 objects at this moment. This is to ensure we can ensure performance across a wide range of devices. For a future update when we enable HW acceleration across a wide range of devices we are considering lifting this limitation. Can you outline the use case where you need more than 5 objects?

For now you could take a look at the [TFLite Task library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/object_detector) that supports Object Detection with pre-trained models or your own model.

**Comment by truongnhat-ryo** [comment]
> The ML Kit ODT API only supports a maximum of 5 objects at this moment. This is to ensure we can ensure performance across a wide range of devices. For a future update when we enable HW acceleration across a wide range of devices we are considering lifting this limitation. Can you outline the use case where you need more than 5 objects?
> 
> For now you could take a look at the [TFLite Task library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/object_detector) that supports Object Detection with pre-trained models or your own model.

**Comment by truongnhat-ryo** [comment]
Use case: count total number of products realtime for market research (tracking, not detection because of a very large space, cannot fit into 1 screen).
I have a really strong android phone, is there anyway to increase number "5", if not do your team have a roadmap plan to do that. Thanks

**Comment by steven-chengji-yan** [comment]
Hi truongnhat-ryo,

Are you expecting one object with tracking ID N moving out of the screen and then coming back with the same tracking ID N? This is not supported by this feature now. When an object re-enter, it will get a new tracking ID. Object is only tracked when it stays within the frame.

Based on the current version, if you want to count total object across many frames, you will need to store the detected object image each time, and use a separate algorithm or model to check whether a certain newly detected object is the same object as you stored before.   But this could be hard, as you can imagine, even for a human, it might not be straightforward to tell two objects are the same one if you look at them from different angles. Let along there might be multiple same objects in the space.

**Comment by RajezMariner** [comment]
@chrisito - May I know how to change the code to have more detections for now? I would like to work on this change as per the customization we have. Could you please help me to work on this change. I will have it customised and raise the pull request

**Comment by ai-plays** [comment]
Hi RajezMariner,

This github repo is only for the demo apps, but not for the SDK implementation itself. The SDK is close source.

As mentioned in https://github.com/googlesamples/mlkit/issues/577, at the moment, if I were you, I would try the TFLite Task library first.

**Comment by RajezMariner** [comment]
@ai-plays - we have already tried our use related to tflite task library for detection purpose. Our use case is tracking right now.
