### ISSUE TITLE
InputImage.fromMediaImage ignores cropRect

### ISSUE THREAD

**Issue by ivan200** [googlesamples/mlkit#234]
I'm trying to use simplest qr scanning image analyzer.
And I am trying to scan not the entire area of the screen, but only the center bounded by the frame.
In this example, I set the crop rect for MediaImage, which will be converted to the InputImage and then passed to the scanner.
but scanner still scan entire area

```
override fun analyze(imageProxy: ImageProxy) {
    val mediaImage = imageProxy.image
    if (mediaImage != null) {
        val cropSize = (min(mediaImage.width, mediaImage.height) * 0.6f).toInt()
        val cropRect = Rect(mediaImage.width / 2 - cropSize / 2, mediaImage.height / 2 - cropSize / 2,
            mediaImage.width / 2 + cropSize / 2, mediaImage.height / 2 + cropSize / 2)

        //here i set crop rect
        mediaImage.cropRect = cropRect
        val image = InputImage.fromMediaImage(mediaImage, imageProxy.imageInfo.rotationDegrees)

        //but here scanner wil process whole image instead of small area
        pendingTask = scanner.process(image)
            .addOnSuccessListener { barcodes ->
                //do something
            }
            .addOnCompleteListener {
                imageProxy.close()
            }
    }
}
```

**Comment by cs-googler** [comment]
Hi, this field is not supported by MLKit currently. We are working on supporting it in future releases.

**Comment by G00fY2** [comment]
Is there any progress or an alternative issue that we can subscribe to?

Currently `UseCaseGroup` is pretty much useless since the Analyzer does not use the `cropRect` of input images. Manually cropping images seems to be pretty messy.

Looking forwards for this feature!

**Comment by G00fY2** [comment]
@cs-googler is this feature still in your backlog? Will this available in the future releases?
