### ISSUE TITLE
Same face, trackingID  is changed,leave the camera and enter the camera again,Looking forward to reply

### ISSUE THREAD

**Issue by chenqi2013** [googlesamples/mlkit#235]
![IMG_0025](https://user-images.githubusercontent.com/3961758/106837048-42d11d00-66d5-11eb-95fb-b0cd348d6bc4.PNG)
![IMG_0026](https://user-images.githubusercontent.com/3961758/106837053-45cc0d80-66d5-11eb-877e-a68fa552b67b.jpg)

We want to do face tracking, but the camera points at someone, then the camera leaves that person, and then points at that person again. TrackingID changes. Is that a bug in the library? Can you keep the trakingID the same when it's the same face?

Looking forward to reply

https://user-images.githubusercontent.com/3961758/106873666-a710d280-670f-11eb-8f64-4da633c6ae8a.MP4

**Comment by chenqi2013** [comment]
@tjohns @sheepmaster @pentiumao @michaelcarrano

**Comment by chenqi2013** [comment]
@Addy
@jkammer
@nic0lette
@PaulRashidi
@samtstern
@shrugs	
@thagikura
@yaraki

**Comment by chenqi2013** [comment]
@Addy Osmani
@Julius Kammerl
@Paul Rashidi
@Sam Stern
@Matt Condon
@Takeshi Hagikura
@Yuichi Araki
@Lady Nicole

this is your ios demo

**Comment by addy** [comment]
Wrong addy

**Comment by chenqi2013** [comment]
@addyosmani

**Comment by samtstern** [comment]
@chenqi2013 please don't spam mention people, especially random people who are not related to the issue at hand.

**Comment by bcdj** [comment]
ML Kit supports only face detection, but not face recognition.  If a face #1 leaves the viewport and re-enters, we treat it as a new face #2, so it can get a new face trackingID.  We do not compare face #1 and #2 to recognize them as the same face.

**Comment by chenqi2013** [comment]
> ML Kit supports only face detection, but not face recognition. If a face #1 leaves the viewport and re-enters, we treat it as a new face #2, so it can get a new face trackingID. We do not compare face #1 and #2 to recognize them as the same face.

ok，thank you！!!!
