### ISSUE TITLE
How do I get logo detection to work in ML Kit?

### ISSUE THREAD

**Issue by marklanhamhc** [googlesamples/mlkit#237]
I've been looking for ways to do logo detection in ML Kit but can't find a way to do it.

**Comment by chrisito** [comment]
ML Kit does not have an API to detect logo. However you may be able to train a model yourself using AutoML Vision Edge or TFLite model maker. We provide some guidance on our [Custom Models](https://developers.google.com/ml-kit/custom-models) page.

**Comment by marklanhamhc** [comment]
Ok thanks, we'll look into it.
