### ISSUE TITLE
<GoogleUtilities/GULLoggerLevel.h>' file not found

### ISSUE THREAD

**Issue by itumeleng-mabote** [googlesamples/mlkit#238]
Hi, just imported the latest 'GoogleMLKit/FaceDetection' version through Cocopods and I get `<GoogleUtilities/GULLoggerLevel.h>' file not found` error in Xcode

**Comment by bcdj** [comment]
I was able to build and run the ML Kit's quickstart vision sample app (containing FaceDetection) without problem:

https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision

Could you compare your Podfile with the one in the above folder?  You can also try out the above sample app and compare its Podfile.lock with yours to see if you are installing the same version of cocoapods, especially the versions of those GoogleMLKit and GoogleUtilities cocoapods.  

Also, please make sure you have cleaned your cocoapod cache.  Try delete your "Pods" subdirectory in your project folder, remove Podfile.lock, remove your project's .xcworkspace file, run "pod cache clean --all" followed by "pod update" from your project directory.
