### ISSUE TITLE
iOS MLKDigitalInkRecognitionCandidate score?

### ISSUE THREAD

**Issue by markyama** [googlesamples/mlkit#239]
I’m running MLKitDigitalInkRecognition v1.1.0. After I do recognizeInk: the MLKDigitalInkRecognitionCandidate seem to always return null for the score.

In the console output I see digital ink does have scores. I will see something like:
`best result: '2'  score: 16.1751`

But that info is not returned in MLKDigitalInkRecognitionCandidate.score. Would it possible to get scores back in the candidates? I am using the “en” language.

Thanks

**Comment by bcdj** [comment]
As documented below, only shape classifiers (emoji, autodraw, shapes) provide scores.  For all others, the `score` is expected to be `nil`:

https://developers.google.com/ml-kit/vision/digital-ink-recognition/ios#dealing-with-ambiguous-shapes
