### ISSUE TITLE
Feature request: Add a new offline module for text-recognition

### ISSUE THREAD

**Issue by matpag** [googlesamples/mlkit#241]
Like pretty every other mlkit library, we should have a 
`com.google.mlkit:text-recognition`
with bundled model which works offline without relying on play services to download `ocr` model afterwards

text-recognition is the only missing offline library based on list here:
https://developers.google.com/ml-kit/release-notes#android-api-latest-versions

**Comment by chrisito** [comment]
Great observation! Please stay tuned, we are working on it.

**Comment by yylingsj** [comment]
Nice request.We also need this feature.
