### ISSUE TITLE
mlkit face detection app: 3D contours and accuracy

### ISSUE THREAD

**Issue by zhuofusong** [googlesamples/mlkit#243]
[This link](https://developers.google.com/ml-kit/vision/face-detection/android), which is the official guideline, contains a demo picture at the end of the page showing the contour lines produced by the face detection app. A small question of mine is, how to measure the accuracy of all detected landmarks displayed. For example, the contour FACE_OVAL seems a bit random since in the person's forehead part, it does not follow the hair line. How to measure the accuracy of the contours? Are they linked with 3D head anatomy model? For phone with depth camera, will it be possible to map 3D contours? Thanks!

**Comment by cs-googler** [comment]
Hi ML Kit provides on-device ML models, which needs to balance model size, performance and accuracy. The accuracy is for-sure sacrificed to get better performance and smaller size on wide range of devices. 

Also, contours where never intended for the medical application / ml annotation / sizing etc. They are primarily aimed at fun applications which are using contours to attach 2d objects to the face / do some basic face texture application etc. 

We are working on new models to improve the accuracy / performance but still won't be aiming a quality to be used for medical applications.
