### ISSUE TITLE
Is the smart reply API used by services such as Gmail in their core?

### ISSUE THREAD

**Issue by tomershay** [googlesamples/mlkit#244]
When comparing the suggested replies from Gmail and the ML kit smart reply API for the same input content, we saw that different suggestions are provided from each of services.
Is Gmail using the same core as the smart reply API in the ML kit? If so, what can be the cause for the difference?

**Comment by cs-googler** [comment]
Hi, they're based on similar technology (see also the [TFLite Smart Reply example](https://www.tensorflow.org/lite/examples/smart_reply/overview)), but the exact model architecture is probably different, and they're trained on different data sets. The ML Kit Smart Reply API is pretty close to what Android Messages uses, though.
