### ISSUE TITLE
PoseDetection landmarks

### ISSUE THREAD

**Issue by Ibernato93** [googlesamples/mlkit#248]
Hello and sorry for my english.
I am testing the PoseDetection API and I noticed that even if the shoulders are not present, the landmark points are still detected. Would it be possible not to detect the points when, for example, only the face is framed?

**Comment by steven-chengji-yan** [comment]
Hi Ibernato93, currently the Pose models are expected to work the best with person's full body shown.

To understand your case better, could you help provide the following information:
- When you say "landmark points are still detected", are they detected correctly or incorrectly? Could you share an image if it is incorrect?
- Are you using SINGLE_IMAGE or STREAM mode when seeing the issue?
- Are you using the pose-detection SDK or pose-detection-accurate?
- Could you describe your use case in brief and why returning detection result when only face is in the frame is a problem to you?

Thanks!

**Comment by Ibernato93** [comment]
Hi @steven-chengji-yan 
this is my PoseDetector configuration:

- STREAM mode (liveness process, so frame by frame)
- Accurate pose detection

I want to understand if I am framing only the face or half torso or the whole body.
See the example image. 

![image](https://user-images.githubusercontent.com/19193773/111378119-bc2f3880-86a1-11eb-85fa-bf691f2508a9.png)


I framed a 3d model with only the face (but this happens sometimes even if I frame a real face).
I expect the shoulder stitches to not be drawn, instead some sort of default pattern is applied.
I know that the posedetector works well framing the whole body, but I wanted to understand if there was the possibility of having this function.

Thanks!

**Comment by steven-chengji-yan** [comment]
Thanks for the details.

We will try to work on some fix for this.

In the meantime, is it possible for you to add some hint in your app's UI suggesting users to take photos with full body or at least half body shown?

**Comment by steven-chengji-yan** [comment]
Hi Ibernato93, 

We had some internal discussion. Will need to do some model retraining work to improve this. Our research team is working on it but sorry I can not promise an exact release at the moment.   In the meantime, some UI hints in your app would be a possible workaround.   Thanks for your feedback!

**Comment by Ibernato93** [comment]
Hi steven,
your Welcome!
