### ISSUE TITLE
Is there a way of linking the MLKit to a static framework?

### ISSUE THREAD

**Issue by joaomelo81** [googlesamples/mlkit#25]
I was wondering if I could link the MLKit.TextRecognition into my static framework. The idea is to use the Text recognition task as a pre-process of the task exposed by my static framework. Since the MLKit is provided as a cocoapod distribution, I'm not sure this is possible.

I was able to do similar integration by using the FirebaseMLKit.TextRecognition with Carthage distribution and then linking the related Firebase frameworks into my static framework. Obviously these dependencies must be embedded into target app, but it was working pretty well.

Do you guys have any help on this kind of integration?

**Comment by calren** [comment]
Hey @joaomelo81 , that's an interesting use case! Would you mind posting this question on stackoverflow instead with the tag `google-mlkit` ? Engineers from the ML Kit team are regularly monitoring Stackoverflow questions with that tag. 

Issues filed on this repo are ideally more focused on the samples themselves, so I'm going to go ahead and close this issue for now.

Feel free to ping this thread again if don't get an answer for your question on Stackoverflow after a few days!

**Comment by AngryDuckFTW** [comment]
I have a similar use case did you ever post this and get any feedback on stackoverflow?
