### ISSUE TITLE
Very low FPS for barcode scanning

### ISSUE THREAD

**Issue by Worien** [googlesamples/mlkit#250]
The FPS is very low, when I debug the method selectPreviewFpsRange - the maximum FPS, which camera gives is 30000 (30*1000). Is there any way to increase FPS for barcode example?

**Comment by steven-chengji-yan** [comment]
Hi Worien,

Could you help provide more context?

- The [return value of selectPreviewFpsRange](https://github.com/googlesamples/mlkit/blob/3f41503f4e917129039391d3d4096da6bfa75673/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/CameraSource.java#L475) includes both lower and upper bound. Could you share both numbers by adding some logs?   If the lower bound is very low, in some conditions (e.g. low lighting), the camera will feed in frames with low FPS to make sure decent exposure. 
- Are you using the Android vision quickstart app and checking the FPS number on screen?
- What resolution are you using? 
- What FPS are you getting?
- What devices are you using?
- Could you try **adb logcat | grep "avg"** and share the log about latency here?

Thanks!

**Comment by Worien** [comment]
Hi, I've got all the classes for barcode detection into my app.
I've changed the resolution to:
```
  public static final int DEFAULT_REQUESTED_CAMERA_PREVIEW_WIDTH = 1440;
  public static final int DEFAULT_REQUESTED_CAMERA_PREVIEW_HEIGHT = 1080;
```
The device is Samsung galaxy S10, the low FPS is visible with an eye. 
selectPreviewFpsRange returns [8000, 30000]

Log from grap:

```
 03-23 06:26:50.617 17331 17331 D VisionProcessorBase: Detector latency: max=100, min=6, avg=25
03-23 06:26:51.663 17331 17331 D VisionProcessorBase: Frame latency: max=164, min=48, avg=77
03-23 06:26:51.663 17331 17331 D VisionProcessorBase: Detector latency: max=100, min=6, avg=23
03-23 06:26:52.593  5830  6146 D BatteryService: online:4, current avg:62, charge type:1, POGO powered:false, power sharing:false, high voltage charger:false, charger_type:0, capacity:280000, misc_event:65536, current_event:0, current_now:-298
03-23 06:26:52.606 17331 17331 D VisionProcessorBase: Frame latency: max=164, min=48, avg=78
03-23 06:26:52.606 17331
```

**Comment by cs-googler** [comment]
Thanks for reporting. What barcode format are you trying to detect? Configure the [DetectionOption](https://developers.google.com/ml-kit/vision/barcode-scanning/android#1.-configure-the-barcode-scanner) with a list of known formats may help you detect faster.

Also, could you share a little bit about your use case? I am curious why you have such a requirement for the speed of detecting barcode in streaming mode?

**Comment by Worien** [comment]
Actually, the detection is pretty fast, but the whole video is not really smooth and luggy, the FPS is low and it spoils the user experience.

**Comment by cs-googler** [comment]
I see. are you using CameraX or camera1 api? 

Also, are you showing the camera preview directly or redraw the preview on your own to synchronize with the detection output? In the vision_quickstart app, we have an option to enable "live viewport" to avoid redraw of the preview when presenting detection result in an overlay.

**Comment by Worien** [comment]
I've used classes from example for barcode scanning. For preview I use class CameraSourcePreview. 
I change method isCameraLiveViewPortEnabled to 
```
    public static boolean isCameraLiveViewportEnabled(Context context) {
        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
        String prefKey = context.getString(R.string.pref_key_camera_live_viewport);
        boolean isEnabled = sharedPreferences.getBoolean(prefKey, true);
        Log.d("PreferenceUtils", "isCameraLiveViewportEnabled = " + isEnabled);
        return isEnabled;
    }
```
and preview start to work smoothly, thanks a lot!

**Comment by JeyBi567** [comment]
> I've used classes from example for barcode scanning. For preview I use class CameraSourcePreview. I change method isCameraLiveViewPortEnabled to
> 
> ```
>     public static boolean isCameraLiveViewportEnabled(Context context) {
>         SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
>         String prefKey = context.getString(R.string.pref_key_camera_live_viewport);
>         boolean isEnabled = sharedPreferences.getBoolean(prefKey, true);
>         Log.d("PreferenceUtils", "isCameraLiveViewportEnabled = " + isEnabled);
>         return isEnabled;
>     }
> ```
> 
> and preview start to work smoothly, thanks a lot!

Brother you are the best. Thanks for saving my day and life. RESPECTO <3
