### ISSUE TITLE
What's the timeline or options for GPU acceleration on pose recognition?

### ISSUE THREAD

**Issue by danj96dev** [googlesamples/mlkit#253]
I'm looking for a way to run pose recognition faster on a very slow android device and I wanted to know if GPU acceleration would be available in mlkit soon. I looked at mediapipe and it seems like you're able to build an aar file with the full body model using gpu with bazel. It's a frustrating setup to say the least but is it the only way to run the pose recognition model with a better performance?

**Comment by steven-chengji-yan** [comment]
Hi danj96dev

Thanks for your feedback. As for timeline, some of my teammates could provide better answer, but I would like to understand your use case a bit more:

- Are you using the base SDK or the accurate one? The base one(com.google.mlkit:pose-detection) should be faster.
- Could you share which device you are trying to run Pose Detection on? What is the current per-frame latency you can achieve on that device with the ML Kit quickstart app?
- Are you also doing some other CPU-heavy process which adds load together with Pose Detection to make whole process slow?
- Is your app specifically only targeting low-end devices? 

Some related background:

- GPU delegate is not well-supported on every device. See [here](https://www.tensorflow.org/lite/performance/gpu#tensorflow_lite_interpreter). For some devices, it could be unstable thus not recommended.
- Even if GPU is supported / stable, it might not always be faster than the current optimized CPU version on every device.

**Comment by danj96dev** [comment]
> 
> 
> Hi danj96dev
> 
> Thanks for your feedback. As for timeline, some of my teammates could provide better answer, but I would like to understand your use case a bit more:
> 
>     * Are you using the base SDK or the accurate one? The base one(com.google.mlkit:pose-detection) should be faster.
> 
>     * Could you share which device you are trying to run Pose Detection on? What is the current per-frame latency you can achieve on that device with the ML Kit quickstart app?
> 
>     * Are you also doing some other CPU-heavy process which adds load together with Pose Detection to make whole process slow?
> 
>     * Is your app specifically only targeting low-end devices?
> 
> 
> Some related background:
> 
>     * GPU delegate is not well-supported on every device. See [here](https://www.tensorflow.org/lite/performance/gpu#tensorflow_lite_interpreter). For some devices, it could be unstable thus not recommended.
> 
>     * Even if GPU is supported / stable, it might not always be faster than the current optimized CPU version on every device.

- I'm using the base SDK and the smallest image sizes I can get away with.
- I can detect a pose in about 500ms (half a second). I'm not doing a lot on the cpu, this is just the constraints of the device.

- We are targeting a custom device but the chipset is a: **rockchip rk3288**
- I've also tried using posenet and the gpu delegate was a massive improvement over CPU only.

**Comment by chrisito** [comment]
Thanks for clarifying your use case. We are planning to enable GPU acceleration, although it is not in our immediate roadmap (likely in Q3). What is clear from your ask is that we should provide a way to override the automatic selection of acceleration so developers like you who develop & test for/on specific devices can get good performance. Since we are focused on Android Phones, I doubt we would automatically enable acceleration on rockchip rk3288 since we don't carry this SoC in our test labs.
