### ISSUE TITLE
is it possible to integrate the hand model from MediaPipe as a custom model

### ISSUE THREAD

**Issue by shadow111** [googlesamples/mlkit#257]
Hello,
will it be possible to integrate the hand model from MediaPipe of the hand model?
MediaPipe doc: https://google.github.io/mediapipe/solutions/hands.html
 TF lite hand landmark model: https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite

**Comment by steven-chengji-yan** [comment]
Hi shadow111,

ML Kit currently doesn't provide a Hand API or a custom model API to use the hand model. 
We will consider investing on that direction if we see more similar requests.

Thanks for your feedback!
