### ISSUE TITLE
Is there is a way to install MLKit in iOS project using Carthage or manually?

### ISSUE THREAD

**Issue by D-Link13** [googlesamples/mlkit#26]
I want to use MLKit for barcode scanning in my iOS app where I'm currently using Carthage as a dependency manager. How I can accomplish this?

**Comment by sheepmaster** [comment]
Sorry, ML Kit is currently only available through Cocoapods (https://cocoapods.org/pods/GoogleMLKit).

**Comment by sergerybchinsky** [comment]
But are you going to start to distribute MLKit using Carthage?

**Comment by bcdj** [comment]
It's not currently planned.
