### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by MrSano** [googlesamples/mlkit#261]
Hello, all landmarks are returning null .

The option is on (to get all landmarks).

Is it possible this is mlkit? or is this me? I cant see where im wrong cause it detects face it just doesnt give me the landamarks like never... If anyone can help i appreciate

**Comment by steven-chengji-yan** [comment]
Hi MrSano, would like to collect a bit more info to understand the issue:

- Landmark is a general term. Are you using Face Detection SDK?
- Android or iOS?
- Does the ML Kit sample app work for you on your device?
- Do you get any exception/error log?
- Did you try both single image case and streaming case? Both not working?
- Is there a way that you can verify whether the image you send to ML Kit API is a correct image with content?

**Comment by MrSano** [comment]
Hi steven,
 Yes face detection mlkit
Android
The sample shows contours...not so sure abou landmarks
No errors just an empty list
Im trying using camera frames using cameraX analyser
It detects the face so i guess the image is right...

**Comment by steven-chengji-yan** [comment]
I just tried on a Pixel 3XL with MLKit quickstart CameraX sample, it works fine for me.

Could you try if the ML Kit sample work for you on your device (trying to understand if it is device specific issue)?
If the ML Kit sample works, could you try checking the difference between the two implementations?

I don't have too much idea with the current available info. Some more info would be helpful.

**Comment by MrSano** [comment]
When i wake up ill try it...thx for the info maybe its my device...its recent so idk...galaxy s21 ultra

Ill try to see if i can get the landmaks with the sample

Thanks

**Comment by MrSano** [comment]
Yeah im not detecting landmarks in the sample aswell... and the angles (X,Y and Z) are the 3 at 0... something that dont happen in my implementation...

**Comment by MrSano** [comment]
I think ive found the reason behing this issue... maybe its my bad... but i dont understand why exist both 
"ALL_LANDMARKS"
and 
"FaceDetectorOptions.ALL_LANDMARKS"
they have different values and both belong to same package... can you explain it to me? And thanks once again

**Comment by steven-chengji-yan** [comment]
What is the full package name for ALL_LANDMARKS? We don't have it on the Face Detection API surface: https://developers.google.com/android/reference/com/google/mlkit/vision/face/package-summary

**Comment by chrisito** [comment]
@MrSano friendly ping

**Comment by MrSano** [comment]
Sorry it was my intention to when i got home to answer but i forgot...

https://developers.google.com/ml-kit/vision/face-detection/android here it confused me so I used ALL_LANDMARKS in this  package com.google.android.gms.vision.face;

**Comment by steven-chengji-yan** [comment]
There is some inconsistent in the dev doc. We will update it. Sorry for the confusion and thanks for the report!

**Comment by MrSano** [comment]
No problem it was a small change thanks!
