### ISSUE TITLE
Errors with models, how can I handle it?

### ISSUE THREAD

**Issue by mrjoelc** [googlesamples/mlkit#263]
Hello, 

I'm using 'com.google.mlkit:object-detection-custom:16.0.0' in my android app for making object detection.

1) I've tried multiple models from TensorFlow Hub as 
- mnasnet_0.50_224_1_metadata_1.tflite
- mnasnet_1.3_224
- and others.
I have this problem:

com.google.android.gms.tasks.RuntimeExecutionException: com.google.mlkit.common.MlKitException: Failed to initialize detector. The type of the input TfLiteTensor is expected to be UINT8 (i.e. --inference_input_type=QUANTIZED_UINT8 is assumed), got FLOAT32 

how can I set different inference input type?

2) I want use models trained on COCO dataset but I don't see any of the models for MLKIT in TensorFlow Hub trained on it. If I try to use a model not included in the compatibles one with MLKit the app crash (obviously) and says that input or output is not as aspected. 
How can I modify, if is possible the input or output of a model?

Thanks in advance!

**Comment by steven-chengji-yan** [comment]
The latest version for object detection is object-detection-custom:16.3.1. After switching to the latest version, all models under the TFHUB MLKit collection should work. https://developers.google.com/ml-kit/custom-models#tfhub

TFLite Model Maker can produce model that is compatible with MLKit via transfer learning https://developers.google.com/ml-kit/custom-models#tensorflow_lite_model_maker Can you make use of it and feed in your dataset?

If you don't do training by yourself and just want to use a model find from somewhere. You will need to modify the model. The general model requirement is listed here: https://developers.google.com/ml-kit/custom-models#model-compatibility
For details, I believe posting a question in StackOverflow with tensorflow-lite tag is a better way to get the most accurate solution: https://stackoverflow.com/questions/tagged/tensorflow-lite.  (If you do, will appreciate if you can share the SO link here, so future readers can find useful redirection as well. Thanks)
