### ISSUE TITLE
model download Failed 

### ISSUE THREAD

**Issue by dhavalSA** [googlesamples/mlkit#266]
i am getting following error if after starting downloading model if i kill app and star downloading model again 

[AnyHashable("MLKModelDownloadUserInfoKeyRemoteModel"): MLKTranslateRemoteModel Language: gu, AnyHashable("MLKModelDownloadUserInfoKeyError"): Error Domain=com.google.mlkit Code=2 "Failed to download the model from the server." UserInfo={NSLocalizedDescription=Failed to download the model from the server.}]

**Comment by bcdj** [comment]
I tried the[ quickstart app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/translate/TranslateExampleObjC), but could not reproduce this issue.

**Comment by dhavalSA** [comment]
This error comes when I kill app during download models and then restarting download when open app again. I am using following method to download model.

 let modelManager = ModelManager.modelManager()
    let languageName = Locale.current.localizedString(forLanguageCode: language.rawValue)!
    if modelManager.isModelDownloaded(model) {
      self.statusTextView.text = "Deleting \(languageName)"
      modelManager.deleteDownloadedModel(model) { error in
        self.statusTextView.text = "Deleted \(languageName)"
        self.setDownloadDeleteButtonLabels()
      }
    } else {
      self.statusTextView.text = "Downloading \(languageName)"
      let conditions = ModelDownloadConditions(
        allowsCellularAccess: true,
        allowsBackgroundDownloading: true
      )
      modelManager.download(model, conditions: conditions)

**Comment by bcdj** [comment]
When the model download fails, did you retry the download to see if the error went away?

**Comment by bcdj** [comment]
Also, you don't have to delete the downloaded model every time before downloading the model. You can call the [`downloadModelIfNeeded(with:completion:)`](https://developers.google.com/ml-kit/reference/swift/mlkittranslate/api/reference/Classes/Translator#downloadmodelifneededwith:completion:) API of the [`Translator`](https://developers.google.com/ml-kit/reference/swift/mlkittranslate/api/reference/Classes/Translator#/c:objc(cs)MLKTranslator(im)downloadModelIfNeededWithConditions:completion:) to download the model.

**Comment by dhavalSA** [comment]
@bcdj here is my final code 
        let model = self.model(forLanguage: translationLanguage)
        let modelManager = ModelManager.modelManager()

         if !modelManager.isModelDownloaded(model)  {
           
          let conditions = ModelDownloadConditions(
            allowsCellularAccess: true,
            allowsBackgroundDownloading: true
          )
   
         modelManager.download(model, conditions: conditions)
            }

still having same issue . 
i am calling this function when user first time login to app . so this method is starting downloading  , now before download completed i kill application. now next time  when user open app i call same function . and got error . this error comes only once  . every time for first time after killing app . if i call this function for second time then it is downloading model .

**Comment by bcdj** [comment]
My suspicion is that since the model is downloaded in a background task, when the app is forcibly killed by the user, the background task did not get a chance to properly stop and cleanup. When download is retried next time, the error from the last attempt was finally returned, which led to the behavior you see.  I would suggest to work around this rare situation by retrying the downloading once after the first failure.

**Comment by dhavalSA** [comment]
@bcdj may be this is the reason for this behaviour , then next question is why this is not happening in provided demo app . this case work proper in demo app . if we kill app while download is in progress . next time when we open app and try to download again then it start downloading properly .
