### ISSUE TITLE
Null value for smiling/open eye probability with LivePreviewActivity

### ISSUE THREAD

**Issue by matteosantini** [googlesamples/mlkit#269]
Hi guys, I'm not able to retrieve the values for the eyes open probabilities and smiling probability when I use the LivePreviewActivity.
I've just cloned this repo and runned with the debug mode activated.
I've seen that those probability works for the StillImageActivity.

![image](https://user-images.githubusercontent.com/62031271/115383533-3fc6d280-a1d6-11eb-8a4f-3c04ad06498f.png)

**Comment by zhouyiself** [comment]
Did you turn on "Classification mode"? (click the button in the top right -> change the "Classification mode" to "All classifications")

**Comment by matteosantini** [comment]
Thanks you now it's working!
