### ISSUE TITLE
number "7" is wrongly labelled as number "1"

### ISSUE THREAD

**Issue by nateshmbhat** [googlesamples/mlkit#27]
See this sample image : 

https://travelandynews.com/wp-content/uploads/2019/09/British-Airways-Amex-credit-Card.jpg

The card number should be detected as : 3759 876543 21001
but it is being detected as 3159 816543 21001

**Comment by chrisito** [comment]
We are looking at improving scenarios like this with the next big update of the Text Recognition API. We don't have a timeframe yet, but please stay tuned.
