### ISSUE TITLE
API to extract the contour points from Selfie segmentation 

### ISSUE THREAD

**Issue by Ashish-Balhara** [googlesamples/mlkit#270]
Is there an API to extract contour points while using selfie segmentation model? 
Although I've used laplacian filter to get the edges, Its not efficient, if we model provide the contour directly, it would be very helpful and efficient.

**Comment by steven-chengji-yan** [comment]
Hi Ashish,

Thanks for your feedback.
Currently, we don't have plan to add that support. Will prioritize it if we hear from more developers about this feature request.
