### ISSUE TITLE
Retrieve bounding box of recognized digital ink strings

### ISSUE THREAD

**Issue by cgilboy** [googlesamples/mlkit#272]
Hi there!

Is it possible to retrieve the bounding rectangle of the characters recognized by the digital ink recognizer? For example, if the recognizer recognized the string 'hello' we would be able to get the bounding rectangle that encloses the ink that was recognized as the character 'h'.

Thanks :)

**Comment by steven-chengji-yan** [comment]
Thanks for the feedback. 

Currently this is not supported. Could you explain a bit more about your use case? Why do you need a per-character bounding box?

**Comment by cgilboy** [comment]
We'd like to use it for highlighting search results, including partial search results.

**Comment by steven-chengji-yan** [comment]
Hi cgilboy,

We had some internal discussions. It is actually non-trivial to support this. It requires decent amount of model, pipeline, API update to get it right. In this case, we don't have a plan to add this support in near future. However, our priority could change if we see more developers requesting the same thing.

In the meantime, if latency is not super critical for your use cases, could you consider some trick on your end based on the current API? For example, after recognizing an entire Ink is a certain word, try passing in half of the Ink into the API again to check the recognized result ... then half again ...  doing some binary search until it locate exactly the character/word you care about.
