### ISSUE TITLE
FaceDetection: InputImage.fromBitmap() causes detector to fail when rotation is not 0

### ISSUE THREAD

**Issue by OmriNach** [googlesamples/mlkit#274]
I am using a bitmap as an input for the face detector api. The detector fails if rotation is not set to 0. My camera rotation is at 90, the face detection works only if I tilt my phone to -90. 

Code below:

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val binding = DataBindingUtil.inflate<FragmentReviewImageBinding>(
                inflater, R.layout.fragment_review_image, container, false)
        // Inflate the layout for this fragment
        val args = reviewImageFragmentArgs.fromBundle(requireArguments())
        binding.imageView.rotation = args.rotation
        binding.imageView.setImageBitmap(args.bitmapImage)
        val rot = args.rotation.toInt()
        Log.d("rot","Rotation is $rot")
        //binding.imageView.scaleType = ImageView.ScaleType.FIT_XY
        detectFace(args.bitmapImage,args.rotation)
        return binding.root
    }

    private fun detectFace(bitmap: Bitmap, rotation:Float) {
        val highAccuracyOpts = FaceDetectorOptions.Builder()
                .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
                .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
                .setContourMode(FaceDetectorOptions.CONTOUR_MODE_ALL)
                .build()
        val image = InputImage.fromBitmap(bitmap,0)
        Log.d("face_found","image : $image")
        val detector = FaceDetection.getClient(highAccuracyOpts)
        val result = detector.process(image)

**Comment by cs-googler** [comment]
Hi, this is an [known issue](https://developers.google.com/ml-kit/known-issues#android_issues) which we will fix in the next release. Thanks for reporting!
