### ISSUE TITLE
NoSuchFieldError: No static field AUTOML of type

### ISSUE THREAD

**Issue by RamiroMoreira** [googlesamples/mlkit#279]
Hello,  i have been struggling with this bug for some time, maybe it's something easy to solve or that i'm doing wrong. I'm working with react-native and doing some custom image labeling in android side. Recently i did a refactor and upgrade all libraries and this bug appeared, can you help me with this?. 

Description:
When i run  "RemoteModelManager.getInstance().download(remoteModel, downloadConditions);" the app crashes with no errors on metro server neither or react-native side. When running adb logcat i find this error: 

![image](https://user-images.githubusercontent.com/10506673/116947186-74b13b80-ac52-11eb-9581-cea045e136f2.png)

my dependencies on /app/build.gradle are:
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  
    implementation 'com.google.mlkit:barcode-scanning:16.1.1'
    implementation 'com.google.mlkit:linkfirebase:16.1.0'
    implementation 'com.google.mlkit:image-labeling-custom:16.3.1'
    implementation 'com.google.mlkit:image-labeling:17.0.3'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    
   debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
```
i have searched for similar issues but i didn't find a clue, any throught would be helpful. Thanks for the time.

**Comment by zhouyiself** [comment]
Thanks for the report and sorry for any inconvenience.

This sounds like an internal version mismatch issue caused by linkfirebase dependency. We'll release a new version soon, and to unblock you temporarily before that, could you try the below mlkit dependencies combination to see if it can bypass this:
    implementation 'com.google.mlkit:barcode-scanning:16.1.0'
    implementation 'com.google.mlkit:linkfirebase:16.1.0'
    implementation 'com.google.mlkit:image-labeling-custom:16.3.0'
    implementation 'com.google.mlkit:image-labeling:17.0.1'

**Comment by zhouyiself** [comment]
Hi RamiroMoreira,

We just released a newer version of com.google.mlkit:linkfirebase:16.1.1 which should fix the crash issue.

Please give it a try and reopen this issue if the issue not resolved.

**Comment by RamiroMoreira** [comment]
It worked! Thanks a lot!!

**Comment by HTML-CODDER** [comment]
greate
