### ISSUE TITLE
com.google.mlkit.common.MlKitException: Failed to initialize detector. Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

### ISSUE THREAD

**Issue by alexanderconner** [googlesamples/mlkit#280]
I have created a CameraX Image Analyzer and a very basic custom Tflite Image Labeling model using [The Make Image Classifier](https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier) and my own images (I used the same tfhub module in the example as well). When I run the analyzer with my camera the OnFailure listener is triggered and I get the error in the title. However I can't seem to find any MLKit documentation on how to add the NormalizationOptions for my custom model. Both of the sample projects listed in the MlKit Docs (including this one) don't seem to need to do this. 

As for my options to get such metadata I am not sure if I need to create it for the model up front or if I can add the metadata myself in the CustomImageLabelerOptions builder (I don't see this as a method). If this is not possible with MLKit do I need to create a new retraining python project entirely (I am a Tensorflow noob so this is not ideal)? 

Any advice appreciated.

See my example code below:

```

private class LabelDocumentImageAnalyzer(context: Context) : ImageAnalysis.Analyzer {

    private val CONFIDENCE_THRESHOLD = 0.7f

    private val localMLKitModel = LocalModel.Builder()
            .setAssetFilePath("mlkit/model_1_0.tflite")
            .build()

    private val customObjectLabelOptions = CustomImageLabelerOptions.Builder(localMLKitModel)
            .setConfidenceThreshold(CONFIDENCE_THRESHOLD)
            .setMaxResultCount(2)
            .build()

    private val imageLabeler = ImageLabeling.getClient(customObjectLabelOptions)

    @SuppressLint("UnsafeExperimentalUsageError")
    override fun analyze(imageProxy: ImageProxy) {
        val mediaImage = imageProxy.image ?: return

        val image = InputImage.fromMediaImage(mediaImage, imageProxy.imageInfo.rotationDegrees)
        
        // Pass image to an ML Kit Vision API
        imageLabeler.process(image)
                .addOnSuccessListener { labels ->
                    for (label in labels) {
                        val text = label.text
                        val confidence = label.confidence
                        val index = label.index
                        val previewText = "Image label found: ${label.text}, with confidence $confidence at index $index"
                        Log.d(TAG, previewText)
                    }

                }
                .addOnFailureListener { e ->
                    Log.e(TAG, "Error analyzing image: $e") //this is what is reporting the error...
                }
                .addOnCompleteListener {
                    imageProxy.close()
                }
    }
}
```

**Comment by SilverDestiny** [comment]
Hi Alex,

Here is the ML Kit doc link and instruction for Metadata, https://developers.google.com/ml-kit/custom-models#metadata
"To use a model with FLOAT32 input tensor, you must specify the NormalizationOptions in the metadata."
Hope this helps. :)

**Comment by alexanderconner** [comment]
Yes I had looked at this. The Tensorflow Lite android library allows Normalization options to be passed into a NormalizeOp object, which I would pass to the ImageProcessor Builder.

![image](https://user-images.githubusercontent.com/24720260/117698065-44592800-b191-11eb-865c-4d818b6b5a20.png)

I would expect to be able to pass a similar option to the CustomImageLabelerOptions builder with MLKit.

**Comment by SilverDestiny** [comment]
Thanks for the feedback Alex!
CustomImageLabelerOptions is used to configure ImageLabeler, while ImageLabeler needs to take in .tflite file as an input for custom models. Currently ML Kit doesn't support adding metadata to .tflite files so that users need to provide the functional models for ML Kit to use.
