### ISSUE TITLE
Text Recognition Exception

### ISSUE THREAD

**Issue by qiangzengli** [googlesamples/mlkit#281]
**Exception: Failed to load deprecated vision dynamite module**

environment:     Android Studio 4.1

implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.1.3'

AndroidManifest.xml:           
  <meta-data
            android:name="com.google.mlkit.vision.DEPENDENCIES"
            android:value="ocr,barcode" />

device :     Mi8

Android  Version: 10
MIUI Version: 12

**Comment by zhouyiself** [comment]
Does your device have Google Play Services installed? Text recognition won't work without it.

**Comment by qiangzengli** [comment]
Google Play Services have been installed on my device

**Comment by zhouyiself** [comment]
What's its version then?

**Comment by qiangzengli** [comment]
21.15.15

**Comment by qiangzengli** [comment]
It was an old version,This is just updated,now excepion: Waiting for the OCR optinal module to be downloaded.Pllease wait.

**Comment by zhouyiself** [comment]
Yeah, that's expected. It relies on a module downloaded from server and should start working once it's available. The downloading time varies but shouldn't take too long.

**Comment by zhouyiself** [comment]
BTW, the error code of this exception is supposed to be UNAVAILABLE that you can used to check such cases
https://developers.google.com/android/reference/com/google/mlkit/common/MlKitException#public-static-final-int-unavailable

**Comment by qiangzengli** [comment]
OK，Thank you very much.
