### ISSUE TITLE
QR Code not recognise

### ISSUE THREAD

**Issue by sooraj-beebakhy** [googlesamples/mlkit#287]
The attach QR Code is not recognised when using the MLKit. Any configuration is needed on my side?
![zapper_code_not_working](https://user-images.githubusercontent.com/5858364/117864519-f3872380-b2a5-11eb-850a-660ee7fe9292.jpg)

**Comment by zhouyiself** [comment]
Seems there's something wrong with this barcode. I tried it with Zxing online and it can't recognize it either.
https://zxing.org/w/decode.jspx

**Comment by sooraj-beebakhy** [comment]
> Is this on Android or iOS?

Having the issue on Android. Have not try it on iOS.

The QR code is recognised using the App QR Droid (http://qrdroid.com) by selected the Zapper engine in the App settings. And with the Zxing it is not recognise either.

**Comment by cs-googler** [comment]
Hi, this is caused by the bad print quality of the QR code. We may come up with better models to handle this in the future but it is not currently planned. Thanks for reporting!
