### ISSUE TITLE
Android project doesn't build

### ISSUE THREAD

**Issue by suyashjoshi** [googlesamples/mlkit#289]
After importing the downloading this git repository, I tried to import it in Android Studio as an existing project but the Gradle sync process failed with the following errors:

```
Could not resolve all dependencies for configuration ':app:proguardRuntimeClasspath'.
Could not create task ':app:minifyProguardWithR8'.
Cannot query the value of this provider because it has no value available.
```

I looked up online and the fix seems to be that one needs to have the right SDK version, in this case, **compileSdkVersion 29** as mentioned in the app's *build.gradle* file. 

It will be helpful to mention this in the README, I might submit a PR for the same.

**Comment by suyashjoshi** [comment]
Alternately, the fix is to just set the *compiledSDKVersion to 30* in your app's *build.gradle* file which is the same as the *targetSdkVersion*

**Comment by zhouyiself** [comment]
Thanks for the report, repo updated.
