### ISSUE TITLE
I managed to fix the issue as it seems like the Android app requires a specific version of the Android SDK Build-tools. I installed a fresh copy of Android Studio so it automatically installed version 30.03 Android SDK Build-tools. However, the app requires version 29.0.2.

### ISSUE THREAD

**Issue by HTML-CODDER** [googlesamples/mlkit#294]
I managed to fix the issue as it seems like the Android app requires a specific version of the Android SDK Build-tools. I installed a fresh copy of Android Studio so it automatically installed version 30.03 Android SDK Build-tools. However, the app requires version 29.0.2. 

I think an update to address this would be warranted in case a person new to Android app development is trying to run this program. It will help streamline the experience :)

_Originally posted by @phillip9077 in https://github.com/googlesamples/mlkit/issues/292#issuecomment-842045322_

**Comment by cs-googler** [comment]
Close as there is no issue needs to be resolved.
