### ISSUE TITLE
Android Studio cannot run demo

### ISSUE THREAD

**Issue by leiiiooo** [googlesamples/mlkit#296]
Android Studio Version: 4.2.1
Target Demo Url: https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
Error: 
![image](https://user-images.githubusercontent.com/17199087/118600179-3b94d180-b7e3-11eb-9b05-2ff78b34d93c.png)

**Comment by leiiiooo** [comment]
Cannot find deps.

**Comment by GaiwkadVivek520** [comment]
Facing same error in my case also

**Comment by cs-googler** [comment]
This is due to an accidental sync with new version numbers, before we upload a fix, please revert changes in this commit and build again. Thanks for reporting!

**Comment by zhouyiself** [comment]
Fix uploaded, please sync to the latest repo version to make it work.

**Comment by leiiiooo** [comment]
Works now, Thank you.
