### ISSUE TITLE
Request to support Mediapipe holistic model in MLKit.

### ISSUE THREAD

**Issue by Ashish-Balhara** [googlesamples/mlkit#298]
We are trying to use MLKit in digital physiotherapy application. To detect the hand motion, it need to detect landmarks of hand joints  as well as landmark of elbow joint.  If feasible, Please do support.

**Comment by steven-chengji-yan** [comment]
Hi Ashish, 

Thanks for the feedback.

We actually evaluated Holistic internally, but thought it is too heavy and might not have enough use cases. 
For your your case, do you only need to get Pose detection + left/right hand detection? Do you also need the face mesh?
The more models it runs, the slower it would be. What is the targeted latency(FPS) your use case needs to achieve?

**Comment by Ashish-Balhara** [comment]
Hi Steven,  
For our use case, pose detection + both hands detection are more than enough. face mash is not even required. As far as latency is concerned, it should be at least 10 FPS. 
Yes, you are right, 3 models in one go, would increase the overall latency. Initially, I also thought what I asked, it is a frivolous requirement.

**Comment by steven-chengji-yan** [comment]
Hi Ashish-Balhara,

We had some internal discussion. Unfortunately, we don't have plan for near-future to add holistic or hand detection APIs.

Will re-evaluate it if we see stronger demand.

Thanks for your feedback!
