### ISSUE TITLE
How to Classify squat and pushup poses. Count reps in streaming mode in iOS?

### ISSUE THREAD

**Issue by LuckyRoc** [googlesamples/mlkit#299]
I found that Andorid has Demo but iOS does not. And can't find the documentation how to implement it in iOS

**Comment by steven-chengji-yan** [comment]
iOS would have the same logic as Android. If you are familiar with Java or Kotlin, you can try mapping the Android classification code to iOS code. The classification code doesn't use any platform specific things, just general process and algorithm.

In the meantime, we will chat internally to see if we have bandwidth to release the iOS sample.

Thanks for your feedback!

**Comment by LuckyRoc** [comment]
I will try it as you say！Thanks for your reply.

**Comment by steven-chengji-yan** [comment]
Had some internal discussion. Unfortunately, there is no plan for adding the iOS version now. 

We could consider re-evaluating it if see strong user demand.

Thanks,

**Comment by eleiannu** [comment]
@steven-chengji-yan By any chance, is there a plan for adding it now? I'm also facing the same situation and it would be very useful to have it! Thanks in advance!

**Comment by bcdj** [comment]
@eleiannu We don't have a plan on this yet, but will consider it in our future planning against all other priorities. In the meantime, as @steven-chengji-yan suggested, you reference the Java implementation to replicate it for iOS.

**Comment by kkangaroo** [comment]
@LuckyRoc @eleiannu there is a recently released push-up counter for iOS and Squat counter in this repo: https://github.com/quickpose/quickpose-ios-sdk
