### ISSUE TITLE
Applying pose detection to existing video file

### ISSUE THREAD

**Issue by sem2205** [googlesamples/mlkit#301]
Hello,

I am looking implement Android ML Kit Pose Detection API to read in video files so that I can process the videos to calculate body key points and InFrameLikelihood.  I am wondering if there is a way to detect poses with ML Kit in "STREAM_MODE" using existing video files stored on my computer or Android device.

**Comment by steven-chengji-yan** [comment]
Hi sem2205,

You will need to extract the image frames from the video, create InputImage for each frames, and pass them into the detector. When creating the detector, you should still use STREAM_MODE.  This mode is to tell the underlying pipeline that all the input frames are related, thus it will do tracking.

Some reference you can take a look:
https://github.com/googlesamples/mlkit/issues/181
https://github.com/googlesamples/mlkit/issues/177

**Comment by bhaskar2728** [comment]
We can use this  https://github.com/google/grafika library's play movie on texture view feature
From there, we can implement onSurfaceTextureUpdated() function and this function runs everytime we get a new screen or frame from the video.And in that function, we can get the image and do pose detection on that.
This is my sample project: https://github.com/bhaskar2728/MLKit-PoseDetection-On-Video-Android
Hope this helps but I strongly believe that there should be a much better way of doing this.

**Comment by sem2205** [comment]
Thank you for the replies!

I am new to Android Studio, and was also convinced that there should be an easier way to do this @bhaskar2728! From my research, I was going to try implementing FFmpegFrameGrabber to extract all frames in the video.

@steven-chengji-yan do you have a recommended way to first extract all the frames?

**Comment by HTML-CODDER** [comment]
@html-codder

**Comment by steven-chengji-yan** [comment]
Hi sem2205, 

I don't have first hand experience on this. 
If you make it work in anyway, please share it here. That will be very helpful for future audience.

**Comment by steven-chengji-yan** [comment]
Close this for now. Let us know if you are still working on this.

**Comment by ZeroOneZeroR** [comment]
May be [this](https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video)  is what you need.
https://github.com/ZeroOneZeroR/android-ml-kit-vision-with-video

**Comment by duckyngo** [comment]
You can easily use the [Fast-Video-Frame-Extraction](https://github.com/duckyngo/Fast-Video-Frame-Extraction) to extract all the frames in video with high speed then apply MLKit Pose Extraction with STREAM_MODE on all frames.
