### ISSUE TITLE
Multi Detector

### ISSUE THREAD

**Issue by blennerSilva** [googlesamples/mlkit#306]
Is it possible to use Barcode detection with TextDetection all togother?

**Comment by swiyu** [comment]
We do not have a merged detection for these two, but you could run two detections separately.

**Comment by blennerSilva** [comment]
ok but back um google vision... you guys had de MULTIDETECTOR object uma using it now but i would to migrate everything....
i need to validate ocr and barcode at the same time.... is there anyway to do that?

**Comment by bcdj** [comment]
You can just call both ocr and barcode on the same image or video frame, then use the results from both detections.
