### ISSUE TITLE
iOS CSV pose classification

### ISSUE THREAD

**Issue by sujie0308** [googlesamples/mlkit#307]
I can already use MediaPipe Colab. Currently, Android has a csv posture classification and counting method. For iOS, I don’t know how to classify posture actions based on csv files. Will this part of the code be added in the future?

**Comment by bcdj** [comment]
Thanks for your feedback! We don't have current plan to provide an iOS example, but if we did, iOS would have the same logic as Android. If you are familiar with Java, you can try to map the Android classification code to iOS code. The classification code doesn't use any platform specific things, just general process and algorithm.

**Comment by sujie0308** [comment]
Thank you. I tried Android Studio and opened the code in the demo. I think I don't know Java and it's still hard to map the Swift code

**Comment by ahmdmau** [comment]
@sujie0308 is ur problem solved? can you share how to solve this issue?

**Comment by sraliu** [comment]
I'm also looking for iOS examples

**Comment by Throvn** [comment]
I was also looking for iOS samples, but didn't find a solution either.
So I mapped the java code to swift and rebuilt the minimal pose classification example.
You can find the code here: https://github.com/Throvn/MLKitPoseClassificationExample

Note though, that I am not a Swift native coder, so parts of the code could be a bit messy. 
Therefore any kind of pull requests are more then welcome.

**Comment by bcdj** [comment]
We don't plan to provide an iOS example, but you can use the Android classification code as an example and try to replicate it on iOS. The classification code doesn't use any platform specific things, just general process and algorithm.

**Comment by ragotrebor** [comment]
I work on the iOS pose classifier, its based on the android project

https://github.com/ragotrebor/mlkit-ios-poseclassifier
