### ISSUE TITLE
Korean and Japanese are different. The two collide and the output is in Japanese.

### ISSUE THREAD

**Issue by nasungtae** [googlesamples/mlkit#31]
problem in ios.
Korean and Japanese are different. The two collide and the output is in Japanese.
android not problem.
Android and IOS have the same settings, but how is the output different?

 setting hints:
   options.languageHints = @[@"ko",@"en",@"zh-CN",@"ja"];
ios
CODE: 
FIRVision *vision = [FIRVision vision];
FIRVisionCloudTextRecognizerOptions *options = [[FIRVisionCloudTextRecognizerOptions alloc] init];
   //kor,@"en",@"ja",@"zh-CN"
    options.languageHints = @[@"ko",@"en",@"zh-CN"];
    FIRVisionTextRecognizer *textRecognizer = [vision cloudTextRecognizerWithOptions:options];
    FIRVisionImage *image = [[FIRVisionImage alloc] initWithImage:img];
    [textRecognizer processImage:image
                    completion:^(FIRVisionText *_Nullable result, NSError *_Nullable error) {
                        [self stopIndicator];
                        if(error != nil || result == nil) {
...
Note : ios deletes ja and ko is read.

![KakaoTalk_Photo_2020-05-25-10-41-43-1](https://user-images.githubusercontent.com/41936914/82770687-59e81b80-9e74-11ea-906f-b7823ce5bf89.jpeg)
android
![photo_2020-05-25 10 51 43](https://user-images.githubusercontent.com/41936914/82771060-c31c5e80-9e75-11ea-8c8b-0a0b78ecdc23.jpeg)

**Comment by cs-googler** [comment]
This is the could text recognizer that is provided by firebase. We made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit.

We are working on adding more language support in the on device mlkit as it currently only support Latin. Please stay tuned.
