### ISSUE TITLE
Pose detection with video input on iOS

### ISSUE THREAD

**Issue by smile176223** [googlesamples/mlkit#313]
Hello,

I am looking for Pose detection with video file input on iOS. I want to use video file input instead of camera. 
Is there any solution or suggestions?
Thanks

**Comment by bcdj** [comment]
You can use [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer) to play a video file and then convert the `CVPixelBuffer` frames in the video output to `CMSampleBuffer`s before creating `VisionImage`s from the latter and feeding them to ML Kit's Pose Detection API.

**Comment by smile176223** [comment]
Thank you for the replies!
Do you mean using CADisPlayLink to get all the frames and feed data to the api synchronously? I tried getting all the frames with AVAsset, but it caused memory problems.

**Comment by bcdj** [comment]
Yes, but not sure why you are having memory problems.  What kind of memory problems do you have?

**Comment by smile176223** [comment]
I used AVAssetReader to read all the frames and then used global().async to feed the CMSampleBuffer to the API.
But I got two problems, the first is that the orientation of the output graph is incorrect, and the second is that it will run very slowly.
I referred to the ML Kit Vision Quickstart Sample, and then used this method to replace the camera part.

**Comment by bcdj** [comment]
Instead of the global().async call, can you just call ML Kit's synchronous API `results(in:)` like in the quickstart (https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L238)?  Pose Detection's synchronous API is intended for the video streaming use cases like yours.

**Comment by smile176223** [comment]
GoogleMLKit/PoseDetection

**Comment by bcdj** [comment]
Sorry for not making it clear: which method/function did you call to do the Pose Detection?  There are two of them: sync and async). Which one do you use?

**Comment by smile176223** [comment]
async.

**Comment by bcdj** [comment]
To double confirm: you are using the async [process(_:completion:)](https://developers.google.com/ml-kit/reference/swift/mlkitposedetectioncommon/api/reference/Classes/PoseDetector#/c:objc(cs)MLKPoseDetector(im)processImage:completion:) method of the `PoseDetector`, not its sync [results(in:)](https://developers.google.com/ml-kit/reference/swift/mlkitposedetectioncommon/api/reference/Classes/PoseDetector#/c:objc(cs)MLKPoseDetector(im)resultsInImage:error:) method.  If so, given you said that you used global().async to feed the CMSampleBuffer to the API, please replace `process(_:completion)` with `results(in:)` to see if that helps with the memory issues.

**Comment by smile176223** [comment]
ok , I will try this way.
I appreciate your help very much.

**Comment by bcdj** [comment]
You are welcome.  Let me know how it goes.
