### ISSUE TITLE
Face Landmarks 

### ISSUE THREAD

**Issue by MrSano** [googlesamples/mlkit#314]
Hello, I've been dealing with a strange issue, even though landmarks are not present ( hidden with something) ,  it returns landmark as not null... 

Is this supposed to happen? I've not got a exact answer on this in the google dev site,  (like for pose it says it returns a point but has coordinates outside range) 

Thanks.

**Comment by steven-chengji-yan** [comment]
Hi MrSano,

In ML Kit, both Face Detection and Pose Detection have landmarks. Based on the details you provided, I assume you are asking for Pose. 

There are two specific cases here:
(1) Part of the person's body is covered by something, e.g. a wall, but if you remove the wall, the entire person is still within the image frame. 
(2) Part of the person's body is out of the image frame.

For both (1) and (2), the ML Kit pose API will try to predict the position of all the landmark.   For (2), on each pose landmark, there is an inFrameLikelihood score, in range [0.0, 1.0]. If a landmark is out of the image frame, it should have a lower inFrameLikelihood.

Currently, we don't expose a score to handle (1). However, please let us know if that is what you want. Some example image would also be helpful.

Best,

**Comment by MrSano** [comment]
Oh sorry , i was asking for face detection forgot to specify that...

Thanks for the answer.

**Comment by bcdj** [comment]
Yes, this is supposed to happen, since the facial landmarks are calculated based on the face position and orientation.

**Comment by MrSano** [comment]
Oh okey, its just that sometimes the "face" is more like a stain than a actual face and it still detects landmarks... any idea how i can prevent this (ignore the stain or covered faces) ?
