### ISSUE TITLE
[Feature Request] ML Kit: On-Device Model Download API

### ISSUE THREAD

**Issue by G00fY2** [googlesamples/mlkit#315]
I found this issue from the old Firebase repo: [[Feature Request] ML Kit: On-Device Model Download API](https://github.com/firebase/firebase-android-sdk/issues/47)

There is still no way to get availability and download status of the unbundled standard ML Kit models (e.g. barcode), right?

Currently we keep the analyzer alive when a `MlKitException.UNAVAILABLE` exception occurs and hope for the Play Services to eventually download the model. But if the user is offline e.g. this won't happen at all and we have no indicator about that.

Is this feature still considered to be implemented?

**Comment by cs-googler** [comment]
Yes, thanks for bringing this up! We had it planned but didn't have cycle to get to it. We will give an update here shortly once we have a concrete plan.

**Comment by jishindev** [comment]
@cs-googler can you give us an update. Its been over six months now?

**Comment by zhouyiself** [comment]
Sorry about the late update.
We're waiting for a download infrastructure update from Play Services to provide better support for this functionality. We don't have a concrete release date yet but would be some point in the second quarter of this year. So stay tuned!

**Comment by nk-alex** [comment]
Hi, any updates on this?

**Comment by ai-plays** [comment]
Yes. Here is the release notes about the support: https://developers.google.com/ml-kit/release-notes#improvements_2

You can use the GMS [ModuleInstallClient API](https://developers.google.com/android/guides/module-install-apis) on ML Kit Detectors that extend [OptionalModuleApi](https://developers.google.com/android/reference/com/google/android/gms/common/api/OptionalModuleApi), e.g. [BarcodeScanner](https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/BarcodeScanner)
