### ISSUE TITLE
Pose Detector: Reduce the number of landmarks

### ISSUE THREAD

**Issue by IvanDeLucasRog** [googlesamples/mlkit#316]
Hi everyone, thanks for sharing this amazing sample. I'm building an app where face and hand landmarks are not usefull, so I wonder if they could be disabled (telling the model to not to look for them) in order to enhance FPS and performance. I know that I can delete the canvas. 

Thanks! I'm a bit noob

**Comment by steven-chengji-yan** [comment]
Hi IvanDeLucasRog,

Currently all the pose landmarks are predicted in one-go with a single model, so we cannot turn on and off part of it. Thanks for the feedback though. **If we see more related feedback**, we could consider investing some effort to address this, e.g. providing a lite model which only returns a subset of the landmarks.

Thanks!
