### ISSUE TITLE
Text Recognition doesn't read embossed credit cards well

### ISSUE THREAD

**Issue by mavispuford** [googlesamples/mlkit#317]
I've been building out a credit card scanner using ML Kit Text Recognition, and it has worked really well with credit/debit cards that have printed text on them ([example here](https://codepen.io/blake-ross/pen/wvdBvwP)).  However, in our testing we noticed that it has a very hard time reading any cards with embossed text (I unfortunately don't have any example images for these).  

Was embossed text a consideration when building out your OCR model?  Could support for embossed text be added?

**Comment by swiyu** [comment]
Thanks for the feedback! Yes, it is a known issue that ML Kit Text Recognition does not work well for embossed credit cards. There is  an on-going effort to resolve this.

**Comment by mavispuford** [comment]
@swiyu Thank you for the update.  Do you have a timeline for when this might be improved?  Also, I assume when the model is updated, our users would just run our app like normal and it should download the latest one, correct?

**Comment by bcdj** [comment]
We can't share the timeline of the improvement at the moment. Yes, it's correct: when the model is updated, your users can just run your app like normal and it should download the latest one.

**Comment by ikallali** [comment]
+1

**Comment by dziter** [comment]
Any update @bcdj ?
