### ISSUE TITLE
Text Recognition not detecting proper blocks and paragraphs

### ISSUE THREAD

**Issue by werohit** [googlesamples/mlkit#318]
I am working on MLKIt on device module where I wanted to detect TextBlocks on an article in sequential manner. I have placed number sequence on every blocks but it seems merging together.

![device-2021-07-01-152522](https://user-images.githubusercontent.com/65589193/124220108-f7535b80-db1a-11eb-8623-4ae317bb2d7a.png)

How to detect proper blocks and with proper sequence.

**Comment by chrisito** [comment]
Hi, if things go well the next ML Kit release (in August) will have a brand-new version of the Text API that has drastic improvements in paragraphing. It should tackle most of these issues. Stay tuned.

**Comment by werohit** [comment]
Thank for valuable time @chrisito , Can you tell us what all the features and improvements taken in this latest release?.
This info will keep our attention towards the latest release.

Thanks.

**Comment by miworking3** [comment]
Hey, please check out the new Text Recognition beta version [here](https://developers.google.com/ml-kit/vision/text-recognition/v2), where it adds new features like new language support, better paragraphing, you can find the release notes [here](https://developers.google.com/ml-kit/release-notes#new_features_4).
