### ISSUE TITLE
Confidence Property has been removed

### ISSUE THREAD

**Issue by pranav-vempati** [googlesamples/mlkit#319]
I'm currently trying to migrate a codebase from Firebase-MLKit to Google-MLKit. The Firebase API exposes a confidence score associated with each TextBlock. This has been excised from the new API, however, according to the migration guide: 

<img width="732" alt="Screen Shot 2021-07-04 at 3 28 13 PM" src="https://user-images.githubusercontent.com/12287058/124401120-8e1b4600-dcdc-11eb-8d39-1c66172aa1cf.png">

Does Google-MLKit offer an equivalent class that exposes this confidence property? If not, is there a known and viable workaround to this issue?

**Comment by chrisito** [comment]
@pranav-vempati For the on-device ML Kit Text Recognition API we never returned the confidence value (see [here](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/vision/text/FirebaseVisionText.TextBlock#getConfidence)). The Cloud Text Recognition API (still offered through Firebase, see [here](https://firebase.google.com/docs/ml/recognize-text) still provides it.

**Comment by mecoFarid** [comment]
@chrisito I am just trying to understand the reason. Is there any reference or reasoning why you never expose it?
