### ISSUE TITLE
MLKit Vision is reading code128 and 39 barcodes poorly

### ISSUE THREAD

**Issue by chrisvanbuskirk** [googlesamples/mlkit#32]
I'm reading a buffer like such:

```
 let visionImage = VisionImage(buffer: sampleBuffer)
            barcodeDetector.detect(in: visionImage) { (barcodes, error) in
           ...
           }
```

I'm seeing errors of random characters being exchanged in code128/39 barcodes.  No errors are raised.  As you can see I'm checking enterprise labels.  The 2D data matrix codes scan fine.  However, their 1d counterparts randomly fail.

![img_0163](https://user-images.githubusercontent.com/3638007/53061732-8dc3dc80-348c-11e9-8edd-50171ee65f2d.jpeg)

**Comment by miworking3** [comment]
Hey Chris,

We upgraded the Firebase MLKit API to the standalone Google MLKit API early this year: https://developers.google.com/ml-kit

I tried the the latest [vision app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision) with the given barcodes, looks like it works well with S, Q, H, could you give it a try and let us know if that would help your case as well?
![H](https://user-images.githubusercontent.com/52680648/89202049-3ffb4100-d567-11ea-997a-0b6c4c2abb0a.PNG)
![S](https://user-images.githubusercontent.com/52680648/89202107-50abb700-d567-11ea-8c12-fc6bade91377.PNG)
![Q](https://user-images.githubusercontent.com/52680648/89202122-56090180-d567-11ea-9382-448f602abdcf.PNG)


Thanks a lot!
Julie from MLKit team

**Comment by chrisvanbuskirk** [comment]
@miworking3 I will test this.

**Comment by chrisvanbuskirk** [comment]
@miworking3 Impressively done.  Thanks!  Closing this issue.

**Comment by chrisvanbuskirk** [comment]
@miworking3 I am reopening.  I was able to have reproduce similar issue, where this barcode produced N51%%3 after several tries.

<img width="433" alt="Screen Shot 2020-08-05 at 1 27 42 PM" src="https://user-images.githubusercontent.com/3638007/89455382-78de1600-d71f-11ea-946c-5bb651231660.png">

**Comment by miworking3** [comment]
Could you help me to reproduce it with the MLKit quickstart app? 

I tried to move the camera off and on several times, the result looks consistent to me.
![barcode](https://user-images.githubusercontent.com/52680648/89542863-16375980-d7b5-11ea-8bd5-12415299de21.gif)

**Comment by chrisvanbuskirk** [comment]
@miworking3 I'm not sure.  I'd have to study the sample more carefully.    This issue is very rare.  You can see in the following screen shot it plugs in the wrong value.  I'm not sure why.  Position of camera.  Some sort of flaw in our barcode.  

![Screenshot 2020-08-05 at 10 14 18 AM](https://user-images.githubusercontent.com/3638007/89548588-741f6d80-d7c4-11ea-955b-5ff98ffbd043.jpeg)

**Comment by chrisvanbuskirk** [comment]
@miworking3 

Fascinating...

I was using 

`            barcodeDetector.process(visionImage) { (barcodes, error) in
`
...and changed to method in the sample and am not seeing the problem.

`              barcodes = try barcodeScanner.results(in: visionImage)
`
I'm going to do even more testing.

**Comment by miworking3** [comment]
Thanks for checking that! Yes, for the realtime video frames, we recommend to use the synchronous API `results(in:)`:
```For processing video frames, use the results(in:) synchronous API of the detector. Call this method from the AVCaptureVideoDataOutputSampleBufferDelegate's captureOutput(_, didOutput:from:) function to synchronously get results from the given video frame. Keep AVCaptureVideoDataOutput's alwaysDiscardsLateVideoFrames as true to throttle calls to the detector. If a new video frame becomes available while the detector is running, it will be dropped.```

https://developers.google.com/ml-kit/vision/barcode-scanning/ios

**Comment by chrisvanbuskirk** [comment]
@miworking3 

     `   self.session.sessionPreset = .hd1280x720`

Seemed to really fix the errors.  Not closing just yet, cause I have more testing..but it's going great so far.

**Comment by miworking3** [comment]
Thank you @chrisvanbuskirk for verifying this. We appreciate the data point from your side.
Yes, the preset can affect the results, and `1280x720` is a recommended setting by our doc as well:
```The named capture session presets—AVCaptureSessionPresetDefault, AVCaptureSessionPresetLow, AVCaptureSessionPresetMedium, and so on)—are not recommended, however, as they can map to unsuitable resolutions on some devices. Instead, use the specific presets such as AVCaptureSessionPreset1280x720.```

https://developers.google.com/ml-kit/vision/barcode-scanning/ios

**Comment by ruslan-podurets** [comment]
Hi, have issue with 128 code barcode, when ml kit returns wrong values. I use com.google.mlkit:barcode-scanning:16.0.2 with default camera resolution settings (tried different).  Also analyze in this way:
val mediaImage = imageProxy.image
val image = InputImage.fromMediaImage(mediaImage, imageProxy.imageInfo.rotationDegrees)
scanner.process(image)
This issue happens on many Android and IPhone devices. F.e HTC U11.
Ussually kit returns wrong short text of numbers like "15771449", but sometimes valid long text: "1076839827*Tan*Carol Windell *A*4030052420". 
img url: https://ibb.co/yh3DJFT

**Comment by miworking3** [comment]
@ruslan-poduret Thanks for reporting this, could you provide more information about the iPhone device that you found this problem? When you mentioned about "This issue happens on many Android and IPhone devices", is it reproducible with the [MLKit iOS quickstart app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision)?

BTW: About the android API, I've already forwarded your message to our Android team, he might have further questions about it later.

**Comment by chrisvanbuskirk** [comment]
@miworking I'm afraid I still am seeing bad reads every 40-50 scans.  Just seems for the 128's.  It's very random and odd, and I can't quite pinpoint why.  If it's distance.  The barcode quality.  Digital v. non digital, etc...

**Comment by miworking3** [comment]
@chrisvanbuskirk Do you know the expected value of the barcode being read? If so, you can save the samplebuffer to an image right at the time when it fails, and with that information, a further investigation can be continued. Thanks!

**Comment by chrisvanbuskirk** [comment]
@miworking3 I will look into it.

**Comment by miworking3** [comment]
It's been a while, with previous major concerns clarified, closing this thread. Pls feel free to reopen it if new updates. Thanks!

**Comment by felipetce** [comment]
I have the version 16.0.2 and the same problem happens

**Comment by miworking3** [comment]
16.0.2 for Android SDK?

**Comment by felipetce** [comment]
I have the version com.google.mlkit:barcode-scanning:16.0.2 and the same problem happens

**Comment by miworking3** [comment]
> I have the version com.google.mlkit:barcode-scanning:16.0.2 and the same problem happens

Could you provide more info about the problem? If there is a sample image that was poorly read, we can take a further look into it.

**Comment by felipetce** [comment]
> > I have the version com.google.mlkit:barcode-scanning:16.0.2 and the same problem happens
> 
> Could you provide more info about the problem? If there is a sample image that was poorly read, we can take a further look into it.

https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
![barcode_com google mlkit vision demo](https://user-images.githubusercontent.com/16478800/140985061-0d240104-e695-44d8-9d11-c62432fa7ce5.jpg)

https://github.com/googlesamples/mlkit/tree/master/android/material-showcase
![barcode_com google mlkit md](https://user-images.githubusercontent.com/16478800/140985093-cf75b6bc-c206-4841-9930-18f94468c8f6.jpg)

**Comment by miworking3** [comment]
Looks like the left part of the barcode is not detected, wonder if it happens because of the angle, do you mind uploading the original photo that was being tested?

**Comment by felipetce** [comment]
> Looks like the left part of the barcode is not detected, wonder if it happens because of the angle, do you mind uploading the original photo that was being tested?

I send the photo, when we used ZXing, the barcode was processed when it fully validated, but now it is processing only a part of the barcode regardless of the angle:

![seals](https://user-images.githubusercontent.com/16478800/141001729-6c56c608-5fe9-4bbd-a8b4-70d0ea0c9ae7.png)

**Comment by miworking3** [comment]
Does it work if you upgrade the barcode to 16.2.1?

**Comment by felipetce** [comment]
> Does it work if you upgrade the barcode to 16.2.1?

I performed the tests with the projects:

https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
https://github.com/googlesamples/mlkit/tree/master/android/material-showcase

who have the version:
![image](https://user-images.githubusercontent.com/16478800/141003366-80ab9988-9dcf-4069-9434-b6bb0d1a3eee.png)

**Comment by felipetce** [comment]
Don't have a way to ensure that the barcode is valid, and is reading completely? We had no problems with ZXing

**Comment by SilverDestiny** [comment]
Hi,

I tried `com.google.mlkit:barcode-scanninig:17.0.0` and `com.google.mlkit:barcode-scanninig:16.2.0` using https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart and it seems working well to detect the full barcode in the image.

`com.google.mlkit:barcode-scanninig:16.0.1` may have the issue as it is an older version/barcode model. Could you verify the new versions work well for the image?

**Comment by felipetce** [comment]
> Hi,
> 
> I tried `com.google.mlkit:barcode-scanninig:17.0.0` and `com.google.mlkit:barcode-scanninig:16.2.0` using https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart and it seems working well to detect the full barcode in the image.
> 
> `com.google.mlkit:barcode-scanninig:16.0.1` may have the issue as it is an older version/barcode model. Could you verify the new versions work well for the image?

Hi, as I mentioned, the images were from barcode-scanninig:17.0.0:

![image](https://user-images.githubusercontent.com/16478800/141015152-dd3b6b96-0523-416a-a757-961aea13077f.png)

![barcode_com google mlkit vision demo](https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg)


![barcode_com google mlkit md](https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg)

**Comment by felipetce** [comment]
After we exchanged Zxing for MLkit, we are having a lot of problems, analyzing the Zxing code, it seems that it had a better validation of the processed barcode

**Comment by felipetce** [comment]
ZXi
![zxing](https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg)
ng

**Comment by SilverDestiny** [comment]
I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg
It seems consistently working for me.

For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).

Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?

It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.

We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.

**Comment by felipetce** [comment]
> I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> 
> For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> 
> Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> 
> It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> 
> We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.

Hello,

I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg
It seems consistently working for me.

For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).

Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?

It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.

We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.

yes, Zxing did not processed barcodes not read completely

**Comment by felipetce** [comment]
> > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> 
> yes, Zxing did not processed barcodes not read completely

By code I verified that the processing of MLKIT barcodes is 1 second

**Comment by felipetce** [comment]
> > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > 
> > 
> > yes, Zxing did not processed barcodes not read completely
> 
> By code I verified that the processing of MLKIT barcodes is 1 second

that is, I think the processing is unsafe

**Comment by felipetce** [comment]
> > > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > > 
> > > 
> > > yes, Zxing did not processed barcodes not read completely
> > 
> > 
> > By code I verified that the processing of MLKIT barcodes is 1 second
> 
> that is, I think the processing is unsafe

we are having a lot of problems having changed the ZXing for ML

**Comment by felipetce** [comment]
> > > > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > > > 
> > > > 
> > > > yes, Zxing did not processed barcodes not read completely
> > > 
> > > 
> > > By code I verified that the processing of MLKIT barcodes is 1 second
> > 
> > 
> > that is, I think the processing is unsafe
> 
> we are having a lot of problems having changed the ZXing for ML

As a multinational company and we need the guarantee of the read codes

**Comment by SilverDestiny** [comment]
> > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> 
> yes, Zxing did not processed barcodes not read completely

Could you share an example for the same cropped image between ML Kit and ZXing?

**Comment by SilverDestiny** [comment]
> > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > 
> > 
> > yes, Zxing did not processed barcodes not read completely
> 
> By code I verified that the processing of MLKIT barcodes is 1 second

Our benchmark tests showed that for 1600x1200 input image, the inference time is around 100 ms.
The inference time depends on the input image size.

**Comment by SilverDestiny** [comment]
> > > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > > 
> > > 
> > > yes, Zxing did not processed barcodes not read completely
> > 
> > 
> > By code I verified that the processing of MLKIT barcodes is 1 second
> 
> that is, I think the processing is unsafe

We're working a project which will not request camera permission for barcode scanning, if you think this sounds safer to you.
It will be released soon next year.

**Comment by SilverDestiny** [comment]
> > > > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > > > 
> > > > 
> > > > yes, Zxing did not processed barcodes not read completely
> > > 
> > > 
> > > By code I verified that the processing of MLKIT barcodes is 1 second
> > 
> > 
> > that is, I think the processing is unsafe
> 
> we are having a lot of problems having changed the ZXing for ML

Could clarify all the problems except this one? We're happy to hear and will try our best to resolve your problems.

**Comment by felipetce** [comment]
> > > I cannot repro your issue for https://user-images.githubusercontent.com/16478800/141014762-323d5709-937c-4a51-ab2b-cca159b29291.jpg It seems consistently working for me.
> > > For https://user-images.githubusercontent.com/16478800/141014875-66fc3c66-9626-4e16-a7ea-285df1d193ff.jpg, it is reproducible, but this image is cropped so that it doesn't contain the full barcode(left side is missing).
> > > Did you mean ZXing also work for cropped images to detect the full barcode? Could you share an example?
> > > It seems working properly for https://user-images.githubusercontent.com/16478800/141017954-1bdc85fe-d3a0-426d-b94a-37d5d6335196.jpg as well.
> > > We probably can improve our model to consider more for the full barcode and ignore the partial barcode in future releases.
> > 
> > 
> > yes, Zxing did not processed barcodes not read completely
> 
> Could you share an example for the same cropped image between ML Kit and ZXing?

**Comment by felipetce** [comment]
Zxing does not process uncompleted scanned barcodes

**Comment by felipetce** [comment]
I found that we have no way to access the image processing source code

**Comment by felipetce** [comment]
Would it be possible to have access to this image processing code?

**Comment by felipetce** [comment]
Esta nos trazendo muitos problemas produticos com a troca do ZXing

**Comment by felipetce** [comment]
It's causing us a lot of production problems with the ZXing switch

**Comment by felipetce** [comment]
I can't reproduce the same problem with ZXing, it seems the image processing is better

**Comment by SilverDestiny** [comment]
> Zxing does not process uncompleted scanned barcodes

We'll work on this to see if we can improve to fix this issue.

**Comment by wsliaw** [comment]
the problem still exists on latest version (android 17.0.2, iOS 2.2.0)
should we reopen it, until `not process uncompleted scanned barcodes` is implement?
thanks 🙏
