### ISSUE TITLE
I would like to know a piece of information I can use this Google Ml Kit Github code in my app

### ISSUE THREAD

**Issue by DIPONGKARGHOSE** [googlesamples/mlkit#322]
I am creating an app that uses Detect Poses with ml kit on android and Pickup a large number code of mlkit (https://github.com/googlesamples/mlkit). I want to publish this app on the google play store.
I would like to know a piece of information I can use this Google Ml Kit Github code(https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/posedetector) in my application .There may be a problem with this Github code in the Google Play Store.

**Comment by steven-chengji-yan** [comment]
Hi DIPONGKARGHOSE

> "I would like to know a piece of information I can use this Google Ml Kit Github code in my application."  
Do you mean you want to know if you can use the mlkit sample code in your app?   

> "There may be a problem with this Github code in the Google Play Store."
Could you elaborate what problem you are referring to?

**Comment by DIPONGKARGHOSE** [comment]
> Do you mean you want to know if you can use the mlkit sample code in your app?
Yes . This question.
I want to know that after publishing this app on the google play store either I am violating any rules of the google play store or not

**Comment by chrisito** [comment]
@DIPONGKARGHOSE The sample-code itself is offered under [Apache 2.0 license](https://github.com/googlesamples/mlkit/blob/master/LICENSE), so as long as you follow that you can use it in your app. For the SDK itself, please refer to [ML Kit Terms & Privacy](https://developers.google.com/ml-kit/terms).
