### ISSUE TITLE
TextRecognizer cannot process single digit in image.

### ISSUE THREAD

**Issue by shafayatb** [googlesamples/mlkit#325]
Hello, I am trying to get the text and the position of the text in the following image,

![paintbynumbers](https://user-images.githubusercontent.com/20676587/126136721-07dd1b0d-67e1-405b-b384-9cf378a2b587.png)

But the text recognizer cannot extract single digit from this image. Is there a way to fix this issue? Thanks.

**Comment by chrisito** [comment]
In the upcoming release of ML Kit (early August) we are providing an update to the Text Recognition API. This will also support detection of individual digits as seen in the screenshot below.

![Screenshot_20210719-113122](https://user-images.githubusercontent.com/4472437/126366604-852e65eb-8494-4969-b568-b1eed2a8b5ae.png)

**Comment by kund3** [comment]
still have this problem, do we have any setting for better single char recognize?
