### ISSUE TITLE
Updated NNAPI/GPU timeline for pose

### ISSUE THREAD

**Issue by jalen-launchpad** [googlesamples/mlkit#327]
Hi, I know this has been asked months ago, but wanted to check in again to see if your team has an updated ETA on GPU/NNAPI acceleration for pose estimation and to confirm that you still plan to eventually support these 2 features?

Thanks!

**Comment by chrisito** [comment]
@jalen-launchpad We still have this on our roadmap, but we have no specific timeline at the moment. The plan is to enable acceleration on select devices first and then expand as we get more confidence. Our utmost priority is to ensure stability / consistency on devices, so we are approaching this carefully. Sorry for not being able to provide a lot more clarity at this point.
