### ISSUE TITLE
iOS pod version not aligned with release notes versions

### ISSUE THREAD

**Issue by QuentinBrun** [googlesamples/mlkit#328]
Hi,

It looks like the release note versions given at the following page: https://developers.google.com/ml-kit/release-notes are not aligned with the one in cocoapods. Is that normal ?

For example, current latest cocoapod version for BarcodeScanning is 0.64.0 while release note state 1.3.0.

See Podfile.lock generated on the 21th of July 2021:

PODS:
  - GoogleDataTransport (8.0.0):
    - nanopb (~> 2.30906.0)
  - GoogleMLKit/BarcodeScanning (0.64.0):
    - GoogleMLKit/MLKitCore
    - MLKitBarcodeScanning (~> 0.64.0)
  - GoogleMLKit/MLKitCore (0.64.0):
    - MLKitCommon (~> 0.64.0)
  - GoogleToolboxForMac/DebugUtils (2.3.0):
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - GoogleToolboxForMac/Defines (2.3.0)
  - GoogleToolboxForMac/Logger (2.3.0):
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - "GoogleToolboxForMac/NSData+zlib (2.3.0)":
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.3.0)":
    - GoogleToolboxForMac/DebugUtils (= 2.3.0)
    - GoogleToolboxForMac/Defines (= 2.3.0)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.3.0)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.3.0)"
  - GoogleUtilities/Environment (7.0.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.0.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/UserDefaults (7.0.0):
    - GoogleUtilities/Logger
  - GoogleUtilitiesComponents (1.0.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.5.0)
  - MLKitBarcodeScanning (0.64.0):
    - MLKitCommon (~> 0.64)
    - MLKitVision (~> 0.64)
  - MLKitCommon (0.64.2):
    - GoogleDataTransport (~> 8.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - GoogleUtilities/UserDefaults (~> 7.0)
    - GoogleUtilitiesComponents (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - MLKitVision (0.64.0):
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
    - MLKitCommon (~> 0.64)
    - Protobuf (~> 3.12)
  - nanopb (2.30906.0):
    - nanopb/decode (= 2.30906.0)
    - nanopb/encode (= 2.30906.0)
  - nanopb/decode (2.30906.0)
  - nanopb/encode (2.30906.0)
  - PromisesObjC (1.2.11)
  - Protobuf (3.13.0)

DEPENDENCIES:
  - GoogleMLKit/BarcodeScanning (= 0.64.0)

SPEC REPOS:
  trunk:
    - GoogleDataTransport
    - GoogleMLKit
    - GoogleToolboxForMac
    - GoogleUtilities
    - GoogleUtilitiesComponents
    - GTMSessionFetcher
    - MLKitBarcodeScanning
    - MLKitCommon
    - MLKitVision
    - nanopb
    - PromisesObjC
    - Protobuf

SPEC CHECKSUMS:
  GoogleDataTransport: 6ce8004a961db1b905740d7be106c61ba7e89c21
  GoogleMLKit: 3c1f895592d95625eb57b8e66d4f13a5d36f9b49
  GoogleToolboxForMac: 1350d40e86a76f7863928d63bcb0b89c84c521c5
  GoogleUtilities: ffb2f4159f2c897c6e8992bd7fbcdef8a300589c
  GoogleUtilitiesComponents: a69c0b3b369ba443e988141e75ef49d9010b1c80
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  MLKitBarcodeScanning: 7b380e25719fb194292063e217c1ddbb0edbb506
  MLKitCommon: bc4f9fc68ea0edba2e8cbb16805df924f40b0e38
  MLKitVision: bd96ec12ea19d589435523c914766538da259161
  nanopb: 1bf24dd71191072e120b83dd02d08f3da0d65e53
  PromisesObjC: 8c196f5a328c2cba3e74624585467a557dcb482f
  Protobuf: 3dac39b34a08151c6d949560efe3f86134a3f748

PODFILE CHECKSUM: 45a287be7cde6be2a0f7044f0e6ccf09c699cbea

COCOAPODS: 1.10.0

It make it more difficult to work with fixed version in the pod file.

Thanks

**Comment by bcdj** [comment]
Thanks for the report.  If you go to cocoapods.org and enter `MLKitBarcodeScanning` in its big SEARCH box, it will show that `1.3.0` is the latest version. You can also find the latest podspec on github [here](https://github.com/CocoaPods/Specs/blob/master/Specs/b/5/4/MLKitBarcodeScanning/1.3.0/MLKitBarcodeScanning.podspec.json). You can try out ML Kit [quickstart vision sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision) and it will use the latest version of MLKitBarcodeScanning. I'm guessing the reason why you are not getting the latest version is either due to your specific Podfile (Does it pin to some older version of cocoapods in your Podfile? Can you share your Podfile?) or you did not clean up your local cache (I usually remove the `Pods` folder and the `Podfile.lock` in my project directory, run `pod cache clean --all`, followed by `pod update`).

**Comment by bcdj** [comment]
Another possibility is your Podfile uses or depends on some old version of cocoapods that only an older version of ML Kit depends on. If you can provide your Podfile, we can try to take a look.

**Comment by QuentinBrun** [comment]
Ok thanks you for your answer. The issue was that I used the module name given in the sample of this repository: ios/quickstarts/vision/Podfile which is pointing on GoogleMLKit/BarcodeScanning and not MLKitBarcodeScanning

The ML Kit quickstart vision sample app is not using the correct pod module.

**Comment by QuentinBrun** [comment]
Even the documentation here is not pointing to the right pod module: https://developers.google.com/ml-kit/vision/barcode-scanning/ios

**Comment by bcdj** [comment]
Using the module name like `GoogleMLKit/BarcodeScanning` (as given in the [Podfile](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile#L6) of the quickstart sample app) is correct and you should be able to download the latest version `1.3.0` (as documented in the [release notes](https://developers.google.com/ml-kit/release-notes)) of `MLKitBarcodeScanning` pod, unless you have other constraints in your own Podfile.

**Comment by bcdj** [comment]
If possible, you can provide your Podfile and Podfile.lock to assist further discussion.

**Comment by QuentinBrun** [comment]
I tried again and it is now working well. Maybe I made a mistake with the clean cache call. Thank for your help.

**Comment by bcdj** [comment]
Glad to hear that and happy to help!
