### ISSUE TITLE
0.20.0 version of FirebaseMLVisionTextModel does not work

### ISSUE THREAD

**Issue by richard-new** [googlesamples/mlkit#33]
Code:
        let vision = Vision.vision()
        let textRecognizer = vision.onDeviceTextRecognizer()
        let imageMetadata = VisionImageMetadata()
        imageMetadata.orientation = GlobalUtils.visionImageOrientation(from:textimageCorpped.imageOrientation)
        let visionImage = VisionImage(image: textimageCorpped)
        visionImage.metadata = imageMetadata
        
        textRecognizer.process(visionImage) { text, error in
            guard error == nil, let text = text else {
                completionBlock(false,"",nil)
                return
            }
            
            let currentText = text.text
            
            completionBlock(true,currentText,text)
        }

The code works fine with version 0.19.0 of FirebaseMLVisionTextModel(firebase version : 6.24.0). upgrade to version 0.20.0 of FirebaseMLVisionTextModel(firebase version:6.27.0),  Xcode report error: -[GMVTextDetector initWith:size:angle:]: unrecognized selector sent to instance 0x60000066aa70

**Comment by cs-googler** [comment]
Hi, we made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit.
