### ISSUE TITLE
Pose detection Question

### ISSUE THREAD

**Issue by liuyunlong-pro** [googlesamples/mlkit#331]
1.Does detection support multiple people?
2.Cannot record video at the same time with CameraX?

**Comment by steven-chengji-yan** [comment]
Hi

1) We don't have multiple person support at the moment. Considering all the cases of people overlapping or touching each other, it is more complicated than single person. Currently, this is not on our near future roadmap. However, if we see more request, we could reconsider it. Thanks for your feedback.

2) Is this question specific to ML Kit? If it is more related to CameraX, I would suggest to ask a question in a CameraX channel, e.g. StackOverflow under the [cameraX tag](https://stackoverflow.com/questions/tagged/android-camerax). If it is a general Android question, StackOverflow could also be one good place to post this question.   However, please do let us know if this is ML Kit specific.
