### ISSUE TITLE
Ml kit flutter integration

### ISSUE THREAD

**Issue by pjbwchn** [googlesamples/mlkit#334]
Do you have any idea when ML Kit will be integrated into Flutter? Many thanks

**Comment by cs-googler** [comment]
Hi, we don't plan to support it officially in the near term but you can find some plugins(for example [this one](https://pub.dev/documentation/google_ml_kit/latest/)) developed by some community members online.

**Comment by pjbwchn** [comment]
Thank you for your reply. When you say 'we' do you mean Google? 

The third party ML Kit plugin you have linked to is buggy and still has Firebase dependencies (for iOS) which make it unusable.

Without Flutter integration there is no way to integrate ML into Flutter projects.

Thanks

**Comment by bcdj** [comment]
Right, Google has no plan to support Flutter integration in the near feature.  It also does not endorse or support flutter plugins provided by other parties.
