### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by PHRNTUT** [googlesamples/mlkit#335]
https://github.com/googlesamples/mlkit/blob/2247619380c137⁴217f8d8aed92d501520eae810d/android/android-snippets/app/src/main/java/com/google/example/mlkit/kotlin/TextRecognitionActivity.kt#L61 #330 @

- [ ] 

> ``

**Comment by jackqdyulei** [comment]
Close it because of incomplete info. Feel free to create a new one using our bug template.
