### ISSUE TITLE
Android Studio vision quick start can't run

### ISSUE THREAD

**Issue by Hilal-Urun** [googlesamples/mlkit#336]
Hi,
When I trying to build the project it gives an error like ;
> No signature of method: build_civko3fqbp11ze1xr754r50tn.android() is applicable for argument types: (build_civko3fqbp11ze1xr754r50tn$_run_closure1) values: [build_civko3fqbp11ze1xr754r50tn$_run_closure1@235ec156]

**Comment by Hilal-Urun** [comment]
![image](https://user-images.githubusercontent.com/37075702/128727201-04746f9c-c44b-4c17-99d8-33ab81a6b7d6.png)

**Comment by zhouyiself** [comment]
Is it same issue as https://github.com/googlesamples/mlkit/issues/123#issuecomment-686816989

**Comment by Hilal-Urun** [comment]
Okey I solved the problem which was gradle build file point to another project file, after fix the path, the problem was solved. Thanks for your response
