### ISSUE TITLE
FIRCannotCallOnMainThread - "This method must be called on a background thread."

### ISSUE THREAD

**Issue by bishalg** [googlesamples/mlkit#34]
I am using NextLevel for Session Capture - https://github.com/NextLevel/NextLevel

I am using Firebase Vision Face Detection to find the Head Z angle (headEulerAngleZ).

on the callback  

`func nextLevel(_ nextLevel: NextLevel, didAppendVideoSampleBuffer sampleBuffer: CMSampleBuffer, inSession session: NextLevelSession) {`

I am using 
`let visionImage = VisionImage(buffer: sampleBuffer)`

From the code of nextLabel it is clear that the callback is made on the main thread - 
```
 DispatchQueue.main.async {
   self.videoDelegate?.nextLevel(self, didAppendVideoSampleBuffer: sampleBuffer, inSession: session)
 }
```

On using the same Main Async Callback App crashed with an error message - 

> Thread 1: Exception: "This method must be called on a background thread."

But if I do process operation on Background 
`DispatchQueue.global(qos: .background).sync {  }` 

Again the code crashed at code - 
> detectedFaces = try faceDetector.results(in: image)

```
var detectedFaces: [VisionFace]? = nil
      do {
        detectedFaces = try faceDetector.results(in: image)
      } catch let error {
        print("Failed to detect faces with error: \(error.localizedDescription).")
      }
```

**Question** - Which is the correct way of calling the 

> Vision Face Detected

 method on a background thread?

**Comment by bcdj** [comment]
The Face detection in Firebase is deprecated. ML Kit (including face detection API) has migrated out of Firebase and become a standalone SDK.  Please check out our quickstart sample app on how to hook up the face detector to a streaming video camera callback:

https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L175

It should demonstrate how to achieve what you want.  Good luck!
