### ISSUE TITLE
iOS Smart Reply crash EXC_BAD_ACCESS, 'sensitiveTopicClassifier_' not found on object of type 'MLKITx_PODSmartReplyApi'

### ISSUE THREAD

**Issue by afanslau** [googlesamples/mlkit#340]
I've followed the instructions from the docs here https://developers.google.com/ml-kit/language/smart-reply/ios

After integrating to my existing project, I'm seeing an `EXC_BAD_ACCESS` crash on this line
`let client = SmartReply.smartReply()`

In the console logs I see only 
`ERROR: Could not open '(null)'.`

The top of the stack trace shows
```
#0	0x000000010853178a in hobbes::mlkit::SmartReplyPredictor::SmartReplyPredictor(std::__1::unique_ptr<tflite::FlatBufferModel, std::__1::default_delete<tflite::FlatBufferModel> >) ()
```

Some details
- Using `pod 'GoogleMLKit/SmartReply', '2.3.0'` in my Podfile
- The issue occurs with Xcode 12.4 and 12.5
- The issue occurs on both simulator and physical device
- Target OS on the project is 11.0, but I see the issue on all simulator OS versions 
- The issue occurs with both swift and objective-c usage
- I tried using another MLKit service (Language Identification), and it works fine. Seems to be only smart reply

I tried integrating the same code into a brand new project, and couldn't reproduce the issue. It seems to only happen in my existing project. 

After digging deeper into the memory graph, I see these more detailed error logs
```
error evaluating expression "(MLKITx_PODSmartReplyApi.sensitiveTopicClassifier_ (unique_ptr<expander::smartreply::classifier::SensitiveTopicsClassifierLite>) *)0x2801d7880": error: <user expression 3>:1:26: property 'sensitiveTopicClassifier_' not found on object of type 'MLKITx_PODSmartReplyApi'
(MLKITx_PODSmartReplyApi.sensitiveTopicClassifier_ (unique_ptr<expander::smartreply::classifier::SensitiveTopicsClassifierLite>) *)0x2801d7880
                         ^
error: <user expression 3>:1:64: use of undeclared identifier 'expander'
(MLKITx_PODSmartReplyApi.sensitiveTopicClassifier_ (unique_ptr<expander::smartreply::classifier::SensitiveTopicsClassifierLite>) *)0x2801d7880
                                                               ^
error: <user expression 3>:1:131: expected expression
(MLKITx_PODSmartReplyApi.sensitiveTopicClassifier_ (unique_ptr<expander::smartreply::classifier::SensitiveTopicsClassifierLite>) *)0x2801d7880
````

Given I can't reproduce the issue outside of my project, it leads me to believe there's something in the build settings that needs to change. Any help would be greatly appreciated. Thanks

**Comment by bcdj** [comment]
We don't debug individual apps, but you can compare your project with [ML Kit's quickstart smartreply sample apps](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/smartreply) (in both swift and objective-c), which work fine on iOS 11 simulator and real device. Good luck!
