### ISSUE TITLE
MLKit translate SDK crashes in release build

### ISSUE THREAD

**Issue by stevan-milovanovic** [googlesamples/mlkit#341]
We used [official guideline](https://developers.google.com/ml-kit/language/translation/android) to implement text translation feature with ML Kit on Android. It works as expected in the debug build but it crashes in the release build with the crash from native code:

`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x78f4752a0a in tid 5897`

If we mark release build as debuggable, crash does not occur.

Any ideas what could go wrong?

**Comment by bcdj** [comment]
This is a duplicate report of another [StackOverflow post](https://stackoverflow.com/questions/68832304/mlkit-translate-sdk-crashes-in-release-build).  Closing this report and let's continue the discussion/investigation using the StackOverflow post.
