### ISSUE TITLE
PoseDetector cannot recognize pose from NV21 InputImage format - Android

### ISSUE THREAD

**Issue by KubaSlowikowski** [googlesamples/mlkit#346]
I'm trying to detect human pose on given InputImage (from camera preview) following oficial [docs](https://developers.google.com/ml-kit/vision/pose-detection/android#java). 

**Problem** _(in detector)_:
`OnSuccessListener` is called, but there are no poses in a result _(size=0)_. Very rarely detects some chaotic points, but once in dozens of attempts detector detected pose correctly (full body image).

Here's my code:
```
     PoseDetectorOptions poseDetectorOptions = new PoseDetectorOptions.Builder()
             .setDetectorMode(PoseDetectorOptions.STREAM_MODE)
             .build();
     PoseDetector poseDetector = PoseDetection.getClient(poseDetectorOptions);

    ...

     Task<Pose> poseDetectorResult = poseDetector.process(inputImage);
     poseDetectorResult
             .addOnSuccessListener(pose -> {
                 pose.getAllPoseLandmarks().forEach(poseLandmark -> {
                     PointF point = poseLandmark.getPosition();
                     canvas.drawCircle(mImageSize.getHeight() - point.x, point.y, 4, paint);
                 });
                 mImageView.setImageBitmap(bitmap);
             })
             .addOnFailureListener(error -> {})  // <- not being called
             .addOnCompleteListener(pose -> {
                 image.close(); // <-- android.media.Image
             });
```
I'd like to add that the same code logic works correct with FaceDetector.
I also tried with higher image resolution.

**EDIT:**
PoseDetector is **not** working when I create `InputImage` from `ByteBuffer`:  (but works perfect and way faster with FaceDetector)
```
public static InputImage fromImageToInputImage(Image image, int rotation) {
        ByteBuffer byteBuffer = image.getPlanes()[0].getBuffer();
        byte[] bytes = new byte[byteBuffer.remaining()];
        byteBuffer.get(bytes);
        InputImage result = InputImage.fromByteBuffer(
                byteBuffer,
                image.getWidth(),
                image.getHeight(),
                rotation,
                InputImage.IMAGE_FORMAT_NV21
        );
        return result;
    }
```
But when I'll try to create InputImage directly from Image, it works (the downside is that approach works too slow with different detector - FaceDetector):
```
    public static InputImage fromImageToInputImage(Image image, int rotation) {
        InputImage result = InputImage.fromMediaImage(image, rotation);
        return result;
    }
```

**Comment by steven-chengji-yan** [comment]
Hi KubaSlowikowski, 

Here is the code example in the vision-quickstart app about [how to convert YUV420 image to NV21](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/BitmapUtils.java#L196).

For your code, you only use the first plane to convert, which doesn't produce a valid NV21 format image.  The reason why FaceDetector works is due to some implementation details that you shouldn't rely on, e.g. FaceDetector may only use the first part of the bytebuffer.   If you use your current logic on some other features, e.g. Selfie Segmentation, it will probably fail as well.

Could you try updating your conversion logic and let us know if it fixes the issue?

**Comment by steven-chengji-yan** [comment]
In the meantime, I will also dig into the code to see if there is any more meaningful error message we could add.

**Comment by KubaSlowikowski** [comment]
> Hi KubaSlowikowski,
> 
> Here is the code example in the vision-quickstart app about [how to convert YUV420 image to NV21](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/BitmapUtils.java#L196).
> 
> For your code, you only use the first plane to convert, which doesn't produce a valid NV21 format image. The reason why FaceDetector works is due to some implementation details that you shouldn't rely on, e.g. FaceDetector may only use the first part of the bytebuffer. If you use your current logic on some other features, e.g. Selfie Segmentation, it will probably fail as well.
> 
> Could you try updating your conversion logic and let us know if it fixes the issue?

@steven-chengji-yan Thank you very much for that explanation. Now it works great :)

I'd like to ask You one more question about `FaceDetector`. If it works with only first plane converted from `Image`, can I use it this way (this solution is much faster than that shown in [BitmapUtils](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/BitmapUtils.java#L196))? Are there any hidden disadvantages of such a solution?

**Comment by steven-chengji-yan** [comment]
FaceDetector working in that way highly depends on its detailed implementation, which is not a contract we could maintain. 
From the InputImage factory method point of view, when you say a bytebuffer is in NV21 format, it should be a valid NV21 buffer. 
Therefore, I would suggest not depending on it. 

As for performance, that is a good point.
- Have you tried to convert the first plane to Bitmap and construct such an InputImage? Would that also be slow?
- For longer-term (no clear ETA), we might be able to consider adding some new format, e.g. single Plane bytebuffer, but we need more research to see whether it make sense or rather bringing in more confusions.
- If the Bitmap approach doesn't work and this "hack" for performance is what you really need, you could always stay with the current face-detection SDK version. And hopefully before the next attractive feature update, you/we could already figure out something to deal with this.

Best,

**Comment by steven-chengji-yan** [comment]
If Bitmap approach is slow, another approach you could try is to apply some 0 bytes behind the first plane buffer to make it a "valid" NV21 buffer.  It probably means you only use the [B/W version of the image](https://en.wikipedia.org/wiki/YUV#/media/File:Barn-yuv.png).  You may want to test whether the detector still works well for all your use cases after doing that.

Please let us know which approach works for you :)

**Comment by steven-chengji-yan** [comment]
I will close this issue for now due to no response in 2 weeks, but feel free to comment your findings or follow up here. Thanks!
