### ISSUE TITLE
App Store Connect ITMS-90562: Invalid Bundle issue

### ISSUE THREAD

**Issue by maxlapides** [googlesamples/mlkit#347]
Hi there! I'm not sure if there is a better place to file this issue, but when we upgrade to the latest versions of the MLKit dependencies, App Store Connect rejects our iOS app with this error:

> ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.

This issue seems to be the same: https://github.com/rmtmckenzie/flutter_qr_mobile_vision/issues/183

Is there some way to update the `GoogleMLKit/BarcodeScanning` to support bitcode in iOS builds?

**Comment by bcdj** [comment]
Which version of xcode are you using?  Can you try xcode 12.4 to see if the same issue happens?

**Comment by maxlapides** [comment]
This is my `Podfile.lock` diff. The old version is working, the new version is rejected by the App Store.

<img width="1385" alt="Screen Shot 2021-09-01 at 9 37 50 PM" src="https://user-images.githubusercontent.com/1874682/131782611-9697e2e0-3f73-4d3a-94f0-b14ea99ed67c.png">

**Comment by Jarutais** [comment]
I'm having the same issue with pod 'GoogleMLKit/SegmentationSelfie', '2.3.0'
It was uploading successfully with previous versions of the framework.

**Comment by miworking3** [comment]
Thanks for the information, this is our top priority right now. 
If this bitcode issue comes from building time, the best solution would be to fix it on the next release, which will be about 1 month later, unless there are any stop-gap that can be applied.

**Comment by miworking3** [comment]
FWIW, does this help?
https://stackoverflow.com/questions/49642653/xcode-9-3-cannot-submit-build-to-app-store/50805000#50805000
`
You can try to rebuild the app from bitcode by yourself and that might give you some more informations. To do that in Xcode archive your app, then in organizer, in archives tab click "Distribute App", select "Development", and after that select "Rebuild from Bitcode" and proceed. After that Xcode will probably show more extended information about the problem which might help you solve it.`

**Comment by Jarutais** [comment]
> FWIW, does this help?
> https://stackoverflow.com/questions/49642653/xcode-9-3-cannot-submit-build-to-app-store/50805000#50805000
> ` You can try to rebuild the app from bitcode by yourself and that might give you some more informations. To do that in Xcode archive your app, then in organizer, in archives tab click "Distribute App", select "Development", and after that select "Rebuild from Bitcode" and proceed. After that Xcode will probably show more extended information about the problem which might help you solve it.`

I got this error

<img width="752" alt="Captura de Tela 2021-09-02 às 16 43 20" src="https://user-images.githubusercontent.com/67167374/131906341-9095eb10-2d1b-4fdf-8b61-940f69444307.png">

**Comment by miworking3** [comment]
I see, this error will require to disable the bitcode if that's acceptable:
https://developer.apple.com/forums/thread/662947

```
Apple Clang - Code Generation --> "ENABLE CODE COVERAGE SUPPORT" need to set "NO" and

Build Option --> "ENABLE BITCODE" need to set "NO"
```

**Comment by maxlapides** [comment]
Unfortunately, I don't think this solution is acceptable for us. Shipping our app to the App Store with bitcode helps us minimize the download size of our app. Also, it is likely that bitcode will eventually be required to submit apps to the App Store.

**Comment by miworking3** [comment]
Understand, thanks for verifying that.

**Comment by bcdj** [comment]
We are working on a fix and plan to ship it in our next release at the end of the month.  A temporary workaround is to use the previous release.  For example, to use barcode scanning, you can have the following in your Podfile: `pod 'GoogleMLKit/BarcodeScanning', '2.2.0'`, and for selfie segmentation, you can use the following in your Podfile: `'GoogleMLKit/SegmentationSelfie', '2.2.0'`.

**Comment by bcdj** [comment]
ML Kit just shipped a new release. This issue is now fixed. Please download the latest ML Kit release using a Podfile similar to [the one](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile) in our vision quickstart sample app. Thank you for your patience!
