### ISSUE TITLE
barcode scan -> code 128B and code 128C scan raw value has an additional character

### ISSUE THREAD

**Issue by brsgina** [googlesamples/mlkit#348]
When I read a code128 or code128A format barcode using mlkit barcode scanner in my app in Android Studio , everything is fine. But when I read a code128B or code128C format barcode, it reads the raw value with an additional character, this: 
![image](https://user-images.githubusercontent.com/57450260/132011800-bf364754-4f44-45e6-ad3b-ab85f60d288e.png)

I used this site for barcode generation: http://www.barcodegenerator.online/

**Comment by zhouyiself** [comment]
I tried one generated from that site and it works fine. Can you share a sample image that didn't work for you?

**Comment by brsgina** [comment]
Of course!

So i generated this barcode first with the selection: **CODE 128**
![image](https://user-images.githubusercontent.com/57450260/132225235-43f325d4-e606-427b-9a83-dcec5ffce216.png)

And I scanned this file with my android app, I printed out the raw value:
![image](https://user-images.githubusercontent.com/57450260/132225500-52000642-f2bf-4c84-8348-bdf1a864ef34.png)

After, I generated the same barcode, but with the selection of **Code128B**
![image](https://user-images.githubusercontent.com/57450260/132225560-7c233f25-f118-4889-8b86-088b0b8d7de7.png)

I scanned that barcode too, and the raw value is the same, but with one char addition (this char is seen only in the log, when I write out in a textview, it is not there):
![image](https://user-images.githubusercontent.com/57450260/132225701-df0c92f3-c581-4084-b8ed-c165a3535e56.png)

**Comment by zhouyiself** [comment]
Hi, the last character is part of the payload (group separator ascii 29), added by the generator.

**Comment by brsgina** [comment]
I thought the same thing, but I tried it with different generator and all generator did the same, but only with that code: KGMIK000072

For example with another code:
![image](https://user-images.githubusercontent.com/57450260/135217034-7310b024-6fa1-40c1-959a-5d5b2109a16b.png)

And when I scan the barcode:
![image](https://user-images.githubusercontent.com/57450260/135217095-0d5de276-fadd-45f9-b4d7-fe9ca4269161.png)
So there is no additional char in this time.

Let's see another online generator: http://generator.onbarcode.com/online-code-128-barcode-generator.aspx
![image](https://user-images.githubusercontent.com/57450260/135217280-36f60aa1-b0df-43ae-ae24-03f946df2594.png)
And when I scan it: 
![image](https://user-images.githubusercontent.com/57450260/135217356-4753bdbb-634a-4c6a-bab3-09948cb5dc19.png)

But with my other code, there is no additional char with this generator either:
![image](https://user-images.githubusercontent.com/57450260/135217596-7b37257a-170b-4a84-b6b7-f5376094879c.png)
![image](https://user-images.githubusercontent.com/57450260/135217624-18ae56e9-7a21-421e-9c6e-f4e0592013a9.png)

Even KGMIK000073 works fine.

**Comment by helsq** [comment]
zhouyiself, group separator ascii 29 is not a part of the payload in this case. ascii 29 (FNC1) in this case is a checksum. I have the same issue. If a checksum equals 29 (FNC1) ml kit returns a char 29 in a raw value.

**For example.** 
Barcode B12326, checksum equals 86 (SYN) raw value B12326
![1](https://user-images.githubusercontent.com/18318842/137444788-efb484a9-4a77-40a2-b122-93a720679435.png)

Barcode B12328, checksum equals 29 (FNC1) raw value B12326[char with ascii code 29]
![2](https://user-images.githubusercontent.com/18318842/137445039-29888467-e637-45df-9d82-42b461419b54.png)

FNC1 can be returned in several cases (see GS1-128) but not when FNC1 is a checksum

**Comment by lk7630** [comment]
> When I read a code128 or code128A format barcode using mlkit barcode scanner in my app in Android Studio , everything is fine. But when I read a code128B or code128C format barcode, it reads the raw value with an additional character, this: ![image](https://user-images.githubusercontent.com/57450260/132011800-bf364754-4f44-45e6-ad3b-ab85f60d288e.png)
> 
> I used this site for barcode generation: http://www.barcodegenerator.online/

Don't know if this is gonna help but if you use getRawValue() you can use getDisplayValue instead

**Comment by zhouyiself** [comment]
Updates: we have fixed this issue internally and the fix will be in our future release that is scheduled to be available at late January 2022.

**Comment by jswolf19** [comment]
Upgrading to 17.0.2 fixed this issue for me.
