### ISSUE TITLE
Live camera 

### ISSUE THREAD

**Issue by Gagandeep1408** [googlesamples/mlkit#349]
Live object detection how it will work?

**Comment by steven-chengji-yan** [comment]
Hi Gagandeep1408,

Could you clarify your question?

**Comment by Gagandeep1408** [comment]
My Question is that In your app there is an option i.e. Live Object 
https://github.com/googlesamples/mlkit/raw/master/android/material-showcase/screenshots/live_odt.gif

This feature is not working.

**Comment by zhouyiself** [comment]
Did you see any error logs?

**Comment by zhouyiself** [comment]
Please reopen with error logs, thanks!

**Comment by Gagandeep1408** [comment]
Is it solved?
