### ISSUE TITLE
Warning when using MLVision

### ISSUE THREAD

**Issue by thefabbulus** [googlesamples/mlkit#35]
Code:

```
let vision = Vision.vision()
let options = VisionFaceDetectorOptions()
options.contourMode = .all
options.performanceMode = .accurate
let faceDetector = vision.faceDetector(options: options)

let image = VisionImage(image: $0)
faceDetector.process(image) { faces, error in
  guard error == nil, let faces = faces, !faces.isEmpty else { return }
  for face in faces {
    if face.contour(ofType: .face) != nil {
      // do something
    }
  }
}
```

Xcode warning:

> +[FBMLx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.

**Comment by cs-googler** [comment]
Hi, we made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit. Could you try the standalone ML Kit to see if you still see this issue? Thanks
