### ISSUE TITLE
SDK memory is too large, how to solve?

### ISSUE THREAD

**Issue by lilitao00** [googlesamples/mlkit#350]
I wanted to apply the MLKitFaceDetection SDK to our ios-app, but the package memory was 203.9m (as shown in the picture). This affects ios-App package memory and affects uploads to the Appstore. So is there a way to change the MLKitFaceDetection SDK memory size?
<img width="892" alt="企业微信截图_19f25857-3425-465c-927f-04c198a4d1b9" src="https://user-images.githubusercontent.com/17545362/132797958-1c328da4-a52b-458d-8da6-431551acb1a9.png">

**Comment by bcdj** [comment]
The size of the MLKitFraceDetection framework is not what the iOS app will include when it's installed on the user's device for two reasons. First, the framework contains two architectures and only one of them will be downloaded from the App Store and used when the app is installed on the user's device. Secondly, majority of the framework size is attributable to bitcode, which allows the App Store to compile your app optimized for the target devices/OSes/etc, but size in the resulted app installed on the device will be much smaller. To get a better estimate of the size impact on the installed app, you can measure it using the [`cocoapod-size` tool](https://github.com/google/cocoapods-size). According to that tool, the size impact of MLKitFaceDetection:1.3.0 is around 26.4 MB, much smaller than the original framework size (192.9 MB).
