### ISSUE TITLE
Possibility of getting "real time" recognition from digitalink.

### ISSUE THREAD

**Issue by rajeevbk** [googlesamples/mlkit#351]
Hi.

I have to admit I have just cloned this repo and haven't gone through the code and the answer to this question is time-critical for me as its for a university project so I'm asking early, hopefully someone can point me in the right direction. 

Right now, the recognition from digitalink happens after I press a button, but is it possible to run the recognizer *as* we type ? The use case here is to feed the output form the recognizer to a predictive text model to gain predictions as we type. 

Thanks in advance!

**Comment by steven-chengji-yan** [comment]
Hi  rajeevbk,

"but is it possible to run the recognizer as we type" - I suppose you mean "... as we write".

Yes. One behavior you could achieve is to trigger the recognition after you draw each stroke. You can do it by setting [this value](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/digitalink/app/src/main/java/com/google/mlkit/samples/vision/digitalink/DigitalInkMainActivity.java#L52) to true instead.

If you want to trigger the recognition differently, you could update the logic [here](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/digitalink/app/src/main/java/com/google/mlkit/samples/vision/digitalink/StrokeManager.java#L156-L158) about when to trigger the recognize(). 

Unfortunately this question is not very related to the ML Kit SDK itself, but more like a general Android programming question. I can only provide you these pointers but couldn't help on a very concrete solution here.  If you would like to get more help, probably ask a more general Android programming question in StackOverflow or similar channel.

Best,

**Comment by rajeevbk** [comment]
Hi Steven,

Yes, you are correct, I did mean to say "write". Thanks for the quick feedback!
