### ISSUE TITLE
Unable to install pod in iOS

### ISSUE THREAD

**Issue by zaidahmed2468** [googlesamples/mlkit#355]
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/TextRecognitionKorean":
  In Podfile:
    GoogleMLKit/TextRecognitionKorean

None of your spec sources contain a spec satisfying the dependency: `GoogleMLKit/TextRecognitionKorean`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by bcdj** [comment]
Please share your Podfile (and Podfile.lock if you have one). You can check out our [quickstart sample apps](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision) supporting GoogleMLKit/TextRecognitionKorean. Specifically, please check out our [sample Podfile](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile).

**Comment by bcdj** [comment]
Closing the report due to lack of response.
