### ISSUE TITLE
Face detect -> ghost?

### ISSUE THREAD

**Issue by monxarat** [googlesamples/mlkit#359]
Hi guys,

I have using `com.google.mlkit:face-detection:16.1.2` for detect face. But is it working not perfect?
I think this framework detects ghost face possible? LOL

![image (1)](https://user-images.githubusercontent.com/4075787/134610399-319863a8-a6d6-425a-a284-e50974d7c270.png)

**Comment by SilverDestiny** [comment]
Hi,

Thanks for reporting this issue!
Do you have concrete steps or example image link that I can use to reproduce this issue? Then I can look more into it.
https://developers.google.com/ml-kit/vision/face-detection/android#input-image-guidelines
This is the public guideline for how to properly set up the inputs to detect faces.

**Comment by monxarat** [comment]
@SilverDestiny
>Do you have concrete steps or example image link that I can use to reproduce this issue? 
I capture it from a camera(USB camera).

Code
```java
// Face detector
  private FaceDetector faceDetector;
...
FaceDetectorOptions options = new FaceDetectorOptions.Builder()
            .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
            .setMinFaceSize(0.35f)
            .enableTracking()
            .build();
    faceDetector = FaceDetection.getClient(options);
...
rgbFrameBitmap = convetNV21ToBitmap.nv21ToBitmap(getYUVNV21Bytes(), previewWidth, previewHeight);
    readyForNextImage();

    final Canvas canvas = new Canvas(croppedBitmap);
    canvas.drawBitmap(rgbFrameBitmap, frameToCropTransform, null);

    InputImage image = InputImage.fromBitmap(croppedBitmap, 0);
    faceDetector.process(image).addOnSuccessListener(faces -> {
              if (faces.size() == 0) {
                updateResults(new LinkedList<>());
                return;
              }
              runInBackground(() -> onFacesDetected(faces));
            });
...

private void onFacesDetected(List<Face> faces) {
    final List<Detector.Recognition> mappedRecognitions = new LinkedList<>();
    // Note this can be done only once
    int sourceW = rgbFrameBitmap.getWidth();
    int sourceH = rgbFrameBitmap.getHeight();
    int targetW = portraitBmp.getWidth();
    int targetH = portraitBmp.getHeight();
    Matrix transform = createTransform(sourceW, sourceH, targetW, targetH, sensorOrientation);
    final Canvas cv = new Canvas(portraitBmp);

    // draws the original image in portrait mode.
    cv.drawBitmap(rgbFrameBitmap, transform, null);

    final Canvas cvFace = new Canvas(faceBmp);

    for (Face face : faces) {
      final RectF boundingBox = new RectF(face.getBoundingBox());

      // maps crop coordinates to original
      cropToFrameTransform.mapRect(boundingBox);

      // maps original coordinates to portrait coordinates
      RectF faceBB = new RectF(boundingBox);
      transform.mapRect(faceBB);

      // translates portrait to origin and scales to fit input inference size
      float sx = ((float) TF_OD_API_INPUT_SIZE_GENDER) / faceBB.width();
      float sy = ((float) TF_OD_API_INPUT_SIZE_GENDER) / faceBB.height();
      Matrix matrix = new Matrix();
      matrix.postTranslate(-faceBB.left, -faceBB.top);
      matrix.postScale(sx, sy);
      cvFace.drawBitmap(portraitBmp, matrix, null);
....

```

Image

![device-2021-09-27-144529](https://user-images.githubusercontent.com/4075787/134851483-594899c5-f785-42b0-b9fc-71e9f426b70e.png)


![device-2021-09-27-143128](https://user-images.githubusercontent.com/4075787/134850830-697165f2-beda-4cc7-9dbb-6c3498ead70f.png)
 
Debug Face Image
![debug_face](https://user-images.githubusercontent.com/4075787/134851148-c9fc11ba-11ec-4b67-9914-a027b0c644aa.jpg)

**Comment by jackqdyulei** [comment]
Close it because of the inactivity. Feel free to open it if you have any other question.

Thanks for your feedback. We will consider it and improving our model quality in 2022.

**Comment by Pthanadol** [comment]
> @SilverDestiny
> 
> > Do you have concrete steps or example image link that I can use to reproduce this issue?
> 
> I capture it from a camera(USB camera) with size 640x480.
> 
> Code
> 
> ```java
> // Face detector
>   private FaceDetector faceDetector;
> ...
> FaceDetectorOptions options = new FaceDetectorOptions.Builder()
>             .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
>             .setMinFaceSize(0.35f)
>             .enableTracking()
>             .build();
>     faceDetector = FaceDetection.getClient(options);
> ...
> rgbFrameBitmap = convetNV21ToBitmap.nv21ToBitmap(getYUVNV21Bytes(), previewWidth, previewHeight);
>     readyForNextImage();
> 
>     final Canvas canvas = new Canvas(croppedBitmap);
>     canvas.drawBitmap(rgbFrameBitmap, frameToCropTransform, null);
> 
>     InputImage image = InputImage.fromBitmap(croppedBitmap, 0);
>     faceDetector.process(image).addOnSuccessListener(faces -> {
>               if (faces.size() == 0) {
>                 updateResults(new LinkedList<>());
>                 return;
>               }
>               runInBackground(() -> onFacesDetected(faces));
>             });
> ...
> 
> private void onFacesDetected(List<Face> faces) {
>     final List<Detector.Recognition> mappedRecognitions = new LinkedList<>();
>     // Note this can be done only once
>     int sourceW = rgbFrameBitmap.getWidth();
>     int sourceH = rgbFrameBitmap.getHeight();
>     int targetW = portraitBmp.getWidth();
>     int targetH = portraitBmp.getHeight();
>     Matrix transform = createTransform(sourceW, sourceH, targetW, targetH, sensorOrientation);
>     final Canvas cv = new Canvas(portraitBmp);
> 
>     // draws the original image in portrait mode.
>     cv.drawBitmap(rgbFrameBitmap, transform, null);
> 
>     final Canvas cvFace = new Canvas(faceBmp);
> 
>     for (Face face : faces) {
>       final RectF boundingBox = new RectF(face.getBoundingBox());
> 
>       // maps crop coordinates to original
>       cropToFrameTransform.mapRect(boundingBox);
> 
>       // maps original coordinates to portrait coordinates
>       RectF faceBB = new RectF(boundingBox);
>       transform.mapRect(faceBB);
> 
>       // translates portrait to origin and scales to fit input inference size
>       float sx = ((float) TF_OD_API_INPUT_SIZE_GENDER) / faceBB.width();
>       float sy = ((float) TF_OD_API_INPUT_SIZE_GENDER) / faceBB.height();
>       Matrix matrix = new Matrix();
>       matrix.postTranslate(-faceBB.left, -faceBB.top);
>       matrix.postScale(sx, sy);
>       cvFace.drawBitmap(portraitBmp, matrix, null);
> ....
> ```
> 
> Image
> 
> ![device-2021-09-27-144529](https://user-images.githubusercontent.com/4075787/134851483-594899c5-f785-42b0-b9fc-71e9f426b70e.png)
> 
> ![device-2021-09-27-143128](https://user-images.githubusercontent.com/4075787/134850830-697165f2-beda-4cc7-9dbb-6c3498ead70f.png)
> 
> Debug Face Image ![debug_face](https://user-images.githubusercontent.com/4075787/134851148-c9fc11ba-11ec-4b67-9914-a027b0c644aa.jpg)

Hi @monxarat I have a question about integration. USB Camera compatible with MLkit. I cannot extract images from USB Camera Garage Can be processed I would like to ask for your advice.

**Comment by monxarat** [comment]
Hi @SilverDestiny,

MLKit doesn't support USB cameras directly. You can use another library to load images from a USB camera and then send those images to MLKit. Currently, MLKit supports loading images from a camera, but it doesn't natively support USB cameras. For USB camera support, you can use this library: https://github.com/saki4510t/UVCCamera.
