### ISSUE TITLE
Unable to detect more than three 2d barcodes at a time

### ISSUE THREAD

**Issue by zburkhardt-zz** [googlesamples/mlkit#36]
It appears that no more than three 2d barcodes are able to be detected in a given image. When passing preview frames to the barcode detector that contain more than three 2d barcodes only three barcodes are returned. Detection sort of bounces around across all of the 2d barcodes but only three can be scanned/tracked at any given time. Conversely, six to eight 1d barcodes seem to be detected/tracked just fine at any given time. 

Is this a limitation of the barcode detector given the complexity of 2d barcodes or is this potentially a known issue that can be remediated?

**Comment by cs-googler** [comment]
Hi, it should be supported. We made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit.
 Please check out the standalone ML Kit to see if you can detect >2 2d barcode.
