### ISSUE TITLE
Do you plan to add MediaPipe hand detection？

### ISSUE THREAD

**Issue by tcll321** [googlesamples/mlkit#360]
We currently use the mlkit pose detection function, but in some scenarios we need to use hand detection. Do you consider the rate of introducing the hand detection in MediaPipe into mlkit?

**Comment by steven-chengji-yan** [comment]
Hi tcll321,

Thanks for your feedback.

We don't have a plan to do it in Q4 this year. Will add it to our internal feature request list.
