### ISSUE TITLE
What if any other language support added onwards for Language Translation? Does It require an app update. Or framework can check and download new model remotely?

### ISSUE THREAD

**Issue by obsidiam-ios** [googlesamples/mlkit#361]
Suppose, we implemented ML Kit for language translation. If in future any other language supports comes, do we need to update our app with the latest framework or framework will be updated automatically to fetch new language remotely?

**Comment by sheepmaster** [comment]
Currently, adding support for new languages will require updating the SDK. We might publish new versions of the language models though, which would be automatically downloaded.
