### ISSUE TITLE
Execution failed for task ':app:validateSigningDebug'.

### ISSUE THREAD

**Issue by Umesh-01** [googlesamples/mlkit#362]
When I am trying to run vision-quickstart,

Error: Execution failed for task ':app:validateSigningDebug'.
> Keystore file 'C:\Users\91954\AndroidStudioProjects\vision-quickstart\app\facedetection' not found for signing config 'debug'.

![image](https://user-images.githubusercontent.com/83420185/135108239-fb6256ab-eff0-4ec0-b730-8a41facef46d.png)

**Comment by jackqdyulei** [comment]
Hi Umesh, it seems you are running your own project instead of ML Kit vision-quickstart in [here](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart/app/src/main), I am not quite sure your setup and in our sample app I don't think we use `app:validateSigningDebug`

**Comment by Umesh-01** [comment]
Hello @jackqdyulei 
I am using [this](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart) sample app...

**Comment by Umesh-01** [comment]
and [this](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/build.gradle) is my build.gradle file

**Comment by jackqdyulei** [comment]
Please also describe the step so I can try to repro, like

1) What command you use to sync the sample app to your directory
2) In which directory did you run the build command
3) What build command did you use
4) If you are building it in Android Studio, how did you import the project

**Comment by jackqdyulei** [comment]
Close it because of inactivity
