### ISSUE TITLE
I use wide camera in mlkit

### ISSUE THREAD

**Issue by jyj902** [googlesamples/mlkit#365]
Is it possible to use wide camera in mlkit?

**Comment by erickramon1235** [comment]
Sí. 

⁣Obtener TypeApp para Android ​

**Comment by jyj902** [comment]
Thanks.
In the Android sample app, CameraSelecter had only Front and Back.
Where can I switch to wide?
I used CameraX API

**Comment by steven-chengji-yan** [comment]
Hi jyj902,

This questions is out of the scope of ML Kit. It is a CameraX question. 
ML Kit just takes in whatever image the camera provides and processes it.

I believe you can find some help on CameraX by asking a question here https://stackoverflow.com/questions/tagged/android-camerax
