### ISSUE TITLE
Barcode scanning -> ITF, Code 128, and Code 39 returning some wrong values

### ISSUE THREAD

**Issue by nickdimiCiQ** [googlesamples/mlkit#367]
When i try to scan continuously (without stopping after a successful scan) ITF, Code 128, and Code 39 barcodes, some times the first characters of the barcode are returned wrong. I used the vision-quickstart app and the only change i made was to add a log line in the BarcodeScannerProcessor class to log the barcodes scanned. **The issue appeared on com.google.mlkit:barcode-scanning:17.0.0 it doesn't happen on earlier versions**

**_Example:_** Scanning an ITF barcode with the value 2401234567 it could return the value **1**401234567 

These are some barcodes with which i manage to reproduce the issue
[BarcodeTesting.docx](https://github.com/googlesamples/mlkit/files/7292329/BarcodeTesting.docx)

The models on which i manage to reproduce the issue: Pixel 3a Android 11, Pixel Android 10, Xcover 4 Android 7

**Comment by SilverDestiny** [comment]
Thanks for reporting this issue!
Just want to double-check to confirm that it happens "sometimes" on com.google.mlkit:barcode-scanning:17.0.0 but not every time, and it didn't happen on earlier versions before, correct?

**Comment by felipetce** [comment]
I have the version 16.0.2 and the same problem happens

**Comment by tramalhoml** [comment]
Hi everyone!

I testing with [quickstart project ](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart)and I have similar error. In my case a partial result is detected (see images below).

**Device**: Redmi 5 plus
**OS**: 8.1.0
**MLKit Library**: com.google.mlkit:barcode-scanning
**MlKiit Library Version**s: 16.1.2 and 17.0.0

16.1.2 | 17.0.0
---------|---------
![partial_scan_16 1 2](https://user-images.githubusercontent.com/54331549/143485848-633b6747-5c97-418e-b05c-39ec5e868e25.gif)|![partial_scan_17 0 0](https://user-images.githubusercontent.com/54331549/143485861-14216a8e-58f4-47d8-af51-7baf60534b82.gif)

**Comment by svangsgaard** [comment]
Hi
16.2.0 seems to work great, but 17.0.0 is really bad. At least it was when I tried it on Code 39 barcodes.

**Comment by tramalhoml** [comment]
Hello @SilverDestiny, there is updates about this issue?

**Comment by SilverDestiny** [comment]
[comment1](https://github.com/googlesamples/mlkit/issues/367#issue-1017908974) was created a bug and we're working on it. I raised the priority for that.

For https://github.com/googlesamples/mlkit/issues/367#issuecomment-979399927, it looks like this is a different issue with partial barcodes are detected. Could you create another issue for it so that we can work on it separately? Thanks!

**Comment by tramalhoml** [comment]
> [comment1](https://github.com/googlesamples/mlkit/issues/367#issue-1017908974) was created a bug and we're working on it. I raised the priority for that.
> 
> For [#367 (comment)](https://github.com/googlesamples/mlkit/issues/367#issuecomment-979399927), it looks like this is a different issue with partial barcodes are detected. Could you create another issue for it so that we can work on it separately? Thanks!

Hello @SilverDestiny there is a issue created in issue tracker:
https://issuetracker.google.com/u/1/issues/207732702

Do you need another issue in github too?

**Comment by SilverDestiny** [comment]
https://issuetracker.google.com/u/1/issues/207732702 this one is enough
Thanks for the link! Our internal team is working on it.

**Comment by jackyk-cognitoiq** [comment]
Hi,

Due to the issue mentioned here, we have been unable to upgrade the mlkit barcode scanning library. With the 16 KB memory page size requirement from Google, the current version we have does not comply to it (v16.2.0).

What would you recommend in this case since this issue is still not resolved?

**Comment by jackyk-cognitoiq** [comment]
@miworking3 Can you possibly comment on the above?
