### ISSUE TITLE
[ML Kit bug] Live text recognition crashing due to memory leak

### ISSUE THREAD

**Issue by aaprokofyev** [googlesamples/mlkit#37]
I've tried to run this sample without any modifications with the latest Firebase version available (6.5.0) and also tried few older versions. When I select 'live' text recognition I see in the xCode Instruments Profiler that there is some memory leak which causing App to consume memory up to 10 Gb (depends on device, I used iPhone 6 iOS 10.3.2) and then crashes. It took about 13 minutes to reproduce the crash on iPhone 6.

![Screenshot 2019-08-02 at 09 44 50](https://user-images.githubusercontent.com/12428705/62350126-6f1d4380-b50a-11e9-93b8-626f771a46e4.png)

**Comment by calren** [comment]
Hey @aaprokofyev, we've made a number of significant improvements to the text recognition sample app, and we think this should be fixed now. If you're still seeing the issue, please do let us know!
