### ISSUE TITLE
is there any way to detect human foot and get its parameter.

### ISSUE THREAD

**Issue by janeSmith99221** [googlesamples/mlkit#380]
I'm working on human foot detection. I want to track foot and get it's parameter. is there any way to do this.

**Comment by steven-chengji-yan** [comment]
MLKit Pose Detection provides 3 landmarks for each foot: https://developers.google.com/ml-kit/vision/pose-detection Each foot landmark have a 3D coordinates (the Z value is still experimental).

We don't have other APIs returning more detailed foot information.

What exact foot parameters are you looking for?

**Comment by janeSmith99221** [comment]
> MLKit Pose Detection provides 3 landmarks for each foot: https://developers.google.com/ml-kit/vision/pose-detection Each foot landmark have a 3D coordinates (the Z value is still experimental). In order to Pose detection to work, the person's face need to be in the image frame. So it won't work if you provide an image only with foot.
> 
> We don't have other APIs returning more detailed foot information.
> 
> What exact foot parameters are you looking for?

I want only foot parameters of foot like, hight, width, leftHeel, rightHeel, leftFootIndex, rightFootIndex, leftAnkle, rightAnkle

**Comment by steven-chengji-yan** [comment]
I will report this to our team as a feature request. However, we don't currently have any plan to work on such a feature. The closest SDK at the moment would be Pose Detection.  

Thanks for your feedback.

**Comment by janeSmith99221** [comment]
> I will report this to our team as a feature request. However, we don't currently have any plan to work on such a feature. The closest SDK at the moment would be Pose Detection.
> 
> Thanks for your feedback.

okay.
Thanks for quick reply.
