### ISSUE TITLE
Barcode parsing?

### ISSUE THREAD

**Issue by firefinchdev** [googlesamples/mlkit#381]
Hi
We can get instance of `Barcode` using `BarcodeScanner`
```
barcodeScanner.process(inputImage)
  .addOnSuccessListener { barcodes ->
      barcodes.forEach { onDetectedBarcode(it) }
  }.addOnCompleteListener {
      imageProxy.close()
  }
```

But if I want to get an instance of `Barcode` from its `rawValue`, how do I get it?

Usecase: Once user has scanned the barcode, I need to save the result on his/her device, so that I can get relevant details next time user opens my app. I can store the `rawValue` provided by `BarCode` in database, but cant get `Barcode` instance using `rawValue` string.

From what I understand, `Barcode` class does not expose a constructor where it can accept `rawValue`.

One workaround is that I generate a barcode Image from rawValue and then pass it to barcodeScanner every time user opens the app, but that just seems a wastage of resources(redundant barcode image generation and scanning every time app is opened).

**Comment by zhouyiself** [comment]
Hi Anirudh,

Barcode class does not implement Parcelable interface currently so there's no way to serialize it for now. My suggestion is that the rawValue is basically representing most things so you can save it and then recover it to get what things you actually want.

**Comment by firefinchdev** [comment]
Hi
I think we should be able to create an object of `Barcode` using rawValue` (maybe a constructor).


That would be really helpful and useful.

**Comment by zhouyiself** [comment]
Barcode contains more things than rawValue (e.g. bounding box), so they are not 100% exchangeable.

A viable way I think is to make it Parcelable in future (will revisit it internally).

For now I guess you have to go with your own workaround or refactor your logic to also accept raw value beside Barcode.
