### ISSUE TITLE
After object detection how can I use that object anchor

### ISSUE THREAD

**Issue by phucnv-2558** [googlesamples/mlkit#385]
After I detect the object I can't find any way to calculate the distance of the object to the screen so I can't 3d attach to the detected object

**Comment by bcdj** [comment]
ML Kit's Object Detection API supports only 2D, i.e. returns only 2D rectangles of the detected objects.  It does not currently support 3D, so can't return the distance between the object and the screen yet.

**Comment by phucnv-2558** [comment]
thank you

**Comment by bcdj** [comment]
you're welcome
