### ISSUE TITLE
How to limit barcode scanning to an Overlay Box Area with ML kit 

### ISSUE THREAD

**Issue by diaz9557** [googlesamples/mlkit#388]
I am using an ScannerOverlay View on Camera . I want to limit the Barcode scanning to the Visible Area only .
`public class ScannerOverlay extends ViewGroup {
    private float left, top;
    private int rectWidth, rectHeight;

    public ScannerOverlay(Context context) {
        super(context);
    }

    public ScannerOverlay(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public ScannerOverlay(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        TypedArray a = context.getTheme().obtainStyledAttributes(
                attrs,
                R.styleable.ScannerOverlay,
                0, 0);
        rectWidth = a.getInteger(R.styleable.ScannerOverlay_square_width, getResources().getInteger(R.integer.scanner_rect_width));
        rectHeight = a.getInteger(R.styleable.ScannerOverlay_square_height, getResources().getInteger(R.integer.scanner_rect_height));
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        setMeasuredDimension(widthMeasureSpec, heightMeasureSpec);
    }

    @Override
    public void onLayout(boolean changed, int left, int top, int right, int bottom) {
    }

    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        left = (w - dpToPx(rectWidth)) / 2;
        top = (h - dpToPx(rectHeight)) / 2;
        super.onSizeChanged(w, h, oldw, oldh);
    }

    public int dpToPx(int dp) {
        DisplayMetrics displayMetrics = getResources().getDisplayMetrics();
        return Math.round(dp * (displayMetrics.xdpi / DisplayMetrics.DENSITY_DEFAULT));
    }

    @Override
    public boolean shouldDelayChildPressedState() {
        return false;
    }

    @Override
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        int cornerRadius = 0;
        Paint eraser = new Paint();
        eraser.setAntiAlias(true);
        eraser.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));
        RectF rect = new RectF(left, top, dpToPx(rectWidth) + left, dpToPx(rectHeight) + top);
        canvas.drawRoundRect(rect, (float) cornerRadius, (float) cornerRadius, eraser);
        invalidate();

    }
}`

I can not find any Box detector in the sample app i was using Vision and it was there and just migrated to ML-kit . 
Can u guys help me with some direction . I found two ways first one is crop the image itself and second one is to discard barcode with the help of 'Barcode#BoundingBox' . But i can't figure out the implementation for this . I am trying with second way .

**Comment by zhouyiself** [comment]
ML Kit doesn't support specifying interesting area for now so you have to do it on your own.

I like your second option (i.e. discard barcode out of the area) considering the barcode detection is generally fast while image processing might not be.

**Comment by diaz9557** [comment]
Thanks for response @zhouyiself  . I got it working with the second approach . took some time but its almost done now.

**Comment by bhavin9488** [comment]
@diaz9557 i am also facing same issue, can you please help me how to solve the issue with second option.?

**Comment by anayaian** [comment]
@bhavin9488 wrote an article for just about that. For future reference https://medium.com/@saiful103a/scan-barcode-only-when-they-are-inside-a-specific-area-of-the-preview-android-fcf8e02404d7
