### ISSUE TITLE
iOS examples fail to build on Apple Silicon Mac/Developer Transition Kit

### ISSUE THREAD

**Issue by jasin755** [googlesamples/mlkit#389]
I'm using the Developer Transition Kit (DTK) which has an Apple Silicon ARM architecture. After a straight download of the repo and pod install with Cocoapods 1.10.0, the example iOS projects (for Translate and Smart Reply, at least) fail to build with these errors, respectively.

Translate

```
ld: building for iOS Simulator, but linking in object file (/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/translate/Pods/MLKitTranslate/Frameworks/MLKitTranslate.framework/MLKitTranslate) built for iOS, file '/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/translate/Pods/MLKitTranslate/Frameworks/MLKitTranslate.framework/MLKitTranslate' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Smart Reply

```
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/tylerhillsman/Downloads/mlkit-master/ios/quickstarts/smartreply/Pods/MLKitLanguageID/Frameworks/MLKitLanguageID.framework/MLKitLanguageID' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm unsure if it's project configuration thing or a dependency limitation at the moment. Any help would be appreciated!

**Comment by bcdj** [comment]
ML Kit does not support M1 yet. We have an internal bug tracking this, but no ETA at the moment due to some required infra is missing.

**Comment by bcdj** [comment]
@jasin755 To help us gauge the importance of supporting M1, could you share the size of your user base? And if you can also provide an App Store link to your app, that would be helpful too. In addition, I assume it's a simulator-only issue? Are you able to test your app on M1 using a real test device (iPhone or iPad)?

**Comment by wayson** [comment]
The solution is purchasing an intel mac mini.
