### ISSUE TITLE
Pose detection 

### ISSUE THREAD

**Issue by bhailal-capermint** [googlesamples/mlkit#390]
Android Pose Detection : When Jump and down than how to identify

**Comment by steven-chengji-yan** [comment]
Could you clarify your question? What do you want to identify? When you say jump/down, is the person always in the image frame?

**Comment by bhailal-capermint** [comment]
hello @steven-chengji-yan I want to jump count when person in frame in streaming use cash, Now we count only pushup and standup-sitdown

**Comment by steven-chengji-yan** [comment]
Currently, we only provide pushup and squat concrete examples in the demo app. The goal was to use them to help developers to know what pose detection is capable. For specific use cases, we provided this guide https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses 

If you have any trouble with the Colab in the link above, could you let us know which exact step you feel unclear and we will see if we can improve the Colab to make it more clear.

Thanks for your feedback.

**Comment by steven-chengji-yan** [comment]
Close due to inactive.
