### ISSUE TITLE
InputImage: com.google.ar.core.exceptions.FatalException: Unknown error in ArImage.getWidth().

### ISSUE THREAD

**Issue by baonq-2356** [googlesamples/mlkit#393]
Hi, i am using Sceneform 1.16.0 with MLKit. 
I get image from arframe by: `frame.acquireCameraImage()`, then i create bitmap from this image to provide to InputImage.fromBitmap
But eveytime i run my application, an exception will be throw:
`com.google.ar.core.exceptions.FatalException: Unknown error in ArImage.getWidth().
        at com.google.ar.core.ArImage.getWidth(ArImage.java:19)
        at com.example.sceneformdemo.MainActivity$onUpdate$1$1.invokeSuspend(MainActivity.kt:121)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`
        
-------------------
This is all of my code:
`
class MainActivity : AppCompatActivity(), Scene.OnUpdateListener {
    var arFragment: ArFragment? = null
    var detector: ObjectDetector? = null
    val coroutineScope = MainScope()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setupArFragment()
        initDetector()
    }

    private fun initDetector() {
        val localModel = LocalModel.Builder()
            .setAssetFilePath("models/object_detection.tflite")
            .build()

        val customObjectDetectorOptions =
            Cu//stomObjectDetectorOptions.Builder(localModel)
                .setDetectorMode(CustomObjectDetectorOptions.SINGLE_IMAGE_MODE)
                .enableMultipleObjects()
                .enableClassification()
                .setClassificationConfidenceThreshold(0.5f)
                .setMaxPerObjectLabelCount(3)
                .build()

        detector = ObjectDetection.getClient(customObjectDetectorOptions)
    }

    private fun setupArFragment() {
        arFragment = fragmentSceneform as? ArFragment
        arFragment?.arSceneView?.scene?.addOnUpdateListener(this)
    }

    override fun onUpdate(frameTime: FrameTime?) {
        arFragment?.let { arFragment ->

            val frame = arFragment.arSceneView.arFrame
            val camera = frame?.camera
            if (camera?.trackingState != TrackingState.TRACKING) return
            val imageFrame = frame.tryAcquireCameraImage()
            val imageFormat = imageFrame?.format
            coroutineScope.launch(Dispatchers.IO) {
                imageFrame?.let { imageFrame ->
                    try {
                        val imageBitmap = Bitmap.createBitmap(imageFrame.width, imageFrame.height, Bitmap.Config.ARGB_8888)
                        val inputImage = InputImage.fromBitmap(imageBitmap, 0)
                        imageFrame.close()

                    detector
                        ?.process(inputImage)
                        ?.addOnFailureListener { e ->
                            Log.e("NQB", "Failure: $e")
                            imageFrame.close()
                     }
                        ?.addOnSuccessListener { results ->
                            results.forEach { obj ->
                               Log.d("NQB", "${obj.labels.firstOrNull()?.text}")
                         }
                           imageFrame.close()
                        }
                    } catch (e: Exception) {
                        Log.d("NQB", "Error:", e)
                    }
                }
            }
            imageFrame?.close()
        }
    }

    private fun Frame.tryAcquireCameraImage() =
        try {
            acquireCameraImage()
        } catch (e: NotYetAvailableException) {
            null
        } catch (e: Throwable) {
            throw e
        }
}
`
-----------------
I was research this error for a long time, but i can't found solution.
Anyone can help me, pls?

**Comment by jackqdyulei** [comment]
Hi it seems there are two issues:

1) Seems you created an empty `imageBitmap` and never pass the real image content into it?

2) The crash happens be in ArImage, before you use ML Kit. Maybe you should ask the question [here](https://github.com/google-ar/sceneform-android-sdk)

**Comment by baonq-2356** [comment]
@jackqdyulei Thankyou so much, friend!

> 1. Seems you created an empty `imageBitmap` and never pass the real image content into it?

Yeah i think so, this line code throws my exception: 

> val imageBitmap = Bitmap.createBitmap(imageFrame.width, imageFrame.height, Bitmap.Config.ARGB_8888)

----------------------


> 2\. The crash happens be in ArImage, before you use ML Kit. Maybe you should ask the question [here](https://github.com/google-ar/sceneform-android-sdk)

Unfotunately, they don't allow add more question. Any other solution have you are?

**Comment by jackqdyulei** [comment]
I did some research and it seems Sceneform is archived(and maybe not maintained)..

Sorry I can't help you with that since it is out of the scope of ML Kit

**Comment by baonq-2356** [comment]
@jackqdyulei so i will close this issue, thank you so much!
