### ISSUE TITLE
Custom model behaves differently with MLKit

### ISSUE THREAD

**Issue by billychasen** [googlesamples/mlkit#394]
I followed the colab training for a custom object detector and tested the resulting tflite model in colab and it worked correctly on a test image.

I took the same image and model and loaded it with `LocalModel` and followed instructions online and it doesn't detect on the same image. Current options are `.singleImage` and I tried changing multiple options.

Any guidance on what it might be or how to get it to work would be greatly appreciated, thanks!

**Comment by jackqdyulei** [comment]
Hey billy, could you provide more information?

1. Version of the object detector SDK
2. Link of the colab and instructions
3. Code snippet if possible, which include the `detector` you used and `InputImage` you created

**Comment by steven-chengji-yan** [comment]
Also, are you using the Android or iOS SDK?

**Comment by billychasen** [comment]
@steven-chengji-yan iOS, @jackqdyulei tried 2.3.0 and 2.4.0. Give me a bit to cook up an example.

**Comment by billychasen** [comment]
@jackqdyulei Here's a full example. With the [example image](https://storage.googleapis.com/mlkit-issue/test_image.jpg), the colab finds [dozens of candidates](https://i.imgur.com/ODb4Dfs.png) and 1 box over the 0.1 threshold. The MLKit version finds nothing.

My main issue is the same model performs differently (although sometimes the MLKit project finds good candidate boxes on other images).

- [Colab to train](https://www.dropbox.com/s/357un7ytoa1a4bo/ML_Training_Bug.ipynb?dl=0) (I made a demo training set of random red squares). 
- [XCode project](https://github.com/billychasen/MLKit-Issue)

**Comment by bcdj** [comment]
@billychasen I'm trying to run your colab, but ran into the following error in "Step 3. Train the TensorFlow model with the training data": model = object_detector.create(train_data, model_spec=spec, epochs=10, batch_size=4, train_whole_model=True, validation_data=validation_data)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-932fe00211c5> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, epochs=10, batch_size=4, train_whole_model=True, validation_data=validation_data)

/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/object_detector.py in create(cls, train_data, model_spec, validation_data, epochs, batch_size, train_whole_model, do_train)
    254           model_spec.compat_tf_versions, compat.get_tf_behavior()))
    255 
--> 256     object_detector = cls(model_spec, train_data.label_map, train_data)
    257 
    258     if do_train:

AttributeError: 'NoneType' object has no attribute 'label_map'

Do you have an idea how to fix that?

Also, the "[example image](https://storage.googleapis.com/mlkit-issue/test_image.jpg)" link in the last post expired? I got the following error:

<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>The billing account for the owning project is disabled in state closed</Details>
</Error>

Could you post the example test_image.jpg again? Thanks!

**Comment by bcdj** [comment]
Also, could you provide the link to the original Google colab for training a custom object detector?  Thanks!

**Comment by bcdj** [comment]
Closing the report due to inactivity.
