### ISSUE TITLE
Pose Detect 

### ISSUE THREAD

**Issue by jyj902** [googlesamples/mlkit#395]
1. Can I know the 3D coordinates between the shoulder and hip landmarks?
2. The detection effect is reduced when lying down or when the face is slightly hidden. Is there any way to compensate?

**Comment by steven-chengji-yan** [comment]
Hi
1. I didn't fully get your question. Currently, we provide 3D coordinates for each landmark (with the Z value as experimental). And you can calculate any relation(e.g. distance, direction) between the 3D positions of multiple landmarks.

2. The current model work the best when the face is clear. 
  - Using pose **accurate** SDK would help improve the detection. 
  - Also if your input is stream/video, you may try if showing the face at the beginning and then lay down could give you better result with the help of tracking.  
  - Another reason could be that when lay down, some of the body part is hidden so it is harder for the model to tell their positions.

**Comment by jyj902** [comment]
Thank steven 
1. -> Do you plan on adding midpoint landmarks to give you an idea of how much your back is bent? (midpoint between hip and shoulder landmarks)
2. -> Is there a model that can only track the body without face recognition?

**Comment by steven-chengji-yan** [comment]
Hi jyj902

1. There is no near future plan for adding that, but thanks for your feature request.
2. At the moment, ML Kit doesn't provide such a model. Showing face helps the model to detect a person.

Thanks for your feedback. I will close this issue for now.
