### ISSUE TITLE
ML Kit Pose Detection in SwiftUI

### ISSUE THREAD

**Issue by IvanDeLucasRog** [googlesamples/mlkit#398]
Hi, I was trying to use pose detection in a SwiftUI project. All works fine after pod install in vision-quickstart, but when I try to migrate the project to Swift UI I get this error when I try to resume canvas. If a don't resume the project builds successfully. 

`Undefined symbols for architecture x86_64:
  "_GULLogBasic", referenced from:
      _MLKLog in MLKitCommon(MLKLogger.o)
  "_GPBClearOneof", referenced from:
      _MLKITx_EPTFlagValue_ClearValueOneOfCase in MLKitCommon(FlagValues.pbobjc.o)
      _MLKITx_PHENORegistrationInfo_ClearApplicationInfoOneOfCase in MLKitCommon(RegistrationInfo.pbobjc.o)
      _MLKITx_CLCCCounter_ClearCounterIdOneOfCase in MLKitCommon(Counters.pbobjc.o)
  "_OBJC_METACLASS_$_GTMLogger", referenced from:
      _OBJC_METACLASS_$_MLKITx_GIPLoggingReroutingGTMLogger in MLKitCommon(GIPLoggingReroutingGTMLogger.o)
  "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from:
      objc-class-ref in MLKitCommon(CCTLogOutputStream.o)
  "_OBJC_CLASS_$_GTMSessionCookieStorage", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
  "_OBJC_CLASS_$_GPBInt32Array", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutLogEvent.o)
  "_OBJC_CLASS_$_GPBFileDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(UploaderState.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(TypedFeatures.pbobjc.o)
      objc-class-ref in MLKitCommon(Clientanalytics.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(UploaderState.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(TypedFeatures.pbobjc.o)
      objc-class-ref in MLKitCommon(Clientanalytics.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GTMLogger", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
      objc-class-ref in MLKitCommon(CCTClearcutMetaLogger.o)
      objc-class-ref in MLKitCommon(PHTFlatFilePhenotype.o)
      objc-class-ref in MLKitCommon(CCTClearcutLogEvent.o)
      objc-class-ref in MLKitCommon(PHTURL.o)
      objc-class-ref in MLKitCommon(CCTLogWriter.o)
      objc-class-ref in MLKitCommon(CCTLogOutputStream.o)
      ...
  "_OBJC_METACLASS_$_GPBMessage", referenced from:
      _OBJC_METACLASS_$_MLKITx_EXHFetchReason in MLKitCommon(Enums.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_CCTUploaderState in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLSystemInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLModelInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLOtherError in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLImageInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLInferenceCommonLogEvent in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBMessage", referenced from:
      _OBJC_CLASS_$_MLKITx_EXHFetchReason in MLKitCommon(Enums.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_CCTUploaderState in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLSystemInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLModelInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLOtherError in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLImageInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLInferenceCommonLogEvent in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GULCCComponentContainer", referenced from:
      objc-class-ref in MLKitCommon(MLKContext.o)
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
  "_OBJC_METACLASS_$_GPBRootObject", referenced from:
      _OBJC_METACLASS_$_MLKITx_EXHEnumsRoot in MLKitCommon(Enums.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_CCTUploaderStateRoot in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLFirebaseMlSdkRoot in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_BARBarhopperRoot in MLKitCommon(Barhopper.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_EPIFlatFileRoot in MLKitCommon(FlatFile.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_TypedFeaturesRoot in MLKitCommon(TypedFeatures.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_ClientanalyticsRoot in MLKitCommon(Clientanalytics.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBEnumArray", referenced from:
      objc-class-ref in MLKitVision(GMVLogger.o)
  "_kGTMSessionFetcherStatusDomain", referenced from:
      ___69-[MLKModelDownloader beginModelDownloadWithURL:modelInfo:conditions:]_block_invoke.285 in MLKitCommon(MLKModelDownloader.o)
      ___91-[MLKITx_PHTInternalHeterodyneSyncer syncHoldingLockWithSyncedScopes:fetchReason:callback:]_block_invoke_2 in MLKitCommon(PHTInternalHeterodyneSyncer.o)
      ___150-[MLKITx_PHTHeterodyneSyncer batchSyncWithAccounts:syncedScopes:fetchReason:throttlingCache:heterodyneSyncInfo:accountToAuthToken:lastError:callback:]_block_invoke_2 in MLKitCommon(PHTHeterodyneSyncer.o)
      ___92-[MLKITx_PHTHeterodyneSyncer syncAccount:syncedScopes:fetchReason:throttlingCache:callback:]_block_invoke_2 in MLKitCommon(PHTHeterodyneSyncer.o)
      ___63-[MLKITx_GMVCloudVisionClient initWithCloudUri:apiKey:options:]_block_invoke in MLKitVision(GMVCloudVisionClient.o)
  "_OBJC_CLASS_$_GDTCORTransport", referenced from:
      objc-class-ref in MLKitCommon(MLKFirelogTransport.o)
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in MLKitCommon(MLKModelDownloader.o)
      objc-class-ref in MLKitVision(GMVCloudVisionClient.o)
  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
      objc-class-ref in MLKitCommon(PHTInternalHeterodyneSyncer.o)
      objc-class-ref in MLKitCommon(PHTHeterodyneSyncer.o)
  "_OBJC_CLASS_$_GTMLogMininumLevelFilter", referenced from:
      objc-class-ref in MLKitCommon(GIPLoggingReroutingGTMLogger.o)
  "_OBJC_CLASS_$_GPBRootObject", referenced from:
      _OBJC_CLASS_$_MLKITx_EXHEnumsRoot in MLKitCommon(Enums.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_CCTUploaderStateRoot in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLFirebaseMlSdkRoot in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_BARBarhopperRoot in MLKitCommon(Barhopper.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_EPIFlatFileRoot in MLKitCommon(FlatFile.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_TypedFeaturesRoot in MLKitCommon(TypedFeatures.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_ClientanalyticsRoot in MLKitCommon(Clientanalytics.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GULUserDefaults", referenced from:
      objc-class-ref in MLKitCommon(MLKAnalyticsLogger.o)
      objc-class-ref in MLKitCommon(MLKModelDownloader.o)
      objc-class-ref in MLKitCommon(MLKModelPreferencesManager.o)
  "_OBJC_CLASS_$_GULCCComponentType", referenced from:
      objc-class-ref in MLKitCommon(MLKContext.o)
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
      objc-class-ref in MLKitCommon(MLKModelManager.o)
  "_OBJC_CLASS_$_GPBEnumDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(Clientanalytics.pbobjc.o)
      objc-class-ref in MLKitCommon(VisionExtension.pbobjc.o)
      objc-class-ref in MLKitCommon(PhenotypeLog.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GULCCComponent", referenced from:
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

If in Build Settings I change VALID_ARCHS to arm64 all of that errors disappear but I get the following one:

`Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by IvanDeLucasRog** [comment]
I think that is a problem with the simulator, the libraries don't exist in the simulator environment.

**Comment by bcdj** [comment]
What's the model of your mac?  Does it use an Apple M1 arm64-based CPU/GPU? Also, please share the OS version of your mac, Xcode version, and the type of your simulator, and the iOS version of the simulator.

**Comment by IvanDeLucasRog** [comment]
Macbook Air M1 GPU
OS version: Monterrey 12.0.1
Xcode 13.1
All simulators (device and canvas in swiftui) with ios 15.0

Thanks a lot

**Comment by bcdj** [comment]
ML Kit does not support M1 yet.  We have an internal bug tracking this, but no ETA at the moment due to some required infra is missing.

**Comment by bcdj** [comment]
@IvanDeLucasRog To help us gauge the importance of supporting M1, could you share the size of your user base? And if you can also provide an App Store link to your app, that would be helpful too.

**Comment by bcdj** [comment]
Also, I assume it's a simulator-only issue? Are you able to test your app on M1 using a real test device (iPhone or iPad)?

**Comment by IvanDeLucasRog** [comment]
@bcdj the app is not in the App Store yet. I have an Android version with about 200 users, but the project is growing quickly.

Yes, it's a simulator only issue while try to run the canvas.

**Comment by maxlapides** [comment]
@bcdj On our project, ML Kit is preventing us from building our app with arm64 architecture. This is important because we are running into this issue: https://developer.apple.com/forums/thread/668488. So, if we remove ML Kit from our project, we can run the app with arm64 and the scrolling issue goes away. The best solution would be if ML Kit could support M1 chips properly. Thanks!
