### ISSUE TITLE
Check if a translate model is downloaded or not

### ISSUE THREAD

**Issue by rudrathedev** [googlesamples/mlkit#405]
I made a translation app, I'm looking for some examples to check if a  translation model is downloaded or not

**Comment by zhouyiself** [comment]
You can use the model management API to check the model availability.
https://developers.google.com/android/reference/com/google/mlkit/common/model/RemoteModelManager#isModelDownloaded(com.google.mlkit.common.model.RemoteModel)

https://developers.google.com/ml-kit/language/translation/android#manage-models
