### ISSUE TITLE
Check for a particular label

### ISSUE THREAD

**Issue by tirumala007** [googlesamples/mlkit#407]
i want to check if a level exists.
below code is from documentation.

       labeler.process(image)
        .addOnSuccessListener { labels ->
            // Task completed successfully
            
         for (label in labels) {
                    val text2 = label.text
                    val confidence = label.confidence
                   val index = label.index
                    text.text= text2 + confidence + index
                }
        }
        .addOnFailureListener { e ->
            // Task failed with an exception
          }

i want to check for the label Screenshot. "Screenshot" is the text i received when i checked.
so i need to check whether the result contains the label.

so, i have tried this,

              if(labels.contains())
            {
                      }

i don't know what to put in that contains argument. help me out
the attached image contains the text returned by the code : val text2 = label.text

![Screenshot_2021-12-13-00-55-50-95](https://user-images.githubusercontent.com/56605252/145726580-def1e96d-28e8-49d4-99e6-e41a83159150.png)
.

**Comment by zhouyiself** [comment]
You can manually use a loop to check if there's a label that has text "Screenshot" or use Java 8 steam utility like this:
`if (labels.stream().anyMatch(label -> label.getText().equals("Screenshot"))) {
    ...
}`

**Comment by tirumala007** [comment]
it requires @RequiresApi(Build.VERSION_CODES.N)
mine minimum target is 23.


![Screenshot (149)](https://user-images.githubusercontent.com/56605252/145750176-e1fbef45-1e78-47d2-a733-50432892cf2a.png)

**Comment by tirumala007** [comment]
i did something.

                    val label: ImageLabel? = null
                        if (label in labels) {
                            if (label != null) {
                                if(label.text == "Screenshot")
                                {
                                      }
                                   }
                                     }

is this a valid approach? i think it is time consuming.

**Comment by zhouyiself** [comment]
It doesn't request minimum API level if you upgrade your project to use Android Gradle Plugin 4.0.0+
https://developer.android.com/studio/write/java8-support#library-desugaring

Iteration on all labels manually should also be fine because the number of returned labels are limited.

**Comment by tirumala007** [comment]
it worked. closing this,
