### ISSUE TITLE
Get bitmap from live preview

### ISSUE THREAD

**Issue by tirumala007** [googlesamples/mlkit#408]
i want to get the bitmap without capturing the image in livepreview activity.
when i stop the preview, i want  to get the last frame. so that i can check my custom model. along with the image classification.

below code is what i used to stop the preview.
           camera_btn.setOnClickListener {
            preview?.stop()
        }
now, i want to get the lables and the bitmap from the last preview.
i have a custom tflite model. so after stopping the preview, i need to perform additional checking.

**Comment by zhouyiself** [comment]
Which Camera API you're using? Camera1, Camera2 or CameraX?

Do you have code to access the preview frame? If so, can't you just save the last frame and convert it to Bitmap for processing?

**Comment by tirumala007** [comment]
i'm using the sample project from git hub.
i'm really new to android studio.

https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/kotlin/LivePreviewActivity.kt

**Comment by zhouyiself** [comment]
Here's the preview frame from the Camera, so you can save the latest one in your own way.
https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/CameraSource.java#L561
