### ISSUE TITLE
Unresolved reference: DEFAULT_OPTIONS

### ISSUE THREAD

**Issue by afskalsfk** [googlesamples/mlkit#409]
I downloaded the JDK NDK and other environment running error:Unresolved reference: DEFAULT_OPTIONS

**Comment by zhouyiself** [comment]
Could you provide more context? Which ML Kit SDK? Which Android OS version?

**Comment by zhouyiself** [comment]
Please reopen with more context.

**Comment by agGitHub** [comment]
Same error when trying to run demo project 'android-snippets'. Any idea?
