### ISSUE TITLE
Face detection writes way too much logs

### ISSUE THREAD

**Issue by derzhavets** [googlesamples/mlkit#410]
I have my Run output window all clogged but this, for every detection cycle:

V/FaceDetectorV2Jni: detectFacesImageByteBufferMultiPlanes.start()
V/FaceDetectorV2Jni: detectFacesImageByteBuffer.end()
V/FaceDetectorV2Jni: detectFacesImageByteBufferMultiPlanes.start()
V/FaceDetectorV2Jni: detectFacesImageByteBuffer.end()
V/FaceDetectorV2Jni: detectFacesImageByteBufferMultiPlanes.start()
V/FaceDetectorV2Jni: detectFacesImageByteBuffer.end()
V/FaceDetectorV2Jni: detectFacesImageByteBufferMultiPlanes.start()
V/FaceDetectorV2Jni: detectFacesImageByteBuffer.end()

Is there any way to make this process less verbose? 

Thank you

**Comment by jackqdyulei** [comment]
Try this? We used `Log.v` for those logs

https://sdks.support.brightcove.com/android/troubleshooting/removing-android-log-messages.html

**Comment by derzhavets** [comment]
> Try this? We used `Log.v` for those logs
> 
> https://sdks.support.brightcove.com/android/troubleshooting/removing-android-log-messages.html

Thank you!

**Comment by fbernaly** [comment]
I am working on this Flutter example app for MLKit and I want to remove the excessive logs from Face detection and I implemented what is suggested here and here: https://stackoverflow.com/a/69476973/3610617
But I am still getting all those logs in my app.
Any help?
These are my changes in my app: https://github.com/flutter-ml/google_ml_kit_flutter/pull/478

**Comment by Marandil** [comment]
> Try this? We used Log.v for those logs
>
> https://sdks.support.brightcove.com/android/troubleshooting/removing-android-log-messages.html

I don't think this is a valid solution for *development* workflow. The release packages of MLKit FaceDetection currently spam **a lot** on D and V levels. I'm getting the following log every 30 ms:

```
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 2
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 3
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 4
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 5
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 6
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 10
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 45
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 43
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 44
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 200
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 220
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 221
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 222
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 223
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 224
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 225
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 226
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 227
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 300
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 302
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 312
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 314
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 315
  2893-3238  ThickFaceDetector       com.example.app       D  Unknown landmark type: 316
  2893-3285  FaceDetectorV2Jni       com.example.app       V  detectFacesImageByteBufferMultiPlanes.start()
  2893-3285  FaceDetectorV2Jni       com.example.app       V  detectFacesImageByteBuffer.end()
```

This in turn makes our app reach log quota very quickly:

```
  2893-3287  LOG_FLOWCTRL            com.example.app       W  ==LOGS OVER PROC QUOTA(300), rows(455) bytes(12491) com.example.app u(0) l(0) t(0) c(0) DROPPED==
```

The first suggested solutions are ok-ish for release builds, but not for development/debug.

CameraX lets us configure its log level like [this](https://developer.android.com/media/camera/camerax/configuration#cameraxconfig):

```kotlin
class CameraApplication : Application(), CameraXConfig.Provider {
   override fun getCameraXConfig(): CameraXConfig {
       return CameraXConfig.Builder.fromConfig(Camera2Config.defaultConfig())
           .setMinimumLoggingLevel(Log.ERROR).build()
   }
}
```

We would appreciate if there was at least a similar way to configure MLKit or individual analyzers.
