### ISSUE TITLE
FaceDetector on iOS: resources keep staying in memory

### ISSUE THREAD

**Issue by ozpopolam** [googlesamples/mlkit#411]
Hi!
Once I finish using FaceDetector (`GoogleMLKit/FaceDetection 2.4.0`), I'd like to free all resources it uses (for Demo it is additional 35 MB according to Xcode Memory report). Looks like there is a suitable method for Android here - https://developers.google.com/android/reference/com/google/mlkit/vision/face/FaceDetector#public-abstract-void-close, but I can't find a way to do it on iOS.

1) So I just install Demo on device:
![2021-12-15_13-25-11](https://user-images.githubusercontent.com/17257151/146172433-b0a45bc6-4a5c-4fb6-8ae0-83af782aa97f.png)

2) Perform my first Face Detection with stored "grace_hopper" image and memory increases to 55 MB:
![2021-12-15_13-27-12](https://user-images.githubusercontent.com/17257151/146172453-8dcd7680-f750-4540-8306-2880129560b5.png)

3) As I keep repeating Detection on the same image it increases to 60 MB and stays on this level:
![2021-12-15_13-29-30](https://user-images.githubusercontent.com/17257151/146172575-233bc0c7-8933-4e85-b667-60e1a52f9588.png)

Could you tell me how to free this memory?

**Comment by miworking3** [comment]
I'm afraid with the shift of priority in our team, there is no plan in the near future to address this.
