### ISSUE TITLE
Can't get eye or smile probability or facial landmarks.

### ISSUE THREAD

**Issue by janeSmith99221** [googlesamples/mlkit#412]
I tried to get eye probability or landmarks from detected face. but it returns null.
I working with ML Kit Vision Quickstart.
is there any way to do this.

**Comment by jackqdyulei** [comment]
Please clarify
1. which version of the SDK
2. Android or IOS

If Android, please make sure the options for [landmark](https://developers.google.com/android/reference/com/google/mlkit/vision/face/FaceDetectorOptions.Builder#setLandmarkMode(int)) and [classification](https://developers.google.com/android/reference/com/google/mlkit/vision/face/FaceDetectorOptions.Builder#setClassificationMode(int)) is ON

**Comment by janeSmith99221** [comment]
> Please clarify
> 
> 1. which version of the SDK
> 2. Android or IOS
> 
> If Android, please make sure the options for [landmark](https://developers.google.com/android/reference/com/google/mlkit/vision/face/FaceDetectorOptions.Builder#setLandmarkMode(int)) and [classification](https://developers.google.com/android/reference/com/google/mlkit/vision/face/FaceDetectorOptions.Builder#setClassificationMode(int)) is ON

SDK version 4.1.1
Android 11

**Comment by jackqdyulei** [comment]
Hmm, I don't think we have any face SDK with version 4.1.1. Can you take a look [here](https://developers.google.com/ml-kit/release-notes) and tell me the SDK name & version(e.g. `com.google.mlkit:face-detection:16.1.3`)

If possible, please share your test image or try that in [our sample app](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart). Please make sure the `face classification` is turned on in the settings in our sample app

**Comment by janeSmith99221** [comment]
yes, it's my mistake. I forgot to enable tracking.
