### ISSUE TITLE
Mlkit Translate about Appbundle

### ISSUE THREAD

**Issue by tmxdyf** [googlesamples/mlkit#416]
Hello, I have a request, can I put the Translate Kit in the AppBundle for dynamic delivery? Can you provide an example?

**Comment by zhouyiself** [comment]
Does this help? https://developers.devsite.corp.google.com/ml-kit/tips/reduce-app-size#advanced_move_optional_ml_features_to_dynamic_feature_modules

**Comment by zhouyiself** [comment]
Please reopen if it doesn't help.
