### ISSUE TITLE
[MLKITx_CCTClearcutUploader crashIfNecessary] 

### ISSUE THREAD

**Issue by ShaikhAfsan** [googlesamples/mlkit#418]
[lvl=3] +[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple up-loaders function correctly but have an adverse affect on battery performance due to lock contention. i am getting this issue while using face detection with live images and getting memory waring and application getting terminated

**Comment by jackqdyulei** [comment]
Could you use our `bug report` template to file issue and include necessary info listed in template? Thanks!

https://github.com/googlesamples/mlkit/issues/new/choose
