### ISSUE TITLE
Application is getting crashed while using GoogleMlkit  for face detection 

### ISSUE THREAD

**Issue by KomalABB1** [googlesamples/mlkit#419]
while app launching getting memory issue  & also randomly getting this issue 

+[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.

+[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention. - getting this issue twise time

**Comment by miworking3** [comment]
Could you use our bug report template to file issue and include necessary info listed in template?  
https://github.com/googlesamples/mlkit/issues/new/choose

This crash doesn't reproduce on my side, so curious what device did you hit this problem.
Thanks!
