### ISSUE TITLE
Application is getting crashed due to memory issue while using google ml kit for face detection

### ISSUE THREAD

**Issue by ShaikhAfsan** [googlesamples/mlkit#420]
**Describe the bug**
I am getting  following issue while using google ml kit's face detection function and due to memory warring my application is getting crashed randomly
[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple up-loaders function correctly but have an adverse affect on battery performance due to lock contention getting this issue in ml kit 

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

faceDetector.process(visionImage) { faces, error in

            guard error == nil, let faces = faces, !faces.isEmpty else {
                // ...
                return
            }
            
            
            self.resultsText = faces.map { face in
                
                let headEulerAngleX = face.hasHeadEulerAngleX ? face.headEulerAngleX.description : "NA"
                let headEulerAngleY = face.hasHeadEulerAngleY ? face.headEulerAngleY.description : "NA"
                let headEulerAngleZ = face.hasHeadEulerAngleZ ? face.headEulerAngleZ.description : "NA"
                
           
                
                self.leftEyeOpenProbability =
                    face.hasLeftEyeOpenProbability
                    ? face.leftEyeOpenProbability.description : "NA"
                self.rightEyeOpenProbability =
                    face.hasRightEyeOpenProbability
                    ? face.rightEyeOpenProbability.description : "NA"
                self.smilingProbability =
                    face.hasSmilingProbability
                    ? face.smilingProbability.description : "NA"
                
                let output = """
                Frame: \(face.frame)
                Head Euler Angle Y: \(headEulerAngleY)
                Left Eye Open Probability: \(self.leftEyeOpenProbability)
                Right Eye Open Probability: \(self.rightEyeOpenProbability)
                Smiling Probability: \(self.smilingProbability)
                """
                print(output)
                
                if "-50" < headEulerAngleY && self.isLookLeft == false {
                    self.isLookLeft = true
                    print(" Look Left")
                    self.lookLeftCheckBox.image = UIImage(named:(self.isLookLeft ? "Check" : "Uncheck"))
                    
                }else if "12" < headEulerAngleY && headEulerAngleY < "36" && self.isLookRight == false  {
                    self.isLookRight = true
                    print ("Look Right")
                    self.lookRightCheckBox.image = UIImage(named:(self.isLookRight ? "Check" : "Uncheck"))
                    
                }
                
                if self.smilingProbability >= "0.80" && self.isSmile == false {
                    self.isSmile = true
                    if self.isSmile == false {
                        self.smileCheckBox.image=UIImage(named: "Uncheck")
                    }else {
                        
                        self.smileCheckBox.image=UIImage(named:"Check")
                    }
                    
                }
                
                
                return "\(output)"
            }.joined(separator: "\n")
            
        }
        // [END detect_faces]
    }

**Expected behavior**
It should give smile ,eye opening and headEulerAngleX probablity

**SDK Info:**
 - pod 'GoogleMLKit/FaceDetection'

**Smartphone:**
 - Device/Simulator: ios 12.4.6 and 12.5.5

**Development Environment:**
xcode version 12.5 and 12.4

**Comment by miworking3** [comment]
[MLKITx_CCTClearcutUploader crashIfNecessary]  is a warning, that won't cause crash. This problem is not reproducible on my side yet, could you provide more info about the crash? Any log in the console when the crash happens? The stack of the crash, or snapshots from [the Instruments in Xcode]( https://developer.apple.com/documentation/xcode/gathering-information-about-memory-use)?

**Comment by ShaikhAfsan** [comment]
Hi julie ,


There is no  crash log in the consloe as well as in the Instruments.


Thanks & Regards,
Afsana Shaikh

**Comment by miworking3** [comment]
Did you see any stack at the time when it crashes?
[How to trace where Xcode program crash](https://stackoverflow.com/questions/10878035/how-to-trace-where-xcode-program-crash)

**Comment by ShaikhAfsan** [comment]
No, I haven't.

**Comment by miworking3** [comment]
If it is a crash, it will come with a stack, so closing it for now. Please double check and reopen it with the crash stack if it is confirmed to be a crash. Thanks.
