### ISSUE TITLE
[Bug report] Chinese text recognition error

### ISSUE THREAD

**Issue by WMSmile** [googlesamples/mlkit#421]
**Describe the bug**
1、Simplified Chinese is recognized as Traditional Chinese，
2、“政” is recognized as  “敢”
3、"作,开启今年第1次国内考察。他强"  should be after "年冬奧奥会、冬残奧会籌办备赛工" 

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. image
[识别的图片](https://github.com/WMSmile/wechat-components/blob/main/screenshots/WechatIMG6462.jpeg)
2.results  : 

时敢微纪录|习近平总书
记冬奧行
央视新间客户端
新年伊始,
习近平总书记心系2022
年冬奧奥会、冬残奧会籌办备赛工
调,办好北京冬奥会、冬残奧会,
是我们向国际社会作出的庄严承
诺。经过几年努力,各项筹备工作
墓本就绪,我们完全有信心、有能
力为世界奉献一届精彩、非凡、卓
作,开启今年第1次国内考察。他强
越的奥运盛会。

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**

**SDK Info:**
 - SDK Name & Version [com.google.mlkit:text-recognition-chinese:16.0.0-beta2]

**Smartphone:**
 - Device/Simulator OS: [Android API 30]

**Development Environment:**
*(For Android issue feel free to skip this section)*

**Comment by zekst** [comment]
is it solved yet?

**Comment by vedopar** [comment]
Thanks for identifying those issues, they are under investigation. They will be addressed as best we can in future releases, there is no immediate fix we can provide now.

**Comment by WMSmile** [comment]
> Thanks for identifying those issues, they are under investigation. They will be addressed as best we can in future releases, there is no immediate fix we can provide now.

Thanks
