### ISSUE TITLE
[Feature request] Java Project for Material Showcase

### ISSUE THREAD

**Issue by 180017656** [googlesamples/mlkit#426]
**What's your feature request? Please describe.**
Could it be possible to have a Java project for the material showcase - it is currently wrote using Kotlin

**Mobile environment**
Android

**Additional context**
N/a

**Comment by zhouyiself** [comment]
Hi, we no longer support the Java version for the sake of simpler maintenance. If you really want to take a look at a similar Java implementation, you can check the below deprecated repo which have both Kotlin and Java versions.
https://github.com/FirebaseExtended/mlkit-material-android/tree/master/app/src/main/java/com/google/firebase/ml/md/java
