### ISSUE TITLE
us drivers license pdf417 barcode not detecting in iPhone 7 plus device

### ISSUE THREAD

**Issue by karthikprabhuA** [googlesamples/mlkit#43]
MLVisionExample is not detecting Delaware and North Carolina state drivers license barcode. I have not checked other state drivers license barcode. 
Tried by providing the UIImagePickerControllerOriginalImage image but success ratio is less than 10% in iPhone 7 plus device. Its working fine on iPhone X. Not tested on other devices.

**Comment by cs-googler** [comment]
Hi, we made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "[ML Kit](https://developers.google.com/ml-kit/guides)"(without firebase branding) contains all the on-device APIs. [Here's]( https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. All further improvements and new APIs will be released only with the new ML Kit.
