### ISSUE TITLE
 Is it possible to hide the download indicator from status bar

### ISSUE THREAD

**Issue by Charukasilva** [googlesamples/mlkit#430]
**Expected behavior**
Hide downloadfile-2.bin status from the user 

 - Samsung Smartphone 
 - Android API 29

**Comment by jackqdyulei** [comment]
Please follow up our template to create bug report. In your case I think following info is extreme helpful.

1. SDK name & version
2. screenshot
3. code snippet

**Comment by edi2212** [comment]
J

**Comment by edi2212** [comment]
![Uploading RDT_20220125_2238163507797216896903824.jpg…]()

**Comment by jackqdyulei** [comment]
Hi edi2212, I assume you want to upload an screenshot however I can't see it..
