### ISSUE TITLE
[Barcode Scanner] Open again the camera scanning

### ISSUE THREAD

**Issue by satriawarn** [googlesamples/mlkit#431]
How to open again the camera after success get 1st raw value, I found addOnSuccessListener but i don't know how to open camera 2nd time.

**Mobile environment**
Android

**Comment by zhouyiself** [comment]
ML Kit SDK doesn't control when to open or close the camera.

Do you mean the camera is closed automatically after first successful scan? Do you use ML Kit sample App or your own? If your own, can you provide some code snippet.

**Comment by zekst** [comment]
can you share the code of the function handling it.

**Comment by satriawarn** [comment]
I'm using ML Kit from [this](https://developers.google.com/ml-kit/vision/barcode-scanning/android) , here's my code

Activity :
![image](https://user-images.githubusercontent.com/33830500/151656178-2654847e-cfea-44e4-bc89-89c3f7ddc381.png)
And i put startCamera in onCreate, I try to open camera again after get the barcode string. The camera doesn't close but i can't get another barcode.

BarcodeAnalyzer:
![image](https://user-images.githubusercontent.com/33830500/151656235-302f1dc9-670c-44c6-a9d9-15214e98b7cf.png)

**Comment by zekst** [comment]
yeah i am looking on it

**Comment by zhouyiself** [comment]
I'm not sure if you do the camera unbinding & binding at the right place, maybe you can take a look at ML Kit's Camerax sample usage.
https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/kotlin/CameraXLivePreviewActivity.kt
