### ISSUE TITLE
how to save Save Selfie segmentation result with transparent background

### ISSUE THREAD

**Issue by pawaom** [googlesamples/mlkit#439]
how to save Save Selfie segmentation result with transparent background

I am referring  this code

https://github.com/googlesamples/mlkit/blob/52295b2ef35923f565b8ffeca31f49d4be6b08fd/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/segmenter/SegmentationGraphic.java#L40

It creates a purple background with the detected selfie image , Is there a way to save the detected image with a transparent background so that we can use it as a overlay over other views.

**Comment by steven-chengji-yan** [comment]
This is probably not very related to the SDK itself, but more about Android image processing.

Here is something you can try: based on the mask returned from the ML Kit API, use the [setPixel](https://developer.android.com/reference/android/graphics/Bitmap#setPixel(int,%20int,%20int)) API of Bitmap to update your original image's pixel values. You can define your own threshold for a pixel being in the background and then set that pixel value to transparent. In the end, you can save the Bitmap to disk.

**Comment by pawaom** [comment]
is there a way just to get the detected selfie and save it as an bitmap not the background. instead of "pixel being in the background and then set that pixel value to transparent".

**Comment by steven-chengji-yan** [comment]
In the current version of the Selfie SDK, there is no such support.

The quickest way for you to achieve what you want would be implementing it by yourself. It may take some time to learn it initially, but I think in the end, the code shouldn't be too complicated.

As for your suggestion, we will note it as a feature request and go through our prioritization process, but it will take some time and no promise to be implemented at the moment.

**Comment by pawaom** [comment]
thanks ,for considering it as a suggestion, please include it as an feature as soon as possible since selfie segmentation is still in beta phase.

**Comment by Office-Murtaza** [comment]
> This is probably not very related to the SDK itself, but more about Android image processing.
> 
> Here is something you can try: based on the mask returned from the ML Kit API, use the [setPixel](https://developer.android.com/reference/android/graphics/Bitmap#setPixel(int,%20int,%20int)) API of Bitmap to update your original image's pixel values. You can define your own threshold for a pixel being in the background and then set that pixel value to transparent. In the end, you can save the Bitmap to disk.


When I resize the bitmap to the mask size and use the set pixels api, I set the background pixel value to transparent. But how can I achieve this with original size bitmap, please suggest me.

**Comment by AboulEinein** [comment]
@pawaom did you manage to achieve this?

I've created a wrapper view for the GraphicOverlay and added a background image to it and I want to set the background pixels to transparent instead of the purple so that the background image is visible
