### ISSUE TITLE
[Issue] MLKIT Text Tecognition Empty on iOS

### ISSUE THREAD

**Issue by digitalbore** [googlesamples/mlkit#440]
I am using [react-native](https://reactnative.dev/), [react-native-vision-camera](https://mrousavy.com/react-native-vision-camera) (with frameProcessor) and [mlkit](https://developers.google.com/ml-kit/vision/text-recognition) to perform in device text recognition.

My code works on Android, but I got always empty results on iOS.

Here is my Objective C implementation:

```
static inline id scanOCR(Frame* frame, NSArray* args) {
  MLKTextRecognizer *textRecognizer = [MLKTextRecognizer textRecognizer];
  MLKVisionImage *image = [[MLKVisionImage alloc] initWithBuffer:frame.buffer];
  image.orientation = frame.orientation;
  
  NSError *error;
  MLKText *result = [textRecognizer resultsInImage:image error:&error];
  if (error != nil || result == nil) {
    NSLog(@"%@", error); // <- This is NEVER called
  } else {
    NSLog(@"text: %@", result.text); // <- this is always empty
    NSLog(@"blocks lenght: %lu", (unsigned long)result.blocks.count); // <- this is always 0
  }
  return @{@"text": result.text};  
}
```

The project corretly compile, with no errors, but results.text is always empty, even if the camera is framing texts.

**SDK Info:**
'GoogleMLKit/TextRecognition','2.2.0'

**Smartphone:**
 - Device: iPhone 8

**Development Environment:**
XCode 13.2.1

**Comment by miworking3** [comment]
1.Does it happen to all images or specific images? Could upload one sample image that fails your iOS code?
2. Does the latest version work for you?
 'GoogleMLKit/TextRecognition','2.5.0'
3. Is this issue reproducible with ML Kit's quickstart app?

**Comment by digitalbore** [comment]
Hi @miworking3, I was able to solve the problem by updating the iOS version of my iPhone 8 from **13.6** to **15.3**.

Do you know why that could happen?

Is MLKIT compatible with older iOS versions?

**Comment by miworking3** [comment]
We tested on iPhone8/iOS 13.2, and it works fine with it.

Were you able to verify that this was reproducible with the MLKit quickstart app(Code in this repository) on iOS 13.6 before upgrading to 15.3? If so, we will need to take further look, because it is not a problem on iOS 13.2 here with this quickstart app.

**Comment by sumi-svmx** [comment]
@digitalbore were you able to solve this issue for ios versions below 15.4.1?

@miworking3 the issue seems to exist with using a camera & text recognition plugin. The result from text recognition always returns empty. I upgraded the mlkit/textrecognition to `3.0.0` and it seems to work, but only if the preset is set to `"vga-640x480"`, which is a pretty low quality.

Reference:
https://github.com/aarongrider/vision-camera-ocr/tree/main/example

**Comment by miworking3** [comment]
(1) Does it work with `3.0.0` with OS version below 15.4.1>
(2) What does `text recognition plugin` mean?
(3) I'm afraid we don't debug on customer's app, we only investigate when it can be reproduced on the quickstart app(some modification is acceptable),

**Comment by sumi-svmx** [comment]
@miworking3 

(1) Works with 3.0.0 when the preset on the camera is set to `vga-640x480`, which is quite a low quality on the camera, and many texts get recognized wrong
(2) It's a library that internally uses `MLKit/TextRecognition` that we incorporate into the project. Follows the same code as given in https://developers.google.com/ml-kit/vision/text-recognition/ios
(3) Ok, no worries. But did notice a significant CPU usage going to 216% on using camera mode with the text recognition example project
https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/textrecognition. Is this expected?

Using iOS v14.6

https://user-images.githubusercontent.com/71371219/174534897-cfd53587-e2ac-4d8e-9910-f40f699b1962.mov

**Comment by IvanByRool** [comment]
> @miworking3
> 
> (1) Works with 3.0.0 when the preset on the camera is set to `vga-640x480`, which is quite a low quality on the camera, and many texts get recognized wrong (2) It's a library that internally uses `MLKit/TextRecognition` that we incorporate into the project. Follows the same code as given in https://developers.google.com/ml-kit/vision/text-recognition/ios (3) Ok, no worries. But did notice a significant CPU usage going to 216% on using camera mode with the text recognition example project https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/textrecognition. Is this expected?
> 
> Using iOS v14.6
> 
>  Screen.Recording.2022-06-20.at.11.29.02.AM.mov

Hey, 

did you find a way to go beyond 640x480 for iOS with ML Kit ? 

Thanks
Ivan
