### ISSUE TITLE
Show error message if Face not detected in Selfie Segmentation

### ISSUE THREAD

**Issue by pawaom** [googlesamples/mlkit#441]
**What's your feature request? Please describe.**
Show error message if Face not detected in Selfie Segmentation

**Mobile environment**
Android 

**Additional context**
 We are currently experimenting with MLKIt selfie Segmentation, Is there any way to detect if face is visible , if not then show an error message, We have looked at the `public interface Segmenter extends Detector<SegmentationMask>` In the `Detector` class  we have 
`@KeepForSdk
    int TYPE_FACE_DETECTION = 2;`  

How can we use this to get the desired effect.

**Comment by steven-chengji-yan** [comment]
Hi pawaom,

Based on the current available ML Kit APIs, you could use [Face Detection](https://developers.google.com/ml-kit/vision/face-detection) first to detect whether there is a face and throw error if there is none as you expected.  

BTW, where did you see the TYPE_FACE_DETECTION? It is some unrelated internal stuff that we didn't expect developers to rely on.  We don't show it in the [dev doc](https://developers.google.com/android/reference/com/google/mlkit/vision/segmentation/Segmenter).  Did you see it in Android Studio?

**Comment by pawaom** [comment]
yes in Adnroid studio , The code that we use is 

```

 private Segmenter segmenter;

 SelfieSegmenterOptions options =
                new SelfieSegmenterOptions.Builder()
                        .setDetectorMode(SelfieSegmenterOptions.SINGLE_IMAGE_MODE)
                        .build();
        segmenter = Segmentation.getClient(options);
```

When you click on the Segmenter  class it opens the 

```
package com.google.mlkit.vision.segmentation;

import androidx.annotation.NonNull;
import androidx.annotation.RecentlyNonNull;
import androidx.lifecycle.OnLifecycleEvent;
import androidx.lifecycle.Lifecycle.Event;
import com.google.android.gms.tasks.Task;
import com.google.android.odml.image.MlImage;
import com.google.mlkit.vision.common.Detector;
import com.google.mlkit.vision.common.InputImage;

public interface Segmenter extends Detector<SegmentationMask> {
    @NonNull
    Task<SegmentationMask> process(@RecentlyNonNull MlImage var1);

    @NonNull
    Task<SegmentationMask> process(@RecentlyNonNull InputImage var1);

    @OnLifecycleEvent(Event.ON_DESTROY)
    void close();
}
```

then you click on the Detector class , here you can find Type Face Detection


```
package com.google.mlkit.vision.common;

import androidx.annotation.NonNull;
import androidx.annotation.RecentlyNonNull;
import androidx.lifecycle.LifecycleObserver;
import com.google.android.gms.common.annotation.KeepForSdk;
import com.google.android.gms.tasks.Task;
import java.io.Closeable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public interface Detector<DetectionResultT> extends Closeable, LifecycleObserver {
    @KeepForSdk
    int TYPE_BARCODE_SCANNING = 1;
    @KeepForSdk
    int TYPE_FACE_DETECTION = 2;
    @KeepForSdk
    int TYPE_IMAGE_LABELING = 3;
    @KeepForSdk
    int TYPE_TEXT_RECOGNITION = 4;
    @KeepForSdk
    int TYPE_OBJECT_DETECTION = 5;
    @KeepForSdk
    int TYPE_POSE_DETECTION = 6;
    @KeepForSdk
    int TYPE_SEGMENTATION = 7;

    @KeepForSdk
    @Detector.DetectorType
    int getDetectorType();

    @KeepForSdk
    @NonNull
    Task<DetectionResultT> process(@RecentlyNonNull InputImage var1);

    @Retention(RetentionPolicy.CLASS)
    @KeepForSdk
    public @interface DetectorType {
    }
}
```

**Comment by steven-chengji-yan** [comment]
I see. It is for annotating the type of the Detector, while Detector is a generic interface.  But anyway, it is some internal stuff, and you don't need to pay attention to them.

Let us know if the Face Detection API fits your use case.

**Comment by pawaom** [comment]
**Face detection should be an integral part of Selfie detection(assuming its a person who is taking their selfie ), no point in using two different features of ML kit again and again,**
Developers should have an option to detect a face and continue or even if face is not detected even then they can continue

**Comment by steven-chengji-yan** [comment]
My suggestion for using Face Detection is just trying to unblock you as soon as possible based on what ML Kit currently offers.  Did you try that? Other than feeling it is not right, are there other requirements that solution won't meet for your case, e.g. performance?

Also, thanks for sharing your idea about the SDK. However, from our side, we will need more time to evaluate that. For example, to do that, we may need to bring in an extra face detection model to the Selfie SDK and other developers may not want to pay the extra size cost if they don't need that ability for detecting face.... There are likely other issues we need to consider if going into details.  But anyway, thanks for the suggestion.

**Comment by steven-chengji-yan** [comment]
This just remind me one thing that the Camera2 API provides some information of Face. https://developer.android.com/reference/android/hardware/camera2/params/Face#inherited-methods

I never tried to use it by myself, but maybe you could do some research in this direction to see if you can find any examples.

**Comment by pawaom** [comment]
your suggestion for camera2 api is interesting I will look into it later on, my problem is exactly the one you might consider  `bring in an extra face detection model   may increase the  size  ` more over its an additional delay for users , when we first check if face is detected then go for further processing , more over mostly selfies are by persons themselves, so it seems logical to have a build in functionality may be from your side as you guys can manage the size and delay aspect better.

**Comment by steven-chengji-yan** [comment]
Thanks for the feedback.

As for "extra size", if your targeted users are users with Google Play Service, you could consider using the unbundled [Face SDK](https://developers.google.com/ml-kit/vision/face-detection/android) `com.google.android.gms:play-services-mlkit-face-detection` which is roughly 800kB.

In ML Kit layer, we cannot simply mix that unbundled Face SDK with Selfie since the current Selfie SDK is a bundled SDK which doesn't require Google Play Service.

**Comment by steven-chengji-yan** [comment]
Hi pawaom, would you mind sharing what path you eventually took? Other people may have similar use cases.

**Comment by pawaom** [comment]
I am using Mlkit to for the image to detect face 

https://developers.google.com/ml-kit/vision/face-detection

It has increased the app size but there is no option.

**Comment by steven-chengji-yan** [comment]
Thanks for sharing.

BTW, if your users have access to Google Play Services, the unbundled version of Face SDK([com.google.android.gms:play-services-mlkit-face-detection](https://developers.google.com/ml-kit/vision/face-detection/android#before-you-begin)) would be much smaller than the bundled version.
