### ISSUE TITLE
Pose Detection multiple people

### ISSUE THREAD

**Issue by liuyunlong-pro** [googlesamples/mlkit#442]
Can you give some advice on how to achieve multi-person identification?

**Comment by steven-chengji-yan** [comment]
Unfortunately, the current models used in ML Kit don't support multi-person detection and we don't have any plan to do so at the moment.

Just share two ideas as brainstorming:
1. Run pose detection on the image, identify one person, then edit the image in memory to add a mask to cover the first person, and run the pose detection again with the edited image.  Keep going until no new person is detected.   However, this is probably a complicated flow and will be slow.
2. Is it possible to add some UI guidance to guide your user to use your app with single person?

**Comment by ai-plays** [comment]
Hi @droplet-js , 

We still don't have plan to support multi-person at the moment. There some extra complexities when it comes to multi-person, e.g. collecting training data with multiple persons and deal with people overlapping (e.g. telling which arm is whose). 

Our solution is based on MediaPipe (https://github.com/google/mediapipe). We already talked with them internally, but you may also post your request in their github repo to get more attention.

To learn a bit more about your use case, how many persons do you expect to detect at the same time? Will they overlap with each other?
