### ISSUE TITLE
[Bug report] a native crash

### ISSUE THREAD

**Issue by dunzhixuan** [googlesamples/mlkit#443]
**Describe the bug**
1
#00 pc 0002dc62 /apex/com.android.runtime/lib/bionic/libc.so (abort+165) [armeabi-v8::21ece86427ccb892a7d044a6b4b4babb]
2
#01 pc 002ae651 /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+1684) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
3
#02 pc 000024f5 /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+412) [armeabi-v8::1932351b1042feef77cc84866d53b23b]
4
#03 pc 001bd1b9 /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1212) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
5
#04 pc 001bd355 /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+64) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
6
#05 pc 001b2add /apex/com.android.runtime/lib/libart.so (art::gc::VerifyReferenceVisitor::VerifyReference(art::mirror::Object*, art::mirror::Object*, art::MemberOffset) const+1844) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
7
#06 pc 001b6e31 /apex/com.android.runtime/lib/libart.so (art::gc::ReferenceProcessor::StopPreservingReferences(art::Thread*)+8) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
8
#07 pc 001b6747 /apex/com.android.runtime/lib/libart.so (void art::gc::accounting::SpaceBitmap<8u>::VisitMarkedRange<art::gc::VerifyObjectVisitor&>(unsigned int, unsigned int, art::gc::VerifyObjectVisitor&&&) const+314) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
9
#08 pc 001a6eb3 /apex/com.android.runtime/lib/libart.so (art::gc::Heap::WaitForGcToComplete(art::gc::GcCause, art::Thread*)+370) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
10
#09 pc 0020e1cf /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoIPutQuick<(art::Primitive::Type)3, false>(art::ShadowFrame const&, art::Instruction const*, unsigned short)+298) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
11
#10 pc 001b01af /apex/com.android.runtime/lib/libart.so (art::gc::Heap::RevokeRosAllocThreadLocalBuffers(art::Thread*)+54) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
12
#11 pc 00139eaf /data/app/com.***-2kZ-b1vryo2UUEjsI9oRFQ==/base.apk (Java_com_google_mlkit_vision_mediapipe_utils_ImageConvertNativeUtils_yuvPlanesToRgb+22)
13
#12 pc 0000d519 /apex/com.android.runtime/lib/libart.so [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
14
#13 pc 00008bc5 /apex/com.android.runtime/lib/libart.so [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
15
#14 pc 00366f01 /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+248) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
16
#15 pc 00010fff /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+198) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
17
#16 pc 00144779 /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
18
#17 pc 00140d81 /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+552) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
19
#18 pc 0014af3f /apex/com.android.runtime/lib/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+9694) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
20
#19 pc 0000e075 /apex/com.android.runtime/lib/libart.so [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
21
#20 pc 0011fadb /apex/com.android.runtime/lib/libart.so (art::ClassTable::UpdateClass(char const*, art::mirror::Class*, unsigned int)+442) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
22
#21 pc 001242e3 /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+154) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
23
#22 pc 00140077 /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+690) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
24
#23 pc 0014bcbb /apex/com.android.runtime/lib/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+13146) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
25
#24 pc 0000e075 /apex/com.android.runtime/lib/libart.so [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
26
#25 pc 0011fadb /apex/com.android.runtime/lib/libart.so (art::ClassTable::UpdateClass(char const*, art::mirror::Class*, unsigned int)+442) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
27
#26 pc 001242e3 /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+154) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
28
#27 pc 00140077 /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+690) [armeabi-v8::6bd5c62acab4b7a1cef980041f94d7db]
29
java:
30
com.google.mlkit.vision.mediapipe.utils.ImageConvertNativeUtils.getRgbBuffer(com.google.mlkit:mediapipe-internal@@17.0.0-beta4:10)
31
com.google.mlkit.vision.pose.internal.zzd.zzc(com.google.mlkit:pose-detection-common@@17.1.0-beta5:2)
32
com.google.mlkit.vision.pose.internal.zzd.run(com.google.mlkit:pose-detection-common@@17.1.0-beta5:1)
33
com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@16.6.0:2)
34
com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
35
com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.4.0:8)
36
com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
37
com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.4.0:2)
38
com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.4.0:4)
39
com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.4.0:1)
40
com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
41
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
42
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
43
com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.4.0:2)
44
com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
45
java.lang.Thread.run(Thread.java:919)

mlkit version：
com.google.mlkit:pose-detection:17.0.1-beta6

**Comment by steven-chengji-yan** [comment]
Thanks for reporting.

Did you try the latest 18.0.0-beta1 version? Do you see the same crash with the latest version?

Did you get this issue from your own app or while using the ML Kit quickstart app? If from your own app, could you first help verify if the ML Kit quickstart app works fine on your device? If so, you could take a closer look to check the difference. 

If it happens on ML Kit quickstart app as well, could you provide the detailed Steps to reproduce the issue?
