### ISSUE TITLE
[Feature request] customized entity extraction, and intent mining/slot filling

### ISSUE THREAD

**Issue by cjwang666** [googlesamples/mlkit#446]
There are 2 features I want.

1. Currently "Entity Extraction" feature is not strong enough and hard to cover all of user request.
I wish NER can support user self defined customized logics.
for example, I tested Chinese time entity, found it can't support hinese holiday, and  chinese "last week" "next month", etc.

2. intent mining and slot filling
Is possible to add on-device intent mining and slot filling feature to ML Kit?
and also provide extention to allow user customized model.

I am very interested in google ML kit and want to use ML kit as on-device extensible NLU framework, not a fixed turn-key solution.

**Comment by jackqdyulei** [comment]
Thanks for your report. We don't have bandwidth to do it in near future however we will definitely consider your requests.
