### ISSUE TITLE
[Bug report] UnsafeIntentLaunchViolation with BarcodeScanning.getClient()

### ISSUE THREAD

**Issue by perracolabs** [googlesamples/mlkit#447]
**Describe the bug**
In Android 12 an **UnsafeIntentLaunchViolation** is raised by **StrictMode** when calling the next line:

```
BarcodeScanning.getClient()
```

**To Reproduce**
1. Test in a device with Android 12.
2. Configure Strict Mode with **detectAll**
3. Call **BarcodeScanning.getClient()**

StrictMode will throw the next issue:

`
    android.os.strictmode.UnsafeIntentLaunchViolation: Launch of unsafe intent: Intent { 
    act=com.google.android.gms.common.telemetry.service.START pkg=com.google.android.gms 
    cmp=com.google.android.gms/.chimera.PersistentApiService }
`

**Expected behavior**
To conform the required rules for Strict Mode in Android 12.

**SDK Info:**
com.google.mlkit:barcode-scanning:17.0.2

**Smartphone:**
 - Device/Simulator: Redmi Note 10 Pro
 - Device/Simulator OS: Android 12 / API 31 (Stock MIUI 13.0.3)

**Comment by jackqdyulei** [comment]
Hi perracolabs, we fixed this issue internally and will release new SDK in future. However if you want to resolve it earlier, please add following dependency in your `build.gradle`. Thanks!

```
implementation "com.google.android.gms:play-services-basement:18.0.1"
```
