### ISSUE TITLE
[Bug report] Ink identification time set length problem

### ISSUE THREAD

**Issue by AiFocus** [googlesamples/mlkit#453]
API call: Android ink recognition

As shown in the Demo, there is a delay of one second for sending messages through the Handler. If the recognition time exceeds one second, data will be lost. If the delay duration is too long, the experience is not good. The API also does not provide a callback to the result of successful ink identification. Please help to see how to fix the problem.

1. It is recommended to add the identification result callback.

**SDK Info:**
     implementation 'com.google.mlkit:digital-ink-recognition:17.0.1'

recognitionTask =
                  new RecognitionTask(modelManager.getRecognizer(), inkBuilder.build());
              uiHandler.sendMessageDelayed(
                  uiHandler.obtainMessage(TIMEOUT_TRIGGER), CONVERSION_TIMEOUT_MS);//Note: here is the logic that is problematic if not within a second

**Comment by steven-chengji-yan** [comment]
Hi AirFocus, 

As for the callback, can you take a look at the comment in #452 to see if it helps.

As for the timeout, this is just an app for demo purpose. After playing with it and reading the code, feel free to update the setup to fit your specific use cases.

**Comment by steven-chengji-yan** [comment]
Close due to no response. Feel free to re-open if you are still working on this.
