### ISSUE TITLE
Where is the pose detection model? 

### ISSUE THREAD

**Issue by blackCmd** [googlesamples/mlkit#455]
I opened an Android sample app.(https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart)

But there is no modmodel related to pose detection in the assets directory.

Where is the pose detectionel related to pose detection in the assets directory.

Where is the pose detection model?

**Comment by steven-chengji-yan** [comment]
The model is in the SDK('com.google.mlkit:pose-detection:18.0.0-beta2') instead of in the sample app.

We only open-source the sample app, but not the SDK.

**Comment by blackCmd** [comment]
> The model is in the SDK('com.google.mlkit:pose-detection:18.0.0-beta2') instead of in the sample app.
> 
> We only open-source the sample app, but not the SDK.

@steven-chengji-yan
Thanks for reply.
Then Can I ask the model's name?
Is it BlazePose?

**Comment by steven-chengji-yan** [comment]
No problem.

Yes, it is one version of BlazePose.

**Comment by blackCmd** [comment]
> No problem.
> 
> Yes, it is one version of BlazePose.

Thank you : )
I hope to support customization of the model and detect multiple poses in the future.

**Comment by steven-chengji-yan** [comment]
For multi-person pose detection, once BlazePose support it, ML Kit will evaluate and consider to integrate.

As for customization, could you elaborate a bit more about what custom behavior you are looking for? Only detect certain poses while ignoring other poses?

There are two models in the Pose pipeline at the moment ([some context](https://developers.googleblog.com/2020/08/introducing-ml-kit-pose-detection.html)): the first model detect where the person is, the second model detect the body landmarks.  Which step do you want to customize?   Also, what's your plan for getting the customized models? Are there any existing tools for training customized pose detection models you are thinking about?
