### ISSUE TITLE
Not compatible with the model of Tensorflow hub.

### ISSUE THREAD

**Issue by blackCmd** [googlesamples/mlkit#458]
I'm using `mlkit` android sample code on android device.

I've downloaded pre-trained tflite model from tensorflow hub and I've changed custom model to `efficientdet.tflite `(https://tfhub.dev/tensorflow/efficientdet/lite0/detection/1).

But I got an error like below.
![image](https://user-images.githubusercontent.com/13531174/157173546-5d614ab8-6b55-4aea-a908-46783793670e.png)

The `mlkit` guide said like below.

![image](https://user-images.githubusercontent.com/13531174/157172645-02751200-d305-4623-8795-1cd22e9c65b0.png)

How can I solve this error?

**Comment by steven-chengji-yan** [comment]
Hi blackCmd,

If you look at [the section below your screenshot](https://developers.google.com/ml-kit/custom-models#use_a_pre-trained_image_classification_model), it explains this more in details.  ML Kit is compatible with a ["selection"](https://tfhub.dev/ml-kit/collections/image-classification/1) of the TFHub models (not all of them).

On that same page, there are also some documentation about [what exact is required for a TFLite model to be used with ML Kit](https://developers.google.com/ml-kit/custom-models#model-compatibility). If you have models from other sources, those will be the actual detailed requirements.

**Comment by zhouyiself** [comment]
Please reopen if the above comment didn't answer your question.
