### ISSUE TITLE
[Bug report] Unable to detect QR code

### ISSUE THREAD

**Issue by pasca** [googlesamples/mlkit#459]
**Describe the bug**
We have an app that use ml-kit to scan QR code.
There is issue when scan printed QR code they are not detected. But we are able to scan the original QR code image.
Just comparing with iOS with it's built-in camera feature, they are able to scan the printed QR code

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
Go to 'Run the MLKit quickstart written in kotlin'
Click on 'LivePreviewActivity or CameraXLivePreviewActivity'
Select 'Barcode scanning' from the options
Scan printed QR code [here](https://imgur.com/a/NFjhjhP).
Observe, the QR code is not detected.

Click setting icon
Select 'rear camera preview size' from the options
Set to the highest size
Scan printed QR code [here](https://imgur.com/a/NFjhjhP).
Observe, the QR code is not detected.

Original QR code [here](https://imgur.com/a/7JxXhDo). download and use image preview to scan

**Expected behavior**
The scanned QR code should be detected

**SDK Info:**
 - SDK Name & Version [com.google.mlkit:barcode-scanning:17.0.2]

**Smartphone:**
 - Device: Galaxy A80, Android 11

**Comment by zhouyiself** [comment]
ML Kit barcode detector currently requires a barcode margin, here's a similar issue https://stackoverflow.com/questions/71278102/google-ml-kit-barcode-scanner-does-not-scan-qr-code-with-green-background

**Comment by pasca** [comment]
hey thanks for the reply
i close this issue as now they have changed the printed QR code with plain white background, it works well now
