### ISSUE TITLE
How to merge the mask (segmenter) and camera preview in one byte array for Android?

### ISSUE THREAD

**Issue by gab07** [googlesamples/mlkit#460]
Currently what I'm doing is to convert a Frame Layout (container for Camera preview and Graphic overlay) to bitmap and then saving the pixels of the bitmap on a byte array. I'm having some issue with SurfaceView though. 

There is a better way to do this?

**Comment by hemant-novotrax** [comment]
> Currently what I'm doing is to convert a Frame Layout (container for Camera preview and Graphic overlay) to bitmap and then saving the pixels of the bitmap on a byte array. I'm having some issue with SurfaceView though.
> 
> There is a better way to do this?

**I also want this thing .please let me know if you find .**

**Comment by steven-chengji-yan** [comment]
What format of input image are you using? Could you iterate through the pixels of the input image and apply the Segmentation result accordingly, then save the edited image?

With this, you work with the image data and detector result directly without touching the UI views.

**Comment by hemant-novotrax** [comment]
> What format of input image are you using? Could you iterate through the pixels of the input image and apply the Segmentation result accordingly, then save the edited image?
> 
> With this, you work with the image data and detector result directly without touching the UI views.

Hello @steven-chengji-yan 
I am not doing extra work in this mlkit sdk , I want single byte array (merge of mask and camera preview) for streaming.

**Comment by gab07** [comment]
@steven-chengji-yan thanks for the response! At the end, I think this issue doesn't belong here. This issue was raised by me not knowing how android graphics works. 

After playing with the vision samples, really good samples btw, I was able to do what I needed. 

@hemant-novotrax my task was to add filters to a video stream. If you have to do something like this, you have to do it by yourself because it's out of the scope of this kit. There are different [approaches](https://medium.com/bobble-engineering/faster-image-processing-in-android-d97eff659b7c). You could start modifying pixels on a bitmap and see if that performant enough for your needs.

You can get the camera input bitmap from here: 

https://github.com/googlesamples/mlkit/blob/4be2fe856e0b3fd95af370fe5413a33494698067/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/VisionProcessorBase.java#L173-L176

Then modify this interface and pass the bitmap: 
https://github.com/googlesamples/mlkit/blob/4be2fe856e0b3fd95af370fe5413a33494698067/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/VisionProcessorBase.java#L392

Then instead of adding an overlay here:

https://github.com/googlesamples/mlkit/blob/4be2fe856e0b3fd95af370fe5413a33494698067/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/segmenter/SegmenterProcessor.java#L62-L66

You can create a canvas with a bitmap a draw the layers there. For example:

https://github.com/googlesamples/mlkit/blob/4be2fe856e0b3fd95af370fe5413a33494698067/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/segmenter/SegmentationGraphic.java#L74-L89

This gives you a bitmap with the shape of the person. You could crop the person from the original bitmap using [this](https://medium.com/@Tarek360/crop-a-shape-from-an-android-bitmap-9690b7432774). With that cropped bitmap you can [Blur](https://github.com/android/renderscript-intrinsics-replacement-toolkit) the person and then in another canvas you can draw the original bitmap and on top of it, the bitmap with the blurred person.

You can get the pixels from the output bitmap (the bitmap used in the canvas) using [Bitmap.getPixels](https://developer.android.com/reference/android/graphics/Bitmap#getPixels(int[],%20int,%20int,%20int,%20int,%20int,%20int))

Hope this helps you!
