### ISSUE TITLE
[Bug report] android  com.google.mlkit:pose-detection-common@@18.0.0-beta1   app crashed

### ISSUE THREAD

**Issue by dblr4287** [googlesamples/mlkit#463]
libxeno_native.so  crash  use pose

com.google.mlkit:pose-detection-common@@18.0.0-beta1

 XiaoMi/MIUI   M2007J17C

log:

#00 pc 0000000000089acc /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) [arm64-v8a::a790cdbd8e44ea8a90802da343cb82ce]

#01 pc 0000000000749f9c /data/app/~~xRqS56lcEr8eXxh29qrfwQ==/taole.com.quokka-Y9rKa3CrGUaInfDQTcBfHA==/lib/arm64/libxeno_native.so (_ZN4absl20raw_logging_internal6RawLogENS_11LogSeverityEPKciS3_z+468) [arm64-v8a::21346b587a8d80e42b8e2bd10b5a0947]

#02 pc 000000000072a218 /data/app/~~xRqS56lcEr8eXxh29qrfwQ==/taole.com.quokka-Y9rKa3CrGUaInfDQTcBfHA==/lib/arm64/libxeno_native.so (_ZN9PerThread10ModuleInit4InitEv+116) [arm64-v8a::21346b587a8d80e42b8e2bd10b5a0947]

#03 pc 000000000004a0f0 /apex/com.android.runtime/bin/linker64 (__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_mbS5_+284) [arm64-v8a::2ff23f1773b306fe3db0f74d8e549264]

#04 pc 000000000004a2f0 /apex/com.android.runtime/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+380) [arm64-v8a::2ff23f1773b306fe3db0f74d8e549264]

#05 pc 0000000000035a4c /apex/com.android.runtime/bin/linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv+2088) [arm64-v8a::2ff23f1773b306fe3db0f74d8e549264]

#06 pc 00000000000310e8 /apex/com.android.runtime/bin/linker64 (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv+80) [arm64-v8a::2ff23f1773b306fe3db0f74d8e549264]

#07 pc 00000000000010b8 /apex/com.android.runtime/lib64/bionic/libdl.so (android_dlopen_ext+12) [arm64-v8a::0ef8b9fd3ba84892809321b735317a50]

#08 pc 000000000001acf0 /apex/com.android.art/lib64/libnativeloader.so [arm64-v8a::d0566dc984bbad4a2afb408a91a40500]

#09 pc 000000000000e748 /apex/com.android.art/lib64/libnativeloader.so (OpenNativeLibraryInNamespace+64) [arm64-v8a::d0566dc984bbad4a2afb408a91a40500]

#10 pc 000000000000e2c8 /apex/com.android.art/lib64/libnativeloader.so (OpenNativeLibrary+132) [arm64-v8a::d0566dc984bbad4a2afb408a91a40500]

#11 pc 000000000038ab6c /apex/com.android.art/lib64/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP7_jclassPS9_+2376) [arm64-v8a::b05be72526974ba3e6f6aba0175f2af8]

#12 pc 000000000000516c /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+416) [arm64-v8a::02c1f85509448a6eece355c5d0c52125]

#13 pc 0000000000080a24 /apex/com.android.art/javalib/arm64/boot.oat [arm64-v8a::81099975b8c7bb4ab40fb39a7086a166]

java:

java.lang.Runtime.nativeLoad(Runtime.java:1131)

java.lang.Runtime.loadLibrary0(Runtime.java:1085)

java.lang.Runtime.loadLibrary0(Runtime.java:1008)

java.lang.System.loadLibrary(System.java:1664)

com.google.mlkit.vision.mediapipe.zzg.<clinit>(com.google.mlkit:mediapipe-internal@@17.0.0-beta6:3)

com.google.mlkit.vision.mediapipe.MediaPipeGraphRunner.load(com.google.mlkit:mediapipe-internal@@17.0.0-beta6:3)

com.google.mlkit.vision.pose.internal.zzd.load(com.google.mlkit:pose-detection-common@@18.0.0-beta1:31)

com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.0.0:4)

com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)

com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.0.0:2)

java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)

java.util.concurrent.FutureTask.run(FutureTask.java:266)

java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

java.lang.Thread.run(Thread.java:923)

**Comment by steven-chengji-yan** [comment]
Hi dblr4287,

What is your gradle dependency? pose-detection-common is an internal SDK and not expected to be depended directly. Instead, developer should use pose-detection or pose-detection-accurate.

The latest version is 18.0.0-beta2. Could you give it a try to see if you still get the issue?

Do you only get the issue on this specific device but work fine on others? 

What is the Android API level?

**Comment by steven-chengji-yan** [comment]
Close due to no response. Feel free to re-open if you are still working on this.
