### ISSUE TITLE
Error: The apk for your currently selected variant cannot be signed. Please specify a signing configuration for this variant (release).

### ISSUE THREAD

**Issue by dmoffett** [googlesamples/mlkit#467]
**Describe the bug**
Checked out source and getting this error from studio.  

Error: The apk for your currently selected variant cannot be signed. Please specify a signing configuration for this variant (release).

**To Reproduce**
1. Clone source open in Android studio Bumble Bee 2021.1.1 Patch 2.
2. Try to run app.  :-(

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
Should compile without a lot of headache and stackoverflow search.  

**SDK Info:**

Android sdk 31
minSdkVersion 28
targetSdkVersion 31

**Smartphone:**
 Pixel 5.

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by zhouyiself** [comment]
Thanks for the feedback!

We have fixed this internally and will sync out with other sample changes in the next release. In case you're interested at, the fix is referred from https://b.corp.google.com/issues/36988145#comment59

**Comment by dmoffett** [comment]
I can't access this link.  Seems like an internal link?  Anyway, not sure why a prominent company like Google would publish things that don't compile.  Kind of sad.  ;-). 

https://b.corp.google.com/issues/36988145#comment59

Left hanging,
David

**Comment by zhouyiself** [comment]
Try this link https://issuetracker.google.com/issues/36988145#comment59

The sample code is actually compilable but just IDE didn't pick up the default DEBUG variant somehow. Instead it chose "release" variant to build which requires a sign config.
