### ISSUE TITLE
[Bug report] pose-detection 18.0.0-beta2 only support compileSdk 31

### ISSUE THREAD

**Issue by dunzhixuan** [googlesamples/mlkit#470]
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.work:work-multiprocess:2.7.0.

why pose-detection must use work manager

How do I work with older versions？

thanks

**Comment by dunzhixuan** [comment]
compileSdkVersion 31 need java 11.
i can't update to java sdk 11 because my Jenkies packer can't update to java 11（there are many project in Jenkies packer）

**Comment by steven-chengji-yan** [comment]
In this case, the easiest way to unblock you at the moment would be for you to use pose-detection 18.0.0-beta1 - the previous version, which doesn't depend on work manager for performance optimization.
