### ISSUE TITLE
[Bug report]A warning for ios when i build the project

### ISSUE THREAD

**Issue by PiBigStar5712** [googlesamples/mlkit#471]
**Describe the bug**
When I build the project downloaded from GitHub it says "No such module 'MLImage' ".
But I didn't find the corresponding dependency library file on GitHub.
Whether this problem can be solved according to the deployment tutorial given by the mediapipe official website.

**Smartphone:**

 - Device/Simulator: iPhoneXR
 - Device/Simulator OS: iOS15.0.1

**Development Environment:**

- IDE Eversion: Xcode 13.2.0, Xcode 13.3.0
- Laptop/Desktop: Mac mini (M1 2020)
- Laptop/Desktop OS/version: macOS 12.0.1

**Comment by bcdj** [comment]
Thanks for the report! There are multiple projects in the github. Which particular one are you building? Could you provide a link to that project?

**Comment by PiBigStar5712** [comment]
> 
Here's a link to that project I'm talking about
[https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision](url)

**Comment by bcdj** [comment]
Are you building the VisionExample app or VisionExampleObjC app? Could you share a screenshot of the build warning?

**Comment by bcdj** [comment]
ML Kit does not yet support M1-based macs. Do you have a non-M1-based mac? If so, do you see the same warning there?

**Comment by PiBigStar5712** [comment]
> ML Kit 尚不支持基于 M1 的 Mac。您有非基于 M1 的 Mac 吗？如果是这样，您是否在那里看到相同的警告？
First of all, thank you for your kindly reply.
![warning](https://user-images.githubusercontent.com/102813129/161371535-6f6462b9-38f8-4d77-b561-9b741069ea3d.jpg)
Here is my warning screenshot. And I don't have any other MAC devices at hand. I wonder if you can help test whether it can work normally on non-M1 MAC devices.
Also, I would like to know if you have any intention to adapt the M1 MAC computer in the future.

**Comment by PiBigStar5712** [comment]
> ML Kit does not yet support M1-based macs. Do you have a non-M1-based mac? If so, do you see the same warning there?

I have solved the problem I described before by reinstalling the pod, and now the project compiles without error, but the following problem is displayed when running on my iPhone XR, how should I solve it?

This is the screenshot of the error
![warning](https://user-images.githubusercontent.com/102813129/162213245-830cd120-39c1-44a4-ac04-a0784c44c19c.jpg)

**Comment by bcdj** [comment]
The latest error seems to indicate that the Main storyboard cannot be found. Could you check in your Project Navigator under VisionExample -> VisionExample -> Supporting Files, do you see the `Main` storyboard there?

**Comment by PiBigStar5712** [comment]
> The latest error seems to indicate that the Main storyboard cannot be found. Could you check in your `Project Navigator` under `VisionExample` -> `VisionExample` -> `Supporting Files`, do you see the `Main` storyboard there?

thank you for your reply. I solved this problem.

**Comment by bcdj** [comment]
Cool!

**Comment by weders** [comment]
> > The latest error seems to indicate that the Main storyboard cannot be found. Could you check in your `Project Navigator` under `VisionExample` -> `VisionExample` -> `Supporting Files`, do you see the `Main` storyboard there?
> 
> thank you for your reply. I solved this problem.

Hi, I face the same problem. Any insight into how you solved the problem? Thank you very much!
