### ISSUE TITLE
Does Google realize monitors are wider than tall?

### ISSUE THREAD

**Issue by dmoffett** [googlesamples/mlkit#472]
**Describe the bug**
Google should realize monitors are wider than tall.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Look at any Google created code and see this:

  // For handling recognition and model downloading.
  private var recognitionTask: RecognitionTask? = null

  @JvmField
  @VisibleForTesting
  var modelManager =
    ModelManager()

2. Needless cr/lf even less that 80 chars.  Why?
3. Monitors are wider than tall.  
4. More code can be see if Google does not use up all the lines with useless cr/lf.

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

  // For handling recognition and model downloading.
  private var recognitionTask: RecognitionTask? = null

  @JvmField
  @VisibleForTesting
  var modelManager =
    ModelManager()

**Expected behavior**
Expect to see more than one word of a line of code per line.** 

**PS - April Fools.

**Comment by steven-chengji-yan** [comment]
Thanks for pointing it out.
