### ISSUE TITLE
[Bug report] PreferenceUtils getUserSpecifiedPreviewSize Size.parseSize expects String gets String?

### ISSUE THREAD

**Issue by conceptualGabrielPutnam** [googlesamples/mlkit#473]
**Describe the bug**
Clean download of MLKit samples fails compile on Bumblebee 2021.1.1 Patch 2 with Android 31 sources.

Error is in:
PreferenceUtils.kt
  getUserSpecifiedPreviewSize
     CameraSizePair
        Size.parseSize( sharedPreferences.getString( previewSizePrefKey, null ) )

because sharedPreferences.getString( previewSizePrefKey, null ) always returns String? type.
(Also, personal note, putting a question mark at the end of a type is an Awful idea, I can't even write the above sentence without adding "type" at the end.  Obviously not your personal fault)

**Works if Changed To**
var previewPrefString = sharedPreferences.getString( previewSizePrefKey, null );
var parsedPreviewSize = previewPrefString?.let { Size.parseSize(it) };
CameraSizePair(
    Size.parseSize( parsedPreviewSize.toString() ),
    sharedPreferences.getString( pictureSizePrefKey, null )?.let { Size.parseSize(it) }
)

**SDK Info:**
 - SDK Name & Version [e.g. com.google.mlkit:face-detection:16.1.3]

**Comment by jackqdyulei** [comment]
Thanks for the feedback. We will fix it shortly.

**Comment by jackqdyulei** [comment]
Fixed internally and will be available in next release.
