### ISSUE TITLE
[Feature request] Support XCFramework / Swift Package Manager

### ISSUE THREAD

**Issue by idwise-team** [googlesamples/mlkit#474]
**What's your feature request? Please describe.**
Would be amazing if you can support XCFramework format / Swift Package Manager because the only reason why we can't offer our SDK as Swift Package Manager is ML-Kit availability in this format

**Mobile environment**
iOS

**Additional context**
Swift Package Manager is gaining very rapid popularity and solves many of the compatibility issues between different versions of XCode and Swift, it allows a seamless update experience which is critical to us to maintain the best developer experience (which I am sure is your aim too!)

**Comment by bcdj** [comment]
Yes, we are working on it. Closing this as a duplicate report of [https://github.com/googlesamples/mlkit/issues/180](https://github.com/googlesamples/mlkit/issues/180).
