### ISSUE TITLE
How to degree of angle  & display on Pose detection in Swift (iOS)

### ISSUE THREAD

**Issue by vnanaware** [googlesamples/mlkit#478]
Hello,
 
        How to calculate & display the degree of angle ie 90°, 30° 180° etc. on Pose detection kit in Swift. 

Thanks & Regards,
Vishal.

**Comment by bcdj** [comment]
Hi Vishal, can you elaborate which angle are you trying to calculate?

**Comment by vnanaware** [comment]
<img width="519" alt="Screenshot 2022-04-18 at 9 45 59 AM" src="https://user-images.githubusercontent.com/16416191/163753628-deae6f05-233b-48ed-bba9-f3729ada9813.png">


I want to achieve like this is it possible?

**Comment by bcdj** [comment]
[This page](https://developers.google.com/ml-kit/vision/pose-detection) provides you the indices of different points returned by ML Kit's pose detection. Hopefully it can help you identify the key landmarks you care about and then based on that, you can use some math to calculate the desired angles.

**Comment by vnanaware** [comment]
Ok, How should I achieve the squats count?

**Comment by vnanaware** [comment]
???

**Comment by bcdj** [comment]
For that, you will need to build a pose classifier that recognizes squat poses. [This page](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses) demonstrates how to use a MediaPipe Colab to build that. It has sample code for Android only. You can use that as the example and provide similar implementation on iOS.

**Comment by vnanaware** [comment]
Ok, Shall I measure distance from live camera to front person in this?

**Comment by bcdj** [comment]
That depends on how your app plans to measure and use it.

**Comment by vnanaware** [comment]
![WhatsApp Image 2022-04-20 at 6 45 19 PM](https://user-images.githubusercontent.com/16416191/164373058-ff7c606e-9dbc-47cd-8347-7baae5486a0d.jpeg)



Every time I got same angle using below code


var rightHipAngle = angle(
                  firstLandmark: pose.landmark(ofType: .rightShoulder),
                  midLandmark: pose.landmark(ofType: .rightHip),
                  lastLandmark: pose.landmark(ofType: .rightKnee))


func angle(
          firstLandmark: PoseLandmark,
          midLandmark: PoseLandmark,
          lastLandmark: PoseLandmark
      ) -> CGFloat {
          let radians: CGFloat =
              atan2(lastLandmark.position.y - midLandmark.position.y,
                        lastLandmark.position.x - midLandmark.position.x) -
                atan2(firstLandmark.position.y - midLandmark.position.y,
                        firstLandmark.position.x - midLandmark.position.x)
          var degrees = radians * 180.0 / .pi
          degrees = abs(degrees) // Angle should never be negative
          if degrees > 180.0 {
              degrees = 360.0 - degrees // Always get the acute representation of the angle
          }
          
          let roundedValue1 = round(degrees)
          return roundedValue1
      }

**Comment by vnanaware** [comment]
??

**Comment by bcdj** [comment]
You could try out this approach. I don't see how you measure the distance from live camera to the person and how you plan to use it in your code snippet though.

**Comment by vnanaware** [comment]
No I need help regarding landmark position. how to achieve it?  please look at the image

**Comment by bcdj** [comment]
Oh, so you are looking for help on debugging the math/geometry logic in your code to calculate the angle?  Sorry, I won't be able to do that.
