### ISSUE TITLE
Using NDK's AImage or ArImage as InputImage parameter

### ISSUE THREAD

**Issue by manwithsteelnerves** [googlesamples/mlkit#481]
**What's your feature request? Please describe.**
As ARCore is completely implemented in C, fetched camera frames are of type AImage or ArImage. This makes it impossible to pass it to MLKit. Please provide a way to let MLKit access ndk classes too.

**Mobile environment**
Android

**Comment by zhouyiself** [comment]
Thanks for the request!

It's not in our radar currently but we'll definitely consider it when we seeing more similar requests.
