### ISSUE TITLE
[Bug report] Valid Datamatrix code not recognized

### ISSUE THREAD

**Issue by EvgenyParfenov** [googlesamples/mlkit#487]
Android, com.google.mlkit:barcode-scanning v.17.0.2
![PXL_20220417_124505385](https://user-images.githubusercontent.com/90598485/164430341-15b21104-fc42-4227-9aff-638846f27237.jpg)

**Comment by ananth10** [comment]
@calren  I have tried barcode scanner from material show case sample app [](https://github.com/googlesamples/mlkit/tree/master/android/material-showcase/app/src/main/java/com/google/mlkit/md/barcodedetection), The scanner is working for most of standard barcode & QR code but the scanner is not working for Data Matrix barcode like Data Matrix (GS1) format. and i have tried to scan the above 2D Data matrix format given by @EvgenyParfenov but the scanner is not detecting it. it would be very great if you suggest a solution/ workaround to make scanner to scan Data Matrix (GS1) format code. Thanks.

**Comment by justinw-SMC** [comment]
May I suggest this as a feature request, not a bug report? 
All supported barcode formats are provided [here](https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/common/Barcode.BarcodeFormat) and GS1 DataMatrix is not the same as DataMatrix as specified [here](https://www.gs1.org/standards/gs1-datamatrix-guideline/25#1-Introduction-to-GS1-DataMatrix)

Links:
https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/common/Barcode.BarcodeFormat
https://www.gs1.org/standards/gs1-datamatrix-guideline/25#1-Introduction-to-GS1-DataMatrix

**Comment by miworking3** [comment]
Yeah, it is on our radar as a feature request.

**Comment by miworking3** [comment]
I'm afraid with the shift of priority in our team, there is no plan in the near future to address this.
