### ISSUE TITLE
Access to pose classification dataset

### ISSUE THREAD

**Issue by Tengoles** [googlesamples/mlkit#490]
Hello! I'm not sure if this is the right place to be asking this but I'm working with the pose classification part of the kit and would really like help to be able to access the dataset used to train the squat/pushup detector. It would give me a nice baseline on several aspects related with having a dataset for pose classification. Thanks!

**Comment by steven-chengji-yan** [comment]
Unfortunately, we cannot share that dataset.

For building your own classifier, you could take some photos (different position, different angle) and build your own dataset. See more details here: https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses#pose_classification_and_repetition_counting_with_the_k-nn_algorithm
