### ISSUE TITLE
Vertical text not detect in image to text

### ISSUE THREAD

**Issue by bipin-sakariya** [googlesamples/mlkit#492]
In Flutter I am trying to detect text from images in horizontal orientation is working perfectly but Vertical orientation text is not detected.
I am using the google_ml_kit plugin.
Anyone has a solution for this or another way to achieve this functionality. 
Here you can check it is working with native android :- https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

**Comment by bcdj** [comment]
I assume that by `google_ml_kit` plugin, you meant [this one](https://pub.dev/packages/google_ml_kit)? If so, it's neither owned or endorsed by the Google ML Kit team. Please use [their support page](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues) to report this issue.
