### ISSUE TITLE
Pose detection, Considered palm as a Fully body.

### ISSUE THREAD

**Issue by vnanaware** [googlesamples/mlkit#495]
![IMG_6664](https://user-images.githubusercontent.com/16416191/166402488-7e17f8b1-8c3b-4bd6-aa53-05139d96c844.jpg)

If I bring only palm in front of camera then it considered as full body,  How to resolve this issue?

**Comment by vnanaware** [comment]
??

**Comment by bcdj** [comment]
ML Kit's Pose Detection feature works best when the subject's entire body is visible in the frame. It's not a hand-only detection feature.
