### ISSUE TITLE
Use ML Kit with NNAPI

### ISSUE THREAD

**Issue by padovanl** [googlesamples/mlkit#50]
I'm trying to use the new Google machine learning sdk, ML Kit, on an Android device that run Android 9. From the official site:

> ML Kit makes it easy to apply ML techniques in your apps by bringing Google's ML technologies, such as the Google Cloud Vision API, TensorFlow Lite, and the Android Neural Networks API together in a single SDK. Whether you need the power of cloud-based processing, the real-time capabilities of mobile-optimized on-device models, or the flexibility of custom TensorFlow Lite models, ML Kit makes it possible with just a few lines of code.

I think it means that on a device with at least Android 8.1 (according to the documentation of nnapi) the SDK can uses NNAPI. But when I run the same app on a device with Android 7.1 (where nnapi is not supported) I obtain the same performance of the device that use Android 9 (and in theory the NNAPI). How i can use ML Kit with NNAPI? I am doing something wrong? Link to documentation of mlkit: https://firebase.google.com/docs/ml-kit/

**Comment by swiyu** [comment]
ML Kit ODT is running with NNAPI on selected devices, and more features will use NNAPI soon. Closing this now.
