### ISSUE TITLE
pod更新报错

### ISSUE THREAD

**Issue by zgddu** [googlesamples/mlkit#505]
When I use https://dl.google.com/dl/cpdc/fed6bd4e423c597b/MLKitBarcodeScanning-2.0.0.tar.gz Address download mlkitbarcodescaning and introduce it into the project. There are many error reports that can't be solved. Please take a look!

**Comment by miworking3** [comment]
More info is needed for further investigation, can you provide more info using this template? Thanks.
https://github.com/googlesamples/mlkit/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by miworking3** [comment]
Having received reply in 4 weeks, closing it for now, please reopen it with requested info.
