### ISSUE TITLE
Unable to decode Barcode.FORMAT_CODE_39 from image

### ISSUE THREAD

**Issue by abubakar0015** [googlesamples/mlkit#506]
**Environment**
Android device: Samsung A52
Android OS version: Android 12
ML kit version: com.google.mlkit:barcode-scanning:17.0.2
**Describe the problem:**
I can't see any barcode result when trying to scan a simple image (sample image attached).
I had also tried with different images and different resolutions. 

**Steps to reproduce:**
Simply run this code with image path and required storage permissions.  
**Observed Results:**
There is no barcode appeared
**Expected Results:**
Barcode should appear with value

** Relevant Code **

   `private fun imageBarcodeScanner(path:String) {

        val options = BarcodeScannerOptions.Builder()
            .setBarcodeFormats(
                Barcode.FORMAT_CODE_39
            )
            .build()

        val image = InputImage.fromFilePath(applicationContext, Uri.parse(path))
        val scanner = BarcodeScanning.getClient(options)

        val result = scanner.process(image)
            .addOnSuccessListener { barcodes ->
                // Task completed successfully
                // ...

                Log.i(TAG, "barcodeScanner: ${barcodes.size}")
                if (barcodes.size > 0) {
                    Log.i(TAG, "barcodeScanner: displayValue: ${barcodes.get(0).displayValue}")
                    Toast.makeText(
                        this@MainActivity,
                        "${barcodes.get(0).displayValue}",
                        Toast.LENGTH_SHORT
                    ).show()
                }
                else{
                    Toast.makeText(
                            this@MainActivity,
                            "${"No BarCode Found"}",
                            Toast.LENGTH_SHORT
                    ).show()
                }
            }
            .addOnFailureListener {
                // Task failed with an exception
                // ...
            }
    }
`
![1650781465525](https://user-images.githubusercontent.com/29165141/167746950-2a6409db-3953-4aee-80d3-c8d2bb333b1e.jpeg)

**Comment by SilverDestiny** [comment]
Hi,

I just tried to scan this barcode using our vision quickstart app in streaming mode: https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

It looks like the barcode of this image is scannable but not very easy (need to adjust the screen to landscape to better scan this barcode). I feel maybe we could improve the quality of the input image and also increase the resolution to be easier to scan this kind of long barcode?

**Comment by abubakar0015** [comment]
@SilverDestiny  I already tried to scan with streaming, and it works. I also tried to scan on bitmap from camera stream and scanned with multiple frames coming from camera to see results. ML kit is not able to decode from almost more than 50% of frames, even image is scannable, but in that use case it is useable.
With single frame or image it is not providing results as expected.

**Comment by SilverDestiny** [comment]
I see. We filed a request internally and will try to improve the performance for single frame/image case.
Thanks for reporting this issue!

**Comment by SilverDestiny** [comment]
Close this issue for now.
Please re-open if it is not useable.
