### ISSUE TITLE
Is it possible to measure Pull-ups, Vertical Jump count in pose detection?

### ISSUE THREAD

**Issue by IBSApple** [googlesamples/mlkit#507]
Hello ,
          Using pose detection feature is it possible to measure count of Pull-ups or Vertical Jump, Planks etc.

Thanks.

**Comment by IBSApple** [comment]
?

**Comment by IBSApple** [comment]
?

**Comment by edi2212** [comment]
ededam9@gmail.com

**Comment by edi2212** [comment]
ededam9@gmail.com

**Comment by edi2212** [comment]
ededam9@gmail.com

**Comment by bcdj** [comment]
@IBSApple Have you check out ML Kit's documentation on [Pose Classification Options](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses)?
