### ISSUE TITLE
Digital Ink Recognition - Get bounds 

### ISSUE THREAD

**Issue by Knaackee** [googlesamples/mlkit#508]
I know that the recognizer does not return the exact bounds of the recognized word. 

Any ideas on how to implement this?

Microsofts Ink Recognition gives back the bounds of the found words.

https://github.com/WICG/handwriting-recognition/blob/main/explainer.md

Thanks!

**Comment by bcdj** [comment]
To clarify: if the input is "hello world", you want not the bounds of the entire "hello world" string (which you should already have based on the input that you provided), but rather the bounds of two words ("hello" and "world") separately, right?  If so, I don't think ML Kit's API currently supports that.
