### ISSUE TITLE
[Bug report] setBarcodeFormats does not work as intended

### ISSUE THREAD

**Issue by rohitr308** [googlesamples/mlkit#510]
**Describe the bug**
There are two issues that I am facing:

1. `setBarcodeFormats` does not work sometimes. I tried setting it to `FORMAT_UPC_A` but sometimes it returns `FORMAT_EAN_13`

```
BarcodeScannerOptions.Builder()
            .setBarcodeFormats(
                Barcode.FORMAT_UPC_A,
            )
```

2. Scanner returns garbage values when the barcode is partially blocked

**To Reproduce**
Steps can be seen in the video

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
Scanner should scan only UPCs with format `FORMAT_EAN_13` and should not return garbage values
**SDK Info:**
 - SDK Name & Version : "com.google.mlkit:barcode-scanning", version = "17.0.0"

**Smartphone:**
 - Device/Simulator: Samsung S9
 - Device/Simulator OS: Android 10

**Comment by panagiac** [comment]
Hello, I opened today this issue (#645) which seems similar to yours.
Did you solve it?
