### ISSUE TITLE
Pose detection 18.0.0-beta2 does not use GPU

### ISSUE THREAD

**Issue by ShakedDovrat** [googlesamples/mlkit#516]
Hello, 
I'm running pose detection 18.0.0-beta2 using the latest sample code (master branch, commit sha 730b9d6) on Samsung S22 Ultra (which has a GPU). Using Samsung's GPUWatch I see that the GPU usage is near zero (~0.4%), while the CPU is at ~50% when running pose detection (which shows great results!).

I found this comment stating that you are supporting GPU in this version.

Please advise, thank you

> Hi WCRohit, pose detection 18.0.0-beta2 uses GPU on applicable devices. (See my comment above for details).
> 
> Please give it a try. Looking forward to your feedback.
> 
> _Originally posted by @steven-chengji-yan in https://github.com/googlesamples/mlkit/issues/136#issuecomment-1110220304_

**Comment by ShakedDovrat** [comment]
@steven-chengji-yan maybe you can help?

**Comment by steven-chengji-yan** [comment]
Hi ShakedDovrat,

Here are more details about when GPU would be used: https://developers.google.com/ml-kit/vision/pose-detection/android#hardware_config

One thing you could try is to use the setPreferredHardwareConfigs to select CPU_GPU only. By doing this, CPU_GPU would be used even if it may be slower than CPU only (you may want to do this if you want to offload CPU for example). In such case, when you use the detector for the first time, it will still use CPU only and in parallel check whether the CPU_GPU path can run stably and correctly (the check will only be done once on each device and the result will be stored) If so, when you run the detector again after the check is finished, CPU_GPU should be used.   However, if you still don't see GPU usage, it means on that specific device, we don't think it is safe to use GPU for Pose detection.

Closing it for now. Feel free to follow up if you still have questions.

**Comment by ShakedDovrat** [comment]
Thank you @steven-chengji-yan 
Using `CPU_GPU`, the system still does not utilize the GPU. My device should be perfectly capable of running this on its GPU. Is there anyway to dig deeper and debug why it is not doing so?
Perhaps there's a closed list of devices which ML-Kit is able to utilize their GPUs?
Or maybe a description of what are the requirement for ML-Kit to decide it is "safe to use GPU for Pose detection"?

**Comment by steven-chengji-yan** [comment]
When you only set CPU_GPU as the preferred hardware, it will be used as long as running on GPU won't crash/timeout and the ML Kit Pose GPU pipeline (models + image processing) can return accurate enough results based on internal error threshold defined by ML Kit. In your case, one of the above requirement doesn't meet.

A bit more background about GPU acceleration: there are a lot of factors affecting whether GPU pipeline can run successfully on a specific device. It is quite possible for GPU pipeline A being able to run on a device while GPU pipeline B not. In your case, it is possible for your device to run some other GPU model inferences while cannot run the ML Kit Pose GPU pipeline correctly.
