### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by gentsamh** [googlesamples/mlkit#518]
When I try to run the project, the error message shows "Caused by: org.gradle.api.GradleException: File google-services.json is missing. The Google Services Plugin cannot function without it."

**Comment by zhouyiself** [comment]
Which sample project this error comes from? vision-quickstart?

**Comment by SilverDestiny** [comment]
If you were trying to run the `automl` project: https://github.com/googlesamples/mlkit/tree/master/android/automl, you need to create a Firebase project to make it work.
This is to set up your own Firebase project and remote model.

![image](https://user-images.githubusercontent.com/29959194/171303719-68c5245e-cddc-4f83-a728-456c33943876.png)

**Comment by zhouyiself** [comment]
Please reopen if the above comment can't help resolve the issue.
