### ISSUE TITLE
[Bug report] “visibility“ for pose detect

### ISSUE THREAD

**Issue by Linda0509** [googlesamples/mlkit#519]
**Describe the bug**
Is there a way to get the visibility parameter in pose detect which is defined in MediaPipe.

visibility: A value in [0.0, 1.0] indicating the likelihood of the landmark being visible (present and not occluded) in the image.

**SDK Info:**
 - pose-detection:18.0.0-beta2

**Comment by steven-chengji-yan** [comment]
Hi Linda0509, 

The MediaPipe visibility score is not supported by ML Kit at the moment. The one we support is the MediaPipe "presence" score, which we call it as inFrameLikelihood.

As for supporting "visibility", we will add it to our feature request list. However, we will need to do some testing before we can release it. Currently, cannot promise any concrete timeline.

**Comment by easytarget2000** [comment]
I would also like to express interest in accessing the MediaPipe `visibility` value from MLKit. It is currently not possible to determine if a landmark is occluded by other body parts. I'd be grateful if this topic gets picked up eventually.
