### ISSUE TITLE
I hope your face recognition library can be expanded to provide live detection and face comparison.

### ISSUE THREAD

**Issue by BraveHL** [googlesamples/mlkit#522]
**What's your feature request? Please describe.**
A clear and concise description of what the request is. Ex. I would like to have X language support in text recognition[...]

The face recognition library in Google's mlkit is really great, especially when you contribute to developers around the world for free, so that technology can benefit more people. But for developers, when they are faced with a face recognition requirement, it usually includes face recognition "live detection" face information comparison differences to determine whether it belongs to a person. Mlkit provides the first step, and the following steps for most developers. 
It is very difficult, and many people are unable to solve it at all, and in the end, they are still unable to meet this demand. At the same time, many commercial companies sell the latter two steps. Their effect is not very good, but they sell at a high price. It hinders the promotion of face recognition, so I hope your face recognition database can be expanded to provide live detection and face comparison. 
Let artificial intelligence technology benefit everyone, so that more people will master the technology related to artificial intelligence, and it will be more difficult for artificial intelligence to threaten ordinary people.

**Mobile environment**
Android, IOS or both

Android

**Additional context**

**Comment by bcdj** [comment]
ML Kit does not currently plan to support face recognition for identifying a person. We support only general detection of a face and facial landmarks.
