### ISSUE TITLE
[Bug report] MLKit on iOS ignore orientation

### ISSUE THREAD

**Issue by manwithsteelnerves** [googlesamples/mlkit#528]
**Describe the bug**
On iOS, MLKit MLKVisionImage or GMLImage ignores the orientation and returns the bounding box in wrong direction.
This is not the case with Android. Based on the rotation specified, bounding box returned on Android is always up and as expected.

**To Reproduce**
1. Use an samplebuffer/pixelbuffer with 90 degree orientation (UIImageOrientationRight)
2. Pass it to Barcode scanner
3. The detected barcode frame is 90 degree rotated instead of up direction (this is proper on Android)

```
CVPixelBufferRef pixelBufferRef = arSession.currentFrame.capturedImage; //Ignore this line (just a way to get pixelbuffer)
GMLImage* image = [[GMLImage alloc] initWithPixelBuffer: pixelBufferRef];
image.orientation = [self getARKitCameraOrientation];//The image orientation is set to 90 CW

-(UIImageOrientation) getARKitCameraOrientation
{
    UIDeviceOrientation deviceOrientation = [[UIDevice currentDevice] orientation];
    switch (deviceOrientation) {
        case UIDeviceOrientationPortrait:
            return UIImageOrientationRight;
        case UIDeviceOrientationLandscapeRight:
            return UIImageOrientationDown;
        default:
            return UIImageOrientationUp;
    }
}


//Pass the above image to barcode scanner client and call resultsInImage. In the resulting barcode, check the frame rotated instead of up direction
```

**Expected behavior**
It's inconsistent with Android. The expected bounding rect should be directed in the right direction as we are already passing orientation.

**SDK Info:**
 - pod 'GoogleMLKit/BarcodeScanning'
  ```
  - GoogleMLKit/BarcodeScanning (3.0.0):
    - GoogleMLKit/MLKitCore
    - MLKitBarcodeScanning (~> 2.0.0)
  - GoogleMLKit/MLKitCore (3.0.0):
    - MLKitCommon (~> 6.0.0)
 ```
   

**Smartphone:**
 - Device: iPhone 12
 - Device  OS: [e.g. iOS15]

**Development Environment:**
- IDE Eversion: Xcode 13.1
- Laptop/Desktop: iMac
- Laptop/Desktop OS/version: macOS 11

**Comment by miworking3** [comment]
We will need more details to reproduce this issue:

Currently the quickstart app is calculating the image orientation in the same way as the code snippet you provided:
https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExampleObjC/CameraViewController.m#L860-L862
https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExampleObjC/UIUtilities.m#L101-L126

and the orientation can be handled correctly in the stream mode:

![orientation](https://user-images.githubusercontent.com/52680648/174494094-d7b20aa5-b0ba-4d73-b2a2-0f0e9da4725a.gif)

**Comment by manwithsteelnerves** [comment]
@miworking3 Thanks for sharing the references.
In this case I see output from iOS seems to be proper (which I got mistaken) but, it leaves me in puzzled as I see android has a different output. If either of the platforms outputs are not same, this bug thread is still valid.

As you can see in below line,
https://github.com/googlesamples/mlkit/blob/2f80c301bae79136efa9096881b6e44bee7866a3/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/barcodescanner/BarcodeGraphic.java#L74
The output rect is getting rotated even when you pass the rotation value to the barcode scanner.
Can you please share your thoughts?

**Comment by manwithsteelnerves** [comment]
@miworking3 I think on iOS too, rotation is applied finally. Please check [here](https://github.com/googlesamples/mlkit/blob/730b9d6db72c9fc74e34b09d28b9314ce3b2f927/ios/quickstarts/vision/VisionExampleObjC/CameraViewController.m#L515).

Can you please explain how exactly orientation is supposed to work? Let me give an example about my expectation.

If I pass an image data and create an MLKit vision image and set orientation to 90, the input image looks like the below


![Rotated](https://user-images.githubusercontent.com/5437614/174782121-9e3c21ed-0e2d-45d9-a72c-f23ec54859da.PNG)

Once the MLKit detects the barcode (qr code here), I'm expecting the frame will be something like this (as if we passed up rotated image). So while displaying I directly use the frame values and display as if its a up direct rect.

![Rotated](https://user-images.githubusercontent.com/5437614/174782768-e203526c-7f93-41b7-8942-4e0bc53cd06d.PNG)


Please correct me if I'm expecting in the wrong way. If the above is wrong, I'm wondering what exactly is the use of passed orientation value.

**Comment by manwithsteelnerves** [comment]
Here are few more details on the issue. I tried passing an image frame with a rotation of UIImageOrientationRight. It returned {{1097, 455}, {274, 475}} frame for below image.

![IMG_8763](https://user-images.githubusercontent.com/5437614/174966401-542d4eaf-7513-4db8-ab82-ffd7a5b46b46.PNG)

In the above image, red lines is the co-ordinates returned by the ml kit on iOS. While expected is marked as green.
Unfortunately, if I pass UIImageOrientationLeft also gives the same rect coordinates. This makes it clear that its ignoring the orientation somehow. 

@miworking3 @miworking Can you please look into it?

**Comment by miworking3** [comment]
Thanks, I will take a look.

**Comment by manwithsteelnerves** [comment]
Also one more to have a note is, the frame width and height are inverted but the position(origin) seems to respect the passed orientation. Overall lot of confusion. Hope you will clear it soon.

**Comment by manwithsteelnerves** [comment]
Thanks for sharing the details. I will go through it. Here is one more test with LeftMirrored image orientation giving weird result on iOS.

When I passed the below image with image orientation as LeftMirrored, it returned me {110, 50, **100, 200**}. Where I expected the width, height to be inverted based on the passed orientation.
![IMG_8767](https://user-images.githubusercontent.com/5437614/175196295-f16defed-1e0b-4f96-9243-e2bf0bf05e65.jpg)

In the below image, red coloured marked values are wrong. The width and height are inverted even though the origin returned is as per the input orientation given. 
![IMG_8767 copy](https://user-images.githubusercontent.com/5437614/175196845-45f8f580-46ac-4077-b803-9e7db725f376.jpg)


Is it something like LeftMirrored is the issue?

**Comment by manwithsteelnerves** [comment]
Thanks for the details. Mainly [this](https://user-images.githubusercontent.com/52680648/175105139-883f994f-571e-498e-90c9-37f582523bce.png) image clarified a lot. Can you please make it explicit about this in your docs?
