### ISSUE TITLE
Barcode scanner  not scanning PDF417 barcode on south african driving license

### ISSUE THREAD

**Issue by ostwalankit** [googlesamples/mlkit#53]
### Step 1: Describe your environment

  * Android device: _Google Pixel 
  * Android OS version: 9 
  * Google Play Services version: "com.google.firebase:firebase-ml-vision:19.0.2"
  * Firebase/Play Services SDK version: _____
  
### Step 2: Describe the problem:

I am not able to scan PDF417 barcode on south african driving license (attached below) . It dosent scan anything. I am using default mlkit project of github. I have added Firebase to the project. 

Following are dependencies used.

    // ML Kit dependencies
    implementation 'com.google.firebase:firebase-ml-vision:19.0.2'
    implementation 'com.google.firebase:firebase-ml-vision-image-label-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:17.0.3'

#### Steps to reproduce:

  1. Load the project ML kit.
  2. Select Java ML Kit
  3. Select Live Preview Activity
  4. Select Barcode detection from spinner at bottom
  5. Now scan the south african driving license. 
  
#### Observed Results:

There are constant recurring logs.
2019-02-28 21:10:34.172 3508-3746/com.google.firebase.samples.apps.mlkit D/MIDemoApp:CameraSource: Process an image
2019-02-28 21:10:34.172 3508-3746/com.google.firebase.samples.apps.mlkit D/skia: onFlyCompress
  
#### Expected Results:

Scan the PDF417 barcode and show appropriate result in context to it. I scanned the same driving license via. Microblink app and it scans perfectly.
  
#### Relevant Code:

Used the mlkit code on github.

![drivers - back](https://user-images.githubusercontent.com/24475508/53578420-ac695800-3b9d-11e9-942d-f215e6e48e85.png)

**Comment by Gilboot** [comment]
Any solution here

**Comment by donaldjansen** [comment]
Has anybody found a way to scan this barcode ?
I have used 1280x720 and 1920x1080 neither worked on this barcode in the image, other PDF417 does work. but if I use the sample apps on Play Store it works

**Comment by Gilboot** [comment]
I had to switch to zxing

**Comment by blen7777** [comment]
Zxing is it working for you?

**Comment by rjmangubat23** [comment]
Did this work for anyone? I am also facing this issue, the workaround I did is adjust the zoom ratio of camera and used 1920x1080 for the size but it does not 100% work fully, especially on complex PDF417 like stated above. Should I consider using zxing? or anyone have a better solution? Thank you in advance!

**Comment by donaldjansen** [comment]
Unfortunately I have not come right, I have also not tried XZing yet. I used the normal google vision library and it worked 100% everytime on a Samsung A2 Core but not on newer devices for somereason. I am busy switching to MLKit at the moment and if that doesn't work I am going to try ZXing

**Comment by ptlkundan** [comment]
> Any update on this?? Not working for Uganda National ID as well

have u any solution for this issue ? facing same issue

**Comment by Hxsyed** [comment]
Hey there, I am trying to scan format PDF 417 as well and it always recognizes it as a TYPE_TEXT. When I scanned my own drivers license it does recognize it was a TYPE_DRIVER_LICENSE. This is weird does anyone know why?

**Comment by rsgilbert** [comment]
You have to use Zxing for barcode scanning and MLkit for everything else such as text-in-image scanning. As for Uganda national Id, Zxing can to a good accuracy (around 90%) scan the bar code of the Uganda National ID but other things like NIN etc, please use MLKit.

**Comment by jtlz2** [comment]
My company (https://www.sprinthive.com) has a commercial service for decoding of the ZA driver's licence (both the alphanumeric and image data - all versions) from the base64-encoded string.

**Comment by hendrelouw73** [comment]
I have the same issue. Both the South African driver's License and the South African ID Card do not scan.

![SouthAfrica](https://user-images.githubusercontent.com/1856547/221163290-b116c346-f60b-4d6d-8eef-598532551b0c.jpg)
.

**Comment by hendrelouw73** [comment]
I have the same problem with the South African driver's license and the ID card. See attached image.

![SouthAfrica](https://user-images.githubusercontent.com/1856547/221164097-6033950f-f341-438e-9a64-fb652de84cf7.jpg)
hed image.

**Comment by nkosingaleka** [comment]
Has anybody found a way to scan this RSA drivers license barcode ?

**Comment by donaldjansen** [comment]
Yes on Android and Windows. both the image and DL information

**Comment by Marvine89** [comment]
Apr 2024, Has anybody found a workaround for this?

**Comment by donaldjansen** [comment]
Yes, I will have to go look for my code. but I had used MLKIT to do it with the correct optimizations.
