### ISSUE TITLE
smartreply demo project doesn't return answers

### ISSUE THREAD

**Issue by agGitHub** [googlesamples/mlkit#533]
**Describe the bug**
I just downloaded and ran the smartreply demo project on my Android phone but it doesn't return any answer. Any idea ?

Thanks.

**Comment by SilverDestiny** [comment]
What input did you use? Do you have a screenshot for the input and result?

Please note that if there is no reply generated, there should be a long Toast message for the reason.

**Comment by SilverDestiny** [comment]
Close this issue as no response for 17 days.

We could reopen it if needed, thanks!
