### ISSUE TITLE
material-showcase returns 'Product title 0' 'Product title 1' etc...

### ISSUE THREAD

**Issue by agGitHub** [googlesamples/mlkit#534]
**Describe the bug**
I just downloaded and ran the demo app material-showcase. It returns a list with 'Product title 0' 'Product title 1' etc... but not with relevant product names.

How to make this demo app work?

Thanks

**Comment by zhouyiself** [comment]
Please check the "Visual Search" section for hooking up instructions.
https://github.com/googlesamples/mlkit/tree/master/android/material-showcase#visual-search
