### ISSUE TITLE
[Feature request] If we get  the Translate close status in MLKIT Translation

### ISSUE THREAD

**Issue by spporan** [googlesamples/mlkit#536]
Sometimes need to know about the status of the ```Translate``` object. Need to know ```Translate``` object has already closed or not. If we can access like ``` translate.isClose()```, It might be helpful for developers.

Android and IOS

**Comment by bcdj** [comment]
Do you have a link to the `Translate` object? I'm not aware of such class. Do you mean `Translator` instead? If so, on iOS, as long as the object is not released from memory, it's not closed and you can continue to call its APIs.

**Comment by bcdj** [comment]
Closing this report due to lack of activity.
