### ISSUE TITLE
[Bug report] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.

### ISSUE THREAD

**Issue by vmic2002** [googlesamples/mlkit#537]
App asks user to take picture of receipt. ML Kit is supposed to extract the prices from the image.
prices and gotPrices are global variables, prices is initialized as empty and gotPrices is initialized to false

Here is the code: 
<img width="246" alt="Screen Shot 2022-06-27 at 10 12 07 AM" src="https://user-images.githubusercontent.com/89990471/175997562-64002fe5-96c6-4ad2-bac4-4b69abc0e97b.png">

<img width="536" alt="Screen Shot 2022-06-27 at 9 55 51 AM" src="https://user-images.githubusercontent.com/89990471/175994970-af52e38a-070e-4fe8-89b1-f97ddcb4e606.png">
<img width="685" alt="Screen Shot 2022-06-27 at 9 56 04 AM" src="https://user-images.githubusercontent.com/89990471/175995003-98625b37-aca7-4be8-9e0d-aaf5b3eb26b1.png">

<img width="573" alt="Screen Shot 2022-06-27 at 9 56 17 AM" src="https://user-images.githubusercontent.com/89990471/175995039-e551cc5d-b80f-413a-b9b6-36d081e5f23a.png">
<img width="761" alt="Screen Shot 2022-06-27 at 9 56 33 AM" src="https://user-images.githubusercontent.com/89990471/175995084-d41475bf-2e03-4cdf-a8f2-6aef64458c10.png">

The bug is this:
<img width="1140" alt="Screen Shot 2022-06-27 at 9 59 11 AM" src="https://user-images.githubusercontent.com/89990471/175995570-4a6d57ff-411b-40f3-8de2-30301fa47206.png">

If I just call the getPricesAsArray function on its own, the text from the picture inputed is printed (which means the ML kit works)
If I call the getPricesAsArray function within the getPrices function (as seen in the image above), the bug occurs.
The textRecognizer.process in getPricesAsArray is not on the main thread. The point of the getPrices function is to call the asynchronous function getPricesAsArray and wait for the text to be recognized fully, which will happen when gotPrices is set to true on line 85.
Once gotPrices is set to true in getPricesAsArray function, the while loop in getPrices function will terminate and a copy of the prices should be returned. (at least this is the desired behavior)

Please help and let me know if I can describe the bug better!

XCODE Version 13.4.1
On macOS Monterey vs 12.4

**Comment by mudulo** [comment]
Hey @vmic2002 what was the Fix here

**Comment by vmic2002** [comment]
Hey @mudulo I used swift’s « try await » for asynchronous functions instead of a while loop that waits until a global variable is set to true. Lmk if that works for you too

**Comment by mudulo** [comment]
Thanks @vmic2002 for the fast reply, let me try this later today and revert
