### ISSUE TITLE
[Mouse open/close ] will mlkit android support detection the mouth open/close ？

### ISSUE THREAD

**Issue by AnyLifeZLB** [googlesamples/mlkit#541]
**What's your feature request? Please describe.**
A clear and concise description of what the request is. Ex. I would like to have X language support in text recognition[...]

**Mobile environment**
Android, IOS or both

**Additional context**

**Comment by jackqdyulei** [comment]
Thanks for your feedback. I assume we are talking about Face detection API correct?

We don't have immediate plan to support it on API level. However I think probably you can predict it from the [Face contour](https://developers.google.com/ml-kit/vision/face-detection/face-detection-concepts#contours).

A naive solution maybe `height(upper lips - lower lips) < x% of height(face)` where you can fine tune the `x`
