### ISSUE TITLE
[Feature request] Pose Classification for iOS (PoseRecognition)

### ISSUE THREAD

**Issue by Throvn** [googlesamples/mlkit#542]
**What's your feature request? Please describe.**
It would be really helpful if the iOS vision example has also a sample pose classification implementation and if this would also be documented. (This repo is rather hidden :P) It seems to be a common issue since you suggested yourself in the docs that keypoins are not really useful on it's own. 

It would be great if you could document that there either is no implementation for iOS currently or as mentioned in another issue, I've already mapped the java code 1:1 to swift, and it was quite a bit of work. So it would be really cool if you could either implement one or mention my repo for guidance somewhere or at least document it [somewhere on this page](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses). Have a great day!

**Mobile environment**
IOS

**Comment by bcdj** [comment]
Thanks for the suggestion and mapping our java code to swift, Throvn! We don't normally reference sample apps that we do not develop, own, and maintain ourselves, but I'm adding a link to [your repo](https://github.com/Throvn/MLKitPoseClassificationExample) here, so that future readers can easily reference. Thank you again!

**Comment by Throvn** [comment]
Thank you, I can fully understand. Have a great day!

**Comment by kkcodes** [comment]
Hi @Throvn ,

The repo link is throwing 404. 
Can you please share the link for new repo or make the repo public again if made private?

**Comment by ragotrebor** [comment]
I work on the iOS pose classifier, its based on the android project

https://github.com/ragotrebor/mlkit-ios-poseclassifier
