### ISSUE TITLE
[Bug report]  Face Detection not detecting

### ISSUE THREAD

**Issue by AmyKao18** [googlesamples/mlkit#545]
i got 
` [WARNING]The specified colorspace format is not supported. Falling back on Libyuv.`
 when i use cutting kit like pod 'QCropper' crop image 
 the same image if i don't use pod 'QCropper' is can be detected
 please fix it , thanks

**To Reproduce**
1. choose image from album
2. use pod 'QCropper' crop image
3. detect cropped image

SDK：GoogleMLKit/FaceDetection (2.5.0)

Xcode 13.2.1 
iPhone 12 pro max

**Comment by miworking3** [comment]
Do you know the output colorspace format from `QCropper`?

**Comment by AmyKao18** [comment]
> Do you know the output colorspace format from `QCropper`?

sorry i don't know how can i  the output colorspace format from `QCropper`

**Comment by AmyKao18** [comment]
> btw: [Determining the Colorspace of a UIImage](https://stackoverflow.com/questions/4168972/determining-the-colorspace-of-a-uiimage) if your output from QCropper is a UIImage.

thanks for your reply , i get the Colorspace of UIImage
`<CGColorSpace 0x281eee880> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; Display P3)`

**Comment by miworking3** [comment]
- Are you able to reproduce this with minimum modification on top of https://github.com/googlesamples/mlkit? Due to limited resources, ML Kit engineers don't debug 3rd party code, but if you provide a way to reproduce it on top of our https://github.com/googlesamples/mlkit, we may be able to look further into that.

**Comment by AmyKao18** [comment]
Hi,after updating the SDK there is no error,thanks
