### ISSUE TITLE
[Bug report] GoogleMLKit is still using FirebaseCore 8.0 when the latest is 9.2

### ISSUE THREAD

**Issue by acoutts** [googlesamples/mlkit#546]
**Describe the bug**
I am unable to use any of the Firebase 9.2 libraries when including any of the `GoogleMLKit` pods in my project. Even with the latest v3.1.0, I'm forced to use FirebaseCore 8.0.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Depend on `'GoogleMLKit/LinkFirebase', '~> 3.1.0'`
2. Run `pod install`

Error:
```
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 9.1.12, which depends on
      Firebase/Analytics (= 9.2.0) was resolved to 9.2.0, which depends on
        Firebase/Core (= 9.2.0) was resolved to 9.2.0, which depends on
          FirebaseAnalytics (~> 9.2.0) was resolved to 9.2.0, which depends on
            FirebaseCore (~> 9.0)

    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.19.1, which depends on
      Firebase/CoreOnly (= 9.2.0) was resolved to 9.2.0, which depends on
        FirebaseCore (= 9.2.0)

    google_mlkit_image_labeling (from `.symlinks/plugins/google_mlkit_image_labeling/ios`) was resolved to 0.3.0, which depends on
      GoogleMLKit/LinkFirebase (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitLinkFirebase (~> 2.1.0) was resolved to 2.1.0, which depends on
          FirebaseCore (~> 8.0)
```

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
GoogleMLKit should support the latest FirebaseCore release. GoogleMLKit should be updated to support firebase 9.x.

**SDK Info:**
 - GoogleMLKit 3.1.0

**Smartphone:**
n/a

**Development Environment:**
n/a

**Comment by bcdj** [comment]
Among all pods in `GoogleMLKit`, I think only `GoogleMLKit/LinkFirebase` pod depends on `FirebaseCore`. To work around the limitation, are you able to avoid including the `GoogleMLKit/LinkFirebase` pod in your app, or is it required by your app? If the latter, could you elaborate why `GoogleMLKit/LinkFirebase` is required in your app?

**Comment by acoutts** [comment]
Particularly it's from the image labeling library. I'm using it in a Flutter app with this library:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_image_labeling/ios/google_mlkit_image_labeling.podspec

It's particularly related to using custom models for image labeling.
Looking at the docs, we can either bundle the models in the app or you can load the models through firebase. It's here where the firebase dependency comes in.

I think I can probably submit a PR to that library to use some build-time flags to include or exclude the firebase dependency (depending if you intend to need it or not), but the larger issue is the google-maintained LinkFirebase pod is using an outdated version of FirebaseCore.

**Comment by acoutts** [comment]
I've added a PR to exclude Firebase: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/297

But for those who do need firebase remote models, it would be nice for the `GoogleMLKit/LinkFirebase` pod to be updated to use the latest firebase core.

**Comment by bcdj** [comment]
`FirebaseCore` dependency will upgraded to 9.3 in the next release coming out in a couple of weeks.

**Comment by bcdj** [comment]
`FirebaseCore` dependency of `GoogleMLKit/LinkFirebase` is now upgraded to 9.3 in the latest release.
