### ISSUE TITLE
Unable to compile Mlkit  ios sample code in xcode

### ISSUE THREAD

**Issue by aruns911** [googlesamples/mlkit#548]
Steps to reproduce.
1. Downloaded the latest zip file  from https://github.com/googlesamples/mlkit/
2. Open the file ios/quickstarts/vision/VisionExample.xcodeproj
3. Error in UiUtilities on line 21
Error message:
Parse Error 
Module MLKit not found

**Comment by miworking3** [comment]
Run `pod install` to download dependencies via Cocoapods
Run open `VisionExample.xcworkspace` to open the project workspace in Xcode.

**Comment by aruns911** [comment]
Thanks for the quick response. 
iIm looking at this directory:
https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision

I don't see VisionExample.xcworkspace. Also when you say "Run open VisionExample.xcworkspace", I assume you mean that I launch xcode and then from the top menu bar, I click "File", "Open" and open the workspace.

**Comment by miworking3** [comment]
Did you see a `Podfile.lock` file after running `pod install`?

**Comment by aruns911** [comment]
So it finally ran through. I have a mac air on m1 chip.
1.  I had to turn on rosetta for terminal. 
2. sudo gem install ffi
3. pod install.

This created  the workspace file, that you described. Now I'm trying to build it xcode. Lots of new errors in xcode. I attached screen shots.  Do I have to do something differently for mac on m1?

<img width="1440" alt="Screen Shot 2022-07-19 at 1 29 07 PM" src="https://user-images.githubusercontent.com/6589043/179842912-1b09494e-84da-4456-b1e9-0d8d2915be81.png">
<img width="1440" alt="Screen Shot 2022-07-19 at 1 29 18 PM" src="https://user-images.githubusercontent.com/6589043/179842907-2e618f24-27c7-417f-b937-19b4cb68dcc3.png">. 

<img width="1440" alt="Screen Shot 2022-07-19 at 1 29 26 PM" src="https://user-images.githubusercontent.com/6589043/179842886-997895ed-937a-4322-ae5a-f65bc83628fe.png">
<img width="1440" alt="Screen Shot 2022-07-19 at 1 29 21 PM" src="https://user-images.githubusercontent.com/6589043/179842900-e3f3dd54-f47c-4e37-8292-edc743777486.png">

**Comment by aruns911** [comment]
Hello,
Is there an update on this?

**Comment by miworking3** [comment]
What's the error message?

**Comment by lipenny00** [comment]
ML Kit does not support simulators on M1 mac yet. Please try building the sample app for a real device connected to your M1 mac.

**Comment by aruns911** [comment]
Here are the error messages:

Showing Recent Errors Only
Undefined symbol: _GULLogBasic

Undefined symbol: _OBJC_METACLASS_$_GTMLogger

Undefined symbol: _GPBClearOneof

Undefined symbol: _OBJC_CLASS_$_GTMSessionCookieStorage

Undefined symbol: _OBJC_CLASS_$_GPBInt32Array

Undefined symbol: _OBJC_CLASS_$_GPBCodedOutputStream

Undefined symbol: _OBJC_CLASS_$_GPBFileDescriptor

Undefined symbol: _OBJC_CLASS_$_GPBDescriptor

Undefined symbol: _OBJC_CLASS_$_GTMLogger

Undefined symbol: _OBJC_METACLASS_$_GPBMessage

Undefined symbol: _OBJC_CLASS_$_GPBMessage

Undefined symbol: _OBJC_CLASS_$_GULCCComponentContainer

Undefined symbol: _OBJC_METACLASS_$_GPBRootObject

Undefined symbol: _OBJC_CLASS_$_GPBEnumArray

Undefined symbol: _kGTMSessionFetcherStatusDomain

Undefined symbol: _OBJC_CLASS_$_GDTCORTransport

Undefined symbol: _OBJC_CLASS_$_GTMSessionFetcherService

Undefined symbol: _OBJC_CLASS_$_GTMSessionFetcher

Undefined symbol: _OBJC_CLASS_$_GTMLogMininumLevelFilter

Undefined symbol: _OBJC_CLASS_$_GULCCComponentType

Undefined symbol: _OBJC_CLASS_$_GPBEnumDescriptor

Undefined symbol: _OBJC_CLASS_$_GULCCComponent

Undefined symbol: _OBJC_CLASS_$_GPBRootObject

Undefined symbol: _OBJC_CLASS_$_GULUserDefaults

**Comment by aruns911** [comment]
Right now it does'nt build. After that I'll have to figure out how to run the sample app.

**Comment by lipenny00** [comment]
Did you build on the simulator device? For now ML Kit does not support simulators on M1 mac yet. Can you try to build on real device and see if there's an issue?

**Comment by hunterZh37** [comment]
same problem here, does not work on real device.

**Comment by disham1** [comment]
This error still persist. Does anybody have idea how to solve it?

**Comment by YanxinTang** [comment]
> This error still persist. Does anybody have idea how to solve it?

Running on real device and solved
