### ISSUE TITLE
FR: Update camera APIs in the MLKit samples and improve performance

### ISSUE THREAD

**Issue by samtstern** [googlesamples/mlkit#55]
This bug is meant to track all of the other bugs about making the MLKit camera samples perform better, so that it can be discussed in one place.

**Comment by kriefsacha** [comment]
Hi, there is update on this ?

**Comment by cs-googler** [comment]
We made some changes to Firebase ML Kit to better distinguish the on-device APIs from cloud based APIs. "ML Kit"(without firebase branding) contains all the on-device APIs. [Here's](https://developers.google.com/ml-kit/migration) the migration guide from firebase mlkit to mlkit. 

For the standalone MLKit, the sample app demonstrate how cameraX can be used, please refer to [this quickstart app](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart)
