### ISSUE TITLE
Face Detected Demo 

### ISSUE THREAD

**Issue by SanganiKrish** [googlesamples/mlkit#550]
This dependency Add :-        //noinspection OutdatedLibrary
                                              implementation 'com.google.firebase:firebase-ml-vision:24.1.0'

Error :- Go to the documentation to learn how to Fix dependency resolution errors.

**Comment by jackqdyulei** [comment]
Hi Sanganikrish, please file issue using our template and provide more info(e.g. which SDK & version add outdated library). Thanks.
