### ISSUE TITLE
[Bug report] SELFIE_SEGMENTATION return the mask has a different size than the original bitmap size

### ISSUE THREAD

**Issue by rtz333** [googlesamples/mlkit#554]
**Describe the bug**
When i create InputImage from uri (Eg :Image image= InputImage.fromFilePath(MainActivity.this,uri)) everything fine but when i use:
Image image= InputImage.fromBitmap(mainBitmap,ExifInterface.ORIENTATION_NORMAL) it return the mask has a different size than the original bitmap size. so when i remove the background of the image it makes the image look unsightly.

Please someone fix it,thanks.

logcat: 
D/cascsa: maskBitmap.getWidth(): 2218--mainBitmap.getWidth(): 1956
D/cascsa: maskBitmap.getHeight(): 2798--mainBitmap.getHeight(): 2608

**SDK Info:**
 - SDK Name & Version: 'com.google.mlkit:segmentation-selfie:16.0.0-beta4'

**Smartphone:**
 - Device/Simulator: SamSung android 11 api30

**Comment by ai-plays** [comment]
The second param of fromBitmap method expects a [rotationDegree](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage#public-static-inputimage-frombitmap-bitmap-bitmap,-int-rotationdegrees), while the ORIENTATION_NORMAL is a constant value 1.

Could you try if passing in 0 could give you correct results? 

It looks like when passing in invalid values, we don't fail aloud at the moment, which is an issue we should fix on our end.

**Comment by rtz333** [comment]
it work as expected . thank you
