### ISSUE TITLE
[Bug report] Face detection fails with orientation

### ISSUE THREAD

**Issue by igibliss00** [googlesamples/mlkit#559]
**Describe the bug**

When the orientation feature is used, the face detection produces numerous empty arrays whereas without the orientation, the face object is produced every time.

**To Reproduce**

```swift
let options = FaceDetectorOptions()
options.isTrackingEnabled = true
options.performanceMode = .accurate
options.landmarkMode = .all

let image: VisionImage = VisionImage(buffer: sampleBuffer) // sampleBuffer is CMSampleBuffer
image.orientation = UIImage.Orientation.leftMirrored // using a constant here for testing

let faceDetector = FaceDetector.faceDetector(options: options)
faceDetector.process(image) { (faces, error) in
    if let error = error {

    } else {

    }
}
```
Execute the face detection with your mobile device in the portrait orientation and using the front facing camera with and without `image.orientation = UIImage.Orientation.leftMirrored`. Logging the `faces` output shows that without the orientation attribute, the array of face objects are produced for every output.  However, numerous empty arrays are produced when the orientation attribute is used even though the device is in a portrait orientation and the front facing camera is used for both cases. 

**Expected behavior**

The SDK is expected to produce same amount of output with or without the orientation. 

**SDK Info:**

 - 'GoogleMLKit/FaceDetection', '3.1.0'
 
**Smartphone:**

 - Device: iPhone 11
 - Device/Simulator OS: iOS 15.5

**Development Environment:**

- IDE Eversion: Xcode 14.0
- Laptop: MacBook M1 Pro 
- Laptop OS/version: Monterey

**Comment by miworking3** [comment]
This is expected:
you need to specify the correct orientation to get face detected: [Make sure to specify the correct .orientation](https://developers.google.com/ml-kit/vision/face-detection/ios#2.-prepare-the-input-image)
e.g., if you use the sample app in portrait mode, open the video streaming with face detection, rotate the camera, it won't return any results when the device is rotated by 90 degree: as the SDK is only expected to detect face when the face is `up` in the camera. 

So if you are using it for other mode, other than Portrait, make sure you [set the orientation correctly](https://developers.google.com/ml-kit/vision/face-detection/ios#2.-prepare-the-input-image)
