### ISSUE TITLE
Image Best Practices

### ISSUE THREAD

**Issue by pablomuniz** [googlesamples/mlkit#561]
Do we have best practices when it comes to the image we pass to the MLKIT text, besides size? only grey scale? brightness? etc..

I am using some semi-old phones with similar characteristics for testing, the one with the best camera (galaxy s8) is by far the worst, and really inconsistent.

All phones have the same input size but the Samsung suffers a lot depending on the angle of the light, even though for a human it barely looks different.

**Comment by stunningdimension22** [comment]
In general for best detection result, text should ideally be at least 24 pixels high, images don't have to be grayscale, axis-aligned or controlled for brightness. 

In some corner cases, it's a known issue that the OCR engine can be unstable: shifting the image by a few pixel changes results.
