### ISSUE TITLE
[Feature request] DigitalInkRecognition: Allow to pre-download and bundle the Ink Recognition Model in the app

### ISSUE THREAD

**Issue by RogVok** [googlesamples/mlkit#573]
I would like to have an option to download a Digital Ink Recognition model separately and bundle it into the app.
Right now users have to download it after installing the app. But I don't want to burden users with additional downloads.

**Mobile environment**
I'm developing for iOS

PS Is there any way that I can download one language Model myself, and bundle it into my app temporarily?

Thank you.

**Comment by miworking3** [comment]
I'm afraid ML Kit doesn't provide such packaging.

**Comment by RogVok** [comment]
Would you like to provide such packaging? In the future releases perhaps?

It will not only simplify the development, and improve user experience but also unload Google servers from unnecessary traffic.

**Comment by rajivgpta** [comment]
I support this request for a future release as well. It would be good to have this pre-packaged to avoid multiple downloads from all users.

**Comment by miworking3** [comment]
I'm afraid we haven't planned this, so probably won't provide this in the future.

**Comment by xubinlu** [comment]
@RogVok Hello, how did you solve this problem? I have the same problem now.

**Comment by RogVok** [comment]
@xubinlu This problem isn't solved yet. I hope that Google engineers will provide that functionality when they have more free time.
