### ISSUE TITLE
Conflict dependencies with com.google.mlkit:barcode-scanning:16.2.0 and com.google.mlkit:face-detection:16.1.5

### ISSUE THREAD

**Issue by nvmabc** [googlesamples/mlkit#574]
**Describe the bug**

**To Reproduce**
The purpose is I want to use:
- Camerax for scan QR code and barcode
- And my project have face-detection also 
So it's conflict dependencies when I use both these in build gradle as below.

**build.gradle:**
 - implementation 'com.google.mlkit:barcode-scanning:16.2.0'
 - implementation 'com.google.mlkit:face-detection:16.1.5'

- minSdkVersion 21
- targetSdkVersion 32

**Error**
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.google.mlkit.vision.barcode.BarcodeScanner, unresolved supertypes: com.google.mlkit.vision.common.internal.Detector
Adding -Xextended-compiler-checks argument might provide additional information.

**Comment by jackqdyulei** [comment]
Hi nvmabc,

Please use latest versions, which are:
`com.google.mlkit:barcode-scanning:17.0.2`
`com.google.mlkit:face-detection:16.1.5`

**Comment by nvmabc** [comment]
Already but still conflict dependencies when we use both.

**Comment by jackqdyulei** [comment]
Can you check our sample app [here](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/build.gradle#L59-L71)

It use the version I mentioned and it doesn't have build error. In your build file please check whether you have other ML Kit related dependency which might be too old

**Comment by nvmabc** [comment]
Now is ok Thanks you so much.
