### ISSUE TITLE
[Feature request] MLKIT API is detecting and tracking maximum only 5 objects

### ISSUE THREAD

**Issue by RajezMariner** [googlesamples/mlkit#577]
**What's your feature request? Please describe.**
As per the documentation in the ML-KIT object detection, it is mentioned that is detecting up to 5 objects from the image and track it. May I know if we can customize this parameter to 50 or more. If it is already exists, please help me on where to change this parameter. 

https://developers.google.com/ml-kit/vision/object-detection/android

**Mobile environment**
Android and IOS

**Additional Context**
I would like to detect multiple objects, track them and store the unique crops of these detections.

**Screenshot of the document**
<img width="878" alt="Screenshot 2022-10-21 at 4 34 26 PM" src="https://user-images.githubusercontent.com/30373242/197181676-79a4f530-b3e7-45b8-a58f-6e010abab417.png">

**Comment by ai-plays** [comment]
Hi RajezMariner,

We don't have a parameter to change the max number of detection at the moment. There is a very similar request from the past. Please take a look: https://github.com/googlesamples/mlkit/issues/233 . It also mentioned some alternatives.

In that post, it also mentioned some tracking needs. However, if an object leaves the frame and comes back, it will be re-assigned to another tracking ID. Are you trying to keep 50 items in frame while tracking them? If possible, could you share a bit more context about your use case?

**Comment by RajezMariner** [comment]
Hi @ai-plays - Really appreciate to respond back. Yes, we are planning to have more than 50 images also in a single frame. 

**Context:** We are planning to have a tracking detection system where we would be detecting the objects present in the kirana (grocery) stores and we will aggregate the group of objects and get the count through the tracking ids. We will send these unique detected objects to the backend to get the list of objects with the number of counts of the same.

**Comment by RajezMariner** [comment]
@ai-plays - I have checked the issue that you have mentioned. As per your suggestions, uploading multiple frames and detecting it is very much heavy weighted tasks. In the sense, lot of backend services should be enabled and co-ordination should happen. Would like to run them on the live video frame since we do not need to do lot of heavy lifting at the backend, else uploading the frame will be really slower as well based on the network bandwidth.

**Comment by ai-plays** [comment]
Yeah. Reducing latency is one of the advantage of on-device ML. 

Given that ML Kit currently don't provide the API to change the max-detection and it may take some time for discussing it, I would suggest giving the [TFLite Task Library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/object_detector) a try first. It has a setMaxResults API.

**Comment by RajezMariner** [comment]
@ai-plays - we have tried it out already for some of our detection use cases which worked really well. we would need to work more on the tracking part right now. Let me know if I could contribute more on the same.

**Comment by RajezMariner** [comment]
@ai-plays - do we have any community channel for the same with whom we can discuss and work on the same? I am really interested in making the above changes as per our use case.

**Comment by ai-plays** [comment]
Hi RajezMariner, the two main channels are Github and https://stackoverflow.com/questions/tagged/google-mlkit .

Maybe you could consider reaching out to people in https://github.com/googlesamples/mlkit/issues/233 ?

**Comment by ai-plays** [comment]
Closing this bug for now. Shared this request internally.

**Comment by qhaas** [comment]
Given phones are getting more and more powerful thanks to the Pixel line, it might be useful to revisit the ability to raise the cap on detected objects.  There are several use cases where one would need to detect / track more than 5 objects in one's field of view, especially since the onboard camera is only getting more and more capable.
