### ISSUE TITLE
Disordering of Extracted Lines from ML kit Text Extraction API(OnDeviceTextRecogniser)

### ISSUE THREAD

**Issue by phani-artiovatic** [googlesamples/mlkit#58]
### Step 1: Describe your environment
  * Android device: _Nokia 2.2____
  * Android OS version: Android 9.0
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
### Step 2: Describe the problem:

On providing images with texts in same line having large spaces in between them are separated into different blocks. This inreturn messes up order of lines in text extraction. But order of lines is very important in our case.

#### Steps to reproduce:

  1.Provide an image with words in same line with large spaces
  2.And check output Text , you can see order of lines disordered in large degree

  
#### Observed Results: This is Raw text from TextExtraction API

Sample Input
![sample](https://user-images.githubusercontent.com/54930857/66197136-633f3080-e6b7-11e9-9023-2e66da656ea9.png)

Output

ORIGINAL
    L For Recioient
    BILL OF SUPPLY
    ABD CO
    20/0/208
    BOS0057
    M.G.RAOD, Delhi, Delhi 110099
    GSTIN 0TA
    State
    PAN
    434
    B Date
    07-Delhi
    AAECC8220
    No
    Reference Nio PO.78708
    Customer Name
    ACC &CO
    Customar GSTIN
    27A
    Place of Supsly
    Billing Addres
    ACC &CO
    Maharashtr
    Shipping Addres
    ACC&CO
    Maharashtra
    120
    27-Maharashtra
    Due Date 24/01/2038
    Discount (
    Rate / tem (
    Total ()
    tem
    HSN/SAC Quantity
    1,809.00
    KGS
    1.Slag for manufacturing iron
    8,678.67
    171,30,30,762.64
    Total ()
    1,30,30,762.64
    1,30,30,763.00
    0.36
    One Crore Thirty Lakh Thirty Thousand Seven Hundred Sity Three Rupees Only
    Total Value
    Rounding off
    Total amount in words)
    For ABD Cco
    Authorised Signatory

#### Expected Results:

Expected result is line by line extraction.Currently its block by block extraction or is there way to acheive it?
  
#### Relevant Code:

depnedecny used com.google.firebase:firebase-ml-vision:20.0.0'(OnDeviceTextRecogniser)
  ```

**Comment by miworking3** [comment]
I'm afraid the iOS version won't adopt such change in the future. Closing it with obsolete as it has been over 2 years.

**Comment by Shahir1730623** [comment]
did anyone find solution to this problem?

**Comment by sidetraxaudio** [comment]
This should be re-opened. The tool is useless for adjacent data extraction from static fields when its return text is totally out of order. There are actually those of us doing professional work not playing with toys in their parents basement in California.
