### ISSUE TITLE
[Feature request]Can the animation of this overlay be made public?

### ISSUE THREAD

**Issue by luohaohaha** [googlesamples/mlkit#590]
**What's your feature request? Please describe.**
like this video

**Mobile environment**
Android iOS

https://user-images.githubusercontent.com/3376376/202900675-d0ed9815-bcb2-4727-99be-8fc173b6d198.mp4

**Comment by zhouyiself** [comment]
Sorry, this code lives in google play service instead of SDK library, so it won't be public.
