### ISSUE TITLE
[Bug report]  Waiting for the face detection module to be downloaded. Please wait.

### ISSUE THREAD

**Issue by allamistiqha** [googlesamples/mlkit#592]
**Bug Description**
"Waiting for the face detection module to be downlaoded. Please wait" when use unbundled version from mlkit face detection dependencies and added this :
 <meta-data
          android:name="com.google.mlkit.vision.DEPENDENCIES"
          android:value="face" >
to AndroidManifest, it's said when i included meta-data in androidManifest, i'll automaticly download the needed module

**SDK Info:**
 - com.google.android.gms:play-services-mlkit-face-detection:17.1.0

**Smartphone:**
 - Device/Simulator OS: [android 11, Versi MIUI 12.5.8 Stable]
 - Device name : Redmi Note 10s

**Comment by jackqdyulei** [comment]
Hi allamistiqha,

Please provide the metadata you added in android manifest.

Also please noted that downloading will be init when app is installed, however it doesn't guarantee it is downloaded when you open the app.

**Comment by allamistiqha** [comment]
<meta-data
            android:name="com.google.mlkit.vision.DEPENDENCIES"
            android:value="face" />

**Comment by jackqdyulei** [comment]
The meta-data is correct. Just like what I mentioned. Downloading will be init when app is installed, however it doesn't guarantee it is downloaded when you open the app.

Let me know if you have other question. Thanks
