### ISSUE TITLE
MLKit Barcode recognize crash

### ISSUE THREAD

**Issue by zhengweishuai** [googlesamples/mlkit#598]
SIGABRT
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeBufferNative+46) [armeabi-v7a::9555e2a1ae799a23f49c50c13e484537

![image](https://user-images.githubusercontent.com/31502852/206083894-bb71ab9f-7553-4b8a-93f5-2bbcd8cf9fb7.png)
![image](https://user-images.githubusercontent.com/31502852/206083965-c54128eb-f24d-403d-9559-10dac0ec3c29.png)

**Comment by SilverDestiny** [comment]
Hi, could you consistently reproduce the crash? If yes, could you share your detailed steps or sample image that we can reproduce your crash?

If no, please share the full log instead of screenshots. Thanks!

**Comment by SilverDestiny** [comment]
Close this issue as no reply yet for a month.

Feel free to reopen it if you still need any help. :)

**Comment by Saloni1232** [comment]
Hi Team,

We are still facing this issue. Please respond.

**Comment by AbelTarazona** [comment]
Hello, in my application I also have this error. Information here: https://apprecio-0j.sentry.io/share/issue/3b7b3fd2e496431aa07490ffd7f9f8c0/
