### ISSUE TITLE
Vision Quickstart app - deploy a new yolov5s model

### ISSUE THREAD

**Issue by HripsimeS** [googlesamples/mlkit#599]
Hello. I check details in the script converting pytorch to TFLite https://github.com/ultralytics/yolov5/blob/master/export.py
It already adding a TFLite metadata. But when I am trying to deploy the converted model into one of MLKit apps, it does not work https://github.com/googlesamples/mlkit/tree/master/android

Is it because the converted model doesn't fit the outputs requirements of your models (EfficientDet, MobileNet, etc) ?

Below you can find my converted models (fp16 and int8)
https://github.com/HripsimeS/Projects/blob/main/yolov5s-fp16.tflite
https://github.com/HripsimeS/Projects/blob/main/yolov5s-int8.tflite

Please let me know how to fix the issue to be able to deploy in MLKit apps, thanks a lot in advance!

**Comment by HripsimeS** [comment]
Hello. I check details in the script converting pytorch to TFLite https://github.com/ultralytics/yolov5/blob/master/export.py  
It already adding a TFLite metadata. But when I am trying to deploy the converted model to one of MLKit apps, it does not work at all https://github.com/googlesamples/mlkit/tree/master/android

Is it because the converted model doesn't fit the outputs requirements of your models (EfficientDet, MobileNet, etc) ?

Below you can find my converted models (fp16 and int8)
https://github.com/HripsimeS/Projects/blob/main/yolov5s-fp16.tflite
https://github.com/HripsimeS/Projects/blob/main/yolov5s-int8.tflite

Please let me know how to fix the issue to be able to deploy in MLKit apps, thanks a lot in advance!

**Comment by SilverDestiny** [comment]
Hi, are you trying to use your custom model in ML Kit custom image labeling or object detection libraries?

https://developers.google.com/ml-kit/custom-models#model-compatibility
Here is the link for model compatibility. Make sure your model follows these patterns.

And if you have the error message of why your model didn't work, please share it and we can take a look. Thanks!

**Comment by SilverDestiny** [comment]
Close it as no reply for a month.

Feel free to reopen this bug if you still need any help. Thanks!
