### ISSUE TITLE
Only run for 'Region of Interest'

### ISSUE THREAD

**Issue by Ectrics** [googlesamples/mlkit#6]
Is it possible to run the camera on a region of interest for maximum speed? As in attached image, only a part of the screen would be actually requested for inference? (I'm interested in doing this for iOS)

<img width="582" alt="RoI_example" src="https://user-images.githubusercontent.com/30905425/83871831-11ace100-a731-11ea-9fc2-96e3c919cbbb.png">

**Comment by bcdj** [comment]
If you always know where your interested region is, have you tried crop the input image to just that region and try it out to see if improves the speed?  Assuming you are using a live video camera and `CMSampleBuffer` as the input format, you can check out this sample code for cropping it: 

https://github.com/FirebaseExtended/mlkit-material-ios/blob/master/ShowcaseApp/ShowcaseAppSwift/Common/ImageUtilities.swift#L85

If your input image format is `UIImage`, I think you can use this:

https://developer.apple.com/documentation/coregraphics/1454683-cgimagecreatewithimageinrect?language=objc

Good luck!
