### ISSUE TITLE
[Bug report] pod install failed: TextRecognition3.2.0 and GoogleDataTransportCCTSupport3.2.0 depends on different version of GoogleDataTransport

### ISSUE THREAD

**Issue by robinmo** [googlesamples/mlkit#602]
**Describe the bug**
My target needs TextRecognition3.2.0 and GoogleDataTransportCCTSupport3.2.0, the pod file like this:
```
target 'xxxx' do
  pod 'GoogleMLKit/TextRecognition', '3.2.0'
  pod 'GoogleDataTransportCCTSupport', '~> 3.2.0'
end
```

after pod install, the terminal shows:

```
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In snapshot (Podfile.lock):
    GoogleDataTransport (= 6.2.1, ~> 6.1)

  In Podfile:
    GoogleDataTransportCCTSupport (~> 3.2.0) was resolved to 3.2.0, which depends on
      GoogleDataTransport (~> 6.1)

    GoogleMLKit/TextRecognition (= 3.2.0) was resolved to 3.2.0, which depends on
      MLKitTextRecognition (~> 1.4.0-beta6) was resolved to 1.4.0-beta6, which depends on
        MLKitCommon (~> 8.0) was resolved to 8.0.0, which depends on
          GoogleDataTransport (~> 9.0)
```

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. create a pod file like my case
2. pod install 

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
pod install success

**SDK Info:**
 - SDK Name & Version [e.g. com.google.mlkit:face-detection:16.1.3]

**Smartphone:**
 - Device/Simulator: [e.g. iPhone6, Pixel 5]
 - Device/Simulator OS: [e.g. iOS8.1, Android API 30]

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: Xcode 14.1
- Laptop/Desktop: Mac Studio (2022)
- Laptop/Desktop OS/version: macOS Monterey 12.6

**Comment by miworking3** [comment]
It is more of an issue of `GoogleDataTransportCCTSupport`, instead of `GoogleMLKit/TextRecognition`: 
The latest version of `GoogleDataTransport` is 9.2.0, and it makes sense for MLKit pods to depend on a more recent version 9.* instead of way back 6.*
Please contact `GoogleDataTransportCCTSupport` team to update their pod dependencies.
