### ISSUE TITLE
[Feature request] Ml kit can only be installed on devices that support GMS?

### ISSUE THREAD

**Issue by sby5388** [googlesamples/mlkit#605]
**What's your feature request? Please describe.**
some devices don't pre-install GMS , so we could not install mlkit-app on these  Android devices ?

**Mobile environment**
Android

**Comment by ai-plays** [comment]
ML Kit provides two types of SDKs. One requires you statically link the library including models in your app and does not require GMS (SDKs with artifact name: com.google.mlkit:xyz). Another type uses models from GMS which saves the apk size for your app (SDKs with artifact name: com.google.android.gms:play-services-mlkit-xyz).

Some features have both versions. For example, barcode: https://developers.google.com/ml-kit/vision/barcode-scanning/android
