### ISSUE TITLE
[Bug report] digitalink RecognitionCandidate return always null score

### ISSUE THREAD

**Issue by tienipia** [googlesamples/mlkit#606]
**Describe the bug**
Recognized result of mlkit digitalink (which is RecognitionCandidate object) returns null score when calling [getScore()](https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/RecognitionCandidate#getScore()) method.

**To Reproduce**
call getScore() of returned result of mlkit.
Language for I've tested on is English/Korean/Japanese.
```
RecognitionCandidate recognitionCadidate = ...; // returned by DigitalinkRecognizer.recognize Task.
Float score = recognitionCadidate.getScore(); // score is always null
```

**Expected behavior**
According to [document](https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/RecognitionCandidate#public-float-getscore), the value is populated only for supported models. However, native logcat print some sort of scores. In my thought, that value must be populated for model output.

**SDK Info:**
```
implementation group: 'com.google.mlkit', name: 'digital-ink-recognition', version: '18.0.0'
```

**Smartphone:**
 - Device/Simulator: All Android devices and simulators.

**Comment by ai-plays** [comment]
Hi tienipia, 

This is working as intended.

The scores you saw in log are internal / uncalibrated scores, so they are not returned. At the moment, only the following models output calibrated scores via the public API: shapes/autodraw/emoji
