### ISSUE TITLE
Other language not working (Recognize text in images with ML Kit

### ISSUE THREAD

**Issue by FrancisRR** [googlesamples/mlkit#61]
Dear Team,

OCR reader(text recognizer) is working fine in english language but not recognized in tamil language may be some of the other languages also not working.
How to solve this issue. please provide the solution.

My code is:

  private fun recognizeText(image: InputImage) {
        val recognizer = TextRecognition.getClient()
        val identification = LanguageIdentification.getClient()
        val result = recognizer.process(image)
            .addOnSuccessListener { visionText: Text ->
                processTextBlock(visionText)
                Log.e(TAG, "Success")
            }
            .addOnFailureListener { e ->
                Log.e(TAG, "${e.message}")
            }}

    private fun processTextBlock(result: Text) {
        val resultText = result.text
        var lineText: String = ""
        for (block in result.textBlocks) {
            val blockText = block.text
            Log.e("Block text", "$blockText")
            for (line in block.lines) {
                lineText = lineText + "\n" + line.text
                Log.e("Line text", "$lineText")
            }
        }

    }

**Comment by sheepmaster** [comment]
The on-device text recognition API in ML Kit only supports Latin script, not Tamil script. [Firebase ML](https://firebase.google.com/docs/ml/recognize-text) supports non-Latin scripts (by using the Cloud API).
