### ISSUE TITLE
[Feature request] Background blur and virtual background for Selfie segmentation

### ISSUE THREAD

**Issue by IvanSimovic** [googlesamples/mlkit#610]
Currently implementing selfie segmentation for Android and the only thing that you can do with Selfie segmentation is to draw over an image with a mask telling you if a part of the image is the background or a person. Could we add better support for modifying the image we are processing? So when we detect the background we can choose what should happen to it? In that case, we could specify that the background should be blurred, colored, or replaced by a different image. Right now I don't understand how to implement virtual background or background blur using Selfie segmentation and the mask I get.

**Comment by ai-plays** [comment]
Thanks for the feedback. Before such functionality is added, here are some ideas about how to achieve them.

The mask result tells you which part is the person, so you can extract those pixels, then copy them to another image. The other image could be a new background image as the virtual background OR you can blur the entire input image you passed to the Segmenter as the new background.   As for how to blur an image on Android, I believe Google search could provide better answers.

I will close this bug but share the request internally. Feel free to re-open if you have followup questions.

**Comment by arianaa30** [comment]
My question too. I was trying to achieve blur effect, but in the vision samples in the two files under `/segmenter`, we don't pass the original frame. So what would be the best way to achieve blur effect? It is quite different that the Pink mask we do right now.
