### ISSUE TITLE
QR Code Scanning

### ISSUE THREAD

**Issue by BhayashriPatil** [googlesamples/mlkit#612]
QR code Scanning not fast working as compared to barcode scanning and few QR scanned in G lens but not mlK

**Mobile environment**
Android
Barcode scanning and QR scanning both are using in single app, barcode working fine but stuck in QR code.
I need support in QR code scanning I made all required changes but not yet able captured all QR code

**Comment by miworking3** [comment]
Thanks for reporting this. For GLen, barcode detection is also integrating the result of server model, while MLKit is using on-device model only, so there is always a trade-off here.
