### ISSUE TITLE
[Bug report] no such module 'MLKit'

### ISSUE THREAD

**Issue by konstantinlois** [googlesamples/mlkit#618]
**Describe the bug**
I am trying to build an ios library that leverages the Google digital ink library. However, I am struggling to import the digital ink library into my own library as a dependency.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. add `s.dependency 'GoogleMLKit/DigitalInkRecognition', '~> 3.2.0'` in the podspec of my library
2. add `import MLKit` somewhere in the project (for example in some view file)
3. run `pod install`
4. try to build the project
5. the following error is shown: `no such module ‘MLKit’` (it’s complaining about the `import MLKit` line)

Am I missing something?

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
App building successfully.

**SDK Info:**
 - SDK Name & Version: 'GoogleMLKit/DigitalInkRecognition', '~> 3.2.0'

**Smartphone:** (not applicable)
 - Device/Simulator: [e.g. iPhone6, Pixel 5]
 - Device/Simulator OS: [e.g. iOS8.1, Android API 30]

**Development Environment:** (can be provided, if important)
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

Thank you for your help.

**Comment by miworking3** [comment]
Are you using a Podfile, could you share your Podfile?

**Comment by konstantinlois** [comment]
Thank you for your response. Regarding your question: Since I was building a module myself, I had no podfile but a podspec.

However, I figured out a solution for the problem. I just had to specifically import only the digital ink part from MLKit (not the whole MLKit). It is working now.

Thank you.
