### ISSUE TITLE
[Bug report]  [iOS] Face not detected in real-time face detection

### ISSUE THREAD

**Issue by yuya1154** [googlesamples/mlkit#620]
**Describe the bug**
I am using AVFoundation in iOS for real-time face detection from camera frames.
When I set the camera quality, AVCaptureSession.sessionPreset, to .photo, the faces were not detected on some models (iPhone8).
When I set AVCaptureSession.sessionPreset to .high, it was able to detect.
However, I would like to use .photo, which has higher image quality, because I want the app to also have the role of taking pictures of the camera.
On the 12mini and 13mini, the .photo detected faces just fine.
Is there a solution to this problem?

```
var captureSession = AVCaptureSession()
captureSession.sessionPreset = AVCaptureSession.Preset.photo
```

**Expected behavior**
Faces are detected in all models when .photo

**SDK Info:**
`pod 'GoogleMLKit/FaceDetection', '3.2.0'`

**Smartphone:**
 - Failure:  iPhone8 iOS15
 - Success: iPhone12mini iOS14.2, iPhone13mini iOS16
 
**Development Environment:**
- IDE Eversion:Xcode14.2
- Laptop/Desktop: MacBook Pro（2021）
- Laptop/Desktop OS/version: macOS 12.6.2

**Comment by miworking3** [comment]
I'm afraid with the shift of priority in our team, there is no plan in the near future to address this.
