### ISSUE TITLE
Comparison of ml kit and media pipe pose detection models

### ISSUE THREAD

**Issue by EinePriseCode** [googlesamples/mlkit#622]
Hi everyone,

here https://developers.google.com/ml-kit/vision/pose-detection I found a link to one of mediapipe's model cards (for pose landmarks). The question is, are the ml kit pose detection models (normal and accurate) the same as the mediapipe ones or are they just using the same base concept?
If they are the same, can I expect the same or pretty similar results for the same inputs in ml kit's or mediapipe's model.
And further more, which are the exact equivalents (because there are only two different models in ml kit but three accurracy levels in mediapipe)?

Thank you.

**Comment by ai-plays** [comment]
The models ML Kit SDK uses and MediaPipe provides may not always be the same, but should be similar.

ML Kit's default model (pose-detection) == MediaPipe's lite model
ML Kit's accurate model (pose-detection-accurate) == MediaPipe's full model
ML Kit doesn't use the MediaPipe heavy model
