### ISSUE TITLE
Slow detection of dens Aztec codes

### ISSUE THREAD

**Issue by swemaz** [googlesamples/mlkit#625]
When trying to scan a aztec code shown on mobile screen it takes more than 10 seconds for the scanner to detect the image.
I've tried to increase the input image resolution but that does not help much.
Scanning an less dens aztec i no problem. 

To reproduce download below image to a mobile device to get the right size. Then try to scan.
![Ticket](https://user-images.githubusercontent.com/27277901/216817671-88798327-b761-4d47-970d-2cd695ff6368.png)
This should not take more than 1-2 seconds.

I'm using
 com.google.mlkit:barcode-scanning:17.0.3
Samsung xCover5 
Android version: 33

**Comment by miworking3** [comment]
There is always a tradeoff between the performance and detectability:
https://developers.google.com/ml-kit/vision/barcode-scanning/android#performance-tips
`
Don't capture input at the camera’s native resolution. On some devices, capturing input at the native resolution produces extremely large (10+ megapixels) images, which results in very poor latency with no benefit to accuracy. Instead, only request the size from the camera that's required for barcode detection,  which is usually no more than 2 megapixels.`
