### ISSUE TITLE
hao to use  multipose model

### ISSUE THREAD

**Issue by GongKuiJun** [googlesamples/mlkit#626]
**What's your feature request? Please describe.**
I want to use multi-person recognition in Mlkit. Do you support it? How to load the model, such as“ https://tfhub.dev/google/lite-model/movenet/multipose/lightning/tflite/float16/1?lite -format=tflite”

**Mobile environment**
Android

**Additional context**

**Comment by ai-plays** [comment]
ML Kit doesn't support running this model. You could consider using TFLite Interpreter directly. https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/InterpreterApi
