### ISSUE TITLE
[Feature request] Allow secondary Firebase project download

### ISSUE THREAD

**Issue by wmbest2** [googlesamples/mlkit#630]
**What's your feature request? Please describe.**
Due to some legacy id format reasons (our firebase project id contains a `:`) we cannot use our primary Firebase project to distribute our model. 

I was unable to find a way to setup the FirebaseModelSource with the secondary project

Can we add the `FirebaseApp` name to the the source for loading from a secondary source.

**Mobile environment**
both

**Additional context**
[Firebase Multiple Project Setup](https://firebase.google.com/docs/projects/multiprojects)

**Comment by ai-plays** [comment]
Could you elaborate a bit more, e.g. which ML Kit feature are you using?

**Comment by wmbest2** [comment]
We are utilizing the Custom Image Labeling with Firebase distribution
https://developers.google.com/ml-kit/vision/image-labeling/custom-models/android#configure_a_firebase-hosted_model_source

We are able to use Firebase directly and all of the old APIs however we require a secondary `FirebaseApp` to host the custom model. Unfortunately neither the `RemoteModelManager` nor the `FirebaseModelSource` allow specifying which `FirebaseApp`. Only the model name can be specified which I assume will download using the default Firebase project.

When using the Firebase downloader we can specify and app [FirebaseModelDownloader.getInstance(app: FirebaseApp)](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader#getInstance(com.google.firebase.FirebaseApp))

**Comment by SilverDestiny** [comment]
Does https://firebase.google.com/docs/projects/multiprojects#use_multiple_projects_in_your_application work?

i.e. call `FirebaseApp.initializeApp(this /* Context */, options, "secondary");` to initialize secondary app

**Comment by SilverDestiny** [comment]
So you mean after init secondary app by `FirebaseApp.initializeApp(this /* Context */, options, "secondary");`, it still tried to get model from the primary app from the model name you specified in `FirebaseModelSource`?

**Comment by SilverDestiny** [comment]
Feel free to reopen if you still have this issue
