### ISSUE TITLE
Adjusting the detection- and tracking confidence for pose detection

### ISSUE THREAD

**Issue by nabens** [googlesamples/mlkit#631]
Hi,

In the MediaPipe Python package one can adjust  the "min_detection_confidence" and
 "min_tracking_confidence" parameters of the pose detection model when initializing it, is it possible to do the equivalent actions when using mlkit's pose detection models?

Thanks.

**Comment by ai-plays** [comment]
We don't have a plan to work on that at the moment. 

Thanks for your feedback! Will let the team know.
