### ISSUE TITLE
Suggestion on segmenting the text recognition only meter reading

### ISSUE THREAD

**Issue by Ranjithsp6** [googlesamples/mlkit#633]
We are trying to build the app where meter reading should be recognized from both static and live camera image.
Google MLkit recognize all the text in image. So we used regex to filter the data. But in live camera all the text are getting displayed in live camera.

Need a suggestion on segmenting the part to recognize only the meter read in both image and live camera case

**Comment by stunningdimension22** [comment]
Hi [Ranjithsp6](https://github.com/Ranjithsp6), the text recognition result is provided in organization of block/line/element/symbol https://developers.google.com/ml-kit/vision/text-recognition/android#4_extract_text_from_blocks_of_recognized_text, does that help with the segmentation you mentioned?

**Comment by Ranjithsp6** [comment]
Hi @stunningdimension22, thanks for the suggestion. Our current requirement is like to scan the meter read text only with specific scan area if we are using the live camera.

**Comment by Ranjithsp6** [comment]
Hi @stunningdimension22 , Any suggestions reg this requirement. Let me know if further details about the functionality i am trying to achieve

**Comment by RanjithSingaravel** [comment]
Any suggestions reg this requirement?

**Comment by RanjithSingaravel** [comment]
Anyone has implemented with same kind of requirement?

**Comment by RanjithSingaravel** [comment]
Any suggestions reg this kind of requirement?

**Comment by RanjithSingaravel** [comment]
Any suggestions reg this requirement. Let me know if further details about the desired functionality

**Comment by RanjithSingaravel** [comment]
Anyone has implemented with same kind of requirement?

**Comment by RanjithSingaravel** [comment]
Any suggestions reg this requirement. Let me know if further details required about the functionality i am trying to achieve

**Comment by stunningdimension22** [comment]
Hi there,

MLKit Text Recognition only takes streaming input or image input and output results, it does not directly control camera flow. So it is out of the scope of MLKit for now (unless one day we have a text recognition UI). From your side as the client, you can choose whatever the input to mlkit or filter the output as you say, either way you have to implement this somewhere.
