### ISSUE TITLE
Why not texture view?

### ISSUE THREAD

**Issue by MHKalantarian** [googlesamples/mlkit#64]
I believe TextureView performance is way better than SurfaceView specially in fragments. So whats the reason behind using SurfaceView in this app?

Also when I tried to convert it to TextureView the Scanner Reticle in the middle will turn to black!
[ScreenShot](https://imgur.com/ZGxGWe1)

**Comment by zhouyiself** [comment]
No particular reason I think, both could work for demo purpose and we didn't try out TextureView and do any performance measurement between them. So feel free to pull a request if one surpasses another obviously :)

**Comment by MHKalantarian** [comment]
> No particular reason I think, both could work for demo purpose and we didn't try out TextureView and do any performance measurement between them. So feel free to pull a request if one surpasses another obviously :)
The problem is I tried to convert it, there is a problem in the reticle which I'm not understanding and will be glad if you or anybody else could help me out.

**Comment by cs-googler** [comment]
Hi, in general SurfaceView performs better and TextureView is compatible(less corner cases with bug) on more API levels.
