### ISSUE TITLE
None of the Activities Gets Loaded

### ISSUE THREAD

**Issue by subrhmanyam** [googlesamples/mlkit#643]
**Describe the bug**
When Launching the Sample on Google Pixel 6 , Only the ActionBar is een

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to Android Studio
2. Run the app
3. Empty Screen Loads

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
Should Load the Activities

**SDK Info:**
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:18.0.0'

**Smartphone:**
Pixel 6

**Development Environment:**
Studio  Electic eel

**Comment by stunningdimension22** [comment]
Can you provide more context? For example any logcat or sceenshot?
