### ISSUE TITLE
[Bug report] Title for the bug

### ISSUE THREAD

**Issue by hashimali1994** [googlesamples/mlkit#647]
i am not geting the birthday in contect info 
using googlebarcode detecter  

barcode.contactInfo?.title.toString()
                                    val name = barcode.contactInfo?.name?.formattedName
                                    val Tel = barcode.contactInfo?.phones?.mapNotNull { it.number }
                                    val email = barcode.contactInfo?.emails?.mapNotNull { it.address }
                                    val company =barcode.contactInfo?.organization.toString()
                                    val address = barcode.contactInfo?.addresses?.firstOrNull()?.addressLines?.joinToString(separator = "\n")
                                    val urls = barcode.contactInfo?.urls?.toList()?.joinToString(separator = "\n")
                                    val intent = Intent(context, ScanResultActivity::class.java)

**Comment by zhouyiself** [comment]
ML Kit Barcode.ContactInfo doesn't support birthday field.
https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/common/Barcode.ContactInfo
