### ISSUE TITLE
Updating to the new Digital Ink Recognition SDK version

### ISSUE THREAD

**Issue by RogVok** [googlesamples/mlkit#648]
1. In the [quickstart project Podfile](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/digitalinkrecognition/Podfile) you have: `pod 'GoogleMLKit/DigitalInkRecognition', '4.0.0'`, but the [official release notes](https://developers.google.com/ml-kit/release-notes#ios-api-latest-versions) state that MLKitDigitalInkRecognition is at version 3.0.0 from 03/21/2023. Which version is correct right now?

2. How will the update process work for the users of the app? If I update the framework version and include it in the next app update, what will happen to the language ML Models that were previously downloaded to the user's phone? Will the user have to download them again? Is it automatic? Should I write this functionality?

P.S. Congrats on the new version release, thank you and keep up the great work :)

**Comment by RogVok** [comment]
UPD: I can answer my first question, Yes it is safe to write `pod 'GoogleMLKit/DigitalInkRecognition', '4.0.0'`. While the `GoogleMLKit` pod will be updated to v 4.0.0, the `MLKitDigitalInkRecognition` pod will be updated to v 3.0.0 accordingly.

**Comment by miworking3** [comment]
The umbrella `GoogleMLKit` pod is now `4.0.0`, while the `MLKitDigitalInkRecognition` pod behind it is actually `3.0.0`, so you can write:
`pod 'GoogleMLKit/DigitalInkRecognition', '4.0.0'`
or 
`pod 'MLKitDigitalInkRecognition', '3.0.0'`
both works

**Comment by miworking3** [comment]
To question 2:
The update progress will be:
(1) Developer run pod install to pull the latest pods
(2) Developer build the ipa, and publish it in AppStore
(3) For user, when they install the updated version and start to use it for the first time, the code will check if the expected model file exists, if not, it will be downloaded again. This process is automated, so you don't need to rewrite the functionality.
