### ISSUE TITLE
How should I attribute the Digital Ink Recognition MLKit SDK use in my app?

### ISSUE THREAD

**Issue by RogVok** [googlesamples/mlkit#649]
I've read the [ML Kit's Terms & Privacy](https://developers.google.com/ml-kit/terms) and [Google APIs Terms of Service](https://developers.google.com/terms#section_6_brand_features_attribution) but haven't found an answer to my question. Google APIs Terms of Service Section 6, b. "Attribution" states:

> You agree to display any attribution(s) required by Google as described in the documentation for the API.

[Digital Ink Recognition API Guide](https://developers.google.com/ml-kit/vision/digital-ink-recognition) doesn't really say what attribution is required. 
Do I have to show users that I use the Digital Ink Recognition SDK or not?

Thank you for your answer.

**Comment by bcdj** [comment]
ML Kit's Digital Ink Recognition API does not have special requirements about attribution(s) other the app developers' responsibility of informing their users about Google's processing of ML Kit metrics data as required by applicable law. This is specified in [ML Kit's Terms & Privacy](https://developers.google.com/ml-kit/terms).
