### ISSUE TITLE
Support for Custom Entity extraction

### ISSUE THREAD

**Issue by pradnya198** [googlesamples/mlkit#656]
Need to extract custom entities for text data using NER and for which models are supported.

**Comment by jackqdyulei** [comment]
Hi to clarify a bit. 

1) you want detected the NER, for example: Name(e.g. Obama), Location(e.g. London) right? Any other type?
2) Do you mean you already have the model? or you want us to provide the model for those usecases?

**Comment by jackqdyulei** [comment]
Close because of inactivity. Feel free to reopen it with the clarification answers.
