### ISSUE TITLE
[Bug report] Cannot scan one-digit barcode

### ISSUE THREAD

**Issue by jude-pinto** [googlesamples/mlkit#659]
**Describe the bug**
The ML Kit sample app cannot recognize a Code-128 barcode that is only one-digit. See screenshots:
| 1-digit barcode | 2-digit barcode |
| ----------- | ----------- |
| ![1-digit-fails](https://user-images.githubusercontent.com/80074077/234079242-18e22e5e-05d3-4c9e-af67-7526621070cd.jpg) | ![2-digit-works](https://user-images.githubusercontent.com/80074077/234079250-a14d85a5-4045-4cee-b2b6-2da98efa2b2f.jpg) | 

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to https://barcode.tec-it.com/en/Code128?data=aa
2. Open the ML Kit sample app: https://github.com/googlesamples/mlkit
3. From the bottom menu, select `Barcode Scanning`
4. Try to focus on the barcode shown on the webpage from Step 1
5. Notice the sample app recognizes the **2-digit barcode**
6. Change the barcode on the webpage in Step 1 from `aa` to `a`
7. Try to focus on the _new_ barcode
8. Notice the sample app does **NOT** recognize the **1-digit barcode**

**Expected behavior**
The sample should recognize the one-digit barcode

**SDK Info:**
 - `com.google.mlkit:barcode-scanning:17.1.0`

**Smartphone:**
- Physical Device. Samsung Galaxy S20 Ultra. Android 12

**Comment by zhouyiself** [comment]
Hi, one-digit barcode is not supported as mentioned in the "Key capabilities" section.
https://developers.google.com/ml-kit/vision/barcode-scanning#key_capabilities
