### ISSUE TITLE
couldn't find "libbarhopper_v3.so"

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [googlesamples/mlkit#663]
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.scan.lens-0jPNRELAyehNJBII1WkDQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.scan.lens-0jPNRELAyehNJBII1WkDQQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libbarhopper_v3.so"

my sdk version:17.1.0

**Comment by zhouyiself** [comment]
Duplicate of #681
