### ISSUE TITLE
Even after covering your eyes or nose or mouth, it give the exact contour points and landmarks

### ISSUE THREAD

**Issue by AshokArya1711** [googlesamples/mlkit#667]
Even after covering your eyes or nose or mouth, it give the points and detecting all of them

**To Reproduce**
1. Go to Camera Preview
2. Check Eyes, Nose, Mouth contours
3. Then Hide anyone of these
4. Still it gives contours also FaceLandmark

**Expected behavior**
After hide it should not give contours or landmarks

**SDK Info:**
com.google.mlkit:face-detection:16.1.5

**Smartphone:**
Samsung A13, Oppo A54

**Development Environment:**
Android Studio

**Comment by jackqdyulei** [comment]
Thanks for the report! We will record it however this is the current intended behavior. It might be useful to provide a visibility field for each point/contour.

For everyone else who need this new functionality, please leave comment so we can better prioritize it.

**Comment by manish89arya** [comment]
@jackqdyulei  It would be great if we can have a functionality around what @AshokArya1711  has mentioned.

**Comment by FaceAI** [comment]
issue closed, MLKit support this function now ? 

@manish89arya @jackqdyulei @AshokArya1711 @sheepmaster
