### ISSUE TITLE
[Feature request] LinkFirebase does not support Firebase SDK V10 for iOS

### ISSUE THREAD

**Issue by yamamotokotaro** [googlesamples/mlkit#679]
**What's your feature request? Please describe.**
I am developing an app using Flutter and when I add LinkFirebase to my podfile to download ML Kit models from Firebase ML, I get an error. The reason for the error was that LinkFirebase does not support V10 of the Firebase Apple SDK, but only up to V9. do you have any plans to make it support V10 of the Firebase Apple SDK?

**Mobile environment**
IOS

**Additional context**
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In snapshot (Podfile.lock):
    FirebaseCore (= 10.9.0, ~> 10.0, ~> 10.5)

  In Podfile:
    GoogleMLKit/LinkFirebase was resolved to 4.0.0, which depends on
      MLKitLinkFirebase (~> 3.0.0) was resolved to 3.0.0, which depends on
        FirebaseCore (~> 9.0)

    firebase_app_check (from `.symlinks/plugins/firebase_app_check/ios`) was resolved to 0.1.4-1, which depends on
      Firebase/CoreOnly (~> 10.9.0) was resolved to 10.9.0, which depends on
        FirebaseCore (= 10.9.0)

    firebase_app_check (from `.symlinks/plugins/firebase_app_check/ios`) was resolved to 0.1.4-1, which depends on
      FirebaseAppCheck (~> 10.9.0-beta) was resolved to 10.9.0, which depends on
        FirebaseCore (~> 10.0)

    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 3.3.1, which depends on
      Firebase/Crashlytics (= 10.9.0) was resolved to 10.9.0, which depends on
        FirebaseCrashlytics (~> 10.9.0) was resolved to 10.9.0, which depends on
          FirebaseCore (~> 10.5)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `FirebaseCore` inside your development pod `firebase_crashlytics`.
   You should run `pod update FirebaseCore` to apply changes you've made.
CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In snapshot (Podfile.lock):
    GoogleMLKit/MLKitCore (= 4.0.0)

  In Podfile:
    GoogleMLKit/LinkFirebase was resolved to 0.60.0, which depends on
      GoogleMLKit/MLKitCore (= 0.60.0)

    google_mlkit_object_detection (from `.symlinks/plugins/google_mlkit_object_detection/ios`) was resolved to 0.7.0, which depends on
      GoogleMLKit/ObjectDetectionCustom (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GoogleMLKit/MLKitCore` inside your development pod `google_mlkit_object_detection`.
   You should run `pod update GoogleMLKit/MLKitCore` to apply changes you've made.

**Comment by KavinduDissanayake** [comment]
@bcdj  @yamamotokotaro  @sheepmaster   @pentiumao  any update ?

**Comment by KavinduDissanayake** [comment]
Since more than one year still hasn't give an update for ios why are you guys doing this?

**Comment by bcdj** [comment]
This issue should have been fixed in the latest release (https://developers.google.com/ml-kit/release-notes).
