### ISSUE TITLE
Request for Swift Package Manager support

### ISSUE THREAD

**Issue by Vlastelin1** [googlesamples/mlkit#683]
Request for Swift Package Manager support

https://github.com/googlesamples/mlkit/issues/180

**Comment by miworking3** [comment]
I'm afraid we don't have a plan to support SPM in the recent future(at least in Q3).

**Comment by milobird** [comment]
Bizarre 🤷‍♂️

**Comment by john-work-ios** [comment]
But why???

**Comment by vanderlin** [comment]
:(
