### ISSUE TITLE
Request for Android Jetpack Compose examples

### ISSUE THREAD

**Issue by pwojtowicz-rg** [googlesamples/mlkit#686]
Can you add examples for Android Jetpack Compose which is so widely advertised, but on the other hand is missing a lot of usage examples?

Thank you!

**Comment by ai-plays** [comment]
The Jetpack Compose is a general tool for UI development which is out of the scope of ML Kit which processes data.  They are on two different layers.  https://developer.android.com/jetpack/compose/tutorial could be a good start for learning Compose.
