### ISSUE TITLE
[Feature request] VisionOS support, and yes also simulator on M1

### ISSUE THREAD

**Issue by abbana** [googlesamples/mlkit#691]
**What's your feature request? Please describe.**
Please support MLKit on VisionOS
Please support it to run on a simulator for VisionOS which runs on M1 chip. Physical device won't be available soon

**Mobile environment**
VisionOS

**Additional context**
See above

**Comment by miworking3** [comment]
I'm afraid we don't have a plan to support this in the near future, at least in Q3 of 2023.

**Comment by importRyan** [comment]
@miworking3 Would Google consider making the framework nonfunctional (throw errors or exceptions) on simulator, but thus liberating projects for completely not compiling on arm64?

For context, most of our app does not depend on your framework to work, but we are unable to use CI technologies that require arm64 compilation to automate a bunch of very valuable tests for us.
