### ISSUE TITLE
[Bug report] Poor result quality when running text recognition in Quickstarts/Vision

### ISSUE THREAD

**Issue by hieunguyen2211** [googlesamples/mlkit#692]
**Describe the bug**
When running text recognition in Quickstarts/Vision, the result's quality is really poor. With the same image, the result's quality when running on Android is far better. 

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Run Quickstarts/Vision project
2. Select Text Recognition and select an image from the gallery
3. Click Detect button
4. See the result

**Test data**
 
![10](https://github.com/googlesamples/mlkit/assets/52429592/8bf5a9d6-7303-4bf5-a4d8-bbb8e3a74bcf)

**Result**
<img width="389" alt="Screen Shot 2023-07-04 at 10 24 59" src="https://github.com/googlesamples/mlkit/assets/52429592/70967a4f-4a6e-4c23-b6a9-4dbd646e2032">

Recognized text: 
RECHNUNG
G-STAR RAW
Bess
hn
os200
Desctt
tesme
Eeche
nE CRRORene

**Expected behavior**
The result's quality could be acceptable, at least the same with Android.

**SDK Info:**
pod 'GoogleMLKit/BarcodeScanning', '3.2.0'
pod 'GoogleMLKit/FaceDetection', '3.2.0'
pod 'GoogleMLKit/ImageLabeling', '3.2.0'
pod 'GoogleMLKit/ImageLabelingCustom', '3.2.0'
pod 'GoogleMLKit/ObjectDetection', '3.2.0'
pod 'GoogleMLKit/ObjectDetectionCustom', '3.2.0'
pod 'GoogleMLKit/PoseDetection', '3.2.0'
pod 'GoogleMLKit/PoseDetectionAccurate', '3.2.0'
pod 'GoogleMLKit/SegmentationSelfie', '3.2.0'
pod 'GoogleMLKit/TextRecognition', '3.2.0'
pod 'GoogleMLKit/TextRecognitionChinese', '3.2.0'
pod 'GoogleMLKit/TextRecognitionDevanagari', '3.2.0'
pod 'GoogleMLKit/TextRecognitionJapanese', '3.2.0'
pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

**Note:** This also happens with pods version '4.0.0'

**Smartphone:**
 - Simulator: iPhone 14
 - Simulator OS: iOS 16.1

**Development Environment:**
- IDE Eversion: Xcode 14.1
- Laptop: MacBook Pro (16-inch, 2021)
- Laptop OS: 12.6.7

**Comment by hieunguyen2211** [comment]
I also measure elapsed time for the function **detectTextOnDevice** in **ViewController** and it only takes *0.000166167 seconds*. Is it really fast like that to recognize text or is there any issue here that is related to the poor result? Because that elapsed time is unrealistic.

**Comment by miworking3** [comment]
Currently, ML Kit is not frequently updating the model for iOS SDKs as Android SDKs, so a discrepancy between iOS and Android implementations can be expected.
