### ISSUE TITLE
Is it possible to detect faces during video playback?

### ISSUE THREAD

**Issue by JamesTongBussiness** [googlesamples/mlkit#694]
Thanks for ML Kit team, now we can detect faces in images and video easily.

I think that it is possible to detect human faces in real time when shooting video with a camera, but is it possible to detect faces with mlkit even during video playback? 

It seems that it is necessary to use the `captureOutput(_, DidOutput:from:)` function of `AVCaptureVideoDataOutputSampleBufferDelegate` when processing video with mlkit, but it is possible to execute that function when playing video with AVPlayer?

If it is possible, please let me know the sample code or how to implement it.

Thanks.

**Comment by miworking3** [comment]
Please refer to Apple's doc on how to get the frames while playing a video and send them to ML Kit on Face Detection. Thanks.
