### ISSUE TITLE
Barcode Scanning is not working on Devices Managed by MDM- Android

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [googlesamples/mlkit#697]
**Describe the bug**
Barcode Scanning is not working on Devices Managed by MDM-Android 

We have using MLKit for Bar code and QR code Scanning, But one of our Customer have disabled the Play services on their devices, and Barcode scanning is not working.

Is there any way we can support ML Kit Barcode on the devices where there is no google  Play services

**Comment by zhouyiself** [comment]
Hi, you can use the bundled version which doesn't require google play services. com.google.mlkit:barcode-scanning
https://developers.google.com/ml-kit/vision/barcode-scanning/android
