### ISSUE TITLE
[Bug report] Encountering SSL Error While Downloading Offline Model via MLKit

### ISSUE THREAD

**Issue by jeasonxiexie** [googlesamples/mlkit#698]
I'm encountering an issue while trying to download an offline model via MLKit.

When initiating the download for the translation model, I'm receiving an error message stating that the model cannot be downloaded from the server. I observed an SSL error when my browser attempted to access a specific URL where the offline model is located:

https://r3---sn-j5o76n76.gvt1-cn.com/edgedl/translate/offline/v5/high/r29/en_es.zip?cms_redirect=yes&mh=30&mip=120.198.210.174&mm=28&mn=sn-j5o76n76&ms=nvh&mt=1689298353&mv=m&mvi=3&pl=23&rmhost=r4---sn-j5o76n76.gvt1-cn.com&shardbypass=sd&smhost=r1---sn-j5o7dn7d.gvt1-cn.com,%20NSErrorFailingURLKey=https://r3---sn-j5o76n76.gvt1-cn.com/edgedl/translate/offline/v5/high/r29/en_es.zip?cms_redirect=yes&mh=30&mip=120.198.210.174&mm=28&mn=sn-j5o76n76&ms=nvh&mt=1689298353&mv=m&mvi=3&pl=23&rmhost=r4---sn-j5o76n76.gvt1-cn.com&shardbypass=sd&smhost=r1---sn-j5o7dn7d.gvt1-cn.com

When I try to download directly from this link using Google Chrome, I'm also encountering an SSL error. My suspicion is that this SSL error is causing the download to be blocked by iOS.

**Comment by jeasonxiexie** [comment]
![Simulator Screenshot - iPhone 14 Plus - 2023-07-16 at 11 07 48](https://github.com/googlesamples/mlkit/assets/95195927/de5175d1-b811-4f1b-9f41-c32e7addfe40)

**Comment by qiantao94** [comment]
Same issue

**Comment by trumanicu** [comment]
same issue!!!!!!!!!!!!!

**Comment by jeasonxiexie** [comment]
any progress on this issue?

**Comment by trumanicu** [comment]
as u know, nothing

**Comment by copperdong** [comment]
same issue
