### ISSUE TITLE
[Bug Report] Incorrect translation result text having @ or URL (http/https) 

### ISSUE THREAD

**Issue by vgawli** [googlesamples/mlkit#703]
I'm encountering an issue while trying to translate the string which contains @ or URL (http/https) 

e.g.
Input Text - @p1user : Test Message with mention
Target Langauge - FR
Output Text - @ P1User: Message de test avec mention 
Issue - after translation, space is getting added between @ & adjacent text (here p1user).  also p1user is getting translated to P1User
**Expected Output**  - @p1user  : Message de test avec mention

Input Text - Test message with mention and link - <br> https://newqapawan.mangopulse.com/mlink/event/NjY1<br>https://newqapawan.mangopulse.com/mlink/feed/NDkzMjA<br>  @akashm      @anilu  
Target Langauge - FR
Output Text - Message de test avec mention et lien - <br> https://newqapawan.mangopulse.com/mlink/event/njy1 <br> https://newqapawan.mangopulse.com/mlink/feed/ndkzmja <br> @Akashm @anilu 
Issue - after translation URLs are getting translated to small case & @akashm is getting translated to @Akashm
**Expected Output**  - Message de test avec mention et lien - <br> https://newqapawan.mangopulse.com/mlink/event/njy1 <br> https://newqapawan.mangopulse.com/mlink/feed/ndkzmja <br> @akashm      @anilu  

Is there any flag by which we can ask translator to do not translate the specific string e.g using any regular expresssion ?

**Comment by jackqdyulei** [comment]
Thanks for reporting it! At this moment we only fix offensive translations. Sometimes model could generate wrong translations like this. We continue to improve our models to work better on such input.
