### ISSUE TITLE
[Feature request] Facial makeup and beauty features?

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#706]
**What's your feature request? Please describe.**
ML Kit is great. But can I use it to do makeups and beauty filters, like eye enlargement, eye color change, skin tone enhancements, etc? If not, are there any official Android ML libraries to achieve that?

**Mobile environment**
Android

**Comment by zhouyiself** [comment]
Thanks for the request! This is not currently in our radar but we're happy to add it into our long-term plan list.
