### ISSUE TITLE
[Feature request] Load model weights locally

### ISSUE THREAD

**Issue by june94** [googlesamples/mlkit#707]
Hello! Is there any storage or source from where I could download tflite-file, model+weights (for example, for barcode-scanner model) locally to my computer? For research and fine-tuning purposes. Thanks in advance!

**Mobile environment**
both, doesn't matter

**Comment by ai-plays** [comment]
Hi June94,

The model ML Kit is using is not open-sourced.

You could find some models in https://tfhub.dev/
