### ISSUE TITLE
[Feature request] Loading GLB model on face in realtime camera with proper face animations using ml-kit

### ISSUE THREAD

**Issue by boy-sincere** [googlesamples/mlkit#709]
**What's your feature request? Please describe.**
I'm using google ml-kit for face detection and animation. I want to load a GLB face model on user's face in realtime camera. Currently I'm using sceneform for loading the glb model and for animations I'm using google ml-kit but I'm not getting proper animations and I'm getting only below mentioned animations which I'm setting to morph targets for model:

    fun tryAcquireCameraImage(it: Frame) {
        try {
            val image = it.acquireCameraImage()
            val frame = MLFrame.fromMediaImage(image, 0)
            analyzer.asyncAnalyseFrame(frame).addOnSuccessListener { faces ->

                if (faces.isNullOrEmpty()) {
                    image.close()
                    return@addOnSuccessListener
                }

                val face = faces[0]
                val smile = face.emotions?.smilingProbability
                val rightEyes = face.features.leftEyeOpenProbability
                val leftEyes = face.features.rightEyeOpenProbability

                Log.e("++++++++", "smile $smile")
                Log.e("++++++++", "left $rightEyes")
                Log.e("++++++++", "right $leftEyes")

                Log.e(TAG, "" + face?.coordinatePoint)
                weights[8] = 1 - leftEyes
                weights[9] = 1 - rightEyes
                weights[55] = smile ?: 0F

//                weights[43] = smile ?: 0F
//                weights[44] = smile ?: 0F
                image.close()

                if (rm != null && rendableManager != null) {
                    rm?.let { rendableManager?.setMorphWeights(it, weights, 0) }
                }

//
            }

        } catch (e: java.lang.Exception) {
            Log.e("++++++++", "image error " + e.message)
            e.printStackTrace()
        }

    }

ML-Kit settings:
var setting: MLFaceAnalyzerSetting = MLFaceAnalyzerSetting.Factory() // Set whether to detect key face points.
        .setKeyPointType(MLFaceAnalyzerSetting.TYPE_KEYPOINTS) // Set whether to detect facial features and expressions.
        .setFeatureType(MLFaceAnalyzerSetting.TYPE_FEATURES) // Enable only facial expression detection and gender detection.
        .setFeatureType(MLFaceAnalyzerSetting.TYPE_FEATURE_EMOTION or MLFaceAnalyzerSetting.TYPE_FEATURE_GENDAR) // Set whether to detect face contour points.
        .setShapeType(MLFaceAnalyzerSetting.TYPE_SHAPES) // Set whether to enable face tracking and specify the fast tracking mode.
        .setTracingAllowed(
            true,
            MLFaceAnalyzerSetting.MODE_TRACING_FAST
        ) // Set the speed and precision of the detector.
        .setPerformanceType(MLFaceAnalyzerSetting.TYPE_PRECISION) // Set whether to enable pose detection (enabled by default).
        .setPoseDisabled(true)
        .create() 

    private var analyzer = MLAnalyzerFactory.getInstance().getFaceAnalyzer(setting)

https://github.com/googlesamples/mlkit/assets/58633636/20aee3a1-0816-49ee-acd4-486291836b38

**Mobile environment**
Android

**Additional context**
Also my face model getting cropped from both ears, If someone can help me fixing that will be appreciated. Thanks

**Comment by jackqdyulei** [comment]
HI [boy-sincere](https://github.com/boy-sincere), can you clarify what's your current problem and expected behavior?(e.g. smilingProbability is incorrect; latency too high)

```Also my face model getting cropped from both ears```
For that part sorry it is not supported in ML Kit Face detection currently.
