### ISSUE TITLE
Brightness adjustment using MLKit

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#715]
I would like to implement automatic brightness adjustment feature on Camera, like what Zoom and Teams do in video meetings. Can I do that with MLKit on Android? 
Any hints or sample codes would be great.

![Adjust Microsoft Teams camera brightness](https://handsontek.net/images/Teams/Camera/Adjust%20brigtness.gif)

**Comment by zhouyiself** [comment]
Sorry, ML Kit doesn't support this currently.
