### ISSUE TITLE
[Bug report] Error when use face detection

### ISSUE THREAD

**Issue by manuelddahmen** [googlesamples/mlkit#717]
I'm using Android 12 and Android 13 (on avd)
 I have a problem with face detection mlkit. It was working when targeting android 13. Now I updated to target Android 14 and libraries.
  E  Error preloading model resource
com.google.mlkit.common.MlKitException: Waiting for the face module to be downloaded. Please wait.
com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:10)
                                                                                                    	
    implementation 'com.google.mlkit:vision-common:17.3.0'
    implementation 'com.google.android.gms:play-services-mlkit-face-detection:17.1.0'

I don't know if I had to remove a dependencies?

  <meta-data
                android:name="com.google.android.gms.vision.DEPENDENCIES"
                android:value="face"
                />

To Reproduce:

            FaceDetectorOptions highAccuracyOpts =
                    new FaceDetectorOptions.Builder()
                            .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
                            .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
                            .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_NONE)
                            .setContourMode(FaceDetectorOptions.CONTOUR_MODE_ALL)
                            .build();

            InputImage inputImage = InputImage.fromBitmap(bitmap, 0);

            mCanvas = new Canvas(mCopy);

            FaceDetector client = FaceDetection.getClient(highAccuracyOpts);
            client.process(inputImage).addOnSuccessListener(faces -> {
                mFaces = faces;

Windows 11, Android Studio Hedgebow

**Comment by manuelddahmen** [comment]
I forgot to put downloaded model:

    implementation "com.google.mlkit:face-detection:16.1.5"

**Comment by jackqdyulei** [comment]
Hi [manuelddahmen](https://github.com/manuelddahmen), thanks for your report!

It seems you have two issues

When you use Face detection(Play services version) and upgrade from Android 13->14, the model cannot be downloaded.
Can you explain what has been changed which triggered this issue, for example:
1) You changed targetSDK in `build.gradle`, re-install the new apk to the same device, then the face module disappeared and need to be re-downloaded? Or the testing device is brand new and doesn't has face module at the beginning?


`java.lang.NoSuchMethodError`
1) Can you show your full `build.gradle`, I want to see what library & version you included that triggered the crash

**Comment by manuelddahmen** [comment]
1. 
I use the same testing device for 6 months, I change 13->14 yesterday. The error appeared at that moment. Before, when I use "target 13" I didn't have this error.
2.
`def compose_version = '1.5.0'

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'maven-publish'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

if (hasProperty('buildScan')) {
    buildScan {
        termsOfServiceUrl = 'https://gradle.com/terms-of-service'
        termsOfServiceAgree = 'yes'
    }
}

def code = 31460000

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of("11"))
    }
}

android {
    namespace 'one.empty3.feature.app.maxSdk29.pro'
    testNamespace 'one.empty3.apps.test'
    packagingOptions {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}', 'META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt', 'META-INF/ASL2.0', 'META-INF/*.kotlin_module', 'xsd/catalog.xml', 'META-INF/LICENSE.md', 'META-INF/NOTICE.md', 'META-INF/io.netty.versions.properties', 'META-INF/INDEX.LIST']
        }
    }


    //buildToolsVersion "34.0.0"
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.java.srcDirs += 'src/main/java'
    }
    /* bundle {
         storeArchive {
             enable = false
         }
     }*/
    signingConfigs {
        debug {
            storeFile file('C:\\Users\\manue\\keystore')
            storePassword 'faeeagrzdsd'
            keyAlias 'manuel'
            keyPassword 'faeeagrzdsd'
        }
        release {
            storeFile file('C:\\Users\\manue\\keystore')
            storePassword 'faeeagrzdsd'
            keyAlias 'manuel'
            keyPassword 'faeeagrzdsd'
        }
    }
    lint {
        baseline = file("lint-baseline.xml")
    }
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
// With compileOptions the warning disappears
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.4.2'
    }

    kotlinOptions {
        jvmTarget = "11"
    }


    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            debuggable false
            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }

        debug {
            debuggable false
            buildConfigField "Boolean", "DEBUG_MODE", "false"
        }
    }

    configurations {
        all*.exclude group: 'xpp3', module: 'xpp3'
        all*.exclude group: 'xml-apis', module: 'xml-apis'
        all*.exclude group: 'net.sf.kxml', module: 'kxml2'
        all*.exclude group: 'xmlpull', module: 'xmlpull'
        all*.exclude group: 'com.sun.activation', module: 'javax.activation'
        //all*.exclude group: 'org.jetbrains.kotlin', module: 'kotlin-compiler-embeddable'
        //all*.exclude group: 'org.jetbrains.kotlin', module: 'kotlin-gradle-plugin-api'
        all*.exclude group: 'org.jetbrains.kotlin', module: 'kotlin-gradle-plugin'
        //all*.exclude group: 'org.jetbrains.kotlin', module: 'kotlin-build-common'
        all {
            resolutionStrategy {
                //force 'xpp3:xpp3:1.1.4c'
                force 'jakarta.activation:jakarta.activation-api:1.2.1'
                //force 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.8.0'
                //force 'org.jetbrains.kotlin:kotlin-build-common:1.8.0'
                //force 'net.sf.kxml:kxml2:2.3.0'
                //force 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'
                //force ' xmlpull:xmlpull:1.1.3.1'
                //force 'org.jetbrains.kotlin:kotlin-compiler:1.8.0'
                //force 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'
                // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
                //force group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: '1.8.0'
// https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
                //force group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.8.0'

            }
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    buildFeatures {
        viewBinding true
        dataBinding true
        compose true
    }
    defaultConfig {
        vectorDrawables {
            useSupportLibrary true
        }
        applicationId "one.empty3.feature.app.maxSdk29.pro"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        targetSdkVersion 34
        minSdkVersion 29
        compileSdkVersion 34
        JavaVersion.VERSION_11
        versionCode code
        versionName "4.0"
        kotlin {
            version "1.8.0"
        }
        /*ndk {
            debugSymbolLevel 'SYMBOL_TABLE'
        }*/
        signingConfig signingConfigs.release
    }
}

dependencies {
    // When using a MDC theme
    implementation "com.google.android.material:compose-theme-adapter:1.2.1"

    implementation "androidx.compose.ui:ui:$compose_version"
//    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation "androidx.compose.material3:material3:1.1.1"
    implementation "androidx.compose.material3:material3-window-size-class:1.1.1"
    implementation "com.android.support:support-v4:27.1.0"
    // When using a AppCompat theme
    //implementation "com.google.accompanist:accompanist-appcompat-theme:0.25.1"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    //implementation 'androidx.activity:activity-compose:1.3.1'
    //implementation 'androidx.compose.compiler:compiler:1.2.0-alpha02'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.0'
    //implementation "com.android.support:recyclerview-v7:28.0.0"
    //implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.16'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    //implementation 'com.google.ar:core:1.32.0'
    implementation 'androidx.activity:activity-compose:1.7.2'
    implementation 'junit:junit:4.13.2'
    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation "androidx.databinding:viewbinding:8.1.0"
    implementation "androidx.databinding:databinding-common:8.1.0"
    implementation "androidx.databinding:databinding-runtime:8.1.0"
    implementation "androidx.databinding:databinding-adapters:8.1.0"
    implementation "androidx.databinding:databinding-compiler:8.1.0"
    implementation "androidx.databinding:databinding-ktx:8.1.0"
    implementation "com.google.android.datatransport:transport-runtime:3.1.9"
    implementation "com.google.android.material:compose-theme-adapter:1.2.1"
    implementation "androidx.compose.ui:ui:1.5.0"
    implementation "androidx.compose.material:material:1.5.0"
    implementation 'androidx.room:room-common:2.5.2'
    implementation 'androidx.room:room-runtime:2.5.2'
    implementation 'androidx.camera:camera-video:1.2.3'
    implementation 'androidx.camera:camera-lifecycle:1.2.3'
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.9.8'
    implementation 'androidx.camera:camera-camera2:1.2.3'
    implementation "com.google.guava:guava:31.0.1-jre"
    implementation 'androidx.work:work-runtime-ktx:2.8.1'
    implementation 'com.google.mlkit:vision-common:17.3.0'
    implementation "com.google.mlkit:face-detection:16.1.5"
    implementation 'com.google.android.gms:play-services-mlkit-face-detection:17.1.0'
    implementation platform('androidx.compose:compose-bom:2023.08.00')
    // Unit testing
    testImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation 'androidx.test:rules:1.5.0'
    testImplementation 'androidx.test:runner:1.5.2'
    testImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    testImplementation 'org.robolectric:robolectric:4.7'
    implementation 'com.google.android.material:material:1.9.0'
    // Instrumented testing
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test:core:1.5.0"
    androidTestImplementation "androidx.test:rules:1.5.0"
    androidTestImplementation "androidx.test:runner:1.5.2"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.5.1"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    annotationProcessor 'androidx.room:room-compiler:2.5.2'
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
    implementation "androidx.core:core-ktx:1.10.1"
    implementation("com.jgoodies:jgoodies-common:1.8.1")
    // Add dependencies.
    //implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.github.yukuku:ambilwarna:2.0.1'
    implementation 'com.squareup.okhttp3:okhttp:4.9.2'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "one.empty3"
            artifactId = "android_app"
            version = "0.9-SNAPSHOT"
        }
    }
    repositories {

        // Check that you have the following line (if not, add it):
        google()  // Google's Maven repository
        maven {
            url "https://maven.pkg.jetbrains.space/empty3/p/empty3/maven"
            credentials {
                username = spaceUsername
                password = spacePassword
            }
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

`

**Comment by manuelddahmen** [comment]
I think perhaps it's the okhttp library that is malicious?
https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/4.9.2

  implementation 'com.squareup.okhttp3:okhttp:4.9.2'
  implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'

**Comment by jackqdyulei** [comment]
Hi I found a few things:

1) In your build.gradle you included `com.google.android.datatransport:transport-runtime:3.1.9`, is that truly needed, in ML Kit it will pull in same library however version is `2.2.6`. Maybe that's the reason why you have the crash in datatransport

2) In your application you need to select between `play-services-mlkit-face-detection` and `face-detection`. If you include both, it will use `face-detection` under the hood. For more info please check https://developers.google.com/ml-kit/vision/face-detection/android

**Comment by manuelddahmen** [comment]
Yes, that was it.

`dependencies {
    // When using a MDC theme
    implementation "com.google.android.material:compose-theme-adapter:1.2.1"

    implementation "androidx.compose.ui:ui:$compose_version"
//    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation "androidx.compose.material3:material3:1.1.1"
    implementation "androidx.compose.material3:material3-window-size-class:1.1.1"
    implementation "com.android.support:support-v4:27.1.0"
    // When using a AppCompat theme
    //implementation "com.google.accompanist:accompanist-appcompat-theme:0.25.1"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    //implementation 'androidx.activity:activity-compose:1.3.1'
    //implementation 'androidx.compose.compiler:compiler:1.2.0-alpha02'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.0'
    //implementation "com.android.support:recyclerview-v7:28.0.0"
    //implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.16'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    //implementation 'com.google.ar:core:1.32.0'
    implementation 'androidx.activity:activity-compose:1.7.2'
    implementation 'junit:junit:4.13.2'
    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation "androidx.databinding:viewbinding:8.1.0"
    implementation "androidx.databinding:databinding-common:8.1.0"
    implementation "androidx.databinding:databinding-runtime:8.1.0"
    implementation "androidx.databinding:databinding-adapters:8.1.0"
    implementation "androidx.databinding:databinding-compiler:8.1.0"
    implementation "androidx.databinding:databinding-ktx:8.1.0"
    //implementation "com.google.android.datatransport:transport-runtime:3.1.9"
    implementation "com.google.android.material:compose-theme-adapter:1.2.1"
    implementation "androidx.compose.ui:ui:1.5.0"
    implementation "androidx.compose.material:material:1.5.0"
    implementation 'androidx.room:room-common:2.5.2'
    implementation 'androidx.room:room-runtime:2.5.2'
    implementation 'androidx.camera:camera-video:1.2.3'
    implementation 'androidx.camera:camera-lifecycle:1.2.3'
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.9.8'
    implementation 'androidx.camera:camera-camera2:1.2.3'
    implementation "com.google.guava:guava:31.0.1-jre"
    implementation 'androidx.work:work-runtime-ktx:2.8.1'
    //implementation 'com.google.mlkit:vision-common:17.3.0'
    implementation "com.google.mlkit:face-detection:16.1.5"
    //implementation 'com.google.android.gms:play-services-mlkit-face-detection:17.1.0'
    //implementation "com.google.android.gms:play-services-vision:20.1.3"
    //implementation 'com.google.firebase:firebase-ml-vision:24.1.0'
    implementation platform('androidx.compose:compose-bom:2023.08.00')
    // Unit testing
    testImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation 'androidx.test:rules:1.5.0'
    testImplementation 'androidx.test:runner:1.5.2'
    testImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    testImplementation 'org.robolectric:robolectric:4.7'
    implementation 'com.google.android.material:material:1.9.0'
    // Instrumented testing
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test:core:1.5.0"
    androidTestImplementation "androidx.test:rules:1.5.0"
    androidTestImplementation "androidx.test:runner:1.5.2"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.5.1"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    annotationProcessor 'androidx.room:room-compiler:2.5.2'
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
    implementation "androidx.core:core-ktx:1.10.1"
    implementation("com.jgoodies:jgoodies-common:1.8.1")
    // Add dependencies.
    //implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.github.yukuku:ambilwarna:2.0.1'
    //implementation 'com.squareup.okhttp3:okhttp:4.9.2'
    //implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'
}
`
