### ISSUE TITLE
[Bug report] iOS - Valid Aztec barcode not recognised in image

### ISSUE THREAD

**Issue by VaryHice** [googlesamples/mlkit#720]
**Describe the bug**

I have Aztec barcode image which is pretty sharp and clean:

![Azteccode](https://github.com/googlesamples/mlkit/assets/67470341/266b0f36-40ed-494f-9c44-d7b48263ec66)

It contains following text:

> ST00012|Name=УФК по Ивановской области г Иваново|PersonalAcc=03100643000000013300|BankName=УФК ПО МОСКОВСКОЙ ОБЛАСТИ|BIC=044525225|CorrespAcc=40102810645370000025|Sum=21300|SumRub=213|Purpose=Платеж в бюджет|PayeeINN=3728012600|PayerINN=259538055402|DrawerStatus=13|KPP=102601492|CBC=18210102020011000110|OKTMO=46771000|PaytReason=ТП|TaxPeriod=КВ.03.2022|DocNo=0|DocDate=0|TaxPaytKind=0|TechCode=09|ClassNum=11|BirthDate=27062000|ExecId=unCWumC nUzYIdBqaFDP ykRglBg uMLlnVgnCH KSjkSSndnYiKPEHxkpve GihseiYBgaPlOrDAbKrP dPVzEZYjZGYsbCWamgWZ AiWojfzkCGfqAovZ YWaanTOlHhTX dmqIUhcpHOurPb glrXxRLaIgRxotKHRa NZTubpox FzHsMIxzycPfTVnniMNMnhlAVfbCpXXos vkyGQBXNmfNTZOfVyN FVxEWmldRWkWWKPpdFFDpK ppwbxeTSvBgPf gPKpstoGoqlOjXZTtLxqhSqriA pBpikPchrkCjQWonnwCEh

Barcode scanner doesn't see it, with no error, just empty results.

At the same time if generate barcode with same text but another image size, it works:

![Azteccode-2](https://github.com/googlesamples/mlkit/assets/67470341/f85bbfc7-a705-4389-a356-bd9c579ef0d2)

**To Reproduce**

I use following code:

```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any])
{
	scanningQueue.async { [weak self] in
		guard let self = self
		else { return }
		
		let image = info[.originalImage] as? UIImage
		let data = image.flatMap { self.barcodeData(from: $0) }
		
		// proceed with result...
	}
}

func barcodeData(from uiImage: UIImage) -> Data?
{
	let image = VisionImage(image: uiImage)
	image.orientation = uiImage.imageOrientation
	
	return try? barcodeScanner.results(in: image)
		.first?
		.rawData
}
```

**Expected behavior**

Expected that both of these barcodes are recognised successfully.

**SDK Info:**

Version 3.2.0, installed with CocoaPods:

`pod 'GoogleMLKit/BarcodeScanning', '3.2.0'`

**Smartphone:**

iPhone 12 mini, iOS 15.7.1. Same problem on some other devices, don't know exact models and OS versions, mostly iOS 15 and 16.

**Development Environment:**

Xcode 14.1, MacBook Pro M2, macOS 13.0.1

**Comment by zhouyiself** [comment]
This is a high density barcode so high resolution may be needed to recognize.
https://developers.google.com/ml-kit/vision/barcode-scanning/ios#input-image-guidelines
