### ISSUE TITLE
[Feature request] Support for recognizing text in Japanese written vertically

### ISSUE THREAD

**Issue by wrightak** [googlesamples/mlkit#721]
The current Google Cloud Vision APIs, and the deprecated Firebase APIs, for text recognition can handle Japanese text written vertically, from top right to bottom left.

From my testing, MLKit on iOS doesn't appear to support this.

Is this in the roadmap?

**Comment by miworking3** [comment]
I'm afraid this feature won't be supported in the near-term roadmap of ML Kit.
