### ISSUE TITLE
A general question 

### ISSUE THREAD

**Issue by tjasmin111** [googlesamples/mlkit#723]
Do you think I can use ML kit face functions for building face filters like those seen in Snapchat (face retouch, whitening teeth, virtual lipstick, ...)? Or for those I have to use specialized GANs and MLKit can not help there?
I would appreciate some general guidance.

**Comment by jackqdyulei** [comment]
Thanks for the request! We'll put it to our feature request list but may not get to it in short time.

**Comment by tjasmin111** [comment]
Hi @jackqdyulei you commented on my SO question with a link to MediaPipe samples. Can you share that link again? I couldn't find your link. 
https://computergraphics.stackexchange.com/questions/13716/how-to-slim-nose-using-face-mesh
