### ISSUE TITLE
Face mesh for transformation

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#726]
So using MLKit we can get 3D face mesh and landmarks coordinates. Is there any ways to use that for facial transformation and warping? Does MLkit provide any built-in support for that? For instance, making the eyebrows or lips thinner or thicker?

![image](https://github.com/googlesamples/mlkit/assets/5509837/3902fbda-5ca9-4f19-b315-b4fe8c43b85c)

**Comment by jackqdyulei** [comment]
Thanks for comment. Currently we don't have a built-in support for that. Will note it down to prioritize it in future.
