### ISSUE TITLE
[Feature request] Detect eye glasses on the user

### ISSUE THREAD

**Issue by Cascade4183** [googlesamples/mlkit#727]
**Detect Eye-glasses for Face Detection ML-Kit.**
Currently when we run a face with eye-glasses through the face detection model in Android (https://developers.google.com/ml-kit/vision/face-detection) it has a hard time recognizing the eye presence along with its open/close probability. 

If we have this extra field that detects the presence of eye-glasses it will let us handle the situation by letting the user know to remove them.

**Mobile environment**
Android, IOS or both

**Additional context**
The eye open probability ranges from .15 to .85 with eye glasses on and with eyes open. Its possible that the ML Model is having a hard time reading the eye status through the glasses due to reflection.

```
leftEyeOpenProbability=0.62330294, rightEyeOpenProbability=0.6911185
leftEyeOpenProbability=0.58168614, rightEyeOpenProbability=0.50434345
leftEyeOpenProbability=0.29744673, rightEyeOpenProbability=0.31330246
leftEyeOpenProbability=0.2853691, rightEyeOpenProbability=0.43438774
leftEyeOpenProbability=0.24561661, rightEyeOpenProbability=0.35133195
leftEyeOpenProbability=0.16252542, rightEyeOpenProbability=0.22126848
```

**Comment by jackqdyulei** [comment]
Thanks for your feedback. Currently it is not supported however we will note it down.
