### ISSUE TITLE
Blur background?

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#736]
I was looking at the selfie segmentation work. Are there any samples to "blur" the background instead of using a Pink mask? It seems a bit different from the mask approach provided in the sample right now and I need an efficient approach to do that.

**Comment by ai-plays** [comment]
Hi ariannaa, this is a little bit out of the scope of the segmentation API and more related to general image processing.

Personally, I never did it before, but Google Bard gave me some pointers to achieve this via RenderScript or OpenCV.

I asked the following in Bard (https://bard.google.com/): "On Android, with Java, I have a Bitmap image and a mask array matching the size of the Bitmap indicating which part of the Bitmap is background.  What are the options to blur the background area?"

It provides detailed code examples. Sometimes, you need some tweak to the code, but worth trying. Hopefully this helps you speed up finding the solution.
