### ISSUE TITLE
Subject segmentation with ML Kit for Android

### ISSUE THREAD

**Issue by VishalTelgaTech** [googlesamples/mlkit#756]
**Describe the bug**
com.google.mlkit.common.MlKitException: Failed to init module subject segmenter

**Comment by SilverDestiny** [comment]
Hi,

Could you provide more details for the error with full log? The log should contain the cause exception of the error. Thanks!

**Comment by SilverDestiny** [comment]
You mean https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart ? It works for me.

There might be something wrong with your Google Play services on device. I need to check the full log to see what went wrong.

**Comment by jackqdyulei** [comment]
Close because of inactivity, feel free to reopen it with full log. Thanks!
