### ISSUE TITLE
Incorrect translation result

### ISSUE THREAD

**Issue by vellrya** [googlesamples/mlkit#76]
Hello. 
I use "translate" sample with zh -> ru translate path,
There is a special symbol, which, as I think, cause incorrect result.
For example, input:
`天圈【6期免息】Huawei /华为nova7 SE 5G超级快充40W 5g手机智能手机华为手机华`
Output:
`Святейший 【【【【【【【【为 为 为 【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【【`

Can you check this issue?

**Comment by fergushenderson** [comment]
Thanks for the bug report.
I have managed to reproduce the issue and have verified that it is still present.
We will continue to investigate.

**Comment by cs-googler** [comment]
Hi, we have internal request opened for updating the translate model but without a clear timeline yet.
