### ISSUE TITLE
[Feature request] Recommended hardware and USB Camera

### ISSUE THREAD

**Issue by in-jenier** [googlesamples/mlkit#762]
**What's your feature request? Please describe.**
What can be a hardware configuration for pose anche object in STREAM_MODE ?

**Mobile environment**
Android,

**Additional context**
For the USB device I have read all the solutions on the web but there are only customized solutions which always present some problems
There is a simple methoid to use usbCamera with mlkit ?

**Comment by ai-plays** [comment]
The vision mlkit API takes an [InputImage](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage). As long as you can construct an InputImage based on supported formats (see documentation), where the image is from doesn't matter.

For general questions about Android device using external camera, it would be out of the scope of this repo. Maybe you could consider asking under a proper tag in StackOverflow to get more audience.
