### ISSUE TITLE
[Feature request] MLKit and Apple’s new Privacy Manifests

### ISSUE THREAD

**Issue by RogVok** [googlesamples/mlkit#765]
**What's your feature request? Please describe.**
Hello,
starting this spring Apple will require SDK developers to provide a so-called privacy manifest. More info: https://developer.apple.com/videos/play/wwdc2023/10060/

Does Google MLKit plan to include a privacy manifest in the SDK?

Many thanks and warm regards!

**Mobile environment**
iOS

**Comment by miworking3** [comment]
Yes, ML Kit is planning a public release in Q1 to address this problem, please stay tuned.

**Comment by Shrirama-Upadhya-A** [comment]
Do we have any updates from Google regarding this? Are there any threads that we can refer to?

**Comment by miworking3** [comment]
The new release will come out this week.

**Comment by RogVok** [comment]
Update: looks like GoogleMLKit v 6.0.0 with a new privacy manifest has been released: https://developers.google.com/ml-kit/release-notes

**Comment by 224XS** [comment]
I tried to update to MLKit Translate 5.0.0 within the new 7.0.0 MLKit for iOS, but the update fails repeatedly.

when i run pod update I get:
[!] CDN: trunk URL couldn't be downloaded: 
Analyzing dependencies
https://cdn.cocoapods.org/Specs/b/8/1/MLKitTranslate/5.0.0/MLKitTranslate.podspec.json 
Response: Failure when receiving data from the peer

The pod spec file appears to actually be intact at that URL.
Any solutions?
