### ISSUE TITLE
MLKit running on GPU?

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#768]
I believe that MLKit always runs on GPU, is that correct? Is it possible that it may not? Is there a flag or settings to force it run on GPU?

**Comment by SilverDestiny** [comment]
Which ML Kit feature are you using? ML Kit is mostly running on CPU

**Comment by arianaa30** [comment]
MLKit vision. I want to use the segmentation model.

**Comment by SilverDestiny** [comment]
Which segmentation feature? Subject or selfie segmentaion?

**Comment by arianaa30** [comment]
Selfie Segmentation. In Android

**Comment by ai-plays** [comment]
Hi arianaa30,

Selfie Segmentation is running on CPU only.

The only ML Kit feature with GPU acceleration today is Pose Detection. Please see more details here https://developers.google.com/ml-kit/vision/pose-detection/android#hardware_config

**Comment by arianaa30** [comment]
Oh I didn't expect it at all. It's a TF model..why not using the gpu delegate to run? Please consider adding this option as a feature.

**Comment by ai-plays** [comment]
There are actually some other complications that when running on GPU, a feature may be slower, less accurate than CPU or even result in crashes. It varies on different devices. 

For Selfie Segmentation, it is already using multi-thread CPU acceleration today.
