### ISSUE TITLE
Using #pod 'GoogleMLKit/FaceDetection' causes all Firebase libraries to downgrade

### ISSUE THREAD

**Issue by nothingimportant55** [googlesamples/mlkit#77]
When I add #pod 'GoogleMLKit/FaceDetection' and do an update, nearly all of my firebase (and some other google) pods all downgrade. Here is the output from the terminal:

Installing Firebase 6.23.0 (was 6.27.0)
Installing FirebaseABTesting 3.2.0 (was 3.3.0)
Installing FirebaseAnalytics 6.4.2 (was 6.6.1)
Installing FirebaseAnalyticsInterop (1.5.0)
Installing FirebaseAuth 6.5.3 (was 6.6.0)
Installing FirebaseAuthInterop (1.1.0)
Installing FirebaseCore 6.6.7 (was 6.8.0)
Installing FirebaseCoreDiagnostics 1.2.1 (was 1.4.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseDynamicLinks 4.0.8 (was 4.1.0)
Installing FirebaseInAppMessaging 0.18.0 (was 0.21.0)
Installing FirebaseInstallations 1.3.0 (was 1.4.0)
Installing FirebaseInstanceID 4.3.4 (was 4.4.0)
Installing FirebaseMLCommon 0.19.0 (was 0.20.1)
Installing FirebaseRemoteConfig 4.5.0 (was 4.6.0)
Installing FirebaseStorage 3.6.1 (was 3.7.0)
Installing Google-Mobile-Ads-SDK 7.62.0 (was 7.61.0)
Installing GoogleAppMeasurement 6.4.2 (was 6.6.1)
Installing GoogleDataTransport 3.3.1 (was 6.2.1)
Installing GoogleDataTransportCCTSupport 1.3.1 (was 3.2.0)
Installing GoogleMLKit (0.61.0)
Installing GoogleUtilities 6.7.0 (was 6.6.0)
Installing GoogleUtilitiesComponents (1.0.0)
Installing MLKitCommon (0.61.0)
Installing MLKitFaceDetection (0.61.0)
Installing MLKitVision (0.61.0)
Installing nanopb 0.3.9011 (was 1.30905.0)

When I remove that one line (#pod 'GoogleMLKit/FaceDetection') and "pod update", they all ugprade again.

Thanks

**Comment by calren** [comment]
Hey @nothingimportant55 , thanks for reporting this! We are actively working on a fix for this. I'll be sure to update this thread with any updates!

**Comment by swiyu** [comment]
It is already fixed with a patch release a couple of days ago. See  https://stackoverflow.com/questions/62885369/using-googlemlkit-0-61-0-thru-cocoapods-is-downgrading-firebase-libs-to-6-20-0

**Comment by calren** [comment]
Hey @nothingimportant55 , since this issue is fixed now, I'm going to go ahead and close this PR. Thanks!
