### ISSUE TITLE
Object detection and Tracking labels

### ISSUE THREAD

**Issue by WildSpirit007** [googlesamples/mlkit#78]
Hello, 
I tried the Object Detection sample. it works fine. However, I have two questions:
1- How can we get the tracking object label?
2- there is labels.txt file. Where is it used?

The file looks like coco dataset labels. My aim is to label each tracked object with its label.

Thank you

**Comment by swiyu** [comment]
The Object Detection and Tracking feature has a build-in classifier to label the object into several pre-defined labels. See here https://developers.google.com/ml-kit/vision/object-detection/android#3.-process-the-image

If you want to use a custom classification model to label the object based on your use case, you could get models from TFHub or  build your own, and then use custom model in ODT. Details here: https://developers.google.com/ml-kit/vision/object-detection/custom-models/android
