### ISSUE TITLE
MLKit change logs?

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mlkit#780]
Where to see change logs for MLKit features? Say what changed in 16.0.0-beta5 for segmentation-selfie?

**Comment by ai-plays** [comment]
You can find detailed release notes in https://developers.google.com/ml-kit/release-notes

If not mentioned specifically, it means it is just for internal version consistency, and there shouldn't be public effect for you.

**Comment by tjasmin111** [comment]
I saw this page. But it only mentions this: No change logs included.

February 20, 2024
This release includes new features and improvements.

**Comment by arianaa30** [comment]
I saw this page. But it only mentions this: No change logs included.

February 20, 2024
This release includes new features and improvements.

**Comment by ai-plays** [comment]
It also says

New features
  On Android, added new Document Scanner API which provides a scanning flow with both UI and ML logic.
Improvements
  On Android, fixed security vulnerability caused by older version of the play-services-basement dependency.

These are what I referred to.
