### ISSUE TITLE
Requesting pages 50 but able to scan only 10 pages

### ISSUE THREAD

**Issue by kiranNanda** [googlesamples/mlkit#782]
I am entering 50 pages in number of pages but when start scanning + sign hides after 10 pages scan. Storage of App get increased in MBs how to manage this .

**Comment by ai-plays** [comment]
I assume you are talking about the document scanner API. (Please consider following the issue template so we can save round-trip for info collection).

I couldn't reproduce this issue. Does it happen every time for you?

For storage increase, it could be the images being scanned. The scanning API returns the Uri for the result. After using, you can delete the file pointed by the Uri to free space.

**Comment by kiranNanda** [comment]
Yes it's happening every time. Whatever page number I entered + button
disappeared after 10 pages scan.

**Comment by lipenny000** [comment]
@kiranNanda I supposed you were using api https://developers.google.com/android/reference/com/google/mlkit/vision/documentscanner/GmsDocumentScannerOptions.Builder#setPageLimit(int) to set the page limit to 50. 

Without setting page limit or limit other than 50, does the issue happen too?

How do you reproduce the issue? Using MLKit document scanner demo app or your own app? If it's your own app, do you mind sharing the code snippets about the setting of GmsDocumentScannerOptions? 

What hardware did you see this issue happen? Have you tried different device and can also reproduce the same issue?

**Comment by kiranNanda** [comment]
Thank you lipenny000 it worked for me
