### ISSUE TITLE
[ML Kit Document scanner] Compatibility issue?

### ISSUE THREAD

**Issue by RoberFranko** [googlesamples/mlkit#791]
I just tried the new document scanner api and tested it on several devices and works perfectly fine, until I started testing it in recent devices. All devices and emulators with API34 don't seem to run it. Checking the log cat theres no errors, nor anything that seems to be incorrect. when I press the scan button does not crash, nor do anything, like if there was no action there.

Any thoughts about this? If you need my code I am able to share it.

Kind regards

**Comment by ai-plays** [comment]
Hi RoberFranko,

I just tested on API34 and it worked fine for me.

For anyone seeing similar issues, could you please upvote this issue and share more details if you could see any related logs?

**Comment by RoberFranko** [comment]
> Hi RoberFranko,
> 
> I just tested on API34 and it worked fine for me.
> 
> For anyone seeing similar issues, could you please upvote this issue and share more details if you could see any related logs?

It's quite strange but i have tested it again with the same code that i had and with the same devices and emulators, weirdly it works now. Not sure why. But thanks anyway

**Comment by ai-plays** [comment]
Glad it works now.
