### ISSUE TITLE
Download translation models

### ISSUE THREAD

**Issue by pri-avhad** [googlesamples/mlkit#81]
I am using Flutter and I want to download the translation models while the app is installed from play store. 
Right now the app only downloads the model when a translation is called but I want them to be downloaded with the app to make it offline.

**Comment by sheepmaster** [comment]
Hi! This doesn't sound like an issue or feature request with the sample app, but like a question that would be better suited e.g. on StackOverflow. If you tag your question with `[https://stackoverflow.com/questions/tagged/google-mlkit](google-mlkit)`, Google engineers are monitoring the tag and are likely to respond there. You can also comment the URL of the question here to make it easier to find. 

Thanks!
