### ISSUE TITLE
MLkit face detection model

### ISSUE THREAD

**Issue by BehnazDibayee** [googlesamples/mlkit#82]
Hi
I want to get the face detection model (which I'm wondering if it is a tflite model or sth else?) that has been used in MLkit face detection and test it on my pc for some accuracy checking.

where can I find the pure model to download?
Is it a tflite model or not?

**Comment by swiyu** [comment]
ML Kit face detection is not a single model, but a list of models with some binary code for image processing. So there is no easy way to run your own accuracy checking on a PC for ML Kit features. One way you could do is to use Android Emulator on your PC and check about the accuracy.
