### ISSUE TITLE
implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0-beta1' getting initialization error captured Failed to Scan: Feature not available in current version of Google on Android 13. Please Help it's urgent

### ISSUE THREAD

**Issue by kiranNanda** [googlesamples/mlkit#823]
implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0-beta1' getting initialization Failed to Scan: Feature not available in current version of Google on Android 13 OnePlus Nord CE 5G although  working fine for OnePlus Nord 2 Android 13.Please help me I have implemented it my project and issue got rendered on demo mobile.

I am using below code to start scanning:
 GmsDocumentScannerOptions.Builder options =
            new GmsDocumentScannerOptions.Builder()
                    .setResultFormats(
                            GmsDocumentScannerOptions.RESULT_FORMAT_JPEG,
                            GmsDocumentScannerOptions.RESULT_FORMAT_PDF)
                    .setGalleryImportAllowed(false);
    options.setScannerMode(GmsDocumentScannerOptions.SCANNER_MODE_FULL);
    options.setPageLimit(12);

    GmsDocumentScanning.getClient(options.build())
            .getStartScanIntent(this)
            .addOnSuccessListener(
                    intentSender ->
                            scannerLauncher.launch(new IntentSenderRequest.Builder(intentSender).build()))
            .addOnFailureListener(
                    e -> resultInfo = (getString(R.string.error_default_message, e.getMessage())));

It's getting compiler to    .addOnFailureListener(
                    e -> resultInfo = (getString(R.string.error_default_message, e.getMessage())));

OnePlus Nord CE 5G Android 13 although it's working fine for OnePlus Nord 2 Android 13.Please check it at your side too.

**Comment by ai-plays** [comment]
Hi kiranNanda, have you tried to update your Google Play services app to the latest version?

You can update in the following way:

Chrome search "Google Play services". In the result card, there should be a button like "Upgrade" or "Update". Tap to update to the latest version.  Feel free to re-open if you still cannot get it working after that.

**Comment by kiranNanda** [comment]
For document scan sdk what's the relation of Google pay service

**Comment by SantoshInchalakaranji** [comment]
> Thank you ai-plays it's working fine

@kiranNanda What was your play services verision, and for what version you have upgraded. I am also getting similar exception and the document scanner not opening.

com.google.mlkit.common.MlKitException: Feature not available in the current version of the Google Play services
  	at com.google.mlkit.vision.documentscanner.internal.zzb.getStartScanIntent(com.google.android.gms:play-services-mlkit-document-scanner@@16.0.0-beta1:23)
How to solve ,

**Comment by kiranNanda** [comment]
I don't know the version because that error occurred only on one mobile and
that is client mobile I had only told them to  upgrade their mobile Google
play services version

**Comment by SantoshInchalakaranji** [comment]
Thank you so much, The solution worked for me also by upgrading Google play
services from Google play store.

**Comment by kiranNanda** [comment]
Glad it worked.
