### ISSUE TITLE
[Feature request] Support to other platforms

### ISSUE THREAD

**Issue by FMorschel** [googlesamples/mlkit#825]
**What's your feature request? Please describe.**
I want to ask for support for other platforms such as Windows, Mac, Web and Linux so that https://github.com/flutter-ml/google_ml_kit_flutter can also support them.

**Mobile environment**
Other platforms

**Additional context**
I want to use it to parse QRCode images from files and similar use cases.

**Comment by zhouyiself** [comment]
ML Kit is current under maintenance mode so no plan for other platforms in the near future.

**Comment by RogVok** [comment]
@zhouyiself Can you please elaborate on what "under maintenance" means? Will the ML Kit project be discontinued?
