### ISSUE TITLE
[Bug report] Waiting for Subject Segmentation optional module to be downloaded

### ISSUE THREAD

**Issue by KoheiMoroi** [googlesamples/mlkit#829]
**Describe the bug**
```
com.google.mlkit.common.MlKitException: Waiting for the subject segmentation optional module to be downloaded. Please wait.
 at com.google.mlkit.vision.segmentation.subject.internal.zzj.load(com.google.android.gms:play-services-mlkit-subject-segmentation@@16.0.0-beta1:5)
 at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.10.0:4)
 at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
 at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.10.0:2)
 at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.10.0:4)
 at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.10.0:1)
 at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.10.0:2)
 at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
 at java.lang.Thread.run(Thread.java:1012)
```

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to Google Play services settings
2. Clear storage data
3. Install module using Google Play services API `ModuleInstallClient#installModule()`
4. Try subject segmentation as per MLKit's documentation

This exception occurs and persists even after retrying, despite the optional module being present on the device, as verified by Google Play services APIs `ModuleInstallClient#installModule()`.
This issue seems to indicate a problem with the module's recognition or post-installation, leading to a persistent state
where the MLKit API waits indefinitely for the module download.

**Expected behavior**

**SDK Info:**
com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1

**Smartphone:**
 - Device/Simulator: Pixel 5a
 - Device/Simulator OS: API 34

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by SilverDestiny** [comment]
How did you verify by `by Google Play services APIs ModuleInstallClient#installModule()` ?

Could you verify by `ModuleInstallClient#areModulesAvailable` API to make sure the module is available? https://developers.google.com/android/reference/com/google/android/gms/common/moduleinstall/ModuleInstallClient#areModulesAvailable(com.google.android.gms.common.api.OptionalModuleApi...)

**Comment by KoheiMoroi** [comment]
@SilverDestiny 

Certainly, here is the snippet to generate the exception:
```kotlin
fun main() {    
    // Install the module.
    GlobalScope.launch {
        if (installModule()) {
          executeSubjectSegmentation()
        }
    }
}

fun executeSubjectSegmentation() {
  // Code to execute the subject segmentation task with MLKit.
}

// When installing the module using TfLiteClient
suspend fun installModule() = suspendCoroutine {
  val moduleInstallClient = moduleInstall.getClient(context)
  val optionalModuleApi = TfLite.getClient(context)
  val moduleInstallRequest =
    ModuleInstallRequest.newBuilder()
      .addApi(optionalModuleApi)
      .setListener(listener)
      .build()

  moduleInstallClient
    .installModules(moduleInstallRequest)
    .addOnSuccessListener {
      if (it.areModulesAlreadyInstalled()) {
        // Modules are already installed when the request is sent.
        it.resume(true)
        return@addOnSuccessListener
      }
      // continue to download
    }
    .addOnFailureListener {
      // Handle failure…
    }
}
```

When an individual Feature is installed, the subject segmentation works well without exception, immediately after installation is complete.
```kotlin
// When installing the module using individual Feature
suspend fun installModule() = suspendCoroutine {
  val moduleInstallClient = moduleInstall.getClient(context)
  // Specify the optional module API to install.
  val optionalModuleApi = OptionalModuleApi { arrayOf(Feature("mlkit.segmentation.subject", 1)) }
  val moduleInstallRequest =
    ModuleInstallRequest.newBuilder()
      .addApi(optionalModuleApi)
      .setListener(listener)
      .build()

  moduleInstallClient
    .installModules(moduleInstallRequest)
    .addOnSuccessListener {
      if (it.areModulesAlreadyInstalled()) {
        // Modules are already installed when the request is sent.
        it.resume(true)
        return@addOnSuccessListener
      }
      // continue to download
    }
    .addOnFailureListener {
      // Handle failure…
    }
}
```

I have verified the module installation using the `ModuleInstallClient#installModule()` method.
However, I will also verify the module availability using the `ModuleInstallClient#areModulesAvailable()` API as you suggested. 
Thank you for your suggestion and provided the link to document.

**Comment by KoheiMoroi** [comment]
@SilverDestiny 
Installing the module individually works well immediately after installation.
Please let me know if this method(the second snippet) could cause any issues or be misused.

**Comment by SilverDestiny** [comment]
I see. The reason the 1st snippet doesn't work is because you used `TfLite.getClient(context)` as `optionalModuleApi`. `TfLite` is just an example in the docs, but it doesn't apply to your case.
We should use `SubjectSegmenter` as `optionalModuleApi`, i.e.
```
val optionalModuleApi =  SubjectSegmentation.getClient(options)
```

**Comment by KoheiMoroi** [comment]
> I see. The reason the 1st snippet doesn't work is because you used `TfLite.getClient(context)` as `optionalModuleApi`. `TfLite` is just an example in the docs, but it doesn't apply to your case. We should use `SubjectSegmenter` as `optionalModuleApi`, i.e.
> 
> ```
> val optionalModuleApi =  SubjectSegmentation.getClient(options)
> ```

@SilverDestiny 
Using `SubjectSegmenter` to request the installation of the module resolved the download error.
While inspecting the MLKit source code, I found the following code:
```java
    static {
        zza = new Feature[]{OptionalModuleUtils.FEATURE_SUBJECT_SEGMENTATION};
    }
```
This indicates that `FEATURE_SUBJECT_SEGMENTATION` is indeed a feature that should be used for subject segmentation subject.
 I guess the documentation should be updated to clarify that `SubjectSegmenter` should be used as the optional module API for subject segmentation task, not TfLite.

**Comment by KoheiMoroi** [comment]
Thank you for your assistance.

**Comment by SilverDestiny** [comment]
https://developers.google.com/android/guides/module-install-apis
This doc is from Google Play services, not ML Kit. They used `play-services-tflite-java` as an example in this doc. `SubjectSegmenter` is also integrated with `OptionalModuleApi`
