### ISSUE TITLE
[Bug report] Failed building After installing MLKit libraries while using some Firebase libraries 

### ISSUE THREAD

**Issue by khaledkutbi** [googlesamples/mlkit#841]
**Describe the bug**
Installing MLKit libraries like FaceDetection and ImageLabeling while FirebaseAnalytics already installed before the compiler complains for missing FirebaseAnalytics module and som times complain about GMLImage architecture even after excluding arm 64 The issue appears while running on simulator and disappears on rosetta and physical device.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to pod file 
2. Add theses pods 
   pod 'Firebase/Messaging'
   pod 'FirebaseAnalytics'
   pod 'FirebaseCrashlytics'
   pod 'FirebasePerformance'
   pod 'GoogleMLKit/FaceDetection'
   pod 'GoogleMLKit/ImageLabeling'
   pod 'GoogleMLKit/ImageLabelingCustom'
4. Open to Terminal in project directory
5. run pod install or update 
6. cmd+k to clean 
7. Wait for project to finish indexing files
8. cmd+B to build the issue will appear 

**Attachment**
![Screenshot 2024-05-26 at 2 04 35 PM](https://github.com/googlesamples/mlkit/assets/108001126/82445213-0604-42bf-acea-0f47fa693a97)

![Screenshot 2024-07-01 at 5 41 11 PM](https://github.com/googlesamples/mlkit/assets/108001126/13f9688f-76c0-44ab-8a95-2f51021b9cae)

**Expected behavior**
the project should build successfully after installing the MLKit pods with out conflicting or effecting the previously installed pods.

**SDK Info:**
 - GoogleMLKit/FaceDetection
 - GoogleMLKit/ImageLabeling
 - GoogleMLKit/ImageLabelingCustom

**Smartphone:**
 - All iPhones latest simulator with out using rosetta destination 

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 15.1]
- Laptop/Desktop: [e.g. MacBook Pro M1 (20221)]
- Laptop/Desktop OS/version: [e.g. macOS  Sonoma 14.5 ]

**Comment by miworking3** [comment]
I'm afraid we don't support M1 simulators: https://developers.google.com/ml-kit/known-issues#ios_issues
