### ISSUE TITLE
[Incompatibility report] GoogleMLKit/TextRecognition for iOS requires GoogleUtilities/UserDefaults < 8.0 while GoogleSignIn's latest version (8.0.0) depends on GoogleUtilities/UserDefaults ~> 8.0

### ISSUE THREAD

**Issue by vlvs** [googlesamples/mlkit#864]
**Describe the bug**
It's impossible to have the current latest versions of `GoogleMLKit/TextRecognition` for iOS (v6.0.0) and the current latest version of the [GoogleSignIn iOS SDK](https://github.com/google/GoogleSignIn-iOS) (v8.0.0) on the same project/target, because:
- `GoogleMLKit/TextRecognition` depends on `GoogleUtilities/UserDefaults` < 8.0.
- `GoogleSignIn` depends on `GoogleUtilities/UserDefaults` ~> 8.0.

**To Reproduce**
Attempt to integrate both SDKs on their latest versions to the same targets of an iOS project.
```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In Podfile:
    GoogleMLKit/TextRecognition (= 6.0.0) was resolved to 6.0.0, which depends on
      GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
        MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleUtilities/UserDefaults (< 8.0, >= 7.13.0)

    GoogleSignIn (= 8.0.0) was resolved to 8.0.0, which depends on
      AppCheckCore (~> 11.0) was resolved to 11.0.0, which depends on
        GoogleUtilities/UserDefaults (~> 8.0)
```

**Expected behavior**
The latest versions of both Google SDKs should be compatible with each other.

**Comment by bcdj** [comment]
GoogleMLKit shipped a new release (7.0.0)

https://developers.google.com/ml-kit/release-notes#september_30_2024

It upgraded its version range of GoogleUtilities/UserDefaults dependency in MLKitCommon from ">= 7.13.0, < 8.0" to "~> 8.0" and should have fixed this dependency conflict issue.
