### ISSUE TITLE
Non latin languages detection

### ISSUE THREAD

**Issue by Srijita-Basak** [googlesamples/mlkit#87]
Can anyone tell me how to detect non latin languages since this project is not done with firebase vision text where we can get the recognition of all languages after upgrading the firebase plan. Here I can see we are doing  textRecognizer = TextRecognition.getClient();
How do we detect all languages here?

**Comment by swiyu** [comment]
ML Kit on-device text recognition only supports latin language for now. We are working on adding more language supports. 

For short-term, the cloud-based Text Recognition supports many languages, and they are still available in Firebase.
