### ISSUE TITLE
[Bug report] Urgent: MLKitCommon needs to update its dependency version of GoogleDataTransport immediately.

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [googlesamples/mlkit#877]
MLKitCommon needs to update its dependency version of GoogleDataTransport immediately.

```

  In Podfile:
    firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.10.0-7, which depends on
      Firebase/Performance (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebasePerformance (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    google_mlkit_face_detection (from `.symlinks/plugins/google_mlkit_face_detection/ios`) was resolved to 0.11.1, which depends on
      GoogleMLKit/FaceDetection (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitFaceDetection (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)
            
  ```

**Comment by psykologist90** [comment]
I'm having issues with this too, the last version of MLKit is not compatible with the last version of FirebaseAnalytics and does not include the necessary privacy manifest that Apple is asking for.
Starting on november 12, if they don't update the apps won't be able to be submited to the Apple Appstore.

**Comment by bahadirarslan** [comment]
This is blocking me even building my apps because other dependencies require higher version of Firebase libraries and this library causes a conflict.

**Comment by vietstone-ng** [comment]
+1

**Comment by ToanDevMobile** [comment]
+1

**Comment by jacopofranza** [comment]
+1 THIS IS A BLOCKING ISSUE

**Comment by RCVZ** [comment]
+1

**Comment by RCVZ** [comment]
@miworking3 Could you look into this?
Also, see the other [issue tracker](https://issuetracker.google.com/issues/362452861)

**Comment by ShuheiSuzuki-07** [comment]
Has it been resolved?

https://issuetracker.google.com/issues/362452861#comment146

**Comment by vietstone-ng** [comment]
It's resolved. Just update to the latest versions.
