### ISSUE TITLE
[Bug report] Incorrect pod version listed in the iOS specific section of "Text recognition v2" documentation

### ISSUE THREAD

**Issue by ArchDevil** [googlesamples/mlkit#880]
**Describe the bug**
[iOS Text recognition v2 documentation](https://developers.google.com/ml-kit/vision/text-recognition/v2/ios)
`pod 'GoogleMLKit/TextRecognition', '15.5.0'`

[Example project podfile](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile)
`pod 'GoogleMLKit/TextRecognition', '7.0.0'`

[30.September Release notes](https://developers.google.com/ml-kit/release-notes#september_30_2024)
> MLKitTextRecognition (v2) 5.0.0

**To Reproduce**
1. Clone the sample app
2. Run pod install
3. Open its pod file which will include the following: `pod 'GoogleMLKit/TextRecognition', '7.0.0'`
4. Change the line to what the documentation suggests: pod 'GoogleMLKit/TextRecognition', '15.5.0'
5. Running pod update reveals that there is no version 15.5.0

**Expected behavior**
Documentation and sample to agree on versioning of pods.

**SDK Info:**
GoogleMLKit 7.0.0
MLKitTextRecognition 5.0.0

**Smartphone:**
Any

**Development Environment:**
Any

**Comment by bcdj** [comment]
The pod version should be fixed now.
