### ISSUE TITLE
[Feature request] Any information regarding the release date of google_mlkit_document_scanner for the iOS platform?

### ISSUE THREAD

**Issue by kalaylienes** [googlesamples/mlkit#899]
I am developing a document scanner and file management application. In this application, I am using Google ML Kit’s Document Scanner, but it is currently available only for the Android platform.

Is there any specific release date planned for iOS? I would like to schedule the release date of my application accordingly. Alternatively, is there any early access program available for iOS?

Thank you for your time.

**Mobile environment**
IOS

**Comment by FenyCz** [comment]
+1

**Comment by elifdogann** [comment]
+1

**Comment by bcdj** [comment]
Given iOS already has alternative options for document scanning, there's no current plan to release google_mlkit_document_scanner on iOS.

**Comment by fpomkla** [comment]
Can you please provide some alternative open source package as option for Flutter? Thank you
